PROMPT XXCOS_CUST_PO_NUMBER_S01.sqs>>>
@XXCOS_CUST_PO_NUMBER_S01.sqs;
PROMPT XXCOS_DEPARTMENT_ORDER_NO_S01.sqs>>>
@XXCOS_DEPARTMENT_ORDER_NO_S01.sqs;
PROMPT XXCOS_DEPOSIT_ORDER_NO_S01.sqs>>>
@XXCOS_DEPOSIT_ORDER_NO_S01.sqs;
PROMPT XXCOS_DEPOSIT_ORDER_NO_S02.sqs>>>
@XXCOS_DEPOSIT_ORDER_NO_S02.sqs;
PROMPT XXCOS_DEPOSIT_ORDER_NO_S03.sqs>>>
@XXCOS_DEPOSIT_ORDER_NO_S03.sqs;
PROMPT XXCOS_DLV_HEADERS_S01.sqs>>>
@XXCOS_DLV_HEADERS_S01.sqs;
PROMPT XXCOS_EDI_DELIVERY_WORK_S01.sqs>>>
@XXCOS_EDI_DELIVERY_WORK_S01.sqs;
PROMPT XXCOS_EDI_ERRORS_S01.sqs>>>
@XXCOS_EDI_ERRORS_S01.sqs;
PROMPT XXCOS_EDI_HEADERS_S01.sqs>>>
@XXCOS_EDI_HEADERS_S01.sqs;
PROMPT XXCOS_EDI_HEADERS_S02.sqs>>>
@XXCOS_EDI_HEADERS_S02.sqs;
PROMPT XXCOS_EDI_INVENTORY_S01.sqs>>>
@XXCOS_EDI_INVENTORY_S01.sqs;
PROMPT XXCOS_EDI_INVENTORY_WORK_S01.sqs>>>
@XXCOS_EDI_INVENTORY_WORK_S01.sqs;
PROMPT XXCOS_EDI_LINES_S01.sqs>>>
@XXCOS_EDI_LINES_S01.sqs;
PROMPT XXCOS_EDI_ORDER_WORK_S01.sqs>>>
@XXCOS_EDI_ORDER_WORK_S01.sqs;
PROMPT XXCOS_EDI_STC_HEADERS_S01.sqs>>>
@XXCOS_EDI_STC_HEADERS_S01.sqs;
PROMPT XXCOS_EDI_STC_LINES_S01.sqs>>>
@XXCOS_EDI_STC_LINES_S01.sqs;
PROMPT XXCOS_FOR_ADPS_BONUS_IF_S01.sqs>>>
@XXCOS_FOR_ADPS_BONUS_IF_S01.sqs;
PROMPT XXCOS_FOR_ADPS_MONTHLY_IF_S01.sqs>>>
@XXCOS_FOR_ADPS_MONTHLY_IF_S01.sqs;
PROMPT XXCOS_ORDER_SOURCE_REF_S01.sqs>>>
@XXCOS_ORDER_SOURCE_REF_S01.sqs;
PROMPT XXCOS_PAYMENT_S01.sqs>>>
@XXCOS_PAYMENT_S01.sqs;
PROMPT XXCOS_REP_BUS_COUNTER_SUM_S01.sqs>>>
@XXCOS_REP_BUS_COUNTER_SUM_S01.sqs;
PROMPT XXCOS_REP_BUS_NEWCUST_SUM_S01.sqs>>>
@XXCOS_REP_BUS_NEWCUST_SUM_S01.sqs;
PROMPT XXCOS_REP_BUS_PERF_S01.sqs>>>
@XXCOS_REP_BUS_PERF_S01.sqs;
PROMPT XXCOS_REP_BUS_REPORT_S01.sqs>>>
@XXCOS_REP_BUS_REPORT_S01.sqs;
PROMPT XXCOS_REP_BUS_SALES_SUM_S01.sqs>>>
@XXCOS_REP_BUS_SALES_SUM_S01.sqs;
PROMPT XXCOS_REP_BUS_S_GROUP_SUM_S01.sqs>>>
@XXCOS_REP_BUS_S_GROUP_SUM_S01.sqs;
PROMPT XXCOS_REP_COST_DIV_LIST_S01.sqs>>>
@XXCOS_REP_COST_DIV_LIST_S01.sqs;
PROMPT XXCOS_REP_DELI_REQ_S01.sqs>>>
@XXCOS_REP_DELI_REQ_S01.sqs;
PROMPT XXCOS_REP_DIG_DV_LIST_S01.sqs>>>
@XXCOS_REP_DIG_DV_LIST_S01.sqs;
PROMPT XXCOS_REP_DIG_LIST_S01.sqs>>>
@XXCOS_REP_DIG_LIST_S01.sqs;
PROMPT XXCOS_REP_DIRECT_LIST_S01.sqs>>>
@XXCOS_REP_DIRECT_LIST_S01.sqs;
PROMPT XXCOS_REP_DLV_CHK_LIST_S01.sqs>>>
@XXCOS_REP_DLV_CHK_LIST_S01.sqs;
PROMPT XXCOS_REP_HHT_ERR_LIST_S01.sqs>>>
@XXCOS_REP_HHT_ERR_LIST_S01.sqs;
PROMPT XXCOS_REP_HHT_ERR_LIST_S02.sqs>>>
@XXCOS_REP_HHT_ERR_LIST_S02.sqs;
PROMPT XXCOS_REP_ORDER_ERR_LIST_S01.sqs>>>
@XXCOS_REP_ORDER_ERR_LIST_S01.sqs;
PROMPT XXCOS_REP_ORDER_LIST_S01.sqs>>>
@XXCOS_REP_ORDER_LIST_S01.sqs;
PROMPT XXCOS_REP_PICK_CHAIN_PRO_S01.sqs>>>
@XXCOS_REP_PICK_CHAIN_PRO_S01.sqs;
PROMPT XXCOS_REP_PICK_DELI_PRO_S01.sqs>>>
@XXCOS_REP_PICK_DELI_PRO_S01.sqs;
PROMPT XXCOS_REP_PICK_DELI_SALE_S01.sqs>>>
@XXCOS_REP_PICK_DELI_SALE_S01.sqs;
PROMPT XXCOS_REP_SCH_DLV_LIST_S01.sqs>>>
@XXCOS_REP_SCH_DLV_LIST_S01.sqs;
PROMPT XXCOS_SALES_EXP_HEADERS_S01.sqs>>>
@XXCOS_SALES_EXP_HEADERS_S01.sqs;
PROMPT XXCOS_SALES_EXP_LINES_S01.sqs>>>
@XXCOS_SALES_EXP_LINES_S01.sqs;
PROMPT XXCOS_SHOP_DIGESTION_HDRS_S01.sqs>>>
@XXCOS_SHOP_DIGESTION_HDRS_S01.sqs;
PROMPT XXCOS_SHOP_DIGESTION_LNS_S01.sqs>>>
@XXCOS_SHOP_DIGESTION_LNS_S01.sqs;
PROMPT XXCOS_TRX_NUMBER_LARGE_S01.sqs>>>
@XXCOS_TRX_NUMBER_LARGE_S01.sqs;
PROMPT XXCOS_TRX_NUMBER_S01.sqs>>>
@XXCOS_TRX_NUMBER_S01.sqs;
PROMPT XXCOS_TRX_NUMBER_SMALL_S01.sqs>>>
@XXCOS_TRX_NUMBER_SMALL_S01.sqs;
PROMPT XXCOS_VD_DIGESTION_HDRS_S01.sqs>>>
@XXCOS_VD_DIGESTION_HDRS_S01.sqs;
PROMPT XXCOS_VD_DIGESTION_LNS_S01.sqs>>>
@XXCOS_VD_DIGESTION_LNS_S01.sqs;
