PROMPT XXCOI_FORM_HEADER_ID_S01.sqs>>>
@XXCOI_FORM_HEADER_ID_S01.sqs;
PROMPT XXCOI_HHT_INV_TRANSACTIONS_S01.sqs>>>
@XXCOI_HHT_INV_TRANSACTIONS_S01.sqs;
PROMPT XXCOI_INVOICE_NO_S01.sqs>>>
@XXCOI_INVOICE_NO_S01.sqs;
PROMPT XXCOI_INV_CONTROL_S01.sqs>>>
@XXCOI_INV_CONTROL_S01.sqs;
PROMPT XXCOI_INV_RESULT_S01.sqs>>>
@XXCOI_INV_RESULT_S01.sqs;
PROMPT XXCOI_MST_VD_COLUMN_S01.sqs>>>
@XXCOI_MST_VD_COLUMN_S01.sqs;
PROMPT XXCOI_REP_KURAGAE_SLIP_S01.sqs>>>
@XXCOI_REP_KURAGAE_SLIP_S01.sqs;
PROMPT XXCOI_REP_STOCK_BALANCE_S01.sqs>>>
@XXCOI_REP_STOCK_BALANCE_S01.sqs;
PROMPT XXCOI_REP_STORAGE_INFO_S01.sqs>>>
@XXCOI_REP_STORAGE_INFO_S01.sqs;
PROMPT XXCOI_REP_VD_INVENTORY_S01.sqs>>>
@XXCOI_REP_VD_INVENTORY_S01.sqs;
PROMPT XXCOI_STORAGE_INFORMATION_S01.sqs>>>
@XXCOI_STORAGE_INFORMATION_S01.sqs;
PROMPT XXCOI_XXWSH_RESERVE_IF_S01.sqs>>>
@XXCOI_XXWSH_RESERVE_IF_S01.sqs;
