PROMPT XXCOK_BACKMARGIN_BALANCE_S01.sqs>>>
@XXCOK_BACKMARGIN_BALANCE_S01.sqs;
PROMPT XXCOK_BM_SUPPORT_BUDGET_S01.sqs>>>
@XXCOK_BM_SUPPORT_BUDGET_S01.sqs;
PROMPT XXCOK_COND_BM_SUPPORT_S01.sqs>>>
@XXCOK_COND_BM_SUPPORT_S01.sqs;
PROMPT XXCOK_CUST_SHIFT_INFO_S01.sqs>>>
@XXCOK_CUST_SHIFT_INFO_S01.sqs;
PROMPT XXCOK_DLV_COST_CALC_BUDGET_S01.sqs>>>
@XXCOK_DLV_COST_CALC_BUDGET_S01.sqs;
PROMPT XXCOK_DLV_COST_RESULT_INFO_S01.sqs>>>
@XXCOK_DLV_COST_RESULT_INFO_S01.sqs;
PROMPT XXCOK_DLV_COST_RESULT_SUM_S01.sqs>>>
@XXCOK_DLV_COST_RESULT_SUM_S01.sqs;
PROMPT XXCOK_MST_BM_CONTRACT_S01.sqs>>>
@XXCOK_MST_BM_CONTRACT_S01.sqs;
PROMPT XXCOK_SELLING_FROM_INFO_S01.sqs>>>
@XXCOK_SELLING_FROM_INFO_S01.sqs;
PROMPT XXCOK_SELLING_RATE_INFO_S01.sqs>>>
@XXCOK_SELLING_RATE_INFO_S01.sqs;
PROMPT XXCOK_SELLING_TO_INFO_S01.sqs>>>
@XXCOK_SELLING_TO_INFO_S01.sqs;
PROMPT XXCOK_SELLING_TRNS_INFO_S01.sqs>>>
@XXCOK_SELLING_TRNS_INFO_S01.sqs;
PROMPT XXCOK_SELLING_TRNS_INFO_S02.sqs>>>
@XXCOK_SELLING_TRNS_INFO_S02.sqs;
PROMPT XXCOK_SLIP_NUMBER_BM_S01.sqs>>>
@XXCOK_SLIP_NUMBER_BM_S01.sqs;
PROMPT XXCOK_SLIP_NUMBER_JI_S01.sqs>>>
@XXCOK_SLIP_NUMBER_JI_S01.sqs;
PROMPT XXCOK_SLIP_NUMBER_TR_S01.sqs>>>
@XXCOK_SLIP_NUMBER_TR_S01.sqs;
PROMPT XXCOK_WHOLESALE_BILL_HEAD_S01.sqs>>>
@XXCOK_WHOLESALE_BILL_HEAD_S01.sqs;
PROMPT XXCOK_WHOLESALE_BILL_LINE_S01.sqs>>>
@XXCOK_WHOLESALE_BILL_LINE_S01.sqs;
PROMPT XXCOK_WHOLESALE_PAYMENT_S01.sqs>>>
@XXCOK_WHOLESALE_PAYMENT_S01.sqs;
PROMPT XXCOK_WK_EDI_SELLING_TRNS_S01.sqs>>>
@XXCOK_WK_EDI_SELLING_TRNS_S01.sqs;
