PROMPT XXCSO_ACCOUNT_SALES_PLANS_S01.sqs>>>
@XXCSO_ACCOUNT_SALES_PLANS_S01.sqs;
PROMPT XXCSO_APPROVAL_S01.sqs>>>
@XXCSO_APPROVAL_S01.sqs;
PROMPT XXCSO_BANK_ACCOUNTS_S01.sqs>>>
@XXCSO_BANK_ACCOUNTS_S01.sqs;
PROMPT XXCSO_CONTRACT_CUSTOMERS_S01.sqs>>>
@XXCSO_CONTRACT_CUSTOMERS_S01.sqs;
PROMPT XXCSO_CONTRACT_CUSTOMERS_S02.sqs>>>
@XXCSO_CONTRACT_CUSTOMERS_S02.sqs;
PROMPT XXCSO_CONTRACT_MANAGEMENTS_S01.sqs>>>
@XXCSO_CONTRACT_MANAGEMENTS_S01.sqs;
PROMPT XXCSO_DEPT_MONTHLY_PLANS_S01.sqs>>>
@XXCSO_DEPT_MONTHLY_PLANS_S01.sqs;
PROMPT XXCSO_DESTINATIONS_S01.sqs>>>
@XXCSO_DESTINATIONS_S01.sqs;
PROMPT XXCSO_IN_NOTES_S01.sqs>>>
@XXCSO_IN_NOTES_S01.sqs;
PROMPT XXCSO_IN_ROUTE_NO_S01.sqs>>>
@XXCSO_IN_ROUTE_NO_S01.sqs;
PROMPT XXCSO_IN_SALES_PLAN_DAY_S01.sqs>>>
@XXCSO_IN_SALES_PLAN_DAY_S01.sqs;
PROMPT XXCSO_IN_SALES_PLAN_MONTH_S01.sqs>>>
@XXCSO_IN_SALES_PLAN_MONTH_S01.sqs;
PROMPT XXCSO_PO_RQISTNS_IN_ALL_S01.sqs>>>
@XXCSO_PO_RQISTNS_IN_ALL_S01.sqs;
PROMPT XXCSO_PO_VENDORS_S01.sqs>>>
@XXCSO_PO_VENDORS_S01.sqs;
PROMPT XXCSO_PV_DEF_S01.sqs>>>
@XXCSO_PV_DEF_S01.sqs;
PROMPT XXCSO_PV_EXTRACT_TERM_DEF_S01.sqs>>>
@XXCSO_PV_EXTRACT_TERM_DEF_S01.sqs;
PROMPT XXCSO_PV_SORT_COLUMN_DEF_S01.sqs>>>
@XXCSO_PV_SORT_COLUMN_DEF_S01.sqs;
PROMPT XXCSO_PV_VIEW_COLUMN_DEF_S01.sqs>>>
@XXCSO_PV_VIEW_COLUMN_DEF_S01.sqs;
PROMPT XXCSO_QUOTE_HEADERS_S01.sqs>>>
@XXCSO_QUOTE_HEADERS_S01.sqs;
PROMPT XXCSO_QUOTE_LINES_S01.sqs>>>
@XXCSO_QUOTE_LINES_S01.sqs;
PROMPT XXCSO_REP_QUOTE_LIST_S01.sqs>>>
@XXCSO_REP_QUOTE_LIST_S01.sqs;
PROMPT XXCSO_SALES_HEADERS_HIST_S01.sqs>>>
@XXCSO_SALES_HEADERS_HIST_S01.sqs;
PROMPT XXCSO_SALES_HEADERS_S01.sqs>>>
@XXCSO_SALES_HEADERS_S01.sqs;
PROMPT XXCSO_SALES_LINES_HIST_S01.sqs>>>
@XXCSO_SALES_LINES_HIST_S01.sqs;
PROMPT XXCSO_SALES_LINES_S01.sqs>>>
@XXCSO_SALES_LINES_S01.sqs;
PROMPT XXCSO_SALES_NOTIFIES_S01.sqs>>>
@XXCSO_SALES_NOTIFIES_S01.sqs;
PROMPT XXCSO_SLS_PRSN_MNTHLY_PLNS_S01.sqs>>>
@XXCSO_SLS_PRSN_MNTHLY_PLNS_S01.sqs;
PROMPT XXCSO_SP_DECISION_ATTACHES_S01.sqs>>>
@XXCSO_SP_DECISION_ATTACHES_S01.sqs;
PROMPT XXCSO_SP_DECISION_CUSTS_S01.sqs>>>
@XXCSO_SP_DECISION_CUSTS_S01.sqs;
PROMPT XXCSO_SP_DECISION_HEADERS_S01.sqs>>>
@XXCSO_SP_DECISION_HEADERS_S01.sqs;
PROMPT XXCSO_SP_DECISION_HEADERS_S02.sqs>>>
@XXCSO_SP_DECISION_HEADERS_S02.sqs;
PROMPT XXCSO_SP_DECISION_LINES_S01.sqs>>>
@XXCSO_SP_DECISION_LINES_S01.sqs;
PROMPT XXCSO_SP_DECISION_SENDS_S01.sqs>>>
@XXCSO_SP_DECISION_SENDS_S01.sqs;
PROMPT XXCSO_SP_DECISION_WF_ORGS_S01.sqs>>>
@XXCSO_SP_DECISION_WF_ORGS_S01.sqs;
PROMPT XXCSO_XX03_VENDORS_IF_S01.sqs>>>
@XXCSO_XX03_VENDORS_IF_S01.sqs;
