PROMPT XXCSM_ITEM_PLAN_BDGT_S01.sqs>>>
@XXCSM_ITEM_PLAN_BDGT_S01.sqs;
PROMPT XXCSM_ITEM_PLAN_HEADER_S01.sqs>>>
@XXCSM_ITEM_PLAN_HEADER_S01.sqs;
PROMPT XXCSM_ITEM_PLAN_LINES_S01.sqs>>>
@XXCSM_ITEM_PLAN_LINES_S01.sqs;
PROMPT XXCSM_NEWS_ITEM_HDRS_ALL_S01.sqs>>>
@XXCSM_NEWS_ITEM_HDRS_ALL_S01.sqs;
PROMPT XXCSM_NEWS_ITEM_LINES_ALL_S01.sqs>>>
@XXCSM_NEWS_ITEM_LINES_ALL_S01.sqs;
PROMPT XXCSM_TMP_ITEM_PLAN_GUN_S01.sqs>>>
@XXCSM_TMP_ITEM_PLAN_GUN_S01.sqs;
PROMPT XXCSM_TMP_ITEM_PLAN_SALES_S01.sqs>>>
@XXCSM_TMP_ITEM_PLAN_SALES_S01.sqs;
PROMPT XXCSM_TMP_ITEM_PLAN_SALSUM_S01.sqs>>>
@XXCSM_TMP_ITEM_PLAN_SALSUM_S01.sqs;
