PROMPT XXCFR_AR_TRX_INTERFACE_S1.sqs>>>
@XXCFR_AR_TRX_INTERFACE_S1.sqs;
PROMPT XXCFR_CSV_OUTS_TEMP_S1.sqs>>>
@XXCFR_CSV_OUTS_TEMP_S1.sqs;
PROMPT XXCFR_INVOICE_HEADERS_S1.sqs>>>
@XXCFR_INVOICE_HEADERS_S1.sqs;
PROMPT XXCFR_PAYMENT_NOTES_S1.sqs>>>
@XXCFR_PAYMENT_NOTES_S1.sqs;
