package itoen.oracle.apps.xxcso.xxcso019009j.lov.server;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class XxcsoRscRtnBaseLovAMImpl extends OAApplicationModuleImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public XxcsoRscRtnBaseLovAMImpl()
  {
  }

  /**
   * 
   * Container's getter for XxcsoRscRtnBaseLovVO1
   */
  public XxcsoRscRtnBaseLovVOImpl getXxcsoRscRtnBaseLovVO1()
  {
    return (XxcsoRscRtnBaseLovVOImpl)findViewObject("XxcsoRscRtnBaseLovVO1");
  }

  /**
   * 
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("itoen.oracle.apps.xxcso.xxcso019009j.lov.server", "XxcsoRscRtnBaseLovAMLocal");
  }
}