PROMPT XXCOS_IN_AA_JX_DIR.dir>>>
@XXCOS_IN_AA_JX_DIR.dir;
PROMPT XXCOS_IN_AB_JX_DIR.dir>>>
@XXCOS_IN_AB_JX_DIR.dir;
PROMPT XXCOS_OUT_AA_HA_DIR.dir>>>
@XXCOS_OUT_AA_HA_DIR.dir;
PROMPT XXCOS_OUT_AA_JX_DIR.dir>>>
@XXCOS_OUT_AA_JX_DIR.dir;
PROMPT XXCOS_OUT_AA_KA_DIR.dir>>>
@XXCOS_OUT_AA_KA_DIR.dir;
PROMPT XXCOS_OUT_AA_KB_DIR.dir>>>
@XXCOS_OUT_AA_KB_DIR.dir;
PROMPT XXCOS_OUT_AA_NA_DIR.dir>>>
@XXCOS_OUT_AA_NA_DIR.dir;
PROMPT XXCOS_OUT_AB_JX_DIR.dir>>>
@XXCOS_OUT_AB_JX_DIR.dir;
PROMPT XXCOS_OUT_AB_KA_DIR.dir>>>
@XXCOS_OUT_AB_KA_DIR.dir;
