PROMPT XXCOK_IN_AJ_JX_DIR.dir>>>
@XXCOK_IN_AJ_JX_DIR.dir;
PROMPT XXCOK_OUT_AH_JX_DIR.dir>>>
@XXCOK_OUT_AH_JX_DIR.dir;
PROMPT XXCOK_OUT_AH_KB_DIR.dir>>>
@XXCOK_OUT_AH_KB_DIR.dir;
PROMPT XXCOK_OUT_AJ_KB_DIR.dir>>>
@XXCOK_OUT_AJ_KB_DIR.dir;
PROMPT XXCOK_OUT_AK_KB_DIR.dir>>>
@XXCOK_OUT_AK_KB_DIR.dir;
