PROMPT XXCSO_HHT_IN_CSV_DIR.dir>>>
@XXCSO_HHT_IN_CSV_DIR.dir;
PROMPT XXCSO_HHT_OUT_CSV_DIR.dir>>>
@XXCSO_HHT_OUT_CSV_DIR.dir;
PROMPT XXCSO_INFO_OUT_CSV_DIR.dir>>>
@XXCSO_INFO_OUT_CSV_DIR.dir;
PROMPT XXCSO_VM_IN_CSV_DIR.dir>>>
@XXCSO_VM_IN_CSV_DIR.dir;
PROMPT XXCSO_VM_OUT_CSV_DIR.dir>>>
@XXCSO_VM_OUT_CSV_DIR.dir;
