CREATE OR REPLACE FORCE VIEW XXCFF_OBJ_INS_DETAILS_V
(
 OBJECT_HEADER_ID        --物件内部ID
,HISTORY_NUM             --変更履歴NO
,OBJECT_CODE             --物件コード
,GENERATION_DATE         --発生日
,OBJECT_STATUS           --物件ステータス
,OBJECT_STATUS_NAME     --物件ステータス名称
,DEPARTMENT_CODE         --管理部門コード
,DEPARTMENT_NAME         --管理部門名称
,INSTALLATION_PLACE      --現設置先
,INSTALLATION_ADDRESS    --現設置場所
,RE_LEASE_TIMES          --再リース回数
,REGISTRATION_NUMBER     --登録番号
,DESCRIPTION             --摘要
,CONTRACT_NUMBER         --契約番号
,CONTRACT_LINE_NUM       --契約枝番
,CREATED_BY              --作成者
,CREATION_DATE           --作成日
,LAST_UPDATED_BY         --最終更新者
,LAST_UPDATE_DATE        --最終更新日
,LAST_UPDATE_LOGIN       --最終更新ﾛｸﾞｲﾝ
)
AS 
SELECT  XOH.OBJECT_HEADER_ID        --物件内部ID
       ,XOH.HISTORY_NUM             --変更履歴NO
       ,XOH.OBJECT_CODE             --物件コード
       ,XOH.GENERATION_DATE         --発生日
       ,XOH.OBJECT_STATUS           --物件ステータス
       ,XOSV.OBJECT_STATUS_NAME     --物件ステータス名称
       ,XOH.DEPARTMENT_CODE         --管理部門コード
       ,XDV.DEPARTMENT_NAME         --管理部門名称
       ,XOH.INSTALLATION_PLACE      --現設置先
       ,XOH.INSTALLATION_ADDRESS    --現設置場所
       ,XOH.RE_LEASE_TIMES          --再リース回数
       ,XOH.REGISTRATION_NUMBER     --登録番号
       ,XOH.DESCRIPTION             --摘要
       ,XCHL.CONTRACT_NUMBER         --契約番号
       ,XCHL.CONTRACT_LINE_NUM       --契約枝番
       ,XOH.CREATED_BY              --作成者
       ,XOH.CREATION_DATE           --作成日
       ,XOH.LAST_UPDATED_BY         --最終更新者
       ,XOH.LAST_UPDATE_DATE        --最終更新日
       ,XOH.LAST_UPDATE_LOGIN       --最終更新ﾛｸﾞｲﾝ
FROM    XXCFF_OBJECT_HISTORIES XOH  --リース物件履歴
       ,XXCFF_OBJECT_STATUS_V  XOSV --物件ステータスビュー
       ,XXCFF_DEPARTMENT_V     XDV  --管理部門ビュー
       ,(
        SELECT  XCH.CONTRACT_NUMBER         --契約番号
               ,XCL.CONTRACT_LINE_NUM       --契約枝番
               ,XCL.OBJECT_HEADER_ID
               ,XCH.RE_LEASE_TIMES
        FROM    XXCFF_CONTRACT_HEADERS XCH  --リース契約
               ,XXCFF_CONTRACT_LINES   XCL  --リース契約明細
        WHERE   XCH.CONTRACT_HEADER_ID = XCL.CONTRACT_HEADER_ID
        ) XCHL
WHERE   XCHL.OBJECT_HEADER_ID(+)   = XOH.OBJECT_HEADER_ID
AND     XOH.OBJECT_STATUS      = XOSV.OBJECT_STATUS_CODE
AND     XOH.RE_LEASE_TIMES     = XCHL.RE_LEASE_TIMES(+)
AND     XOH.DEPARTMENT_CODE    = XDV.DEPARTMENT_CODE
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.OBJECT_HEADER_ID IS '物件内部ID'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.HISTORY_NUM IS '変更履歴NO'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.OBJECT_CODE IS '物件コード'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.GENERATION_DATE IS '発生日'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.OBJECT_STATUS IS '物件ステータス'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.OBJECT_STATUS_NAME IS '物件ステータス名称'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.DEPARTMENT_CODE IS '管理部門コード'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.DEPARTMENT_NAME IS '管理部門名称'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.INSTALLATION_PLACE IS '現設置先'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.INSTALLATION_ADDRESS IS '現設置場所'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.RE_LEASE_TIMES IS '再リース回数'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.REGISTRATION_NUMBER IS '登録番号'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.REGISTRATION_NUMBER IS '登録番号'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.DESCRIPTION IS '摘要'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.CONTRACT_NUMBER IS '契約番号'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.CONTRACT_LINE_NUM IS '契約枝番'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.CREATED_BY IS '作成者'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.CREATION_DATE IS '作成日'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.LAST_UPDATED_BY IS '最終更新者'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.LAST_UPDATE_DATE IS '最終更新日'
/
COMMENT ON COLUMN XXCFF_OBJ_INS_DETAILS_V.LAST_UPDATE_LOGIN IS '最終更新ﾛｸﾞｲﾝ'
/
COMMENT ON TABLE XXCFF_OBJ_INS_DETAILS_V IS 'リース物件履歴一覧照会明細画面ビュー'
/
