CREATE OR REPLACE FORCE VIEW XXCFF_OBJ_INS_REFERENCE_V
(
 OBJECT_HEADER_ID           --物件内部ＩＤ
,HISTORY_NUM                --MAX(変更履歴ＮＯ)
,GENERATION_DATE            --変更日
,OBJECT_CODE                --物件コード
,LEASE_CLASS                --リース種別
,LEASE_CLASS_NAME          --リース種別名
,OWNER_COMPANY              --本社工場区分
,OWNER_COMPANY_NAME        --本社工場区分名
,DEPARTMENT_CODE            --管理部門
,DEPARTMENT_NAME            --管理部門名
,PO_NUMBER                  --発注番号
,MANUFACTURER_NAME          --メーカー名
,MODEL                      --機種
,SERIAL_NUMBER              --機番
,AGE_TYPE                   --年式
,QUANTITY                   --数量
,CHASSIS_NUMBER             --車台番号
,REGISTRATION_NUMBER        --登録番号
,INSTALLATION_PLACE         --現設置先
,INSTALLATION_ADDRESS       --現設置場所
,RE_LEASE_FLAG              --再リース要
,OBJECT_STATUS              --物件ステータス
,OBJECT_STATUS_NAME         --物件ステータス名
,LEASE_TYPE                 --リース区分
,LEASE_TYPE_NAME            --リース区分名
,RE_LEASE_TIMES             --再リース回数
,BOND_ACCEPTANCE_FLAG       --証書受領フラグ
,DESCRIPTION                --摘要
,FULL_NAME                  --作成者名
,CREATED_BY                 --作成者
,CREATION_DATE              --作成日
,LAST_UPDATED_BY            --最終更新者
,LAST_UPDATE_DATE           --最終更新日
,LAST_UPDATE_LOGIN          --最終更新ﾛｸﾞｲﾝ
,CANCELLATION_TYPE          --解約区分
,CANCELLATION_TYPE_NAME     --解約区分名
,LEASE_COMPANY              --リース会社
,LEASE_COMPANY_NAME         --リース会社名
,CONTRACT_NUMBER            --契約番号
,LEASE_START_DATE           --リース開始日
,LEASE_END_DATE             --リース終了日
,CONTRACT_LINE_NUM          --契約枝番
,LEASE_KIND                 --リース種類
,LEASE_KIND_NAME           --リース種類名
,ESTIMATED_CASH_PRICE       --見積現金購入価額
,SECOND_TOTAL_CHARGE        --2回目以降計_リース料
,SECOND_TOTAL_DEDUCTION     --2回目以降計_控除額
,GROSS_TOTAL_CHARGE         --総額計_リース料
,FIRST_INSTALLATION_PLACE   --初回設置先
,FIRST_INSTALLATION_ADDRESS --初回設置場所
)
AS 
SELECT XOH.OBJECT_HEADER_ID           --物件内部ＩＤ
      ,XOH.HISTORY_NUM                --MAX(変更履歴ＮＯ)
      ,XOH.GENERATION_DATE            --変更日
      ,XOH.OBJECT_CODE                --物件コード
      ,XOH.LEASE_CLASS                --リース種別
      ,XLCV.LEASE_CLASS_NAME          --リース種別名
      ,XOH.OWNER_COMPANY              --本社工場区分
      ,XOCV.OWNER_COMPANY_NAME        --本社工場区分名
      ,XOH.DEPARTMENT_CODE            --管理部門
      ,XDV.DEPARTMENT_NAME            --管理部門名
      ,XOH.PO_NUMBER                  --発注番号
      ,XOH.MANUFACTURER_NAME          --メーカー名
      ,XOH.MODEL                      --機種
      ,XOH.SERIAL_NUMBER              --機番
      ,XOH.AGE_TYPE                   --年式
      ,XOH.QUANTITY                   --数量
      ,XOH.CHASSIS_NUMBER             --車台番号
      ,XOH.REGISTRATION_NUMBER        --登録番号
      ,XOH.INSTALLATION_PLACE         --現設置先
      ,XOH.INSTALLATION_ADDRESS       --現設置場所
      ,XOH.RE_LEASE_FLAG              --再リース要
      ,XOH.OBJECT_STATUS              --物件ステータス
      ,XOSV.OBJECT_STATUS_NAME        --物件ステータス名
      ,XOH.LEASE_TYPE                 --リース区分
      ,XLTV.LEASE_TYPE_NAME           --リース区分名
      ,XOH.RE_LEASE_TIMES             --再リース回数
      ,XOH.BOND_ACCEPTANCE_FLAG       --証書受領フラグ
      ,XOH.DESCRIPTION                --摘要
      ,PPF.FULL_NAME                  --作成者名
      ,XOH.CREATED_BY                 --作成者
      ,XOH.CREATION_DATE              --作成日
      ,XOH.LAST_UPDATED_BY            --最終更新者
      ,XOH.LAST_UPDATE_DATE           --最終更新日
      ,XOH.LAST_UPDATE_LOGIN          --最終更新ﾛｸﾞｲﾝ
      ,XOH.CANCELLATION_TYPE          --解約区分
      ,XCTV.CANCELLATION_TYPE_NAME    --解約区分名
      ,XGK.LEASE_COMPANY              --リース会社
      ,XLCV.LEASE_COMPANY_NAME        --リース会社名
      ,XGK.CONTRACT_NUMBER            --契約番号
      ,XGK.LEASE_START_DATE           --リース開始日
      ,XGK.LEASE_END_DATE             --リース終了日
      ,XGK.CONTRACT_LINE_NUM          --契約枝番
      ,XGK.LEASE_KIND                 --リース種類
      ,XGK.LEASE_KIND_NAME            --リース種類名
      ,XGK.ESTIMATED_CASH_PRICE       --見積現金購入価額
      ,XGK.SECOND_TOTAL_CHARGE        --2回目以降計_リース料
      ,XGK.SECOND_TOTAL_DEDUCTION     --2回目以降計_控除額
      ,XGK.GROSS_TOTAL_CHARGE         --総額計_リース料
      ,XGK.FIRST_INSTALLATION_PLACE   --初回設置先
      ,XGK.FIRST_INSTALLATION_ADDRESS --初回設置場所
FROM   XXCFF_OBJECT_HISTORIES XOH     --リース物件履歴
      ,XXCFF_LEASE_CLASS_V    XLCV    --リース種別ビュー
      ,XXCFF_OWNER_COMPANY_V  XOCV    --本社工場ビュー
      ,XXCFF_DEPARTMENT_V     XDV     --管理部門ビュー
      ,XXCFF_LEASE_COMPANY_V  XLCV    --リース会社ビュー
      ,XXCFF_LEASE_TYPE_V     XLTV    --リース区分ビュー
      ,XXCFF_OBJECT_STATUS_V  XOSV    --物件ステータスビュー
      ,XXCFF_CANCELLATION_TYPE_V XCTV --リース解約区分ビュー
        ,(
        SELECT XCH.LEASE_COMPANY              --リース会社
              ,XCH.CONTRACT_NUMBER            --契約番号
              ,XCH.LEASE_START_DATE           --リース開始日
              ,XCH.LEASE_END_DATE             --リース終了日
              ,XCH.RE_LEASE_TIMES             --リース回数
              ,XCL.OBJECT_HEADER_ID
              ,XCL.CONTRACT_LINE_NUM          --契約枝番
              ,XCL.LEASE_KIND                 --リース種類
              ,XCL.ESTIMATED_CASH_PRICE       --見積現金購入価額
              ,XCL.SECOND_TOTAL_CHARGE        --2回目以降計_リース料
              ,XCL.SECOND_TOTAL_DEDUCTION     --2回目以降計_控除額
              ,XCL.GROSS_TOTAL_CHARGE         --総額計_リース料
              ,XCL.FIRST_INSTALLATION_PLACE   --初回設置先
              ,XCL.FIRST_INSTALLATION_ADDRESS --初回設置場所
              ,XLKV.LEASE_KIND_NAME           --リース種類名
        FROM   XXCFF_CONTRACT_HEADERS XCH     --リース契約
              ,XXCFF_CONTRACT_LINES   XCL     --リース契約明細
              ,XXCFF_LEASE_KIND_V     XLKV    --リース種類ビュー
        WHERE  XCH.CONTRACT_HEADER_ID = XCL.CONTRACT_HEADER_ID
        AND    XCL.LEASE_KIND         = XLKV.LEASE_KIND_CODE(+)
        ) XGK
       ,(
        SELECT  FU.USER_ID
               ,PPF.FULL_NAME
        FROM    FND_USER FU
               ,PER_PEOPLE_F PPF
        WHERE   FU.EMPLOYEE_ID = PPF.PERSON_ID
        AND     SYSDATE 
        BETWEEN PPF.EFFECTIVE_START_DATE
        AND     PPF.EFFECTIVE_END_DATE
        )PPF
WHERE  XOH.OBJECT_HEADER_ID   = XGK.OBJECT_HEADER_ID(+)
AND    XGK.LEASE_COMPANY      = XLCV.LEASE_COMPANY_CODE(+)
AND    XOH.RE_LEASE_TIMES     = XGK.RE_LEASE_TIMES(+)
AND    XOH.LEASE_CLASS        = XLCV.LEASE_CLASS_CODE(+)
AND    XOH.OWNER_COMPANY      = XOCV.OWNER_COMPANY_CODE(+)
AND    XOH.DEPARTMENT_CODE    = XDV.DEPARTMENT_CODE(+)
AND    XOH.LEASE_TYPE         = XLTV.LEASE_TYPE_CODE(+)
AND    XOH.OBJECT_STATUS      = XOSV.OBJECT_STATUS_CODE(+)
AND    XOH.CANCELLATION_TYPE  = XCTV.CANCELLATION_TYPE_CODE(+)
AND    PPF.USER_ID(+)            = XOH.CREATED_BY
;
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.OBJECT_HEADER_ID  IS '物件内部ＩＤ';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.HISTORY_NUM       IS 'MAX(変更履歴ＮＯ)';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.GENERATION_DATE   IS '変更日';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.OBJECT_CODE       IS '物件コード';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.LEASE_CLASS       IS 'リース種別';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.LEASE_CLASS_NAME  IS 'リース種別名';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.OWNER_COMPANY     IS '本社工場区分';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.OWNER_COMPANY_NAME IS '本社工場区分名';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.DEPARTMENT_CODE IS '管理部門';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.DEPARTMENT_NAME IS '管理部門名';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.PO_NUMBER       IS '発注番号';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.MANUFACTURER_NAME IS 'メーカー名';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.MODEL  IS '機種';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.SERIAL_NUMBER IS '機番';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.AGE_TYPE IS '年式';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.QUANTITY IS '数量';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.CHASSIS_NUMBER IS '車台番号';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.REGISTRATION_NUMBER IS '登録番号';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.INSTALLATION_PLACE  IS '現設置先';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.INSTALLATION_ADDRESS IS '現設置場所';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.RE_LEASE_FLAG IS '再リース要';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.OBJECT_STATUS IS '物件ステータス';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.OBJECT_STATUS_NAME IS '物件ステータス名';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.LEASE_TYPE IS 'リース区分';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.LEASE_TYPE_NAME IS 'リース区分名';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.RE_LEASE_TIMES IS '再リース回数';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.BOND_ACCEPTANCE_FLAG IS '証書受領フラグ';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.DESCRIPTION IS '摘要';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.FULL_NAME IS '作成者名';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.CREATED_BY IS '作成者';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.CREATION_DATE IS '作成日';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.LAST_UPDATED_BY IS '最終更新者';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.LAST_UPDATE_DATE IS '最終更新日';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.LAST_UPDATE_LOGIN IS '最終更新ﾛｸﾞｲﾝ';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.CANCELLATION_TYPE IS '解約区分';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.CANCELLATION_TYPE_NAME IS '解約区分名';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.LEASE_COMPANY IS 'リース会社';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.LEASE_COMPANY_NAME IS 'リース会社名';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.CONTRACT_NUMBER IS '契約番号';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.LEASE_START_DATE IS 'リース開始日';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.LEASE_END_DATE IS 'リース終了日';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.CONTRACT_LINE_NUM IS '契約枝番';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.LEASE_KIND IS 'リース種類';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.LEASE_KIND_NAME IS 'リース種類名';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.ESTIMATED_CASH_PRICE IS '見積現金購入価額';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.SECOND_TOTAL_CHARGE IS '2回目以降計_リース料';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.SECOND_TOTAL_DEDUCTION IS '2回目以降計_控除額';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.GROSS_TOTAL_CHARGE IS '総額計_リース料';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.FIRST_INSTALLATION_PLACE IS '初回設置先';
COMMENT ON COLUMN XXCFF_OBJ_INS_REFERENCE_V.FIRST_INSTALLATION_ADDRESS IS '初回設置場所';
COMMENT ON TABLE XXCFF_OBJ_INS_REFERENCE_V IS 'リース物件履歴照会画面ビュー';
