CREATE OR REPLACE OUTLINE XXCOI_XXCOI009A03R_OUTLINE FOR CATEGORY XXCOI_XXCOI ON
SELECT SUB.IN_BASE_CODE ,SUB.ACCOUNT_NAME ,SUB.INVENTORY_ITEM_ID ,
  SUB.TRANSACTION_QTY ,SUB.TRANSACTION_DATE ,SUB.ITEM_NO ,SUB.ITEM_SHORT_NAME 
  ,SUB.ITEM_CATEGORY 
FROM
 (SELECT /*+ use_nl(iimb ximb cat msib mmt msi hca) */ MSI.ATTRIBUTE7 
  IN_BASE_CODE ,SUBSTRB(HCA.ACCOUNT_NAME,1,8) ACCOUNT_NAME ,
  MMT.INVENTORY_ITEM_ID INVENTORY_ITEM_ID ,MMT.TRANSACTION_QUANTITY 
  TRANSACTION_QTY ,MMT.TRANSACTION_DATE TRANSACTION_DATE ,MSIB.SEGMENT1 
  ITEM_NO ,XIMB.ITEM_SHORT_NAME ITEM_SHORT_NAME ,CASE WHEN 
  SUBSTRB(MSIB.SEGMENT1, 1, 1) = '5' THEN :B10 WHEN SUBSTRB(MSIB.SEGMENT1, 1, 
  1) = '6' THEN :B10 ELSE MCB.SEGMENT1 END ITEM_CATEGORY FROM 
  INV.MTL_SECONDARY_INVENTORIES MSI ,APPS.HZ_CUST_ACCOUNTS HCA ,
  INV.MTL_MATERIAL_TRANSACTIONS MMT ,INV.MTL_SYSTEM_ITEMS_B MSIB ,
  APPS.IC_ITEM_MST_B IIMB ,XXCMN.XXCMN_ITEM_MST_B XIMB ,
  INV.MTL_CATEGORY_SETS_B MCSB ,INV.MTL_CATEGORY_SETS_TL MCST ,
  INV.MTL_CATEGORIES_B MCB ,INV.MTL_ITEM_CATEGORIES MIC WHERE 
  MMT.TRANSACTION_DATE >= TO_DATE(:B9 , 'YYYY/MM') AND MMT.TRANSACTION_DATE < 
  LAST_DAY(TO_DATE(:B9 , 'YYYY/MM')) + 1 AND MMT.TRANSACTION_TYPE_ID IN (:B8 ,
   :B7 , :B6 , :B5 ) AND MMT.SUBINVENTORY_CODE = MSI.SECONDARY_INVENTORY_NAME 
  AND MSI.ATTRIBUTE7 = :B1 AND MSI.ATTRIBUTE1 IN ('1', '3', '4') AND 
  MSI.ORGANIZATION_ID = :B2 AND HCA.ACCOUNT_NUMBER = MSI.ATTRIBUTE7 AND 
  HCA.CUSTOMER_CLASS_CODE = :B4 AND HCA.STATUS = 'A' AND 
  MSIB.INVENTORY_ITEM_ID = MMT.INVENTORY_ITEM_ID AND MSIB.ORGANIZATION_ID = 
  :B2 AND MSIB.SEGMENT1 = IIMB.ITEM_NO AND IIMB.ITEM_ID = XIMB.ITEM_ID AND 
  MSIB.INVENTORY_ITEM_ID = MIC.INVENTORY_ITEM_ID AND MCB.CATEGORY_ID = 
  MIC.CATEGORY_ID AND MCSB.CATEGORY_SET_ID = MIC.CATEGORY_SET_ID AND 
  MCB.STRUCTURE_ID = MCSB.STRUCTURE_ID AND MCST.CATEGORY_SET_ID = 
  MCSB.CATEGORY_SET_ID AND MCST.LANGUAGE = USERENV( 'LANG' ) AND 
  MCST.CATEGORY_SET_NAME = :B3 AND MIC.ORGANIZATION_ID = :B2 AND 
  MSIB.ORGANIZATION_ID = MIC.ORGANIZATION_ID AND MMT.TRANSACTION_DATE BETWEEN 
  XIMB.START_DATE_ACTIVE AND NVL(XIMB.END_DATE_ACTIVE, MMT.TRANSACTION_DATE) )
   SUB WHERE SUB.ITEM_CATEGORY = NVL(:B11 , SUB.ITEM_CATEGORY) ORDER BY 
  SUB.IN_BASE_CODE ,SUB.ITEM_CATEGORY ,SUB.ITEM_NO 
;