CREATE OR REPLACE OUTLINE XXPO_XXPO300001F_OUTLINE_03 FOR CATEGORY XXCMN_XXCMN ON
INSERT INTO PO_ONLINE_REPORT_TEXT_GT(ONLINE_REPORT_ID, LAST_UPDATE_LOGIN, 
  LAST_UPDATED_BY, LAST_UPDATE_DATE, CREATED_BY, CREATION_DATE, LINE_NUM, 
  SHIPMENT_NUM, DISTRIBUTION_NUM, SEQUENCE, TEXT_LINE, MESSAGE_NAME) SELECT 
  :B9 , :B8 , :B7 , SYSDATE, :B7 , SYSDATE, PL.LINE_NUM, PLL.SHIPMENT_NUM, 0, 
  :B6 + ROWNUM, SUBSTR(:B5 ||:B3 ||PL.LINE_NUM||:B3 || :B4 ||:B3 
  ||PLL.SHIPMENT_NUM||:B3 ||:B2 ,1,240), 'PO_ALL_NO_ITEM' FROM PO_HEADERS_GT 
  PH,PO_LINES_GT PL,PO_LINE_LOCATIONS_GT PLL,MTL_SYSTEM_ITEMS ITM,
  PO_LINE_TYPES_B PLT WHERE ITM.INVENTORY_ITEM_ID = PL.ITEM_ID AND PL.ITEM_ID 
  IS NOT NULL AND ITM.ORGANIZATION_ID = PLL.SHIP_TO_ORGANIZATION_ID AND 
  ITM.PURCHASING_ENABLED_FLAG = 'N' AND PL.PO_LINE_ID = PLL.PO_LINE_ID AND 
  PH.PO_HEADER_ID = PLL.PO_HEADER_ID AND PH.PO_HEADER_ID = :B1 AND 
  PL.PO_HEADER_ID = PH.PO_HEADER_ID AND PL.LINE_TYPE_ID = PLT.LINE_TYPE_ID 
  AND NVL(PLT.OUTSIDE_OPERATION_FLAG,'N') = NVL(ITM.OUTSIDE_OPERATION_FLAG,
  'N') AND (PL.CREATION_DATE >= NVL(PH.APPROVED_DATE,PL.CREATION_DATE)) AND 
  PLL.PO_RELEASE_ID IS NULL
;
