CREATE OR REPLACE OUTLINE XXPO_XXPO300001F_OUTLINE_02 FOR CATEGORY XXCMN_XXCMN ON
INSERT INTO PO_ONLINE_REPORT_TEXT_GT(ONLINE_REPORT_ID, LAST_UPDATE_LOGIN, 
  LAST_UPDATED_BY, LAST_UPDATE_DATE, CREATED_BY, CREATION_DATE, LINE_NUM, 
  SHIPMENT_NUM, DISTRIBUTION_NUM, SEQUENCE, TEXT_LINE, MESSAGE_NAME) SELECT 
  :B9 , :B8 , :B7 , SYSDATE, :B7 , SYSDATE, POL.LINE_NUM, PLL.SHIPMENT_NUM, 0,
   :B6 + ROWNUM, SUBSTR(:B5 ||:B3 ||POL.LINE_NUM||:B3 ||:B4 ||:B3 
  ||PLL.SHIPMENT_NUM||:B3 ||:B2 ,1,240), 'PO_SUB_ITEM_ASL_DEBARRED' FROM 
  MTL_SYSTEM_ITEMS MSI, PO_LINE_LOCATIONS_GT PLL, PO_LINES_GT POL, 
  PO_HEADERS_GT POH, FINANCIALS_SYSTEM_PARAMETERS FSP WHERE POH.PO_HEADER_ID =
   :B1 AND POH.PO_HEADER_ID = POL.PO_HEADER_ID AND PLL.PO_LINE_ID(+) = 
  POL.PO_LINE_ID AND PLL.PO_RELEASE_ID IS NULL AND MSI.ORGANIZATION_ID = 
  PLL.SHIP_TO_ORGANIZATION_ID AND MSI.INVENTORY_ITEM_ID = POL.ITEM_ID AND 
  POL.ITEM_ID IS NOT NULL AND NVL(PLL.CLOSED_CODE,'OPEN') <> 'FINALLY CLOSED' 
  AND NVL(POL.CANCEL_FLAG,'N') = 'N' AND NVL(PLL.CANCEL_FLAG,'N') = 'N' AND 
  NVL(MSI.MUST_USE_APPROVED_VENDOR_FLAG,'N') = 'Y' AND EXISTS (SELECT 
  SUM(DECODE(ASR.ALLOW_ACTION_FLAG, 'Y', 1, -1000)) FROM 
  PO_APPROVED_SUPPLIER_LIS_VAL_V ASL, PO_ASL_STATUS_RULES ASR WHERE 
  ASL.USING_ORGANIZATION_ID IN (PLL.SHIP_TO_ORGANIZATION_ID, -1) AND 
  ASL.VENDOR_ID = POH.VENDOR_ID AND NVL(ASL.VENDOR_SITE_ID, 
  POH.VENDOR_SITE_ID) = POH.VENDOR_SITE_ID AND ASL.ITEM_ID = POL.ITEM_ID AND 
  ASL.ASL_STATUS_ID = ASR.STATUS_ID AND ASR.BUSINESS_RULE = '1_PO_APPROVAL' 
  HAVING SUM(DECODE(ASR.ALLOW_ACTION_FLAG, 'Y', 1, -1000)) < 0 UNION ALL 
  SELECT SUM(DECODE(ASR.ALLOW_ACTION_FLAG, 'Y', 1, -1000)) FROM 
  PO_APPROVED_SUPPLIER_LIS_VAL_V ASL, PO_ASL_STATUS_RULES ASR WHERE 
  ASL.USING_ORGANIZATION_ID IN (PLL.SHIP_TO_ORGANIZATION_ID, -1) AND 
  ASL.VENDOR_ID = POH.VENDOR_ID AND NVL(ASL.VENDOR_SITE_ID, 
  POH.VENDOR_SITE_ID) = POH.VENDOR_SITE_ID AND ASL.ITEM_ID IS NULL AND 
  ASL.CATEGORY_ID IN (SELECT MIC.CATEGORY_ID FROM MTL_ITEM_CATEGORIES MIC 
  WHERE MIC.INVENTORY_ITEM_ID = POL.ITEM_ID AND MIC.ORGANIZATION_ID = 
  PLL.SHIP_TO_ORGANIZATION_ID) AND ASL.ASL_STATUS_ID = ASR.STATUS_ID AND 
  ASR.BUSINESS_RULE = '1_PO_APPROVAL' HAVING SUM(DECODE(ASR.ALLOW_ACTION_FLAG,
   'Y', 1, -1000)) < 0)
;
