insert into ra_customer_trx
(
customer_trx_id,
last_update_date,
last_updated_by,
creation_date,
created_by,
last_update_login,
trx_number,
cust_trx_type_id,
trx_date,
set_of_books_id,
ct_reference,
interface_header_context,
interface_header_attribute1,
interface_header_attribute2,
interface_header_attribute3,
interface_header_attribute4,
interface_header_attribute5,
interface_header_attribute6,
interface_header_attribute7,
interface_header_attribute8,
interface_header_attribute9,
interface_header_attribute10,
interface_header_attribute11,
interface_header_attribute12,
interface_header_attribute13,
interface_header_attribute14,
interface_header_attribute15,
bill_to_contact_id,
batch_id,
batch_source_id,
sold_to_customer_id,
bill_to_customer_id,
bill_to_address_id,
ship_to_customer_id,
ship_to_contact_id,
ship_to_address_id,
ship_to_site_use_id,
term_id,
previous_customer_trx_id,
primary_salesrep_id,
purchase_order,
purchase_order_revision,
purchase_order_date,
comments,
internal_notes,
exchange_rate_type,
exchange_date,
exchange_rate,
invoice_currency_code,
initial_customer_trx_id,
agreement_id,
request_id,
program_application_id,
program_id,
program_update_date,
complete_flag,
doc_sequence_value,
credit_method_for_rules,
credit_method_for_installments,
customer_bank_account_id,
receipt_method_id,
doc_sequence_id,
related_customer_trx_id,
invoicing_rule_id,
ship_via,
ship_date_actual,
waybill_number,
fob_point,
territory_id,
attribute_category,
attribute1,
attribute2,
attribute3,
attribute4,
attribute5,
attribute6,
attribute7,
attribute8,
attribute9,
attribute10,
attribute11,
attribute12,
attribute13,
attribute14,
attribute15,
global_attribute_category,
global_attribute1,
global_attribute2,
global_attribute3,
global_attribute4,
global_attribute5,
global_attribute6,
global_attribute7,
global_attribute8,
global_attribute9,
global_attribute10,
global_attribute11,
global_attribute12,
global_attribute13,
global_attribute14,
global_attribute15,
global_attribute16,
global_attribute17,
global_attribute18,
global_attribute19,
global_attribute20,
global_attribute21,
global_attribute22,
global_attribute23,
global_attribute24,
global_attribute25,
global_attribute26,
global_attribute27,
global_attribute28,
global_attribute29,
global_attribute30,
status_trx,
posting_control_id,
created_from,
paying_customer_id,
paying_site_use_id,
reason_code,
printing_option,
orig_system_batch_name,
payment_server_order_num,
approval_code,
contract_id)
select
l.customer_trx_id,
sysdate,
:b_last_updated_by,
sysdate,
:b_created_by,
:b_last_update_login,
l.trx_number,
l.cust_trx_type_id,
l.trx_date,
l.set_of_books_id,
DECODE(b.DEFAULT_REFERENCE,
       '1', l.interface_line_attribute1,
       '2', l.interface_line_attribute2,
       '3', l.interface_line_attribute3,
       '4', l.interface_line_attribute4,
       '5', l.interface_line_attribute5,
       '6', l.interface_line_attribute6,
       '7', l.interface_line_attribute7,
       '8', l.interface_line_attribute8,
       '9', l.interface_line_attribute9,
       '10', l.interface_line_attribute10,
       '11', l.interface_line_attribute11,
       '12', l.interface_line_attribute12,
       '13', l.interface_line_attribute13,
       '14', l.interface_line_attribute14,
       '15', l.interface_line_attribute15,
       NULL ),
substr(decode(l.interface_line_context, 
       'Global Data Elements', decode(1, 0, null, 'îÃîÑé¿ê—'), 
       decode(1, 1, l.interface_line_context, 'îÃîÑé¿ê—')), 1,30),
l.interface_line_attribute1,
l.interface_line_attribute2,
l.interface_line_attribute3,
l.interface_line_attribute4,
l.interface_line_attribute5,
l.interface_line_attribute6,
l.interface_line_attribute7,
l.interface_line_attribute8,
l.interface_line_attribute9,
l.interface_line_attribute10,
l.interface_line_attribute11,
l.interface_line_attribute12,
l.interface_line_attribute13,
l.interface_line_attribute14,
l.interface_line_attribute15,
l.orig_system_bill_contact_id,
:b_batch_id,
:b_batch_source_id,
l.orig_system_sold_customer_id,
l.orig_system_bill_customer_id,
l.orig_system_bill_address_id,
l.orig_system_ship_customer_id,
l.orig_system_ship_contact_id,
l.orig_system_ship_address_id,
null,
l.term_id,
l.previous_customer_trx_id,
l.primary_salesrep_id,
l.purchase_order,
l.purchase_order_revision,
l.purchase_order_date,
l.comments,
l.internal_notes,
decode(l.currency_code, g.currency_code, null, l.conversion_type),
decode(l.currency_code, g.currency_code, null,
       nvl(l.conversion_date, l.trx_date)),
decode(l.currency_code, g.currency_code, null, l.conversion_rate),
l.currency_code,
l.initial_customer_trx_id,
l.agreement_id,
:b1,
:b_program_application_id,
:b_program_id,
sysdate,
'N',
l.document_number,
l.credit_method_for_acct_rule,
l.credit_method_for_installments,
l.customer_bank_account_id,
l.receipt_method_id,
l.document_number_sequence_id,
l.related_customer_trx_id,
l.invoicing_rule_id,
l.ship_via,
l.ship_date_actual,
l.waybill_number,
l.fob_point,
l.territory_id,
 l.header_attribute_category,
rtrim(l.header_attribute1),
rtrim(l.header_attribute2),
rtrim(l.header_attribute3),
rtrim(l.header_attribute4),
rtrim(l.header_attribute5),
rtrim(l.header_attribute6),
rtrim(l.header_attribute7),
rtrim(l.header_attribute8),
rtrim(l.header_attribute9),
rtrim(l.header_attribute10),
rtrim(l.header_attribute11),
rtrim(l.header_attribute12),
rtrim(l.header_attribute13),
rtrim(l.header_attribute14),
rtrim(l.header_attribute15),
l.header_gdf_attr_category,
l.header_gdf_attribute1,
l.header_gdf_attribute2,
l.header_gdf_attribute3,
l.header_gdf_attribute4,
l.header_gdf_attribute5,
l.header_gdf_attribute6,
l.header_gdf_attribute7,
l.header_gdf_attribute8,
l.header_gdf_attribute9,
l.header_gdf_attribute10,
l.header_gdf_attribute11,
l.header_gdf_attribute12,
l.header_gdf_attribute13,
l.header_gdf_attribute14,
l.header_gdf_attribute15,
l.header_gdf_attribute16,
l.header_gdf_attribute17,
l.header_gdf_attribute18,
l.header_gdf_attribute19,
l.header_gdf_attribute20,
l.header_gdf_attribute21,
l.header_gdf_attribute22,
l.header_gdf_attribute23,
l.header_gdf_attribute24,
l.header_gdf_attribute25,
l.header_gdf_attribute26,
l.header_gdf_attribute27,
l.header_gdf_attribute28,
l.header_gdf_attribute29,
l.header_gdf_attribute30,
'OP',
-3,
'RAXTRX',
decode(l.receipt_method_id, null, null, l.paying_customer_id),
decode(l.receipt_method_id, null, null, l.paying_site_use_id),
l.reason_code,
l.printing_option,
l.orig_system_batch_name,
l.payment_server_order_num,
l.approval_code,
l.contract_id
from  ra_interface_lines_gt l,
      ra_batch_sources b,
      gl_sets_of_books g
where l.set_of_books_id = g.set_of_books_id
      and b.name = l.batch_source_name
      and l.interface_line_id in (
select /*+ INDEX(l1 RA_INTERFACE_LINES_N1) */ min(l1.interface_line_id)
from   ra_interface_lines_gt l1
where  l1.request_id = :b2
and    l1.customer_trx_id is not null
and    nvl(l1.interface_status, '~') != 'P'
and    l1.link_to_line_id is null
and    not ((l1.reference_line_id is not null
or l1.reference_line_attribute1
|| l1.reference_line_attribute2
|| l1.reference_line_attribute3
|| l1.reference_line_attribute4
|| l1.reference_line_attribute5
|| l1.reference_line_attribute6
|| l1.reference_line_attribute7
|| l1.reference_line_attribute8
|| l1.reference_line_attribute9
|| l1.reference_line_attribute10
|| l1.reference_line_attribute11
|| l1.reference_line_attribute12
|| l1.reference_line_attribute13
|| l1.reference_line_attribute14
|| l1.reference_line_attribute15 is not null)
            and exists
            (select 'x'
             from   ra_cust_trx_types t
             where  t.cust_trx_type_id = l1.cust_trx_type_id
             and    t.type = 'CM'))and ( l1.customer_trx_id,
      NVL(l1.ship_date_actual,to_date('01/01/0001','dd-mm-yyyy')) ) IN
         ( select /*+ NO_INDEX(l2 RA_INTERFACE_LINES_N1) INDEX(l2 RA_INTERFACE_LINES_N2) */ l2.customer_trx_id,
                  NVL(MIN(l2.ship_date_actual),to_date('01/01/0001','dd-mm-yyyy'))
           from   ra_interface_lines_gt l2
           where  request_id = :b3
           group  by l2.customer_trx_id )group by l1.customer_trx_id )