INSERT INTO AR_LINE_CONTS ( CUSTOMER_TRX_LINE_ID, CONTINGENCY_CODE, 
  EXPIRATION_DATE, EXPIRATION_DAYS, COMPLETED_FLAG, REQUEST_ID, CREATED_BY, 
  CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN ) 
  SELECT CTL.CUSTOMER_TRX_LINE_ID, 'AR_CUSTOMER_CREDIT', NULL, NULL, 'N', 
  CTL.REQUEST_ID, :B2 , SYSDATE, :B2 , SYSDATE, :B2 FROM 
  RA_CUSTOMER_TRX_LINES CTL, RA_CUSTOMER_TRX CT, RA_CUST_TRX_TYPES CTT WHERE 
  CTL.REQUEST_ID = :B1 AND CTL.CUSTOMER_TRX_ID = CT.CUSTOMER_TRX_ID AND 
  CT.BATCH_SOURCE_ID NOT IN (20, 21) AND CT.CUST_TRX_TYPE_ID = 
  CTT.CUST_TRX_TYPE_ID AND CTT.TYPE = 'INV' AND CTL.LINE_TYPE = 'LINE' AND 
  AR_REVENUE_MANAGEMENT_PVT.CREDITWORTHY (CT.BILL_TO_CUSTOMER_ID, 
  CT.BILL_TO_SITE_USE_ID)= 0 AND NOT EXISTS (SELECT 'errors' FROM 
  RA_INTERFACE_ERRORS IE WHERE IE.INTERFACE_LINE_ID = 
  CTL.CUSTOMER_TRX_LINE_ID)
