SELECT 
  /*+ 
    LEADING(GPS GJH GJL XTCV GCC XAV)
    USE_NL (GJL XTCV)
    USE_NL (GCC XAV)
    INDEX  (GJL GL_JE_LINES_U1)
    INDEX  (GCC GL_CODE_COMBINATIONS_U1)
    INDEX  (XCV FND_FLEX_VALUES_N1)
    INDEX  (XAV FND_FLEX_VALUES_N1)
    INDEX  (XTCV AP_TAX_CODES_N1)
  */
  GCC.SEGMENT1 BALANCING_SEG_CODE, XCV.DESCRIPTION BALANCING_SEG_DESC, 
  GCC.SEGMENT3 ACCOUNT_SEG_CODE, XAV.DESCRIPTION ACCOUNT_SEG_DESC, 
  GJH.SET_OF_BOOKS_ID SET_OF_BOOKS_ID, DECODE(XTCV.ATTRIBUTE2, '2', 
  NVL(GJL.ACCOUNTED_DR,0)-NVL(GJL.ACCOUNTED_CR,0), NVL(GJL.ACCOUNTED_CR,0)
  -NVL(GJL.ACCOUNTED_DR,0)) AMOUNT, GJL.ATTRIBUTE1 TAX_CODE, XTCV.TAX_RATE 
  TAX_RATE, XTCV.ATTRIBUTE1 TAX_ASSORTMENT_CODE, XTCV.ATTRIBUTE2 
  TAX_SUMMARY_TYPE_CODE, XTCV.DESCRIPTION TAX_DESC 
FROM
 GL_PERIOD_STATUSES GPS, GL_CODE_COMBINATIONS GCC, GL_JE_HEADERS GJH, 
  GL_JE_LINES GJL, XX03_COMPANIES_V XCV, XX03_ACCOUNTS_V XAV, 
  XX03_TAX_CODES_V XTCV WHERE GJL.CODE_COMBINATION_ID = 
  GCC.CODE_COMBINATION_ID AND GJL.JE_HEADER_ID = GJH.JE_HEADER_ID AND 
  GJH.ACTUAL_FLAG = :B7 AND GJH.STATUS = :B6 AND GJH.CURRENCY_CODE != :B5 AND 
  GJH.SET_OF_BOOKS_ID = :B1 AND GPS.EFFECTIVE_PERIOD_NUM BETWEEN :B4 AND :B3 
  AND GJH.PERIOD_NAME = GPS.PERIOD_NAME AND GPS.APPLICATION_ID = :B2 AND 
  GPS.SET_OF_BOOKS_ID = :B1 AND GJL.ATTRIBUTE1 IS NOT NULL AND GJL.ATTRIBUTE1 
  = XTCV.NAME AND GJH.DEFAULT_EFFECTIVE_DATE BETWEEN NVL(XTCV.START_DATE, 
  TO_DATE('1000/01/01', 'YYYY/MM/DD')) AND NVL(XTCV.INACTIVE_DATE, 
  TO_DATE('4712/12/31', 'YYYY/MM/DD')) AND GCC.SEGMENT1 = XCV.FLEX_VALUE AND 
  GCC.SEGMENT3 = XAV.FLEX_VALUE AND XAV.ATTRIBUTE6 IS NULL ORDER BY 
  GCC.SEGMENT1, XTCV.ATTRIBUTE2
