SELECT /*+ INDEX ( MSI MTL_SYSTEM_ITEMS_B_U1 ) */
  MSI.ROWID MSI_ROWID, MSI.INVENTORY_ITEM_STATUS_CODE MSI_STATUS_CODE, 
  MSI.LIFECYCLE_ID MSI_LIFECYCLE_ID, MSI.CURRENT_PHASE_ID 
  MSI_CURRENT_PHASE_ID, MSI.ITEM_CATALOG_GROUP_ID MSI_CATALOG_GROUP_ID, 
  MSI.INVENTORY_ITEM_FLAG INV_ITEM_FLAG, MSI.PURCHASING_ITEM_FLAG 
  PURCHASING_FLAG, MSI.INTERNAL_ORDER_FLAG INT_ORDER_FLAG, 
  MSI.MRP_PLANNING_CODE PLANNING_CODE, MSI.SERVICE_ITEM_FLAG SERV_ITEM_FLAG, 
  MSI.CUSTOMER_ORDER_FLAG CUST_ORD_FLAG, MSI.COSTING_ENABLED_FLAG COST_FLAG, 
  MSI.ENG_ITEM_FLAG ENG_FLAG, MSI.EAM_ITEM_TYPE EAM_TYPE, 
  MSI.CONTRACT_ITEM_TYPE_CODE CONTRACT_TYPE, MSI.INVENTORY_ASSET_FLAG 
  INV_ASSET_FLAG, MSII.ROWID MSII_ROWID, MSII.* 
FROM
 MTL_SYSTEM_ITEMS_B MSI, MTL_SYSTEM_ITEMS_INTERFACE MSII WHERE :B2 = 
  MSII.INVENTORY_ITEM_ID AND :B2 = MSI.INVENTORY_ITEM_ID AND 
  MSII.TRANSACTION_TYPE IN ('UPDATE','AUTO_CHILD') AND MSI.ORGANIZATION_ID = 
  MSII.ORGANIZATION_ID AND MSII.PROCESS_FLAG = 4 AND (MSII.SET_PROCESS_ID = 
  :B1 OR MSII.SET_PROCESS_ID = :B1 + 1000000000000) FOR UPDATE OF 
  MSI.INVENTORY_ITEM_ID NOWAIT
