INSERT INTO MRP_FORECAST_ITEMS ( INVENTORY_ITEM_ID, ORGANIZATION_ID, 
  FORECAST_DESIGNATOR, LAST_UPDATE_DATE, LAST_UPDATED_BY, CREATION_DATE, 
  CREATED_BY, LAST_UPDATE_LOGIN ) SELECT /*+ index_ffs (dates 
  MRP_FORECAST_DATES_N1) */ DISTINCT INVENTORY_ITEM_ID, ORGANIZATION_ID, 
  FORECAST_DESIGNATOR, SYSDATE, 1, SYSDATE, 1, -1 FROM MRP_FORECAST_DATES 
  DATES WHERE NOT EXISTS (SELECT NULL FROM MRP_FORECAST_ITEMS ITEMS WHERE 
  ITEMS.ORGANIZATION_ID = DATES.ORGANIZATION_ID AND ITEMS.FORECAST_DESIGNATOR 
  = DATES.FORECAST_DESIGNATOR AND ITEMS.INVENTORY_ITEM_ID = 
  DATES.INVENTORY_ITEM_ID)
