SELECT /*+ USE_NL (WIAS WI)
           INDEX (WIAS WF_ITEM_ACTIVITY_STATUSES_PK) */
       WI.ITEM_KEY 
FROM
 WF_ITEM_ACTIVITY_STATUSES WIAS, WF_ITEMS WI WHERE WI.ITEM_TYPE = 'WFERROR' 
  AND WI.PARENT_ITEM_TYPE = WIAS.ITEM_TYPE AND WI.PARENT_ITEM_KEY = 
  WIAS.ITEM_KEY AND WI.PARENT_CONTEXT = WIAS.PROCESS_ACTIVITY AND 
  WIAS.ACTIVITY_STATUS = 'COMPLETE'