PROMPT XXCOS_DEPOSIT_VD_SLIP_WORK.tab>>>
@XXCOS_DEPOSIT_VD_SLIP_WORK.tab;
PROMPT XXCOS_DLV_HEADERS.tab>>>
@XXCOS_DLV_HEADERS.tab;
PROMPT XXCOS_DLV_HEADERS_WORK.tab>>>
@XXCOS_DLV_HEADERS_WORK.tab;
PROMPT XXCOS_DLV_LINES.tab>>>
@XXCOS_DLV_LINES.tab;
PROMPT XXCOS_DLV_LINES_WORK.tab>>>
@XXCOS_DLV_LINES_WORK.tab;
PROMPT XXCOS_EDI_DELIVERY_WORK.tab>>>
@XXCOS_EDI_DELIVERY_WORK.tab;
PROMPT XXCOS_EDI_ERRORS.tab>>>
@XXCOS_EDI_ERRORS.tab;
PROMPT XXCOS_EDI_HEADERS.tab>>>
@XXCOS_EDI_HEADERS.tab;
PROMPT XXCOS_EDI_INVENTORY.tab>>>
@XXCOS_EDI_INVENTORY.tab;
PROMPT XXCOS_EDI_INVENTORY_WORK.tab>>>
@XXCOS_EDI_INVENTORY_WORK.tab;
PROMPT XXCOS_EDI_LINES.tab>>>
@XXCOS_EDI_LINES.tab;
PROMPT XXCOS_EDI_ORDER_WORK.tab>>>
@XXCOS_EDI_ORDER_WORK.tab;
PROMPT XXCOS_EDI_STC_HEADERS.tab>>>
@XXCOS_EDI_STC_HEADERS.tab;
PROMPT XXCOS_EDI_STC_LINES.tab>>>
@XXCOS_EDI_STC_LINES.tab;
PROMPT XXCOS_FOR_ADPS_BONUS_IF.tab>>>
@XXCOS_FOR_ADPS_BONUS_IF.tab;
PROMPT XXCOS_FOR_ADPS_MONTHLY_IF.tab>>>
@XXCOS_FOR_ADPS_MONTHLY_IF.tab;
PROMPT XXCOS_PAYMENT.tab>>>
@XXCOS_PAYMENT.tab;
PROMPT XXCOS_PAYMENT_WORK.tab>>>
@XXCOS_PAYMENT_WORK.tab;
PROMPT XXCOS_REPORT_FORMS_REGISTER.tab>>>
@XXCOS_REPORT_FORMS_REGISTER.tab;
PROMPT XXCOS_REP_BUS_COUNT_SUM.tab>>>
@XXCOS_REP_BUS_COUNT_SUM.tab;
PROMPT XXCOS_REP_BUS_NEWCUST_SUM.tab>>>
@XXCOS_REP_BUS_NEWCUST_SUM.tab;
PROMPT XXCOS_REP_BUS_PERF.tab>>>
@XXCOS_REP_BUS_PERF.tab;
PROMPT XXCOS_REP_BUS_REPORT.tab>>>
@XXCOS_REP_BUS_REPORT.tab;
PROMPT XXCOS_REP_BUS_SALES_SUM.tab>>>
@XXCOS_REP_BUS_SALES_SUM.tab;
PROMPT XXCOS_REP_BUS_S_GROUP_SUM.tab>>>
@XXCOS_REP_BUS_S_GROUP_SUM.tab;
PROMPT XXCOS_REP_COST_DIV_LIST.tab>>>
@XXCOS_REP_COST_DIV_LIST.tab;
PROMPT XXCOS_REP_DELI_REQ.tab>>>
@XXCOS_REP_DELI_REQ.tab;
PROMPT XXCOS_REP_DIG_DV_LIST.tab>>>
@XXCOS_REP_DIG_DV_LIST.tab;
PROMPT XXCOS_REP_DIG_LIST.tab>>>
@XXCOS_REP_DIG_LIST.tab;
PROMPT XXCOS_REP_DIRECT_LIST.tab>>>
@XXCOS_REP_DIRECT_LIST.tab;
PROMPT XXCOS_REP_DLV_CHK_LIST.tab>>>
@XXCOS_REP_DLV_CHK_LIST.tab;
PROMPT XXCOS_REP_HHT_ERR_LIST.tab>>>
@XXCOS_REP_HHT_ERR_LIST.tab;
PROMPT XXCOS_REP_ORDER_ERR_LIST.tab>>>
@XXCOS_REP_ORDER_ERR_LIST.tab;
PROMPT XXCOS_REP_ORDER_LIST.tab>>>
@XXCOS_REP_ORDER_LIST.tab;
PROMPT XXCOS_REP_PICK_CHAIN_PRO.tab>>>
@XXCOS_REP_PICK_CHAIN_PRO.tab;
PROMPT XXCOS_REP_PICK_DELI_PRO.tab>>>
@XXCOS_REP_PICK_DELI_PRO.tab;
PROMPT XXCOS_REP_PICK_DELI_SALE.tab>>>
@XXCOS_REP_PICK_DELI_SALE.tab;
PROMPT XXCOS_REP_SCH_DLV_LIST.tab>>>
@XXCOS_REP_SCH_DLV_LIST.tab;
PROMPT XXCOS_SALES_EXP_HEADERS.tab>>>
@XXCOS_SALES_EXP_HEADERS.tab;
PROMPT XXCOS_SALES_EXP_LINES.tab>>>
@XXCOS_SALES_EXP_LINES.tab;
PROMPT XXCOS_SHOP_DIGESTION_HDRS.tab>>>
@XXCOS_SHOP_DIGESTION_HDRS.tab;
PROMPT XXCOS_SHOP_DIGESTION_LNS.tab>>>
@XXCOS_SHOP_DIGESTION_LNS.tab;
PROMPT XXCOS_UNIT_PRICE_MST_WORK.tab>>>
@XXCOS_UNIT_PRICE_MST_WORK.tab;
PROMPT XXCOS_VD_COLUMN_HEADERS.tab>>>
@XXCOS_VD_COLUMN_HEADERS.tab;
PROMPT XXCOS_VD_COLUMN_LINES.tab>>>
@XXCOS_VD_COLUMN_LINES.tab;
PROMPT XXCOS_VD_DELIV_HEADERS.tab>>>
@XXCOS_VD_DELIV_HEADERS.tab;
PROMPT XXCOS_VD_DELIV_LINES.tab>>>
@XXCOS_VD_DELIV_LINES.tab;
PROMPT XXCOS_VD_DIGESTION_HDRS.tab>>>
@XXCOS_VD_DIGESTION_HDRS.tab;
PROMPT XXCOS_VD_DIGESTION_LNS.tab>>>
@XXCOS_VD_DIGESTION_LNS.tab;
