PROMPT XXCOI_COOPERATION_CONTROL.tab>>>
@XXCOI_COOPERATION_CONTROL.tab;
PROMPT XXCOI_HHT_INV_TRANSACTIONS.tab>>>
@XXCOI_HHT_INV_TRANSACTIONS.tab;
PROMPT XXCOI_INV_CONTROL.tab>>>
@XXCOI_INV_CONTROL.tab;
PROMPT XXCOI_INV_RECEPTION_DAILY.tab>>>
@XXCOI_INV_RECEPTION_DAILY.tab;
PROMPT XXCOI_INV_RECEPTION_MONTHLY.tab>>>
@XXCOI_INV_RECEPTION_MONTHLY.tab;
PROMPT XXCOI_INV_RECEPTION_SUM.tab>>>
@XXCOI_INV_RECEPTION_SUM.tab;
PROMPT XXCOI_INV_RESULT.tab>>>
@XXCOI_INV_RESULT.tab;
PROMPT XXCOI_IN_HHT_INV_TRANSACTIONS.tab>>>
@XXCOI_IN_HHT_INV_TRANSACTIONS.tab;
PROMPT XXCOI_IN_INV_RESULT_FILE_IF.tab>>>
@XXCOI_IN_INV_RESULT_FILE_IF.tab;
PROMPT XXCOI_MST_VD_COLUMN.tab>>>
@XXCOI_MST_VD_COLUMN.tab;
PROMPT XXCOI_REP_BASE_DETAIL_EXPEND.tab>>>
@XXCOI_REP_BASE_DETAIL_EXPEND.tab;
PROMPT XXCOI_REP_BASE_DETAIL_RCPT.tab>>>
@XXCOI_REP_BASE_DETAIL_RCPT.tab;
PROMPT XXCOI_REP_BASE_EXPEND.tab>>>
@XXCOI_REP_BASE_EXPEND.tab;
PROMPT XXCOI_REP_BASE_RCPT.tab>>>
@XXCOI_REP_BASE_RCPT.tab;
PROMPT XXCOI_REP_EMPLOYEE_RCPT.tab>>>
@XXCOI_REP_EMPLOYEE_RCPT.tab;
PROMPT XXCOI_REP_FACTORY_STORE_LIST.tab>>>
@XXCOI_REP_FACTORY_STORE_LIST.tab;
PROMPT XXCOI_REP_INV_CHECKLIST.tab>>>
@XXCOI_REP_INV_CHECKLIST.tab;
PROMPT XXCOI_REP_KURAGAE_SHIP_LIST.tab>>>
@XXCOI_REP_KURAGAE_SHIP_LIST.tab;
PROMPT XXCOI_REP_KURAGAE_SLIP.tab>>>
@XXCOI_REP_KURAGAE_SLIP.tab;
PROMPT XXCOI_REP_PRACTICE_INVENTORY.tab>>>
@XXCOI_REP_PRACTICE_INVENTORY.tab;
PROMPT XXCOI_REP_SHIPSTORE_JOUR_LIST.tab>>>
@XXCOI_REP_SHIPSTORE_JOUR_LIST.tab;
PROMPT XXCOI_REP_STOCK_BALANCE_LIST.tab>>>
@XXCOI_REP_STOCK_BALANCE_LIST.tab;
PROMPT XXCOI_REP_STORAGE_INFO.tab>>>
@XXCOI_REP_STORAGE_INFO.tab;
PROMPT XXCOI_REP_VD_INVENTORY.tab>>>
@XXCOI_REP_VD_INVENTORY.tab;
PROMPT XXCOI_REP_WAREHOUSE_RCPT.tab>>>
@XXCOI_REP_WAREHOUSE_RCPT.tab;
PROMPT XXCOI_STORAGE_INFORMATION.tab>>>
@XXCOI_STORAGE_INFORMATION.tab;
PROMPT XXCOI_TMP_INV_RESULT.tab>>>
@XXCOI_TMP_INV_RESULT.tab;
PROMPT XXCOI_TMP_STANDARD_INV.tab>>>
@XXCOI_TMP_STANDARD_INV.tab;
PROMPT XXCOI_TMP_SVD_TRANSACTIONS.tab>>>
@XXCOI_TMP_SVD_TRANSACTIONS.tab;
PROMPT XXCOI_VD_RECEPTION_INFO.tab>>>
@XXCOI_VD_RECEPTION_INFO.tab;
PROMPT XXCOI_WK_COST_VARIANCE.tab>>>
@XXCOI_WK_COST_VARIANCE.tab;
