PROMPT XXCOK_BACKMARGIN_BALANCE.tab>>>
@XXCOK_BACKMARGIN_BALANCE.tab;
PROMPT XXCOK_BM_CONTRACT_ERR.tab>>>
@XXCOK_BM_CONTRACT_ERR.tab;
PROMPT XXCOK_BM_SUPPORT_BUDGET.tab>>>
@XXCOK_BM_SUPPORT_BUDGET.tab;
PROMPT XXCOK_COND_BM_SUPPORT.tab>>>
@XXCOK_COND_BM_SUPPORT.tab;
PROMPT XXCOK_CUST_SHIFT_INFO.tab>>>
@XXCOK_CUST_SHIFT_INFO.tab;
PROMPT XXCOK_DLV_COST_CALC_BUDGET.tab>>>
@XXCOK_DLV_COST_CALC_BUDGET.tab;
PROMPT XXCOK_DLV_COST_RESULT_INFO.tab>>>
@XXCOK_DLV_COST_RESULT_INFO.tab;
PROMPT XXCOK_DLV_COST_RESULT_SUM.tab>>>
@XXCOK_DLV_COST_RESULT_SUM.tab;
PROMPT XXCOK_MST_BM_CONTRACT.tab>>>
@XXCOK_MST_BM_CONTRACT.tab;
PROMPT XXCOK_REP_BM_BALANCE.tab>>>
@XXCOK_REP_BM_BALANCE.tab;
PROMPT XXCOK_REP_BM_CONTRACT_ERR.tab>>>
@XXCOK_REP_BM_CONTRACT_ERR.tab;
PROMPT XXCOK_REP_BM_PG_DETAIL.tab>>>
@XXCOK_REP_BM_PG_DETAIL.tab;
PROMPT XXCOK_REP_BM_PG_RECEIPT.tab>>>
@XXCOK_REP_BM_PG_RECEIPT.tab;
PROMPT XXCOK_REP_SELLING_TRNS_CHK.tab>>>
@XXCOK_REP_SELLING_TRNS_CHK.tab;
PROMPT XXCOK_REP_WHOLESALE_PAY.tab>>>
@XXCOK_REP_WHOLESALE_PAY.tab;
PROMPT XXCOK_SELLING_FROM_INFO.tab>>>
@XXCOK_SELLING_FROM_INFO.tab;
PROMPT XXCOK_SELLING_RATE_INFO.tab>>>
@XXCOK_SELLING_RATE_INFO.tab;
PROMPT XXCOK_SELLING_TO_INFO.tab>>>
@XXCOK_SELLING_TO_INFO.tab;
PROMPT XXCOK_SELLING_TRNS_INFO.tab>>>
@XXCOK_SELLING_TRNS_INFO.tab;
PROMPT XXCOK_TMP_001A05F_SEC_CODE.tab>>>
@XXCOK_TMP_001A05F_SEC_CODE.tab;
PROMPT XXCOK_TMP_EDI_SELLING_TRNS.tab>>>
@XXCOK_TMP_EDI_SELLING_TRNS.tab;
PROMPT XXCOK_TMP_SELLING_RATE.tab>>>
@XXCOK_TMP_SELLING_RATE.tab;
PROMPT XXCOK_TMP_WHOLESALE_BILL.tab>>>
@XXCOK_TMP_WHOLESALE_BILL.tab;
PROMPT XXCOK_WHOLESALE_BILL_HEAD.tab>>>
@XXCOK_WHOLESALE_BILL_HEAD.tab;
PROMPT XXCOK_WHOLESALE_BILL_LINE.tab>>>
@XXCOK_WHOLESALE_BILL_LINE.tab;
PROMPT XXCOK_WHOLESALE_PAYMENT.tab>>>
@XXCOK_WHOLESALE_PAYMENT.tab;
PROMPT XXCOK_WK_EDI_SELLING_TRNS.tab>>>
@XXCOK_WK_EDI_SELLING_TRNS.tab;
