PROMPT XXCOP_APPL_CONTROLS.tab>>>
@XXCOP_APPL_CONTROLS.tab;
PROMPT XXCOP_LEAF_DAY_OF_SERVICE.tab>>>
@XXCOP_LEAF_DAY_OF_SERVICE.tab;
PROMPT XXCOP_MRP_SCHEDULE_INTERFACE.tab>>>
@XXCOP_MRP_SCHEDULE_INTERFACE.tab;
PROMPT XXCOP_REP_FORECAST_CHECK_LIST.tab>>>
@XXCOP_REP_FORECAST_CHECK_LIST.tab;
PROMPT XXCOP_REP_FORECAST_PLANNING.tab>>>
@XXCOP_REP_FORECAST_PLANNING.tab;
PROMPT XXCOP_SHIPMENT_RESULTS.tab>>>
@XXCOP_SHIPMENT_RESULTS.tab;
PROMPT XXCOP_WK_FORECAST_TOTALING.tab>>>
@XXCOP_WK_FORECAST_TOTALING.tab;
PROMPT XXCOP_WK_SHIP_PLANNING.tab>>>
@XXCOP_WK_SHIP_PLANNING.tab;
PROMPT XXCOP_WK_SHIP_PLANNING_OUTPUT.tab>>>
@XXCOP_WK_SHIP_PLANNING_OUTPUT.tab;
PROMPT XXCOP_WK_YOKO_PLAN_OUTPUT.tab>>>
@XXCOP_WK_YOKO_PLAN_OUTPUT.tab;
