PROMPT XXCSO_ACCOUNT_SALES_PLANS.tab>>>
@XXCSO_ACCOUNT_SALES_PLANS.tab;
PROMPT XXCSO_BANK_ACCOUNTS.tab>>>
@XXCSO_BANK_ACCOUNTS.tab;
PROMPT XXCSO_CODE_ASSIGNMENTS.tab>>>
@XXCSO_CODE_ASSIGNMENTS.tab;
PROMPT XXCSO_CONTRACT_CUSTOMERS.tab>>>
@XXCSO_CONTRACT_CUSTOMERS.tab;
PROMPT XXCSO_CONTRACT_MANAGEMENTS.tab>>>
@XXCSO_CONTRACT_MANAGEMENTS.tab;
PROMPT XXCSO_DEPT_MONTHLY_PLANS.tab>>>
@XXCSO_DEPT_MONTHLY_PLANS.tab;
PROMPT XXCSO_DEPT_SALES_STAFFS.tab>>>
@XXCSO_DEPT_SALES_STAFFS.tab;
PROMPT XXCSO_DESTINATIONS.tab>>>
@XXCSO_DESTINATIONS.tab;
PROMPT XXCSO_IB_INFO_H.tab>>>
@XXCSO_IB_INFO_H.tab;
PROMPT XXCSO_IN_ITEM_DATA.tab>>>
@XXCSO_IN_ITEM_DATA.tab;
PROMPT XXCSO_IN_NOTES.tab>>>
@XXCSO_IN_NOTES.tab;
PROMPT XXCSO_IN_ROUTE_NO.tab>>>
@XXCSO_IN_ROUTE_NO.tab;
PROMPT XXCSO_IN_SALES_PLAN_DAY.tab>>>
@XXCSO_IN_SALES_PLAN_DAY.tab;
PROMPT XXCSO_IN_SALES_PLAN_MONTH.tab>>>
@XXCSO_IN_SALES_PLAN_MONTH.tab;
PROMPT XXCSO_IN_WORK_DATA.tab>>>
@XXCSO_IN_WORK_DATA.tab;
PROMPT XXCSO_PV_DEF.tab>>>
@XXCSO_PV_DEF.tab;
PROMPT XXCSO_PV_EXTRACT_TERM_DEF.tab>>>
@XXCSO_PV_EXTRACT_TERM_DEF.tab;
PROMPT XXCSO_PV_SORT_COLUMN_DEF.tab>>>
@XXCSO_PV_SORT_COLUMN_DEF.tab;
PROMPT XXCSO_PV_VIEW_COLUMN_DEF.tab>>>
@XXCSO_PV_VIEW_COLUMN_DEF.tab;
PROMPT XXCSO_QUOTE_HEADERS.tab>>>
@XXCSO_QUOTE_HEADERS.tab;
PROMPT XXCSO_QUOTE_LINES.tab>>>
@XXCSO_QUOTE_LINES.tab;
PROMPT XXCSO_REP_AUTO_SALE_CONT.tab>>>
@XXCSO_REP_AUTO_SALE_CONT.tab;
PROMPT XXCSO_REP_NOVISIT.tab>>>
@XXCSO_REP_NOVISIT.tab;
PROMPT XXCSO_REP_QUOTE_LIST.tab>>>
@XXCSO_REP_QUOTE_LIST.tab;
PROMPT XXCSO_REP_VISIT_ROUTE_MNG.tab>>>
@XXCSO_REP_VISIT_ROUTE_MNG.tab;
PROMPT XXCSO_REP_VISIT_SALESEMP.tab>>>
@XXCSO_REP_VISIT_SALESEMP.tab;
PROMPT XXCSO_REP_VISIT_SALE_PLAN.tab>>>
@XXCSO_REP_VISIT_SALE_PLAN.tab;
PROMPT XXCSO_SALES_HEADERS.tab>>>
@XXCSO_SALES_HEADERS.tab;
PROMPT XXCSO_SALES_HEADERS_HIST.tab>>>
@XXCSO_SALES_HEADERS_HIST.tab;
PROMPT XXCSO_SALES_LINES.tab>>>
@XXCSO_SALES_LINES.tab;
PROMPT XXCSO_SALES_LINES_HIST.tab>>>
@XXCSO_SALES_LINES_HIST.tab;
PROMPT XXCSO_SALES_NOTIFIES.tab>>>
@XXCSO_SALES_NOTIFIES.tab;
PROMPT XXCSO_SLS_PRSN_MNTHLY_PLNS.tab>>>
@XXCSO_SLS_PRSN_MNTHLY_PLNS.tab;
PROMPT XXCSO_SP_DECISION_ATTACHES.tab>>>
@XXCSO_SP_DECISION_ATTACHES.tab;
PROMPT XXCSO_SP_DECISION_CUSTS.tab>>>
@XXCSO_SP_DECISION_CUSTS.tab;
PROMPT XXCSO_SP_DECISION_HEADERS.tab>>>
@XXCSO_SP_DECISION_HEADERS.tab;
PROMPT XXCSO_SP_DECISION_LINES.tab>>>
@XXCSO_SP_DECISION_LINES.tab;
PROMPT XXCSO_SP_DECISION_SENDS.tab>>>
@XXCSO_SP_DECISION_SENDS.tab;
PROMPT XXCSO_SP_DECISION_WF_ORGS.tab>>>
@XXCSO_SP_DECISION_WF_ORGS.tab;
PROMPT XXCSO_SUM_VISIT_SALE_REP.tab>>>
@XXCSO_SUM_VISIT_SALE_REP.tab;
PROMPT XXCSO_TMP_SALES_PLAN.tab>>>
@XXCSO_TMP_SALES_PLAN.tab;
PROMPT XXCSO_TMP_SALES_REQUEST.tab>>>
@XXCSO_TMP_SALES_REQUEST.tab;
PROMPT XXCSO_TMP_SP_DEC_REQUEST.tab>>>
@XXCSO_TMP_SP_DEC_REQUEST.tab;
PROMPT XXCSO_TMP_TXN_UTILITY.tab>>>
@XXCSO_TMP_TXN_UTILITY.tab;
PROMPT XXCSO_WK_REQUISITION_PROC.tab>>>
@XXCSO_WK_REQUISITION_PROC.tab;
