PROMPT XXCSM_ITEM_PLAN_HEADERS.tab>>>
@XXCSM_ITEM_PLAN_HEADERS.tab;
PROMPT XXCSM_ITEM_PLAN_LINES.tab>>>
@XXCSM_ITEM_PLAN_LINES.tab;
PROMPT XXCSM_ITEM_PLAN_LOC_BDGT.tab>>>
@XXCSM_ITEM_PLAN_LOC_BDGT.tab;
PROMPT XXCSM_ITEM_PLAN_RESULT.tab>>>
@XXCSM_ITEM_PLAN_RESULT.tab;
PROMPT XXCSM_MST_GRANT_POINT.tab>>>
@XXCSM_MST_GRANT_POINT.tab;
PROMPT XXCSM_MST_QUALIFICATE_PNT.tab>>>
@XXCSM_MST_QUALIFICATE_PNT.tab;
PROMPT XXCSM_NEWS_ITEM_HEADERS_ALL.tab>>>
@XXCSM_NEWS_ITEM_HEADERS_ALL.tab;
PROMPT XXCSM_NEWS_ITEM_LINES_ALL.tab>>>
@XXCSM_NEWS_ITEM_LINES_ALL.tab;
PROMPT XXCSM_NEW_CUST_POINT_HST.tab>>>
@XXCSM_NEW_CUST_POINT_HST.tab;
PROMPT XXCSM_SALES_PLAN.tab>>>
@XXCSM_SALES_PLAN.tab;
PROMPT XXCSM_TMP_CUST_ACCOUNTS.tab>>>
@XXCSM_TMP_CUST_ACCOUNTS.tab;
PROMPT XXCSM_TMP_ITEM_PLAN_GUN.tab>>>
@XXCSM_TMP_ITEM_PLAN_GUN.tab;
PROMPT XXCSM_TMP_ITEM_PLAN_SALES.tab>>>
@XXCSM_TMP_ITEM_PLAN_SALES.tab;
PROMPT XXCSM_TMP_ITEM_PLAN_SALES_SUM.tab>>>
@XXCSM_TMP_ITEM_PLAN_SALES_SUM.tab;
PROMPT XXCSM_TMP_MONTH_ITEM_PLAN.tab>>>
@XXCSM_TMP_MONTH_ITEM_PLAN.tab;
PROMPT XXCSM_TMP_SALES_PLAN_CS.tab>>>
@XXCSM_TMP_SALES_PLAN_CS.tab;
PROMPT XXCSM_TMP_SALES_PLAN_GUN.tab>>>
@XXCSM_TMP_SALES_PLAN_GUN.tab;
PROMPT XXCSM_TMP_SALES_PLAN_HON.tab>>>
@XXCSM_TMP_SALES_PLAN_HON.tab;
PROMPT XXCSM_TMP_SALES_PLAN_REF.tab>>>
@XXCSM_TMP_SALES_PLAN_REF.tab;
PROMPT XXCSM_TMP_SALES_PLAN_TIME.tab>>>
@XXCSM_TMP_SALES_PLAN_TIME.tab;
PROMPT XXCSM_TMP_SALES_RESULT.tab>>>
@XXCSM_TMP_SALES_RESULT.tab;
PROMPT XXCSM_WK_NEW_CUST_GET_EMP.tab>>>
@XXCSM_WK_NEW_CUST_GET_EMP.tab;
PROMPT XXCSM_WK_SALES_PLAN.tab>>>
@XXCSM_WK_SALES_PLAN.tab;
PROMPT XXCSM_WK_VENDING_PNT.tab>>>
@XXCSM_WK_VENDING_PNT.tab;
