PROMPT XXCFO_ADPS_GL_INTERFACE.tab>>>
@XXCFO_ADPS_GL_INTERFACE.tab;
PROMPT XXCFO_PO_STATUS_MNG.tab>>>
@XXCFO_PO_STATUS_MNG.tab;
PROMPT XXCFO_REP_STANDARD_PO.tab>>>
@XXCFO_REP_STANDARD_PO.tab;
PROMPT XXCFO_TMP_STANDARD_DATA_PO.tab>>>
@XXCFO_TMP_STANDARD_DATA_PO.tab;
