PROMPT XXCFR_CSV_OUTS_TEMP.tab>>>
@XXCFR_CSV_OUTS_TEMP.tab;
PROMPT XXCFR_INVOICE_HEADERS.tab>>>
@XXCFR_INVOICE_HEADERS.tab;
PROMPT XXCFR_INVOICE_LINES.tab>>>
@XXCFR_INVOICE_LINES.tab;
PROMPT XXCFR_INV_INFO_TRANSFER.tab>>>
@XXCFR_INV_INFO_TRANSFER.tab;
PROMPT XXCFR_INV_TARGET_CUST_LIST.tab>>>
@XXCFR_INV_TARGET_CUST_LIST.tab;
PROMPT XXCFR_PAYMENT_NOTES.tab>>>
@XXCFR_PAYMENT_NOTES.tab;
PROMPT XXCFR_REP_INVOICE_LIST.tab>>>
@XXCFR_REP_INVOICE_LIST.tab;
PROMPT XXCFR_REP_SALES_REP_PAY_SCH.tab>>>
@XXCFR_REP_SALES_REP_PAY_SCH.tab;
PROMPT XXCFR_REP_ST_INVOICE_EX_TAX.tab>>>
@XXCFR_REP_ST_INVOICE_EX_TAX.tab;
PROMPT XXCFR_REP_ST_INVOICE_INC_TAX.tab>>>
@XXCFR_REP_ST_INVOICE_INC_TAX.tab;
PROMPT XXCFR_SALES_DATA_RELETES.tab>>>
@XXCFR_SALES_DATA_RELETES.tab;
PROMPT XXCFR_TAX_GAP_TRX_LIST.tab>>>
@XXCFR_TAX_GAP_TRX_LIST.tab;
