PROMPT XXCMM_CUST_ACCOUNTS.tab>>>
@XXCMM_CUST_ACCOUNTS.tab;
PROMPT XXCMM_IN_PEOPLE_IF.tab>>>
@XXCMM_IN_PEOPLE_IF.tab;
PROMPT XXCMM_MST_CORPORATE.tab>>>
@XXCMM_MST_CORPORATE.tab;
PROMPT XXCMM_OUT_PEOPLE_D_DISPENSER.tab>>>
@XXCMM_OUT_PEOPLE_D_DISPENSER.tab;
PROMPT XXCMM_REP_UNDEAL_LIST.tab>>>
@XXCMM_REP_UNDEAL_LIST.tab;
PROMPT XXCMM_SYSTEM_ITEMS_B.tab>>>
@XXCMM_SYSTEM_ITEMS_B.tab;
PROMPT XXCMM_SYSTEM_ITEMS_B_HST.tab>>>
@XXCMM_SYSTEM_ITEMS_B_HST.tab;
PROMPT XXCMM_WK_CUST_BATCH_REGIST.tab>>>
@XXCMM_WK_CUST_BATCH_REGIST.tab;
PROMPT XXCMM_WK_DISCCOST_BATCH_REGIST.tab>>>
@XXCMM_WK_DISCCOST_BATCH_REGIST.tab;
PROMPT XXCMM_WK_ITEMRSV_CSV.tab>>>
@XXCMM_WK_ITEMRSV_CSV.tab;
PROMPT XXCMM_WK_ITEM_BATCH_REGIST.tab>>>
@XXCMM_WK_ITEM_BATCH_REGIST.tab;
PROMPT XXCMM_WK_ITEM_CSV.tab>>>
@XXCMM_WK_ITEM_CSV.tab;
PROMPT XXCMM_WK_OPMCOST_BATCH_REGIST.tab>>>
@XXCMM_WK_OPMCOST_BATCH_REGIST.tab;
PROMPT XXCMM_WK_PEOPLE_RESP.tab>>>
@XXCMM_WK_PEOPLE_RESP.tab;
