PROMPT XXCCP_IF_JOB_STATUS.tab>>>
@XXCCP_IF_JOB_STATUS.tab;
PROMPT XXCCP_MRP_FILE_UL_INTERFACE.tab>>>
@XXCCP_MRP_FILE_UL_INTERFACE.tab;
PROMPT XXCCP_PROCESS_DATES.tab>>>
@XXCCP_PROCESS_DATES.tab;
