LOAD DATA
INFILE *
APPEND
INTO TABLE XXCMN_SITE_IF
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
SEQ_NUMBER,
PROC_CODE,
SHIP_TO_CODE,
BASE_CODE,
PARTY_SITE_NAME1,
PARTY_SITE_NAME2,
PARTY_SITE_ADDR1,
PARTY_SITE_ADDR2,
PHONE,
FAX,
ZIP,
PARTY_NUM,
ZIP2,
CUSTOMER_NAME1,
CUSTOMER_NAME2,
SALE_BASE_CODE,
RES_SALE_BASE_CODE,
CHAIN_STORE,
CHAIN_STORE_NAME,
CAL_CUST_APP_FLG,
DIRECT_SHIP_CODE,
SHIFT_JUDG_FLG
)