/************************************************************************
 * Copyright(c)Oracle Corporation Japan, 2008. All rights reserved.
 *
 * View Name       : XXCOP_STC_TRANS_P1_MV
 * Description     : 計画_入出庫情報マテリアライズドビュー
 * Version         : 1.3
 *
 * Change Record
 * ------------- ----- ---------------- ---------------------------------
 *  Date          Ver.  Editor           Description
 * ------------- ----- ---------------- ---------------------------------
 *  2009-03-04    1.0   SCS.Goto         新規作成(2009/01/23生産入出庫情報ビュー)
 *  2009-03-25    1.1   S.Kayahara       1408行目のセミコロン削除
 *  2009-06-08    1.2   SCS.Goto         T1_1365対応
 *  2009-09-14    1.3   SCS.Goto         障害:0001362対応
 *
 ************************************************************************/
--20090914_Ver1.3_0001362_SCS.Goto_DEL_START
--CREATE MATERIALIZED VIEW APPS.XXCOP_STC_TRANS_P1_MV
----20090608_Ver1.2_T1_1365_SCS.Goto_MOD_START
----ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
----STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
----PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
----TABLESPACE "APPS_TS_TX_DATA"
--  TABLESPACE "XXDATA2"
----20090608_Ver1.2_T1_1365_SCS.Goto_MOD_END
--  BUILD IMMEDIATE
--  USING INDEX
--  REFRESH COMPLETE ON DEMAND START WITH SYSDATE+0 NEXT SYSDATE + 1/24/60*10
--  USING DEFAULT LOCAL ROLLBACK SEGMENT
--  DISABLE QUERY REWRITE
--  AS
--  SELECT
--    ownership_code
--   ,whse_code
--   ,organization_id
--   ,item_no
--   ,inventory_location_id
--   ,item_id
--   ,lot_id
--   ,lot_no
--   ,manufacture_date
--   ,uniqe_sign
--   ,expiration_date
--   ,arrival_date
--   ,leaving_date
--   ,status
--   ,reason_code
--   ,reason_code_name
--   ,voucher_no
--   ,ukebaraisaki_name
--   ,deliver_to_name
--   ,stock_quantity
--   ,leaving_quantity
--FROM
--(
--  ------------------------------------------------------------------------
--  -- 入庫予定
--  ------------------------------------------------------------------------
--  -- 発注受入予定
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,iimb.item_no              item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,iimb.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TO_DATE(pha.attribute4, 'YYYY/MM/DD') arrival_date
--   ,TO_DATE(pha.attribute4, 'YYYY/MM/DD') leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,pha.segment1              voucher_no
--   ,xv.vendor_name            ukebaraisaki_name
--   ,NULL                      deliver_to_name
--   ,pla.quantity              stock_quantity
--   ,0                         leaving_quantity
--  FROM
--    po_headers_all     pha
--   ,po_lines_all       pla
--   ,po_vendors         pv
--   ,xxcmn_vendors      xv
--   ,ic_whse_mst        iwm
--   ,mtl_item_locations mil
--   ,ic_item_mst_b      iimb
--   ,mtl_system_items_b msib
--   ,ic_lots_mst        ilm
--   ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--    FROM
--      xxcmn_rcv_pay_mst xrpm
--     ,fnd_lookup_values flv
--    WHERE flv.lookup_type           = 'XXCMN_NEW_DIVISION'
--      AND flv.language              = 'JA'
--      AND flv.lookup_code           = xrpm.new_div_invent
--      AND xrpm.doc_type             = 'PORC'
--      AND xrpm.source_document_code = 'PO'
--      AND xrpm.use_div_invent       = 'Y'
--      AND xrpm.transaction_type     = 'DELIVER'
--    ) xrpm
--  WHERE pha.po_header_id        = pla.po_header_id
--    AND pha.attribute1         IN ('20', '25')
--    AND pla.attribute13         = 'N'
--    AND pla.cancel_flag        <> 'Y'
--    AND pla.item_id             = msib.inventory_item_id
--    AND pla.attribute1          = ilm.lot_no
--    AND ilm.item_id             = iimb.item_id
--    AND iimb.item_no            = msib.segment1
--    AND msib.organization_id    = FND_PROFILE.VALUE('XXCMN_MASTER_ORG_ID')
--    AND pha.attribute5          = mil.segment1
--    AND pha.vendor_id           = pv.vendor_id
--    AND pv.vendor_id            = xv.vendor_id
--    AND xv.start_date_active   <= TRUNC(SYSDATE)
--    AND xv.end_date_active     >= TRUNC(SYSDATE)
--    AND iwm.mtl_organization_id = mil.organization_id
--  UNION ALL
--  -- 移動入庫予定(指示 積送あり)
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,xmld.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TRUNC(xmrih.schedule_arrival_date)  arrival_date
--   ,TRUNC(xmrih.schedule_ship_date)     leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,xmrih.mov_num             voucher_no
--   ,mil2.description          ukebaraisaki_name
--   ,NULL                      deliver_to_name
--   ,xmld.actual_quantity      stock_quantity
--   ,0                         leaving_quantity
--  FROM
--    xxinv_mov_req_instr_headers xmrih
--   ,xxinv_mov_req_instr_lines   xmril
--   ,xxinv_mov_lot_details       xmld
--   ,ic_whse_mst                 iwm
--   ,mtl_item_locations          mil
--   ,mtl_item_locations          mil2
--   ,ic_lots_mst                 ilm
--   ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--    FROM
--      xxcmn_rcv_pay_mst xrpm
--     ,fnd_lookup_values flv
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'XFER'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.rcv_pay_div    = '1'
--    ) xrpm
--  WHERE xmrih.mov_hdr_id        = xmril.mov_hdr_id
--    AND xmrih.ship_to_locat_id  = mil.inventory_location_id
--    AND iwm.mtl_organization_id = mil.organization_id
--    AND xmrih.shipped_locat_id  = mil2.inventory_location_id
--    AND xmld.mov_line_id        = xmril.mov_line_id
--    AND xmld.item_id            = ilm.item_id
--    AND xmld.lot_id             = ilm.lot_id
--    AND xmld.document_type_code = '20'
--    AND xmld.record_type_code   = '10'
--    AND xmrih.mov_type          = '1'
--    AND xmrih.comp_actual_flg   = 'N'
--    AND xmrih.status           IN ('02', '03')
--    AND xmril.delete_flg        = 'N'
--  UNION ALL
--  -- 移動入庫予定(指示 積送なし)
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,xmld.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TRUNC(xmrih.schedule_arrival_date)  arrival_date
--   ,TRUNC(xmrih.schedule_ship_date)     leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,xmrih.mov_num             voucher_no
--   ,mil2.description          ukebaraisaki_name
--   ,NULL                      deliver_to_name
--   ,xmld.actual_quantity      stock_quantity
--   ,0                         leaving_quantity
--  FROM
--    xxinv_mov_req_instr_headers xmrih
--   ,xxinv_mov_req_instr_lines   xmril
--   ,xxinv_mov_lot_details       xmld
--   ,ic_whse_mst                 iwm
--   ,mtl_item_locations          mil
--   ,mtl_item_locations          mil2
--   ,ic_lots_mst                 ilm
--  ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--    FROM
--      xxcmn_rcv_pay_mst xrpm
--     ,fnd_lookup_values flv
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'TRNI'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.rcv_pay_div    = '1'
--    ) xrpm
--  WHERE xmrih.mov_hdr_id        = xmril.mov_hdr_id
--    AND xmrih.ship_to_locat_id  = mil.inventory_location_id
--    AND iwm.mtl_organization_id = mil.organization_id
--    AND xmrih.shipped_locat_id  = mil2.inventory_location_id
--    AND xmld.mov_line_id        = xmril.mov_line_id
--    AND xmld.item_id            = ilm.item_id
--    AND xmld.lot_id             = ilm.lot_id
--    AND xmld.document_type_code = '20'
--    AND xmld.record_type_code   = '10'
--    AND xmrih.mov_type          = '2'
--    AND xmrih.comp_actual_flg   = 'N'
--    AND xmrih.status           IN ('02', '03')
--    AND xmril.delete_flg        = 'N'
--  UNION ALL
--  -- 移動入庫予定(出庫報告有 積送あり)
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,xmld.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TRUNC(xmrih.schedule_arrival_date)  arrival_date
--   ,TRUNC(xmrih.schedule_ship_date)     leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,xmrih.mov_num             voucher_no
----20090608_Ver1.2_T1_1365_SCS.Goto_MOD_START
---- ,mil2.description          deliver_to_name
--   ,mil2.description          ukebaraisaki_name
----20090608_Ver1.2_T1_1365_SCS.Goto_MOD_END
--   ,NULL                      deliver_to_name
--   ,xmld.actual_quantity      stock_quantity
--   ,0                         leaving_quantity
--  FROM
--    xxinv_mov_req_instr_headers xmrih
--   ,xxinv_mov_req_instr_lines   xmril
--   ,xxinv_mov_lot_details       xmld
--   ,ic_whse_mst                 iwm
--   ,mtl_item_locations          mil
--   ,mtl_item_locations          mil2
--   ,ic_lots_mst                 ilm
--  ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--    FROM
--      xxcmn_rcv_pay_mst xrpm
--     ,fnd_lookup_values flv
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'XFER'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.rcv_pay_div    = '1'
--    ) xrpm
--  WHERE xmrih.mov_hdr_id        = xmril.mov_hdr_id
--    AND xmrih.ship_to_locat_id  = mil.inventory_location_id
--    AND iwm.mtl_organization_id = mil.organization_id
--    AND xmrih.shipped_locat_id  = mil2.inventory_location_id
--    AND xmld.mov_line_id        = xmril.mov_line_id
--    AND xmld.item_id            = ilm.item_id
--    AND xmld.lot_id             = ilm.lot_id
--    AND xmld.document_type_code = '20'
--    AND xmld.record_type_code   = '20'
--    AND xmrih.mov_type          = '1'
--    AND xmrih.comp_actual_flg   = 'N'
--    AND xmrih.status            = '04'
--    AND xmril.delete_flg        = 'N'
--  UNION ALL
--  -- 移動入庫予定(出庫報告有 積送なし)
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,xmld.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TRUNC(xmrih.schedule_arrival_date)  arrival_date
--   ,TRUNC(xmrih.schedule_ship_date)     leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,xmrih.mov_num             voucher_no
----20090608_Ver1.2_T1_1365_SCS.Goto_MOD_START
---- ,mil2.description          deliver_to_name
--   ,mil2.description          ukebaraisaki_name
----20090608_Ver1.2_T1_1365_SCS.Goto_MOD_END
--   ,NULL                      deliver_to_name
--   ,xmld.actual_quantity      stock_quantity
--   ,0                         leaving_quantity
--  FROM
--    xxinv_mov_req_instr_headers xmrih
--   ,xxinv_mov_req_instr_lines   xmril
--   ,xxinv_mov_lot_details       xmld
--   ,ic_whse_mst                 iwm
--   ,mtl_item_locations          mil
--   ,mtl_item_locations          mil2
--   ,ic_lots_mst                 ilm
--  ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--    FROM
--      xxcmn_rcv_pay_mst xrpm
--     ,fnd_lookup_values flv
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'TRNI'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.rcv_pay_div    = '1'
--    ) xrpm
--  WHERE xmrih.mov_hdr_id        = xmril.mov_hdr_id
--    AND xmrih.ship_to_locat_id  = mil.inventory_location_id
--    AND iwm.mtl_organization_id = mil.organization_id
--    AND xmrih.shipped_locat_id  = mil2.inventory_location_id
--    AND xmld.mov_line_id        = xmril.mov_line_id
--    AND xmld.item_id            = ilm.item_id
--    AND xmld.lot_id             = ilm.lot_id
--    AND xmld.document_type_code = '20'
--    AND xmld.record_type_code   = '20'
--    AND xmrih.mov_type          = '2'
--    AND xmrih.comp_actual_flg   = 'N'
--    AND xmrih.status            = '04'
--    AND xmril.delete_flg        = 'N'
--  UNION ALL
--  -- 生産入庫予定
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,gmd.item_id               item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TRUNC(gbh.plan_start_date)  arrival_date
--   ,TRUNC(gbh.plan_start_date)  leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,gbh.batch_no              voucher_no
--   ,grt.routing_desc          ukebaraisaki_name
--   ,NULL                      deliver_to_name
--   ,NVL(xmld.actual_quantity, 0) stock_quantity
--   ,0                         leaving_quantity
--  FROM
--    gme_batch_header      gbh
--   ,gme_material_details  gmd
--   ,gmd_routings_b        grb
--   ,gmd_routings_tl       grt
--   ,xxinv_mov_lot_details xmld
--   ,ic_tran_pnd           itp
--   ,ic_whse_mst           iwm
--   ,mtl_item_locations    mil
--   ,ic_lots_mst           ilm
--   ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--     ,xrpm.doc_type
--     ,xrpm.routing_class
--     ,xrpm.line_type
--     ,xrpm.hit_in_div
--    FROM
--      xxcmn_rcv_pay_mst xrpm
--     ,fnd_lookup_values flv
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'PROD'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.routing_class <> '70'
--    ) xrpm
--  WHERE gbh.batch_id            = gmd.batch_id
--    AND gmd.line_type          IN (1, 2)
--    AND itp.doc_type            = xrpm.doc_type
--    AND itp.doc_id              = gmd.batch_id
--    AND itp.line_id             = gmd.material_detail_id
--    AND itp.doc_line            = gmd.line_no
--    AND itp.line_type           = gmd.line_type
--    AND itp.item_id             = gmd.item_id
--    AND itp.completed_ind       = 0
--    AND itp.delete_mark         = 0
--    AND itp.item_id             = ilm.item_id
--    AND itp.lot_id              = ilm.lot_id
--    AND grb.attribute9          = mil.segment1
--    AND xmld.mov_line_id        = gmd.material_detail_id
--    AND xmld.document_type_code = '40'
--    AND xmld.record_type_code   = '10'
--    AND xmld.lot_id             = ilm.lot_id
--    AND gbh.batch_status       IN (1, 2)
--    AND grb.routing_id          = gbh.routing_id
--    AND xrpm.routing_class      = grb.routing_class
--    AND xrpm.line_type          = gmd.line_type
--    AND ((( gmd.attribute5 IS NULL )     AND ( xrpm.hit_in_div IS NULL ))
--      OR (( gmd.attribute5 IS NOT NULL ) AND ( xrpm.hit_in_div  = gmd.attribute5 )))
--    AND grb.routing_id          = grt.routing_id
--    AND grt.language            = 'JA'
--    AND iwm.mtl_organization_id = mil.organization_id
--  UNION ALL
--  -- 品目振替予定
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,xmld.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TRUNC(gbh.plan_start_date)  arrival_date
--   ,TRUNC(gbh.plan_start_date)  leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,gbh.batch_no              voucher_no
--   ,grt.routing_desc          ukebaraisaki_name
--   ,NULL                      deliver_to_name
--   ,xmld.actual_quantity      stock_quantity
--   ,0                         leaving_quantity
--  FROM
--    gme_batch_header      gbh
--   ,gme_material_details  gmd
--   ,gme_material_details  gmd2
--   ,xxinv_mov_lot_details xmld
--   ,gmd_routings_b        grb
--   ,gmd_routings_tl       grt
--   ,ic_tran_pnd           itp
--   ,ic_whse_mst           iwm
--   ,mtl_item_locations    mil
--   ,ic_lots_mst           ilm
--   ,gmi_item_categories   gic
--   ,mtl_categories_b      mcb
--   ,gmi_item_categories   gic2
--   ,mtl_categories_b      mcb2
--   ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--     ,xrpm.routing_class
--     ,xrpm.line_type
--     ,xrpm.doc_type
--     ,xrpm.item_div_origin
--     ,xrpm.item_div_ahead
--    FROM
--      fnd_lookup_values flv
--     ,xxcmn_rcv_pay_mst xrpm
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'PROD'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.routing_class  = '70'
--    ) xrpm
--  WHERE gbh.batch_id            = gmd.batch_id
--    AND gmd.material_detail_id  = xmld.mov_line_id
--    AND gmd.line_type          IN (1, 2)
--    AND itp.doc_type            = xrpm.doc_type
--    AND itp.doc_id              = gmd.batch_id
--    AND itp.line_id             = gmd.material_detail_id
--    AND itp.doc_line            = gmd.line_no
--    AND itp.line_type           = gmd.line_type
--    AND itp.item_id             = gmd.item_id
--    AND itp.completed_ind       = 0
--    AND itp.delete_mark         = 0
--    AND itp.item_id             = ilm.item_id
--    AND itp.lot_id              = ilm.lot_id
--    AND itp.item_id             = gic.item_id
--    AND gic.category_set_id     = FND_PROFILE.VALUE('XXCMN_ITEM_CATEGORY_ITEM_CLASS')
--    AND mcb.category_id         = gic.category_id
--    AND xrpm.item_div_ahead     = mcb.segment1
--    AND gmd2.item_id            = gic2.item_id
--    AND gic2.category_set_id    = FND_PROFILE.VALUE('XXCMN_ITEM_CATEGORY_ITEM_CLASS')
--    AND mcb2.category_id        = gic.category_id
--    AND xrpm.item_div_origin    = mcb2.segment1
--    AND xmld.document_type_code = '40'
--    AND xmld.record_type_code   = '10'
--    AND xmld.item_id            = ilm.item_id
--    AND xmld.lot_id             = ilm.lot_id
--    AND grb.attribute9          = mil.segment1
--    AND iwm.mtl_organization_id = mil.organization_id
--    AND gbh.batch_status       IN (1, 2)
--    AND grb.routing_id          = gbh.routing_id
--    AND xrpm.routing_class      = grb.routing_class
--    AND xrpm.line_type          = gmd.line_type
--    AND gbh.batch_id            = gmd2.batch_id
--    AND gmd.batch_id            = gmd2.batch_id
--    AND gmd2.line_type          = -1
--    AND grb.routing_id          = grt.routing_id
--    AND grt.language            = 'JA'
--  UNION ALL
--  ------------------------------------------------------------------------
--  -- 出庫予定
--  ------------------------------------------------------------------------
--  -- 移動出庫予定(指示 積送あり)
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,xmld.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TRUNC(xmrih.schedule_arrival_date)  arrival_date
--   ,TRUNC(xmrih.schedule_ship_date)     leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,xmrih.mov_num             voucher_no
--   ,mil2.description          ukebaraisaki_name
--   ,NULL                      deliver_to_name
--   ,0                         stock_quantity
--   ,xmld.actual_quantity      leaving_quantity
--  FROM
--    xxinv_mov_req_instr_headers xmrih
--   ,xxinv_mov_req_instr_lines   xmril
--   ,xxinv_mov_lot_details       xmld
--   ,ic_whse_mst                 iwm
--   ,mtl_item_locations          mil
--   ,mtl_item_locations          mil2
--   ,ic_lots_mst                 ilm
--   ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--    FROM
--      fnd_lookup_values flv
--     ,xxcmn_rcv_pay_mst xrpm
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'XFER'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.rcv_pay_div    = '-1'
--    ) xrpm
--  WHERE xmrih.mov_hdr_id        = xmril.mov_hdr_id
--    AND xmrih.shipped_locat_id  = mil.inventory_location_id
--    AND iwm.mtl_organization_id = mil.organization_id
--    AND xmrih.ship_to_locat_id  = mil2.inventory_location_id
--    AND xmld.mov_line_id        = xmril.mov_line_id
--    AND xmld.item_id            = ilm.item_id
--    AND xmld.lot_id             = ilm.lot_id
--    AND xmld.document_type_code = '20'
--    AND xmld.record_type_code   = '10'
--    AND xmrih.mov_type          = '1'
--    AND xmrih.comp_actual_flg   = 'N'
--    AND xmrih.status           IN ('02', '03')
--    AND xmril.delete_flg        = 'N'
--  UNION ALL
--  -- 移動出庫予定(指示 積送なし)
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,xmld.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TRUNC(xmrih.schedule_arrival_date)  arrival_date
--   ,TRUNC(xmrih.schedule_ship_date)     leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,xmrih.mov_num             voucher_no
--   ,mil2.description          ukebaraisaki_name
--   ,NULL                      deliver_to_name
--   ,0                         stock_quantity
--   ,xmld.actual_quantity      leaving_quantity
--  FROM
--    xxinv_mov_req_instr_headers xmrih
--   ,xxinv_mov_req_instr_lines   xmril
--   ,xxinv_mov_lot_details       xmld
--   ,ic_whse_mst                 iwm
--   ,mtl_item_locations          mil
--   ,mtl_item_locations          mil2
--   ,ic_lots_mst                 ilm
--   ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--    FROM
--      fnd_lookup_values flv
--     ,xxcmn_rcv_pay_mst xrpm
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'TRNI'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.rcv_pay_div    = '-1'
--    ) xrpm
--  WHERE xmrih.mov_hdr_id        = xmril.mov_hdr_id
--    AND xmrih.shipped_locat_id  = mil.inventory_location_id
--    AND iwm.mtl_organization_id = mil.organization_id
--    AND xmrih.ship_to_locat_id  = mil2.inventory_location_id
--    AND xmld.mov_line_id        = xmril.mov_line_id
--    AND xmld.item_id            = ilm.item_id
--    AND xmld.lot_id             = ilm.lot_id
--    AND xmld.document_type_code = '20'
--    AND xmld.record_type_code   = '10'
--    AND xmrih.mov_type          = '2'
--    AND xmrih.comp_actual_flg   = 'N'
--    AND xmrih.status           IN ('02', '03')
--    AND xmril.delete_flg        = 'N'
--  UNION ALL
--  -- 移動出庫予定(入庫報告有 積送あり)
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,xmld.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TRUNC(xmrih.schedule_arrival_date)  arrival_date
--   ,TRUNC(xmrih.schedule_ship_date)     leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,xmrih.mov_num             voucher_no
--   ,mil2.description          ukebaraisaki_name
--   ,NULL                      deliver_to_name
--   ,0                         stock_quantity
--   ,xmld.actual_quantity      leaving_quantity
--  FROM
--    xxinv_mov_req_instr_headers xmrih
--   ,xxinv_mov_req_instr_lines   xmril
--   ,xxinv_mov_lot_details       xmld
--   ,ic_whse_mst                 iwm
--   ,mtl_item_locations          mil
--   ,mtl_item_locations          mil2
--   ,ic_lots_mst                 ilm
--   ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--    FROM
--      fnd_lookup_values flv
--     ,xxcmn_rcv_pay_mst xrpm
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'XFER'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.rcv_pay_div    = '-1'
--    ) xrpm
--  WHERE xmrih.mov_hdr_id        = xmril.mov_hdr_id
--    AND xmrih.shipped_locat_id  = mil.inventory_location_id
--    AND iwm.mtl_organization_id = mil.organization_id
--    AND xmrih.ship_to_locat_id  = mil2.inventory_location_id
--    AND xmld.mov_line_id        = xmril.mov_line_id
--    AND xmld.item_id            = ilm.item_id
--    AND xmld.lot_id             = ilm.lot_id
--    AND xmld.document_type_code = '20'
--    AND xmld.record_type_code   = '30'
--    AND xmrih.mov_type          = '1'
--    AND xmrih.comp_actual_flg   = 'N'
--    AND xmrih.status            = '05'
--    AND xmril.delete_flg        = 'N'
--  UNION ALL
--  -- 移動出庫予定(入庫報告有 積送なし)
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,xmld.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TRUNC(xmrih.schedule_arrival_date)  arrival_date
--   ,TRUNC(xmrih.schedule_ship_date)     leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,xmrih.mov_num             voucher_no
--   ,mil2.description          ukebaraisaki_name
--   ,NULL                      deliver_to_name
--   ,0                         stock_quantity
--   ,xmld.actual_quantity      leaving_quantity
--  FROM
--    xxinv_mov_req_instr_headers xmrih
--   ,xxinv_mov_req_instr_lines   xmril
--   ,xxinv_mov_lot_details       xmld
--   ,ic_whse_mst                 iwm
--   ,mtl_item_locations          mil
--   ,mtl_item_locations          mil2
--   ,ic_lots_mst                 ilm
--   ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--    FROM
--      fnd_lookup_values flv
--     ,xxcmn_rcv_pay_mst xrpm
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'TRNI'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.rcv_pay_div    = '-1'
--    ) xrpm
--  WHERE xmrih.mov_hdr_id        = xmril.mov_hdr_id
--    AND xmrih.shipped_locat_id  = mil.inventory_location_id
--    AND iwm.mtl_organization_id = mil.organization_id
--    AND xmrih.ship_to_locat_id  = mil2.inventory_location_id
--    AND xmld.mov_line_id        = xmril.mov_line_id
--    AND xmld.item_id            = ilm.item_id
--    AND xmld.lot_id             = ilm.lot_id
--    AND xmld.document_type_code = '20'
--    AND xmld.record_type_code   = '30'
--    AND xmrih.mov_type          = '2'
--    AND xmrih.comp_actual_flg   = 'N'
--    AND xmrih.status            = '05'
--    AND xmril.delete_flg        = 'N'
--  UNION ALL
--  -- 受注出荷予定
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,xmld.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TRUNC(xoha.schedule_arrival_date) arrival_date
--   ,TRUNC(xoha.schedule_ship_date)    leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,xoha.request_no           voucher_no
--   ,xp.party_name             ukebaraisaki_name
--   ,xpas.party_site_name      deliver_to_name
--   ,0                         stock_quantity
--   ,xmld.actual_quantity      leaving_quantity
--  FROM
--    xxwsh_order_headers_all   xoha
--   ,xxwsh_order_lines_all     xola
--   ,xxinv_mov_lot_details     xmld
--   ,oe_transaction_types_all  otta
--   ,ic_whse_mst               iwm
--   ,mtl_item_locations        mil
--   ,ic_item_mst_b             iimb2
--   ,mtl_system_items_b        msib2
--   ,ic_lots_mst               ilm
--   ,hz_cust_accounts          hcsa
--   ,hz_party_sites            hpas
--   ,xxcmn_party_sites         xpas
--   ,gmi_item_categories       gic
--   ,mtl_categories_b          mcb
--   ,xxcmn_parties             xp
--   ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--     ,xrpm.shipment_provision_div
--     ,xrpm.ship_prov_rcv_pay_category
--    FROM
--      fnd_lookup_values flv
--     ,xxcmn_rcv_pay_mst xrpm
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'OMSO'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.shipment_provision_div = '1'
--      AND xrpm.item_div_origin        = '5'
--      AND xrpm.item_div_ahead         = '5'
--    ) xrpm
--  WHERE xoha.order_header_id                = xola.order_header_id
--    AND xoha.deliver_from_id                = mil.inventory_location_id
--    AND iwm.mtl_organization_id             = mil.organization_id
--    AND xola.request_item_id                = msib2.inventory_item_id
--    AND iimb2.item_no                       = msib2.segment1
--    AND msib2.organization_id               = FND_PROFILE.VALUE('XXCMN_MASTER_ORG_ID')
--    AND xmld.mov_line_id                    = xola.order_line_id
--    AND xmld.document_type_code             = '10'
--    AND xmld.record_type_code               = '10'
--    AND xmld.item_id                        = ilm.item_id
--    AND xmld.lot_id                         = ilm.lot_id
--    AND xoha.req_status                     = '03'
--    AND NVL(xoha.actual_confirm_class, 'N') = 'N'
--    AND xoha.latest_external_flag           = 'Y'
--    AND xola.delete_flag                    = 'N'
--    AND xoha.order_type_id                  = otta.transaction_type_id
--    AND xrpm.shipment_provision_div         = otta.attribute1
--    AND gic.item_id                         = iimb2.item_id
--    AND gic.category_id                     = mcb.category_id
--    AND gic.category_set_id                 = FND_PROFILE.VALUE('XXCMN_ITEM_CATEGORY_ITEM_CLASS')
--    AND mcb.segment1                        = '5'
--    AND ( xrpm.ship_prov_rcv_pay_category   = otta.attribute11
--      OR  xrpm.ship_prov_rcv_pay_category  IS NULL )
--    AND xoha.head_sales_branch              = hcsa.account_number
--    AND xoha.deliver_to_id                  = hpas.party_site_id
--    AND hpas.party_site_id                  = xpas.party_site_id
--    AND hpas.party_id                       = xpas.party_id
--    AND hpas.location_id                    = xpas.location_id
--    AND xpas.start_date_active             <= TRUNC(SYSDATE)
--    AND xpas.end_date_active               >= TRUNC(SYSDATE)
--    AND hcsa.party_id                       = xp.party_id
--    AND xp.start_date_active               <= TRUNC(SYSDATE)
--    AND xp.end_date_active                 >= TRUNC(SYSDATE)
----20090608_Ver1.2_T1_1365_SCS.Goto_DEL_START
----UNION ALL
------ 有償出荷予定
----SELECT
----  iwm.attribute1            ownership_code
---- ,iwm.whse_code             whse_code
---- ,mil.organization_id       organization_id
---- ,xmld.item_code            item_no
---- ,mil.inventory_location_id inventory_location_id
---- ,xmld.item_id              item_id
---- ,ilm.lot_id                lot_id
---- ,ilm.lot_no                lot_no
---- ,ilm.attribute1            manufacture_date
---- ,ilm.attribute2            uniqe_sign
---- ,ilm.attribute3            expiration_date
---- ,NVL(TRUNC(xoha.schedule_arrival_date)
----     ,TRUNC(xoha.schedule_ship_date)) arrival_date
---- ,TRUNC(xoha.schedule_ship_date)      leaving_date
---- ,'1'                       status
---- ,xrpm.new_div_invent       reason_code
---- ,xrpm.meaning              reason_code_name
---- ,xoha.request_no           voucher_no
---- ,xvsa.vendor_site_name     ukebaraisaki_name
---- ,NULL                      vendor_site_name
---- ,0                         stock_quantity
---- ,CASE
----    WHEN ( xrpm.new_div_invent = '104' AND otta.order_category_code = 'RETURN' )
----  THEN
----    ABS(xmld.actual_quantity) * -1
----  ELSE
----    xmld.actual_quantity
----  END                       leaving_quantity
----FROM
----  xxwsh_order_headers_all   xoha
---- ,xxwsh_order_lines_all     xola
---- ,xxinv_mov_lot_details     xmld
---- ,oe_transaction_types_all  otta
---- ,ic_whse_mst               iwm
---- ,mtl_item_locations        mil
---- ,ic_item_mst_b             iimb
---- ,mtl_system_items_b        msib
---- ,ic_item_mst_b             iimb2
---- ,mtl_system_items_b        msib2
---- ,ic_lots_mst               ilm
---- ,gmi_item_categories       gic
---- ,mtl_categories_b          mcb
---- ,gmi_item_categories       gic2
---- ,mtl_categories_b          mcb2
---- ,xxcmn_vendor_sites_all    xvsa
---- ,(
----  SELECT
----    xrpm.new_div_invent
----   ,flv.meaning
----   ,xrpm.shipment_provision_div
----   ,xrpm.ship_prov_rcv_pay_category
----   ,xrpm.item_div_origin
----   ,xrpm.item_div_ahead
----  FROM
----    fnd_lookup_values flv
----   ,xxcmn_rcv_pay_mst xrpm
----  WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
----    AND flv.language        = 'JA'
----    AND flv.lookup_code     = xrpm.new_div_invent
----    AND xrpm.doc_type       = 'OMSO'
----    AND xrpm.use_div_invent = 'Y'
----    AND xrpm.shipment_provision_div = '2'
----    AND xrpm.item_div_origin        = '5'
----    AND xrpm.item_div_ahead         = '5'
----    AND xrpm.prod_div_origin       IS NOT NULL
----    AND xrpm.prod_div_ahead        IS NOT NULL
----  ) xrpm
----WHERE xoha.order_header_id                = xola.order_header_id
----  AND xoha.deliver_from_id                = mil.inventory_location_id
----  AND iwm.mtl_organization_id             = mil.organization_id
----  AND xola.shipping_inventory_item_id    <> xola.request_item_id
----  AND xola.request_item_id                = msib.inventory_item_id
----  AND iimb.item_no                        = msib.segment1
----  AND msib.organization_id                = FND_PROFILE.VALUE('XXCMN_MASTER_ORG_ID')
----  AND xola.shipping_inventory_item_id     = msib2.inventory_item_id
----  AND iimb2.item_no                       = msib2.segment1
----  AND msib2.organization_id               = FND_PROFILE.VALUE('XXCMN_MASTER_ORG_ID')
----  AND xmld.mov_line_id                    = xola.order_line_id
----  AND xmld.document_type_code             = '30'
----  AND xmld.record_type_code               = '10'
----  AND ilm.item_id                         = iimb2.item_id
----  AND xmld.lot_id                         = ilm.lot_id
----  AND xoha.req_status                     = '07'
----  AND NVL(xoha.actual_confirm_class, 'N') = 'N'
----  AND xoha.latest_external_flag           = 'Y'
----  AND xola.delete_flag                    = 'N'
----  AND xoha.order_type_id                  = otta.transaction_type_id
----  AND xrpm.shipment_provision_div         = otta.attribute1
----  AND gic.item_id                         = iimb.item_id
----  AND gic.category_id                     = mcb.category_id
----  AND gic.category_set_id                 = FND_PROFILE.VALUE('XXCMN_ITEM_CATEGORY_ITEM_CLASS')
----  AND mcb.segment1                        = '5'
----  AND gic2.item_id                        = iimb2.item_id
----  AND gic2.category_id                    = mcb2.category_id
----  AND gic2.category_set_id                = FND_PROFILE.VALUE('XXCMN_ITEM_CATEGORY_ITEM_CLASS')
----  AND mcb2.segment1                       = '5'
----  AND ( xrpm.ship_prov_rcv_pay_category   = otta.attribute11
----    OR  xrpm.ship_prov_rcv_pay_category  IS NULL )
----  AND xrpm.item_div_origin                = mcb2.segment1
----  AND xrpm.item_div_ahead                 = mcb.segment1
----  AND xvsa.vendor_site_id                 = xoha.vendor_site_id
----  AND xvsa.start_date_active             <= TRUNC(SYSDATE)
----  AND xvsa.end_date_active               >= TRUNC(SYSDATE)
----UNION ALL
----SELECT
----  iwm.attribute1            ownership_code
---- ,iwm.whse_code             whse_code
---- ,mil.organization_id       organization_id
---- ,xmld.item_code            item_no
---- ,mil.inventory_location_id inventory_location_id
---- ,xmld.item_id              item_id
---- ,ilm.lot_id                lot_id
---- ,ilm.lot_no                lot_no
---- ,ilm.attribute1            manufacture_date
---- ,ilm.attribute2            uniqe_sign
---- ,ilm.attribute3            expiration_date
---- ,NVL(TRUNC(xoha.schedule_arrival_date)
----     ,TRUNC(xoha.schedule_ship_date)) arrival_date
---- ,TRUNC(xoha.schedule_ship_date)      leaving_date
---- ,'1'                       status
---- ,xrpm.new_div_invent       reason_code
---- ,xrpm.meaning              reason_code_name
---- ,xoha.request_no           voucher_no
---- ,xvsa.vendor_site_name     ukebaraisaki_name
---- ,NULL                      vendor_site_name
---- ,0                         stock_quantity
---- ,CASE
----    WHEN ( xrpm.new_div_invent = '104' AND otta.order_category_code = 'RETURN' )
----  THEN
----    ABS(xmld.actual_quantity) * -1
----  ELSE
----    xmld.actual_quantity
----  END                       leaving_quantity
----FROM
----  xxwsh_order_headers_all   xoha
---- ,xxwsh_order_lines_all     xola
---- ,xxinv_mov_lot_details     xmld
---- ,oe_transaction_types_all  otta
---- ,ic_whse_mst               iwm
---- ,mtl_item_locations        mil
---- ,ic_item_mst_b             iimb
---- ,mtl_system_items_b        msib
---- ,ic_item_mst_b             iimb2
---- ,mtl_system_items_b        msib2
---- ,ic_lots_mst               ilm
---- ,gmi_item_categories       gic
---- ,mtl_categories_b          mcb
---- ,gmi_item_categories       gic2
---- ,mtl_categories_b          mcb2
---- ,xxcmn_vendor_sites_all    xvsa
---- ,(
----  SELECT
----    xrpm.new_div_invent
----   ,flv.meaning
----   ,xrpm.shipment_provision_div
----   ,xrpm.ship_prov_rcv_pay_category
----   ,xrpm.item_div_origin
----   ,DECODE(xrpm.item_div_ahead, '5', '5', 'Dummy') item_div_ahead
----  FROM
----    fnd_lookup_values flv
----   ,xxcmn_rcv_pay_mst xrpm
----  WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
----    AND flv.language        = 'JA'
----    AND flv.lookup_code     = xrpm.new_div_invent
----    AND xrpm.doc_type       = 'OMSO'
----    AND xrpm.use_div_invent = 'Y'
----    AND xrpm.shipment_provision_div = '2'
----    AND xrpm.item_div_origin        = '5'
----    AND xrpm.prod_div_origin       IS NULL
----    AND xrpm.prod_div_ahead        IS NULL
----  ) xrpm
----WHERE xoha.order_header_id                = xola.order_header_id
----  AND xoha.deliver_from_id                = mil.inventory_location_id
----  AND iwm.mtl_organization_id             = mil.organization_id
----  AND xola.shipping_inventory_item_id    <> xola.request_item_id
----  AND xola.request_item_id                = msib.inventory_item_id
----  AND iimb.item_no                        = msib.segment1
----  AND msib.organization_id                = FND_PROFILE.VALUE('XXCMN_MASTER_ORG_ID')
----  AND xola.shipping_inventory_item_id     = msib2.inventory_item_id
----  AND iimb2.item_no                       = msib2.segment1
----  AND msib2.organization_id               = FND_PROFILE.VALUE('XXCMN_MASTER_ORG_ID')
----  AND xmld.mov_line_id                    = xola.order_line_id
----  AND xmld.document_type_code             = '30'
----  AND xmld.record_type_code               = '10'
----  AND ilm.item_id                         = iimb2.item_id
----  AND xmld.lot_id                         = ilm.lot_id
----  AND xoha.req_status                     = '07'
----  AND NVL(xoha.actual_confirm_class, 'N') = 'N'
----  AND xoha.latest_external_flag           = 'Y'
----  AND xola.delete_flag                    = 'N'
----  AND xoha.order_type_id                  = otta.transaction_type_id
----  AND xrpm.shipment_provision_div         = otta.attribute1
----  AND gic.item_id                         = iimb.item_id
----  AND gic.category_id                     = mcb.category_id
----  AND gic.category_set_id                 = FND_PROFILE.VALUE('XXCMN_ITEM_CATEGORY_ITEM_CLASS')
----  AND mcb.segment1                        = '5'
----  AND gic2.item_id                        = iimb2.item_id
----  AND gic2.category_id                    = mcb2.category_id
----  AND gic2.category_set_id                = FND_PROFILE.VALUE('XXCMN_ITEM_CATEGORY_ITEM_CLASS')
----  AND xrpm.item_div_origin                = DECODE(mcb2.segment1, '5', '5', 'Dummy')
----  AND xrpm.item_div_ahead                 = mcb.segment1
----  AND ( xrpm.ship_prov_rcv_pay_category   = otta.attribute11
----    OR  xrpm.ship_prov_rcv_pay_category   IS NULL )
----  AND xvsa.vendor_site_id                 = xoha.vendor_site_id
----  AND xvsa.start_date_active             <= TRUNC(SYSDATE)
----  AND xvsa.end_date_active               >= TRUNC(SYSDATE)
----UNION ALL
----SELECT
----  iwm.attribute1            ownership_code
---- ,iwm.whse_code             whse_code
---- ,mil.organization_id       organization_id
---- ,xmld.item_code            item_no
---- ,mil.inventory_location_id inventory_location_id
---- ,xmld.item_id              item_id
---- ,ilm.lot_id                lot_id
---- ,ilm.lot_no                lot_no
---- ,ilm.attribute1            manufacture_date
---- ,ilm.attribute2            uniqe_sign
---- ,ilm.attribute3            expiration_date
---- ,NVL(TRUNC(xoha.schedule_arrival_date)
----     ,TRUNC(xoha.schedule_ship_date)) arrival_date
---- ,TRUNC(xoha.schedule_ship_date)      leaving_date
---- ,'1'                       status
---- ,xrpm.new_div_invent       reason_code
---- ,xrpm.meaning              reason_code_name
---- ,xoha.request_no           voucher_no
---- ,xvsa.vendor_site_name     ukebaraisaki_name
---- ,NULL                      vendor_site_name
---- ,0                         stock_quantity
---- ,CASE
----    WHEN ( xrpm.new_div_invent = '104' AND otta.order_category_code = 'RETURN' )
----  THEN
----    ABS(xmld.actual_quantity) * -1
----  ELSE
----    xmld.actual_quantity
----  END                       leaving_quantity
----FROM
----  xxwsh_order_headers_all   xoha
---- ,xxwsh_order_lines_all     xola
---- ,xxinv_mov_lot_details     xmld
---- ,oe_transaction_types_all  otta
---- ,ic_whse_mst               iwm
---- ,mtl_item_locations        mil
---- ,ic_item_mst_b             iimb
---- ,mtl_system_items_b        msib
---- ,ic_item_mst_b             iimb2
---- ,mtl_system_items_b        msib2
---- ,ic_lots_mst               ilm
---- ,gmi_item_categories       gic
---- ,mtl_categories_b          mcb
---- ,gmi_item_categories       gic2
---- ,mtl_categories_b          mcb2
---- ,xxcmn_vendor_sites_all    xvsa
---- ,(
----  SELECT
----    xrpm.new_div_invent
----   ,flv.meaning
----   ,xrpm.shipment_provision_div
----   ,xrpm.ship_prov_rcv_pay_category
----   ,xrpm.item_div_origin
----   ,DECODE(xrpm.item_div_ahead, '5', '5', 'Dummy') item_div_ahead
----  FROM
----    fnd_lookup_values flv
----   ,xxcmn_rcv_pay_mst xrpm
----  WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
----    AND flv.language        = 'JA'
----    AND flv.lookup_code     = xrpm.new_div_invent
----    AND xrpm.doc_type       = 'OMSO'
----    AND xrpm.use_div_invent = 'Y'
----    AND xrpm.shipment_provision_div = '2'
----    AND xrpm.item_div_origin        = '5'
----    AND xrpm.prod_div_origin       IS NULL
----    AND xrpm.prod_div_ahead        IS NULL
----  ) xrpm
----WHERE xoha.order_header_id                = xola.order_header_id
----  AND xoha.deliver_from_id                = mil.inventory_location_id
----  AND iwm.mtl_organization_id             = mil.organization_id
----  AND xola.shipping_inventory_item_id     = xola.request_item_id
----  AND xola.request_item_id                = msib.inventory_item_id
----  AND iimb.item_no                        = msib.segment1
----  AND msib.organization_id                = FND_PROFILE.VALUE('XXCMN_MASTER_ORG_ID')
----  AND xola.shipping_inventory_item_id     = msib2.inventory_item_id
----  AND iimb2.item_no                       = msib2.segment1
----  AND msib2.organization_id               = FND_PROFILE.VALUE('XXCMN_MASTER_ORG_ID')
----  AND xmld.mov_line_id                    = xola.order_line_id
----  AND xmld.document_type_code             = '30'
----  AND xmld.record_type_code               = '10'
----  AND ilm.item_id                         = iimb2.item_id
----  AND xmld.lot_id                         = ilm.lot_id
----  AND xoha.req_status                     = '07'
----  AND NVL(xoha.actual_confirm_class, 'N') = 'N'
----  AND xoha.latest_external_flag           = 'Y'
----  AND xola.delete_flag                    = 'N'
----  AND xoha.order_type_id                  = otta.transaction_type_id
----  AND xrpm.shipment_provision_div         = otta.attribute1
----  AND gic.item_id                         = iimb.item_id
----  AND gic.category_id                     = mcb.category_id
----  AND gic.category_set_id                 = FND_PROFILE.VALUE('XXCMN_ITEM_CATEGORY_ITEM_CLASS')
----  AND mcb.segment1                        = '5'
----  AND gic2.item_id                        = iimb2.item_id
----  AND gic2.category_id                    = mcb2.category_id
----  AND gic2.category_set_id                = FND_PROFILE.VALUE('XXCMN_ITEM_CATEGORY_ITEM_CLASS')
----  AND ( xrpm.ship_prov_rcv_pay_category   = otta.attribute11
----    OR  xrpm.ship_prov_rcv_pay_category  IS NULL )
----  AND xrpm.item_div_origin                = DECODE(mcb2.segment1, '5', '5', 'Dummy')
----  AND xrpm.item_div_ahead                 = mcb.segment1
----  AND xvsa.vendor_site_id                 = xoha.vendor_site_id
----  AND xvsa.start_date_active             <= TRUNC(SYSDATE)
----  AND xvsa.end_date_active               >= TRUNC(SYSDATE)
----20090608_Ver1.2_T1_1365_SCS.Goto_DEL_END
--  UNION ALL
--  -- 生産原料投入予定
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,xmld.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TRUNC(gbh.plan_start_date)  arrival_date
--   ,TRUNC(gbh.plan_start_date)  leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,gbh.batch_no              voucher_no
--   ,grt.routing_desc          ukebaraisaki_name
--   ,NULL                      deliver_to_name
--   ,0                         stock_quantity
--   ,xmld.actual_quantity      leaving_quantity
--  FROM
--    gme_batch_header      gbh
--   ,gme_material_details  gmd
--   ,xxinv_mov_lot_details xmld
--   ,gmd_routings_b        grb
--   ,gmd_routings_tl       grt
--   ,ic_tran_pnd           itp
--   ,ic_whse_mst           iwm
--   ,mtl_item_locations    mil
--   ,ic_lots_mst           ilm
--   ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--     ,xrpm.routing_class
--     ,xrpm.line_type
--     ,xrpm.hit_in_div
--     ,xrpm.doc_type
--    FROM
--      fnd_lookup_values flv
--     ,xxcmn_rcv_pay_mst xrpm
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'PROD'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.routing_class <> '70'
--    ) xrpm
--  WHERE gbh.batch_id            = gmd.batch_id
--    AND gmd.material_detail_id  = xmld.mov_line_id
--    AND gmd.line_type           = -1
--    AND itp.doc_type            = xrpm.doc_type
--    AND itp.doc_id              = gmd.batch_id
--    AND itp.line_id             = gmd.material_detail_id
--    AND itp.doc_line            = gmd.line_no
--    AND itp.line_type           = gmd.line_type
--    AND itp.item_id             = gmd.item_id
--    AND itp.completed_ind       = 0
--    AND itp.delete_mark         = 0
--    AND itp.item_id             = ilm.item_id
--    AND itp.lot_id              = ilm.lot_id
--    AND xmld.document_type_code = '40'
--    AND xmld.record_type_code   = '10'
--    AND xmld.item_id            = ilm.item_id
--    AND xmld.lot_id             = ilm.lot_id
--    AND grb.attribute9          = mil.segment1
--    AND iwm.mtl_organization_id = mil.organization_id
--    AND gbh.batch_status       IN (1, 2)
--    AND grb.routing_id          = gbh.routing_id
--    AND xrpm.routing_class      = grb.routing_class
--    AND xrpm.line_type          = gmd.line_type
--    AND ((( gmd.attribute5 IS NULL ) AND ( xrpm.hit_in_div IS NULL ))
--      OR (( gmd.attribute5  = 'Y' )  AND ( xrpm.hit_in_div  = gmd.attribute5 )))
--    AND grb.routing_id          = grt.routing_id
--    AND grt.language            = 'JA'
--  UNION ALL
--  -- 品目振替予定
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,xmld.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TRUNC(gbh.plan_start_date)  arrival_date
--   ,TRUNC(gbh.plan_start_date)  leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,gbh.batch_no              voucher_no
--   ,grt.routing_desc          ukebaraisaki_name
--   ,NULL                      deliver_to_name
--   ,0                         stock_quantity
--   ,xmld.actual_quantity      leaving_quantity
--  FROM
--    gme_batch_header      gbh
--   ,gme_material_details  gmd
--   ,gme_material_details  gmd2
--   ,xxinv_mov_lot_details xmld
--   ,gmd_routings_b        grb
--   ,gmd_routings_tl       grt
--   ,ic_tran_pnd           itp
--   ,ic_whse_mst           iwm
--   ,mtl_item_locations    mil
--   ,ic_lots_mst           ilm
--   ,gmi_item_categories   gic
--   ,mtl_categories_b      mcb
--   ,gmi_item_categories   gic2
--   ,mtl_categories_b      mcb2
--   ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--     ,xrpm.routing_class
--     ,xrpm.line_type
--     ,xrpm.doc_type
--     ,xrpm.item_div_origin
--     ,xrpm.item_div_ahead
--    FROM
--      fnd_lookup_values flv
--     ,xxcmn_rcv_pay_mst xrpm
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'PROD'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.routing_class  = '70'
--    ) xrpm
--  WHERE gbh.batch_id            = gmd.batch_id
--    AND gmd.material_detail_id  = xmld.mov_line_id
--    AND gmd.line_type           = -1
--    AND itp.doc_type            = xrpm.doc_type
--    AND itp.doc_id              = gmd.batch_id
--    AND itp.line_id             = gmd.material_detail_id
--    AND itp.doc_line            = gmd.line_no
--    AND itp.line_type           = gmd.line_type
--    AND itp.item_id             = gmd.item_id
--    AND itp.completed_ind       = 0
--    AND itp.delete_mark         = 0
--    AND itp.item_id             = ilm.item_id
--    AND itp.lot_id              = ilm.lot_id
--    AND itp.item_id             = gic.item_id
--    AND gic.category_set_id     = FND_PROFILE.VALUE('XXCMN_ITEM_CATEGORY_ITEM_CLASS')
--    AND mcb.category_id         = gic.category_id
--    AND xrpm.item_div_ahead     = mcb.segment1
--    AND gmd2.item_id            = gic2.item_id
--    AND gic2.category_set_id    = FND_PROFILE.VALUE('XXCMN_ITEM_CATEGORY_ITEM_CLASS')
--    AND mcb2.category_id        = gic.category_id
--    AND xrpm.item_div_origin    = mcb2.segment1
--    AND xmld.document_type_code = '40'
--    AND xmld.record_type_code   = '10'
--    AND xmld.item_id            = ilm.item_id
--    AND xmld.lot_id             = ilm.lot_id
--    AND grb.attribute9          = mil.segment1
--    AND iwm.mtl_organization_id = mil.organization_id
--    AND gbh.batch_status       IN (1, 2)
--    AND grb.routing_id          = gbh.routing_id
--    AND xrpm.routing_class      = grb.routing_class
--    AND xrpm.line_type          = gmd.line_type
--    AND gbh.batch_id            = gmd2.batch_id
--    AND gmd.batch_id            = gmd2.batch_id
--    AND gmd2.line_type          = -1
--    AND grb.routing_id          = grt.routing_id
--    AND grt.language            = 'JA'
--  UNION ALL
--  -- 相手先在庫出庫予定
--  SELECT
--    iwm.attribute1            ownership_code
--   ,iwm.whse_code             whse_code
--   ,mil.organization_id       organization_id
--   ,xmld.item_code            item_no
--   ,mil.inventory_location_id inventory_location_id
--   ,iimb.item_id              item_id
--   ,ilm.lot_id                lot_id
--   ,ilm.lot_no                lot_no
--   ,ilm.attribute1            manufacture_date
--   ,ilm.attribute2            uniqe_sign
--   ,ilm.attribute3            expiration_date
--   ,TO_DATE(pha.attribute4, 'YYYY/MM/DD') arrival_date
--   ,TO_DATE(pha.attribute4, 'YYYY/MM/DD') leaving_date
--   ,'1'                       status
--   ,xrpm.new_div_invent       reason_code
--   ,xrpm.meaning              reason_code_name
--   ,pha.segment1              voucher_no
--   ,xv.vendor_name            ukebaraisaki_name
--   ,NULL                      deliver_to_name
--   ,0                         stock_quantity
--   ,pla.quantity              leaving_quantity
--  FROM
--    po_headers_all        pha
--   ,po_lines_all          pla
--   ,xxinv_mov_lot_details xmld
--   ,ic_whse_mst           iwm
--   ,mtl_item_locations    mil
--   ,ic_item_mst_b         iimb
--   ,mtl_system_items_b    msib
--   ,ic_lots_mst           ilm
--   ,po_vendors            pv
--   ,xxcmn_vendors         xv
--   ,(
--    SELECT
--      xrpm.new_div_invent
--     ,flv.meaning
--    FROM
--      fnd_lookup_values flv
--     ,xxcmn_rcv_pay_mst xrpm
--    WHERE flv.lookup_type     = 'XXCMN_NEW_DIVISION'
--      AND flv.language        = 'JA'
--      AND flv.lookup_code     = xrpm.new_div_invent
--      AND xrpm.doc_type       = 'ADJI'
--      AND xrpm.use_div_invent = 'Y'
--      AND xrpm.reason_code    = 'X977'
--      AND xrpm.rcv_pay_div    = '-1'
--    ) xrpm
--  WHERE pha.po_header_id        = pla.po_header_id
--    AND pha.attribute1         IN ('20', '25')
--    AND pla.attribute13         = 'N'
--    AND pha.attribute11         = '3'
--    AND pla.po_line_id          = xmld.mov_line_id
--    AND pla.item_id             = msib.inventory_item_id
--    AND iimb.item_no            = msib.segment1
--    AND msib.organization_id    = FND_PROFILE.VALUE('XXCMN_MASTER_ORG_ID')
--    AND xmld.item_id            = ilm.item_id
--    AND xmld.lot_id             = ilm.lot_id
--    AND xmld.document_type_code = '50'
--    AND xmld.record_type_code   = '10'
--    AND pla.attribute12         = mil.segment1
--    AND iwm.mtl_organization_id = mil.organization_id
--    AND pha.vendor_id           = xv.vendor_id
--    AND pv.vendor_id            = xv.vendor_id
--    AND xv.start_date_active   <= TRUNC(SYSDATE)
--    AND xv.end_date_active     >= TRUNC(SYSDATE)
--)
--/
--20090914_Ver1.3_0001362_SCS.Goto_DEL_END
--20090914_Ver1.3_0001362_SCS.Goto_ADD_START
CREATE MATERIALIZED VIEW APPS.XXCOP_STC_TRANS_P1_MV
  TABLESPACE "XXDATA2"
  BUILD IMMEDIATE
  USING INDEX
  REFRESH COMPLETE ON DEMAND START WITH SYSDATE+0 NEXT SYSDATE + 1/24
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS
  SELECT
    '0'                     ownership_code,
    'A20'                   whse_code,
    1                       organization_id,
    '0000001'               item_no,
    1                       inventory_location_id,
    1                       item_id,
    ilm.lot_id              lot_id,
    ilm.lot_no              lot_no,
    FND_DATE.STRING_TO_DATE(ilm.attribute1, 'YYYY/MM/DD') manufacture_date,
    ilm.attribute2          uniqe_sign,
    FND_DATE.STRING_TO_DATE(ilm.attribute3, 'YYYY/MM/DD') expiration_date,
    FND_DATE.STRING_TO_DATE('2009/09/01', 'YYYY/MM/DD')   arrival_date,
    FND_DATE.STRING_TO_DATE('2009/09/01', 'YYYY/MM/DD')   leaving_date,
    '1'                     status,
    '100'                   reason_code,
    ' '                     reason_code_name,
    '000000000000'          voucher_no,
    ' '                     ukebaraisaki_name,
    ' '                     deliver_to_name,
    0                       stock_quantity,
    0                       leaving_quantity
  FROM ic_lots_mst  ilm
  WHERE ROWNUM = 1
/
--20090914_Ver1.3_0001362_SCS.Goto_ADD_END
--
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.OWNERSHIP_CODE IS '名義コード'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.WHSE_CODE IS '倉庫コード'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.ORGANIZATION_ID IS '在庫組織ID'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.ITEM_NO IS '品目コード'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.INVENTORY_LOCATION_ID IS '保管倉庫ID'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.ITEM_ID IS '品目ID'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.LOT_ID IS 'ロットID'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.LOT_NO IS 'ロットNO'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.MANUFACTURE_DATE IS '製造年月日'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.UNIQE_SIGN IS '固有記号'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.EXPIRATION_DATE IS '賞味期限'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.ARRIVAL_DATE IS '着日'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.LEAVING_DATE IS '発日'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.STATUS IS 'ステータス'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.REASON_CODE IS '事由コード'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.REASON_CODE_NAME IS '事由コード名'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.VOUCHER_NO IS '伝票NO'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.UKEBARAISAKI_NAME IS '受払先'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.DELIVER_TO_NAME IS '配送先'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.STOCK_QUANTITY IS '入庫数'
/
COMMENT ON COLUMN APPS.XXCOP_STC_TRANS_P1_MV.LEAVING_QUANTITY IS '出庫数'
/
