/*============================================================================
* ファイル名 : XxcsoCsvDownVORowImpl
* 概要説明   : ファイルダウンロードVO行クラス
* バージョン : 1.0
*============================================================================
* 修正履歴
* 日付       Ver. 担当者       修正内容
* ---------- ---- ------------ ----------------------------------------------
* 2008-12-19 1.0  SCS朴邦彦　  新規作成
*============================================================================
*/
package itoen.oracle.apps.xxcso.xxcso001001j.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.BlobDomain;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

/*******************************************************************************
 * ファイルダウンロードVO行クラス
 * @author  SCS朴邦彦
 * @version 1.0
 *******************************************************************************
 */
public class XxcsoCsvDownVORowImpl extends OAViewRowImpl 
{


  protected static final int BASENAME = 0;
  protected static final int BUSINESSYEAR = 1;
  protected static final int FILENAME = 2;
  protected static final int FILEDATA = 3;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public XxcsoCsvDownVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute BaseName
   */
  public String getBaseName()
  {
    return (String)getAttributeInternal(BASENAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute BaseName
   */
  public void setBaseName(String value)
  {
    setAttributeInternal(BASENAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute BusinessYear
   */
  public String getBusinessYear()
  {
    return (String)getAttributeInternal(BUSINESSYEAR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute BusinessYear
   */
  public void setBusinessYear(String value)
  {
    setAttributeInternal(BUSINESSYEAR, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute FileName
   */
  public String getFileName()
  {
    return (String)getAttributeInternal(FILENAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute FileName
   */
  public void setFileName(String value)
  {
    setAttributeInternal(FILENAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute FileData
   */
  public BlobDomain getFileData()
  {
    return (BlobDomain)getAttributeInternal(FILEDATA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute FileData
   */
  public void setFileData(BlobDomain value)
  {
    setAttributeInternal(FILEDATA, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case BASENAME:
        return getBaseName();
      case BUSINESSYEAR:
        return getBusinessYear();
      case FILENAME:
        return getFileName();
      case FILEDATA:
        return getFileData();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case BASENAME:
        setBaseName((String)value);
        return;
      case BUSINESSYEAR:
        setBusinessYear((String)value);
        return;
      case FILENAME:
        setFileName((String)value);
        return;
      case FILEDATA:
        setFileData((BlobDomain)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}