PROMPT XXCOS_BUSINESS_CONDITIONS_V.vw>>>
@XXCOS_BUSINESS_CONDITIONS_V.vw;
PROMPT XXCOS_CUSTOMER_ITEMS_V.vw>>>
@XXCOS_CUSTOMER_ITEMS_V.vw;
PROMPT XXCOS_EDI_STC_FORWARD_NUM_V.vw>>>
@XXCOS_EDI_STC_FORWARD_NUM_V.vw;
PROMPT XXCOS_EMPLOYEE_V.vw>>>
@XXCOS_EMPLOYEE_V.vw;
PROMPT XXCOS_GOOD_PROD_CLASS_V.vw>>>
@XXCOS_GOOD_PROD_CLASS_V.vw;
PROMPT XXCOS_HEAD_PROD_CLASS_V.vw>>>
@XXCOS_HEAD_PROD_CLASS_V.vw;
PROMPT XXCOS_ITEM_CONVERSIONS_V.vw>>>
@XXCOS_ITEM_CONVERSIONS_V.vw;
PROMPT XXCOS_LOOKUP_VALUES_V.vw>>>
@XXCOS_LOOKUP_VALUES_V.vw;
PROMPT XXCOS_ORDER_SALESREP_INFO_V.vw>>>
@XXCOS_ORDER_SALESREP_INFO_V.vw;
PROMPT XXCOS_RS_INFO_V.vw>>>
@XXCOS_RS_INFO_V.vw;
PROMPT XXCOS_SALESREPS_V.vw>>>
@XXCOS_SALESREPS_V.vw;
PROMPT XXCOS_TAX_RATE_V.vw>>>
@XXCOS_TAX_RATE_V.vw;
PROMPT XXCOS_USER_INFO_V.vw>>>
@XXCOS_USER_INFO_V.vw;
PROMPT XXCOS_CREATED_BY_OWN_BASE_V.vw>>>
@XXCOS_CREATED_BY_OWN_BASE_V.vw;
PROMPT XXCOS_LOGIN_BASE_INFO_V.vw>>>
@XXCOS_LOGIN_BASE_INFO_V.vw;
PROMPT XXCOS_LOGIN_OWN_BASE_INFO_V.vw>>>
@XXCOS_LOGIN_OWN_BASE_INFO_V.vw;
PROMPT XXCOS_ORDER_LOOKUP_VALUES_V.vw>>>
@XXCOS_ORDER_LOOKUP_VALUES_V.vw;
PROMPT XXCOS_CHAIN_STORE_SECURITY_V.vw>>>
@XXCOS_CHAIN_STORE_SECURITY_V.vw;
PROMPT XXCOS_CUSTOMER_SECURITY_V.vw>>>
@XXCOS_CUSTOMER_SECURITY_V.vw;
PROMPT XXCOS_DEPT_STORE_SECURITY_V.vw>>>
@XXCOS_DEPT_STORE_SECURITY_V.vw;
PROMPT XXCOS_EDI_CHAIN_SECURITY_V.vw>>>
@XXCOS_EDI_CHAIN_SECURITY_V.vw;
PROMPT XXCOS_EDI_STC_CHAIN_STORE_V.vw>>>
@XXCOS_EDI_STC_CHAIN_STORE_V.vw;
PROMPT XXCOS_ORDER_CUSOMTER_NUMBER_V.vw>>>
@XXCOS_ORDER_CUSOMTER_NUMBER_V.vw;
PROMPT XXCOS_TO_SUBINVENTORY_CODE_V.vw>>>
@XXCOS_TO_SUBINVENTORY_CODE_V.vw;
PROMPT XXCOS_CHAIN_SECURITY_V.vw>>>
@XXCOS_CHAIN_SECURITY_V.vw;
PROMPT XXCOS_DEPT_SECURITY_V.vw>>>
@XXCOS_DEPT_SECURITY_V.vw;
PROMPT XXCOS_DEPOSIT_STORE_SECURITY_V.vw>>>
@XXCOS_DEPOSIT_STORE_SECURITY_V.vw;
PROMPT XXCOS_DLV_HEADERS_INFO_V.vw>>>
@XXCOS_DLV_HEADERS_INFO_V.vw;
PROMPT XXCOS_EDI_STC_HEADERS_SUM_V.vw>>>
@XXCOS_EDI_STC_HEADERS_SUM_V.vw;
PROMPT XXCOS_LOGIN_BASE_DIRECT_V.vw>>>
@XXCOS_LOGIN_BASE_DIRECT_V.vw;
PROMPT XXCOS_DEPOSIT_SECURITY_V.vw>>>
@XXCOS_DEPOSIT_SECURITY_V.vw;
PROMPT XXCOS_DLV_LINES_INFO_V.vw>>>
@XXCOS_DLV_LINES_INFO_V.vw;
PROMPT XXCOS_CUST_HIERARCHY_V.vw>>>
@XXCOS_CUST_HIERARCHY_V.vw;
PROMPT XXCOS_ORDER_NUMBER_V.vw>>>
@XXCOS_ORDER_NUMBER_V.vw;
