PROMPT XXCOI_BASE_INFO2_V.vw>>>
@XXCOI_BASE_INFO2_V.vw;
PROMPT XXCOI_BASE_INFO_V.vw>>>
@XXCOI_BASE_INFO_V.vw;
PROMPT XXCOI_HHT_EBS_CONVERT_V.vw>>>
@XXCOI_HHT_EBS_CONVERT_V.vw;
PROMPT XXCOI_ITEM_TRANS_IN_V.vw>>>
@XXCOI_ITEM_TRANS_IN_V.vw;
PROMPT XXCOI_ITEM_TRANS_OUT_V.vw>>>
@XXCOI_ITEM_TRANS_OUT_V.vw;
PROMPT XXCOI_RECEIPT_SHIP_INPUT_V.vw>>>
@XXCOI_RECEIPT_SHIP_INPUT_V.vw;
PROMPT XXCOI_STORAGE_INFORMATION_V.vw>>>
@XXCOI_STORAGE_INFORMATION_V.vw;
PROMPT XXCOI_SUBINVENTORY_INFO_V.vw>>>
@XXCOI_SUBINVENTORY_INFO_V.vw;
PROMPT XXCOI_USER_BASE_INFO2_V.vw>>>
@XXCOI_USER_BASE_INFO2_V.vw;
PROMPT XXCOI_HHT_INV_DATE_V.vw>>>
@XXCOI_HHT_INV_DATE_V.vw;
PROMPT XXCOI_INV_YEAR_MONTH_V.vw>>>
@XXCOI_INV_YEAR_MONTH_V.vw;
PROMPT XXCOI_PRACTICE_MONTH_DAY_V.vw>>>
@XXCOI_PRACTICE_MONTH_DAY_V.vw;
PROMPT XXCOI_REC_DAILY_MONTHLY_V.vw>>>
@XXCOI_REC_DAILY_MONTHLY_V.vw;
PROMPT XXCOI_INVENTORY_APPROVE_V.vw>>>
@XXCOI_INVENTORY_APPROVE_V.vw;
PROMPT XXCOI_TXN_ENABLE_ITEM_INFO_V.vw>>>
@XXCOI_TXN_ENABLE_ITEM_INFO_V.vw;
PROMPT XXCOI_VD_COL_M_MTC_V.vw>>>
@XXCOI_VD_COL_M_MTC_V.vw;
PROMPT XXCOI_USER_BASE_INFO_V.vw>>>
@XXCOI_USER_BASE_INFO_V.vw;
