PROMPT XXCOP_ITEM_CATEGORIES1_V.vw>>>
@XXCOP_ITEM_CATEGORIES1_V.vw;
PROMPT XXCOP_PROD_CATEGORIES1_V.vw>>>
@XXCOP_PROD_CATEGORIES1_V.vw;
PROMPT XXCOP_STC_TRANS_P1_MV.vw>>>
@XXCOP_STC_TRANS_P1_MV.vw;
PROMPT XXCOP_STC_TRANS_V.vw>>>
@XXCOP_STC_TRANS_V.vw;
PROMPT XXCOP_BASE_CODE_V.vw>>>
@XXCOP_BASE_CODE_V.vw;
