PROMPT XXCSO_ACCT_WEEKLY_PLANS_V.vw>>>
@XXCSO_ACCT_WEEKLY_PLANS_V.vw;
PROMPT XXCSO_AFF_BASE_LEVEL_V.vw>>>
@XXCSO_AFF_BASE_LEVEL_V.vw;
PROMPT XXCSO_AFF_BASE_V.vw>>>
@XXCSO_AFF_BASE_V.vw;
PROMPT XXCSO_CUST_RESOURCES_V.vw>>>
@XXCSO_CUST_RESOURCES_V.vw;
PROMPT XXCSO_CUST_ROUTES_V.vw>>>
@XXCSO_CUST_ROUTES_V.vw;
PROMPT XXCSO_EMPLOYEES_V.vw>>>
@XXCSO_EMPLOYEES_V.vw;
PROMPT XXCSO_INVENTORY_ITEMS_V.vw>>>
@XXCSO_INVENTORY_ITEMS_V.vw;
PROMPT XXCSO_LOCATIONS_V.vw>>>
@XXCSO_LOCATIONS_V.vw;
PROMPT XXCSO_PV_EXTRACT_TERM_DEF_V.vw>>>
@XXCSO_PV_EXTRACT_TERM_DEF_V.vw;
PROMPT XXCSO_QUOTE_LINES_SALES_V.vw>>>
@XXCSO_QUOTE_LINES_SALES_V.vw;
PROMPT XXCSO_QUOTE_LINES_STORE_V.vw>>>
@XXCSO_QUOTE_LINES_STORE_V.vw;
PROMPT XXCSO_REP_VISIT_SALE_PLAN_V.vw>>>
@XXCSO_REP_VISIT_SALE_PLAN_V.vw;
PROMPT XXCSO_RESOURCES_V.vw>>>
@XXCSO_RESOURCES_V.vw;
PROMPT XXCSO_RESOURCE_CUSTS_V.vw>>>
@XXCSO_RESOURCE_CUSTS_V.vw;
PROMPT XXCSO_RESOURCE_RELATIONS_V.vw>>>
@XXCSO_RESOURCE_RELATIONS_V.vw;
PROMPT XXCSO_SALES_LINES_V.vw>>>
@XXCSO_SALES_LINES_V.vw;
PROMPT XXCSO_SALES_V.vw>>>
@XXCSO_SALES_V.vw;
PROMPT XXCSO_SP_DECISION_CUSTS_V.vw>>>
@XXCSO_SP_DECISION_CUSTS_V.vw;
PROMPT XXCSO_SP_DECISION_HEADERS_V.vw>>>
@XXCSO_SP_DECISION_HEADERS_V.vw;
PROMPT XXCSO_SP_DECISION_LINES_V.vw>>>
@XXCSO_SP_DECISION_LINES_V.vw;
PROMPT XXCSO_VISIT_ACTUAL_V.vw>>>
@XXCSO_VISIT_ACTUAL_V.vw;
PROMPT XXCSO_VISIT_V.vw>>>
@XXCSO_VISIT_V.vw;
PROMPT XXCSO_AFF_BASE_LEVEL_V2.vw>>>
@XXCSO_AFF_BASE_LEVEL_V2.vw;
PROMPT XXCSO_AFF_BASE_V2.vw>>>
@XXCSO_AFF_BASE_V2.vw;
PROMPT XXCSO_BANK_ACCTS_V.vw>>>
@XXCSO_BANK_ACCTS_V.vw;
PROMPT XXCSO_CUST_RESOURCES_V2.vw>>>
@XXCSO_CUST_RESOURCES_V2.vw;
PROMPT XXCSO_CUST_ROUTES_V2.vw>>>
@XXCSO_CUST_ROUTES_V2.vw;
PROMPT XXCSO_DEPT_MONTHLY_PLANS_V.vw>>>
@XXCSO_DEPT_MONTHLY_PLANS_V.vw;
PROMPT XXCSO_INVENTORY_ITEMS_V2.vw>>>
@XXCSO_INVENTORY_ITEMS_V2.vw;
PROMPT XXCSO_LOCATIONS_V2.vw>>>
@XXCSO_LOCATIONS_V2.vw;
PROMPT XXCSO_RTN_RSRC_V.vw>>>
@XXCSO_RTN_RSRC_V.vw;
PROMPT XXCSO_RESOURCE_CUSTS_V2.vw>>>
@XXCSO_RESOURCE_CUSTS_V2.vw;
PROMPT XXCSO_CUST_ACCOUNTS_V.vw>>>
@XXCSO_CUST_ACCOUNTS_V.vw;
PROMPT XXCSO_CUST_ACCT_SITES_V.vw>>>
@XXCSO_CUST_ACCT_SITES_V.vw;
PROMPT XXCSO_EMPLOYEES_V2.vw>>>
@XXCSO_EMPLOYEES_V2.vw;
PROMPT XXCSO_RESOURCES_V2.vw>>>
@XXCSO_RESOURCES_V2.vw;
PROMPT XXCSO_RESOURCE_RELATIONS_V2.vw>>>
@XXCSO_RESOURCE_RELATIONS_V2.vw;
PROMPT XXCSO_INSTALL_BASE_V.vw>>>
@XXCSO_INSTALL_BASE_V.vw;
PROMPT XXCSO_REQUISITION_LINES_V.vw>>>
@XXCSO_REQUISITION_LINES_V.vw;
PROMPT XXCSO_SALES_FOR_SLS_PRSN_V.vw>>>
@XXCSO_SALES_FOR_SLS_PRSN_V.vw;
PROMPT XXCSO_VISIT_SALES_RESULTS_V.vw>>>
@XXCSO_VISIT_SALES_RESULTS_V.vw;
PROMPT XXCSO_ACCT_MONTHLY_PLANS_V.vw>>>
@XXCSO_ACCT_MONTHLY_PLANS_V.vw;
