PROMPT XXCSM_PROCESS_DATE_V.vw>>>
@XXCSM_PROCESS_DATE_V.vw;
PROMPT XXCSM_SALES_EXP_HEADERS_V.vw>>>
@XXCSM_SALES_EXP_HEADERS_V.vw;
PROMPT XXCSM_SALES_EXP_LINES_V.vw>>>
@XXCSM_SALES_EXP_LINES_V.vw;
PROMPT XXCSM_DUTIES_LIST_V.vw>>>
@XXCSM_DUTIES_LIST_V.vw;
PROMPT XXCSM_HIERARCHY_LIST_V.vw>>>
@XXCSM_HIERARCHY_LIST_V.vw;
PROMPT XXCSM_ITEM_CATEGORY_V.vw>>>
@XXCSM_ITEM_CATEGORY_V.vw;
PROMPT XXCSM_LOC_LEVEL_LIST_V.vw>>>
@XXCSM_LOC_LEVEL_LIST_V.vw;
PROMPT XXCSM_LOC_NAME_LIST_V.vw>>>
@XXCSM_LOC_NAME_LIST_V.vw;
PROMPT XXCSM_MST_GRANT_POINT_V.vw>>>
@XXCSM_MST_GRANT_POINT_V.vw;
PROMPT XXCSM_NEWS_ITEM_HEADERS_ALL_V.vw>>>
@XXCSM_NEWS_ITEM_HEADERS_ALL_V.vw;
PROMPT XXCSM_QUALIFICATE_LIST_V.vw>>>
@XXCSM_QUALIFICATE_LIST_V.vw;
PROMPT XXCSM_NEWS_ITEM_SELECT_V.vw>>>
@XXCSM_NEWS_ITEM_SELECT_V.vw;
PROMPT XXCSM_ITEM_GROUP_1_NM_V.vw>>>
@XXCSM_ITEM_GROUP_1_NM_V.vw;
PROMPT XXCSM_ITEM_GROUP_2_NM_V.vw>>>
@XXCSM_ITEM_GROUP_2_NM_V.vw;
PROMPT XXCSM_ITEM_GROUP_3_NM_V.vw>>>
@XXCSM_ITEM_GROUP_3_NM_V.vw;
PROMPT XXCSM_ITEM_GROUP_ALL_V.vw>>>
@XXCSM_ITEM_GROUP_ALL_V.vw;
PROMPT XXCSM_COMMODITY_GROUP2_V.vw>>>
@XXCSM_COMMODITY_GROUP2_V.vw;
PROMPT XXCSM_COMMODITY_GROUP3_V.vw>>>
@XXCSM_COMMODITY_GROUP3_V.vw;
PROMPT XXCSM_COMMODITY_GROUP4_V.vw>>>
@XXCSM_COMMODITY_GROUP4_V.vw;
PROMPT XXCSM_NEWS_ITEM_LINES_ALL_V.vw>>>
@XXCSM_NEWS_ITEM_LINES_ALL_V.vw;
PROMPT XXCSM_LOCATION_ALL_V.vw>>>
@XXCSM_LOCATION_ALL_V.vw;
PROMPT XXCSM_MY_BRANCH_V.vw>>>
@XXCSM_MY_BRANCH_V.vw;
PROMPT XXCSM_MST_QUALIFICATE_PNT_V.vw>>>
@XXCSM_MST_QUALIFICATE_PNT_V.vw;
