PROMPT XXCFO_PAY_GROUP_V.vw>>>
@XXCFO_PAY_GROUP_V.vw;
PROMPT XXCFO_PO_DEPT_V.vw>>>
@XXCFO_PO_DEPT_V.vw;
PROMPT XXCFO_SECURITY_KOUBAI_V.vw>>>
@XXCFO_SECURITY_KOUBAI_V.vw;
PROMPT XXCFO_SECURITY_ZAIMU_V.vw>>>
@XXCFO_SECURITY_ZAIMU_V.vw;
