PROMPT XXCFF_ACCOUNTING_IF_FLAG_V.vw>>>
@XXCFF_ACCOUNTING_IF_FLAG_V.vw;
PROMPT XXCFF_ACTIVE_FLAG_V.vw>>>
@XXCFF_ACTIVE_FLAG_V.vw;
PROMPT XXCFF_AFF_ACCOUNT_V.vw>>>
@XXCFF_AFF_ACCOUNT_V.vw;
PROMPT XXCFF_AFF_BUSINESS_TYPE_V.vw>>>
@XXCFF_AFF_BUSINESS_TYPE_V.vw;
PROMPT XXCFF_AFF_COMPANY_V.vw>>>
@XXCFF_AFF_COMPANY_V.vw;
PROMPT XXCFF_AFF_DEPARTMENT_V.vw>>>
@XXCFF_AFF_DEPARTMENT_V.vw;
PROMPT XXCFF_AFF_FUTURE_V.vw>>>
@XXCFF_AFF_FUTURE_V.vw;
PROMPT XXCFF_AFF_PARTNER_V.vw>>>
@XXCFF_AFF_PARTNER_V.vw;
PROMPT XXCFF_AFF_PROJECT_V.vw>>>
@XXCFF_AFF_PROJECT_V.vw;
PROMPT XXCFF_AFF_SUB_ACCOUNT_V.vw>>>
@XXCFF_AFF_SUB_ACCOUNT_V.vw;
PROMPT XXCFF_BOND_ACCEPTANCE_FLAG_V.vw>>>
@XXCFF_BOND_ACCEPTANCE_FLAG_V.vw;
PROMPT XXCFF_CANCELLATION_CLASS_V.vw>>>
@XXCFF_CANCELLATION_CLASS_V.vw;
PROMPT XXCFF_CANCELLATION_TYPE_V.vw>>>
@XXCFF_CANCELLATION_TYPE_V.vw;
PROMPT XXCFF_CATEGORY_V.vw>>>
@XXCFF_CATEGORY_V.vw;
PROMPT XXCFF_CONTRACT_STATUS_V.vw>>>
@XXCFF_CONTRACT_STATUS_V.vw;
PROMPT XXCFF_DEPARTMENT_V.vw>>>
@XXCFF_DEPARTMENT_V.vw;
PROMPT XXCFF_FA_CATEGORY_V.vw>>>
@XXCFF_FA_CATEGORY_V.vw;
PROMPT XXCFF_FA_CCID_V.vw>>>
@XXCFF_FA_CCID_V.vw;
PROMPT XXCFF_FA_LOCATION_V.vw>>>
@XXCFF_FA_LOCATION_V.vw;
PROMPT XXCFF_LEASE_CLASS_V.vw>>>
@XXCFF_LEASE_CLASS_V.vw;
PROMPT XXCFF_LEASE_COMPANY_V.vw>>>
@XXCFF_LEASE_COMPANY_V.vw;
PROMPT XXCFF_LEASE_JOURNAL_PTN_V.vw>>>
@XXCFF_LEASE_JOURNAL_PTN_V.vw;
PROMPT XXCFF_LEASE_KIND_V.vw>>>
@XXCFF_LEASE_KIND_V.vw;
PROMPT XXCFF_LEASE_TYPE_V.vw>>>
@XXCFF_LEASE_TYPE_V.vw;
PROMPT XXCFF_OBJECT_ADJ_UPLOAD_V.vw>>>
@XXCFF_OBJECT_ADJ_UPLOAD_V.vw;
PROMPT XXCFF_OBJECT_STATUS_V.vw>>>
@XXCFF_OBJECT_STATUS_V.vw;
PROMPT XXCFF_OBJ_INS_STATUS_V.vw>>>
@XXCFF_OBJ_INS_STATUS_V.vw;
PROMPT XXCFF_OWNER_COMPANY_V.vw>>>
@XXCFF_OWNER_COMPANY_V.vw;
PROMPT XXCFF_PAYMENT_MATCH_FLAG_V.vw>>>
@XXCFF_PAYMENT_MATCH_FLAG_V.vw;
PROMPT XXCFF_PAYMENT_PLAN_DTL_V.vw>>>
@XXCFF_PAYMENT_PLAN_DTL_V.vw;
PROMPT XXCFF_PAYMENT_TYPE_V.vw>>>
@XXCFF_PAYMENT_TYPE_V.vw;
PROMPT XXCFF_RE_LEASE_FLAG_V.vw>>>
@XXCFF_RE_LEASE_FLAG_V.vw;
PROMPT XXCFF_OBJ_INS_DETAILS_V.vw>>>
@XXCFF_OBJ_INS_DETAILS_V.vw;
PROMPT XXCFF_OBJ_INS_HEADER_V.vw>>>
@XXCFF_OBJ_INS_HEADER_V.vw;
PROMPT XXCFF_FIXED_ASSETS_V.vw>>>
@XXCFF_FIXED_ASSETS_V.vw;
PROMPT XXCFF_PAYMENT_COLLATION_V.vw>>>
@XXCFF_PAYMENT_COLLATION_V.vw;
PROMPT XXCFF_LEASED_CONTRACT_INS_V.vw>>>
@XXCFF_LEASED_CONTRACT_INS_V.vw;
PROMPT XXCFF_LEASE_CONTRACT_DTL_INS_V.vw>>>
@XXCFF_LEASE_CONTRACT_DTL_INS_V.vw;
PROMPT XXCFF_LEASED_ASSETS_V.vw>>>
@XXCFF_LEASED_ASSETS_V.vw;
PROMPT XXCFF_LEASED_CONTRACT_V.vw>>>
@XXCFF_LEASED_CONTRACT_V.vw;
PROMPT XXCFF_LEASED_OBJECT_INS_V.vw>>>
@XXCFF_LEASED_OBJECT_INS_V.vw;
PROMPT XXCFF_LEASED_OBJECT_V.vw>>>
@XXCFF_LEASED_OBJECT_V.vw;
PROMPT XXCFF_OBJ_INS_REFERENCE_V.vw>>>
@XXCFF_OBJ_INS_REFERENCE_V.vw;
