PROMPT XXCFR_BILL_CUSTOMERS_V.vw>>>
@XXCFR_BILL_CUSTOMERS_V.vw;
PROMPT XXCFR_CUST_HIERARCHY_V.vw>>>
@XXCFR_CUST_HIERARCHY_V.vw;
PROMPT XXCFR_RECEIPT_CUST_ACCOUNTS_V.vw>>>
@XXCFR_RECEIPT_CUST_ACCOUNTS_V.vw;
