PROMPT XXCMM_CUST_ACCOUNTS_V.vw>>>
@XXCMM_CUST_ACCOUNTS_V.vw;
PROMPT XXCMM_HIERARCHY_DEPT_ALL_V.vw>>>
@XXCMM_HIERARCHY_DEPT_ALL_V.vw;
PROMPT XXCMM_OPMMTL_ITEMS_V.vw>>>
@XXCMM_OPMMTL_ITEMS_V.vw;
PROMPT XXCMM_HIERARCHY_DEPT_V.vw>>>
@XXCMM_HIERARCHY_DEPT_V.vw;
PROMPT XXCMM_ITEM_SCREEN_V.vw>>>
@XXCMM_ITEM_SCREEN_V.vw;
PROMPT XXCMM_CHANGE_RSV_V.vw>>>
@XXCMM_CHANGE_RSV_V.vw;
