/*============================================================================
 * Copyright(c)Sumisho Computer Systems Corporation, 2008. All rights reserved.
 * ファイル名 : Xx03ChkArCustomerVORowImpl.java
 * 概要説明   : 顧客ID存在チェック処理
 * バージョン : 1.0
 *============================================================================
 * 修正履歴
 * 日付       Ver. 担当者       修正内容
 * ---------- ---- ------------ ----------------------------------------------
 * 2008-11-10 1.0  scs 山口 優  新規作成
 *===========================================================================*/
package oracle.apps.xx03.ar.input.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
/**
 *
 * Xx03InvoiceInputPGのVO
 * @author      scs 山口 優
 * @version     1.0
 */
public class Xx03ChkArCustomerVORowImpl extends OAViewRowImpl 
{













  protected static final int CUSTOMERCNT = 0;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public Xx03ChkArCustomerVORowImpl()
  {
  }


  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CUSTOMERCNT:
        return getCustomerCnt();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CUSTOMERCNT:
        setCustomerCnt((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute CustomerCnt
   */
  public Number getCustomerCnt()
  {
    return (Number)getAttributeInternal(CUSTOMERCNT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute CustomerCnt
   */
  public void setCustomerCnt(Number value)
  {
    setAttributeInternal(CUSTOMERCNT, value);
  }
}