/*===========================================================================
 * Copyright (c) Oracle Corporation Japan, 2004-2005. All rights reserved.
 * FILENAME     Xx03ArCustomerLovVORowImpl.java
 * VERSION      11.5.10.2.8
 * DATE         2005/12/09
 * HISTORY      2005/02/14 ver 1.0         新規作成
 *              2005/09/26 ver 11.5.10.1.5 自動更新（パフォーマンス改善対応）
 *              2005/12/09 ver 11.5.10.1.6 値リストの表示をコードの昇順にする
 *                                          (ORDER BY句追加)
 *              2008/11/05 ver 11.5.10.2.8  値リストにセキュリティ条件を追加
 *===========================================================================*/
package oracle.apps.xx03.lov.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class Xx03ArCustomerLovVORowImpl extends OAViewRowImpl 
{


  protected static final int CUSTOMERNAME = 0;
  protected static final int ATTRIBUTE1 = 1;
  protected static final int CUSTOMERID = 2;
  protected static final int ADDRESSID = 3;
  protected static final int CUSTRECEIPTMETHODID = 4;
  protected static final int RECEIPTMETHODNAME = 5;
  protected static final int STANDARDTERMS = 6;
  protected static final int STANDARDTERMSNAME = 7;
  protected static final int ATTRIBUTE2 = 8;
  protected static final int TAXHEADERLEVELFLAG = 9;
  protected static final int TAXROUNDINGRULE = 10;
  protected static final int ADDRESSNAME = 11;
  protected static final int CUSTOMERNUMBER = 12;
  protected static final int PARTYNAME = 13;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public Xx03ArCustomerLovVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute CustomerName
   */
  public String getCustomerName()
  {
    return (String)getAttributeInternal(CUSTOMERNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute CustomerName
   */
  public void setCustomerName(String value)
  {
    setAttributeInternal(CUSTOMERNAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Attribute1
   */
  public String getAttribute1()
  {
    return (String)getAttributeInternal(ATTRIBUTE1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Attribute1
   */
  public void setAttribute1(String value)
  {
    setAttributeInternal(ATTRIBUTE1, value);
  }





  /**
   * 
   * Gets the attribute value for the calculated attribute ReceiptMethodName
   */
  public String getReceiptMethodName()
  {
    return (String)getAttributeInternal(RECEIPTMETHODNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ReceiptMethodName
   */
  public void setReceiptMethodName(String value)
  {
    setAttributeInternal(RECEIPTMETHODNAME, value);
  }



  /**
   * 
   * Gets the attribute value for the calculated attribute StandardTermsName
   */
  public String getStandardTermsName()
  {
    return (String)getAttributeInternal(STANDARDTERMSNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute StandardTermsName
   */
  public void setStandardTermsName(String value)
  {
    setAttributeInternal(STANDARDTERMSNAME, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CUSTOMERNAME:
        return getCustomerName();
      case ATTRIBUTE1:
        return getAttribute1();
      case CUSTOMERID:
        return getCustomerId();
      case ADDRESSID:
        return getAddressId();
      case CUSTRECEIPTMETHODID:
        return getCustReceiptMethodId();
      case RECEIPTMETHODNAME:
        return getReceiptMethodName();
      case STANDARDTERMS:
        return getStandardTerms();
      case STANDARDTERMSNAME:
        return getStandardTermsName();
      case ATTRIBUTE2:
        return getAttribute2();
      case TAXHEADERLEVELFLAG:
        return getTaxHeaderLevelFlag();
      case TAXROUNDINGRULE:
        return getTaxRoundingRule();
      case ADDRESSNAME:
        return getAddressName();
      case CUSTOMERNUMBER:
        return getCustomerNumber();
      case PARTYNAME:
        return getPartyName();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CUSTOMERNAME:
        setCustomerName((String)value);
        return;
      case ATTRIBUTE1:
        setAttribute1((String)value);
        return;
      case ATTRIBUTE2:
        setAttribute2((String)value);
        return;
      case TAXHEADERLEVELFLAG:
        setTaxHeaderLevelFlag((String)value);
        return;
      case TAXROUNDINGRULE:
        setTaxRoundingRule((String)value);
        return;
      case ADDRESSNAME:
        setAddressName((String)value);
        return;
      case CUSTOMERNUMBER:
        setCustomerNumber((String)value);
        return;
      case PARTYNAME:
        setPartyName((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute CustomerId
   */
  public String getCustomerId()
  {
    return (String)getAttributeInternal(CUSTOMERID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute CustomerId
   */
  public void setCustomerId(String value)
  {
    setAttributeInternal(CUSTOMERID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute AddressId
   */
  public String getAddressId()
  {
    return (String)getAttributeInternal(ADDRESSID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute AddressId
   */
  public void setAddressId(String value)
  {
    setAttributeInternal(ADDRESSID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute CustReceiptMethodId
   */
  public String getCustReceiptMethodId()
  {
    return (String)getAttributeInternal(CUSTRECEIPTMETHODID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute CustReceiptMethodId
   */
  public void setCustReceiptMethodId(String value)
  {
    setAttributeInternal(CUSTRECEIPTMETHODID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute StandardTerms
   */
  public String getStandardTerms()
  {
    return (String)getAttributeInternal(STANDARDTERMS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute StandardTerms
   */
  public void setStandardTerms(String value)
  {
    setAttributeInternal(STANDARDTERMS, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Attribute2
   */
  public String getAttribute2()
  {
    return (String)getAttributeInternal(ATTRIBUTE2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Attribute2
   */
  public void setAttribute2(String value)
  {
    setAttributeInternal(ATTRIBUTE2, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute TaxHeaderLevelFlag
   */
  public String getTaxHeaderLevelFlag()
  {
    return (String)getAttributeInternal(TAXHEADERLEVELFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute TaxHeaderLevelFlag
   */
  public void setTaxHeaderLevelFlag(String value)
  {
    setAttributeInternal(TAXHEADERLEVELFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute TaxRoundingRule
   */
  public String getTaxRoundingRule()
  {
    return (String)getAttributeInternal(TAXROUNDINGRULE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute TaxRoundingRule
   */
  public void setTaxRoundingRule(String value)
  {
    setAttributeInternal(TAXROUNDINGRULE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute AddressName
   */
  public String getAddressName()
  {
    return (String)getAttributeInternal(ADDRESSNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute AddressName
   */
  public void setAddressName(String value)
  {
    setAttributeInternal(ADDRESSNAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute CustomerNumber
   */
  public String getCustomerNumber()
  {
    return (String)getAttributeInternal(CUSTOMERNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute CustomerNumber
   */
  public void setCustomerNumber(String value)
  {
    setAttributeInternal(CUSTOMERNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute PartyName
   */
  public String getPartyName()
  {
    return (String)getAttributeInternal(PARTYNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute PartyName
   */
  public void setPartyName(String value)
  {
    setAttributeInternal(PARTYNAME, value);
  }
}