/*============================================================================
 * Copyright(c)Sumisho Computer Systems Corporation, 2008. All rights reserved.
 * ファイル名 : Xx03ChkArCustomerVOImpl.java
 * 概要説明   : 顧客ID存在チェック処理
 * バージョン : 1.0
 *============================================================================
 * 修正履歴
 * 日付       Ver. 担当者       修正内容
 * ---------- ---- ------------ ----------------------------------------------
 * 2008-11-10 1.0  scs 山口 優  新規作成
 *===========================================================================*/
package oracle.apps.xx03.ar.input.server;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
/**
 *
 * Xx03InvoiceInputPGのVO
 * @author      scs 山口 優
 * @version     1.0
 */
public class Xx03ChkArCustomerVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public Xx03ChkArCustomerVOImpl()
  {
  }

  /**
   * 
   * initQuery
   * @param customerId 顧客ＩＤ
   */
  public void initQuery(Number customerId)
  {
    setWhereClauseParams(null);
    setWhereClauseParam(0, customerId);
    executeQuery();
  } // initQuery

}