/*===========================================================================
 * Copyright (c) Oracle Corporation Japan, 2004-2005  All rights reserved
 * FILENAME   Xx03ArCustomerLovVOImpl.java
 * VERSION    11.5.10.2.8
 * DATE       2007/03/06
 * HISTORY    2005/09/26 ver 11.5.10.1.5  新規作成（パフォーマンス改善対応）
 *            2005/12/09 ver 11.5.10.1.6  値リストの表示をコードの昇順にする
 *                                        (JDevにてORDER BYオプション追加)
 *            2007/03/06 ver 11.5.10.2.7  セパレータを":"固定で判定している
 *                                        プロファイルの値を使用するように修正
 *            2008/11/05 ver 11.5.10.2.8  値リストにセキュリティ条件を追加
 *===========================================================================*/
package oracle.apps.xx03.lov.server;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import java.util.Vector;

//ver 11.5.10.2.7 Add Start
import oracle.apps.fnd.framework.server.OADBTransaction;
import oracle.apps.xx03.util.Xx03CommonUtil;
//ver 11.5.10.2.7 Add End

//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class Xx03ArCustomerLovVOImpl extends OAViewObjectImpl 
{

  /**
   * executeQuery
   */
  public void executeQuery()
  {
    super.executeQuery();
  } // executeQuery()

  /**
   * setWhere
   */
  public void setWhere(String searchText, String lovCategoryChoice)
  {
    StringBuffer whereClause = new StringBuffer(300);
    Vector       parameters  = new Vector(1);
    int clauseCount = 0;
    int bindCount   = 0;

    setWhereClauseParams(null);
    if((!"".equals(searchText)) && (searchText != null) 
                                && lovCategoryChoice.equals("CustomerName"))
    {
      whereClause.append(" (");

      //ver 11.5.10.2.7 Chg Start
      //// 「：」付き検索対応 
      //int codePos = searchText.indexOf(":");
      // プロファイル(セパレータ)付き検索対応 
      OADBTransaction transaction = (OADBTransaction)getDBTransaction();
      String delimiter = Xx03CommonUtil.getDelimiter(transaction);
      int codePos = searchText.indexOf(delimiter);
      //ver 11.5.10.2.7 Chg End
      if (codePos >= 0)
      {
        searchText = searchText.substring(0, codePos);
      }
      
      // like query
      whereClause.append(" CUSTOMER_NUMBER LIKE :");
      whereClause.append(++bindCount);
      parameters.addElement(searchText + "%");
      clauseCount++;

      // like query
      whereClause.append(" OR PARTY_NAME LIKE :");
      whereClause.append(++bindCount);
      parameters.addElement(searchText + "%");
      clauseCount++;

      whereClause.append(" )");
    }

    setWhereClause(whereClause.toString());

    if (bindCount > 0)
    {
      Object[] params = new Object[bindCount];
    
      parameters.copyInto(params);
      setWhereClauseParams(params);
    }
    
  } // setWhere()

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public Xx03ArCustomerLovVOImpl()
  {
  }
}