-- プロファイル値テーブル
--
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10878,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(    1,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(    2,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(    3,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(    4,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(    5,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(    6,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(    7,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(    8,'10001','0','P2D',SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(    9,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   10,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   11,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   12,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   13,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   14,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   15,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   16,'10001','0','P2D',SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   17,'10001','0','P2D',SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   18,'10001','0','P1D',SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   19,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   20,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   21,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   22,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   23,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   24,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   25,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   26,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(   27,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));

INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES( 1001,'10001','1', 'XXCCD010',SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES( 1002,'10001','1', 'Upload Interface Error and Job Output File to Universal Content Management',SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));

INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES( 1003,'10001','1', 'XXCCD010',SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES( 1004,'10001','1', 'Import Journals',SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES( 1003,'10001','2', 'XXCCD010',SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES( 1004,'10001','2', 'Upload Interface Error and Job Output File to Universal Content Management',SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));

INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10001,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10002,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10003,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10004,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10005,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10006,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10007,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10008,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10009,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10010,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10011,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10012,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10013,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10014,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10015,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10016,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10017,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10018,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10019,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10020,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10021,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));
INSERT INTO XXCCD_PROFILE_OPTION_VALUES VALUES(10022,'10001','0', null,SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'),SYS_CONTEXT('USERENV','SESSION_USER'),systimestamp at time zone('UTC'));

COMMIT;
