LOAD DATA
INFILE *
APPEND
INTO TABLE XXCMN_PARTY_IF
FIELDS TERMINATED BY ',' 
TRAILING NULLCOLS
(
SEQ_NUMBER,
PROC_CODE,
BASE_CODE,
PARTY_NAME,
PARTY_SHORT_NAME,
PARTY_NAME_ALT,
ADDRESS,
ZIP,
PHONE,
FAX,
OLD_DIVISION_CODE,
NEW_DIVISION_CODE,
DIVISION_START_DATE          DATE(8) "YYYYMMDD",
LOCATION_REL_CODE,
SHIP_MNG_CODE,
DISTRICT_CODE,
WAREHOUSE_CODE,
TERMINAL_CODE,
ZIP2,
SPARE
)
