/*============================================================================
* ファイル名 : XxccpLookUpValueVORowImpl.java
* 概要説明   : 参照タイプビューオブジェクト
* バージョン : 1.0
*============================================================================
* 修正履歴
* 日付       Ver. 担当者       修正内容
* ---------- ---- ------------ ----------------------------------------------
* 2008-11-13 1.0  SCS KUME     新規作成
*============================================================================
*/
package itoen.oracle.apps.xxccp.xxccp008A01j.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class XxccpLookUpValueVORowImpl extends OAViewRowImpl 
{
  protected static final int LOOKUPTYPE = 0;


  protected static final int LOOKUPCODE = 1;
  protected static final int MEANING = 2;
  protected static final int DESCRIPTION = 3;
  protected static final int STARTDATEACTIVE = 4;
  protected static final int ENDDATEACTIVE = 5;
  protected static final int SECURITYGROUPID = 6;
  protected static final int ATTRIBUTE1 = 7;
  protected static final int USER_CONCURRENT_PROGRAM_NAME = 8;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public XxccpLookUpValueVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute LookupType
   */
  public String getLookupType()
  {
    return (String)getAttributeInternal(LOOKUPTYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute LookupType
   */
  public void setLookupType(String value)
  {
    setAttributeInternal(LOOKUPTYPE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute LookupCode
   */
  public String getLookupCode()
  {
    return (String)getAttributeInternal(LOOKUPCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute LookupCode
   */
  public void setLookupCode(String value)
  {
    setAttributeInternal(LOOKUPCODE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Meaning
   */
  public String getMeaning()
  {
    return (String)getAttributeInternal(MEANING);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Meaning
   */
  public void setMeaning(String value)
  {
    setAttributeInternal(MEANING, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Description
   */
  public String getDescription()
  {
    return (String)getAttributeInternal(DESCRIPTION);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Description
   */
  public void setDescription(String value)
  {
    setAttributeInternal(DESCRIPTION, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute StartDateActive
   */
  public Date getStartDateActive()
  {
    return (Date)getAttributeInternal(STARTDATEACTIVE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute StartDateActive
   */
  public void setStartDateActive(Date value)
  {
    setAttributeInternal(STARTDATEACTIVE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute EndDateActive
   */
  public Date getEndDateActive()
  {
    return (Date)getAttributeInternal(ENDDATEACTIVE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute EndDateActive
   */
  public void setEndDateActive(Date value)
  {
    setAttributeInternal(ENDDATEACTIVE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute SecurityGroupId
   */
  public Number getSecurityGroupId()
  {
    return (Number)getAttributeInternal(SECURITYGROUPID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute SecurityGroupId
   */
  public void setSecurityGroupId(Number value)
  {
    setAttributeInternal(SECURITYGROUPID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Attribute1
   */
  public String getAttribute1()
  {
    return (String)getAttributeInternal(ATTRIBUTE1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Attribute1
   */
  public void setAttribute1(String value)
  {
    setAttributeInternal(ATTRIBUTE1, value);
  }
  /**
   * 
   * Gets the attribute value for the calculated attribute Programname
   */
  public String getProgramname()
  {
    return (String)getAttributeInternal(USER_CONCURRENT_PROGRAM_NAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Programname
   */
  public void setProgramname(String value)
  {
    setAttributeInternal(USER_CONCURRENT_PROGRAM_NAME, value);
  }

  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case LOOKUPTYPE:
        return getLookupType();
      case LOOKUPCODE:
        return getLookupCode();
      case MEANING:
        return getMeaning();
      case DESCRIPTION:
        return getDescription();
      case STARTDATEACTIVE:
        return getStartDateActive();
      case ENDDATEACTIVE:
        return getEndDateActive();
      case SECURITYGROUPID:
        return getSecurityGroupId();
      case ATTRIBUTE1:
        return getAttribute1();
      case USER_CONCURRENT_PROGRAM_NAME:
        return getProgramname();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case LOOKUPTYPE:
        setLookupType((String)value);
        return;
      case LOOKUPCODE:
        setLookupCode((String)value);
        return;
      case MEANING:
        setMeaning((String)value);
        return;
      case DESCRIPTION:
        setDescription((String)value);
        return;
      case STARTDATEACTIVE:
        setStartDateActive((Date)value);
        return;
      case ENDDATEACTIVE:
        setEndDateActive((Date)value);
        return;
      case SECURITYGROUPID:
        setSecurityGroupId((Number)value);
        return;
      case ATTRIBUTE1:
        setAttribute1((String)value);
        return;
      case USER_CONCURRENT_PROGRAM_NAME:
        setProgramname((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}