PROMPT XXCOK_001A01F_V.vw>>>
@XXCOK_001A01F_V.vw;
PROMPT XXCOK_BASE_ALL_V.vw>>>
@XXCOK_BASE_ALL_V.vw;
PROMPT XXCOK_BASE_V.vw>>>
@XXCOK_BASE_V.vw;
PROMPT XXCOK_LOOKUPS_V.vw>>>
@XXCOK_LOOKUPS_V.vw;
PROMPT XXCOK_LOV_BASE_CODE_V.vw>>>
@XXCOK_LOV_BASE_CODE_V.vw;
PROMPT XXCOK_021A02_HEADERS_V.vw>>>
@XXCOK_021A02_HEADERS_V.vw;
PROMPT XXCOK_BASE_CHILD_V.vw>>>
@XXCOK_BASE_CHILD_V.vw;
PROMPT XXCOK_021A02_LINES_V.vw>>>
@XXCOK_021A02_LINES_V.vw;
PROMPT XXCOK_SELLING_TRNS_FROM_V.vw>>>
@XXCOK_SELLING_TRNS_FROM_V.vw;
PROMPT XXCOK_SELLING_TRNS_TO_V.vw>>>
@XXCOK_SELLING_TRNS_TO_V.vw;
