package itoen.oracle.apps.xxinv.xxinv510002j.server;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class XxInvMovementShippedLotPVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public XxInvMovementShippedLotPVOImpl()
  {
  }
}