PROMPT XXCOS_CUST_PO_NUMBER_S01.syn>>>
@XXCOS_CUST_PO_NUMBER_S01.syn;
PROMPT XXCOS_DEPARTMENT_ORDER_NO_S01.syn>>>
@XXCOS_DEPARTMENT_ORDER_NO_S01.syn;
PROMPT XXCOS_DEPOSIT_ORDER_NO_S01.syn>>>
@XXCOS_DEPOSIT_ORDER_NO_S01.syn;
PROMPT XXCOS_DEPOSIT_ORDER_NO_S02.syn>>>
@XXCOS_DEPOSIT_ORDER_NO_S02.syn;
PROMPT XXCOS_DEPOSIT_ORDER_NO_S03.syn>>>
@XXCOS_DEPOSIT_ORDER_NO_S03.syn;
PROMPT XXCOS_DEPOSIT_VD_SLIP_WORK.syn>>>
@XXCOS_DEPOSIT_VD_SLIP_WORK.syn;
PROMPT XXCOS_DLV_HEADERS.syn>>>
@XXCOS_DLV_HEADERS.syn;
PROMPT XXCOS_DLV_HEADERS_S01.syn>>>
@XXCOS_DLV_HEADERS_S01.syn;
PROMPT XXCOS_DLV_HEADERS_WORK.syn>>>
@XXCOS_DLV_HEADERS_WORK.syn;
PROMPT XXCOS_DLV_LINES.syn>>>
@XXCOS_DLV_LINES.syn;
PROMPT XXCOS_DLV_LINES_WORK.syn>>>
@XXCOS_DLV_LINES_WORK.syn;
PROMPT XXCOS_EDI_DELIVERY_WORK.syn>>>
@XXCOS_EDI_DELIVERY_WORK.syn;
PROMPT XXCOS_EDI_DELIVERY_WORK_S01.syn>>>
@XXCOS_EDI_DELIVERY_WORK_S01.syn;
PROMPT XXCOS_EDI_ERRORS.syn>>>
@XXCOS_EDI_ERRORS.syn;
PROMPT XXCOS_EDI_ERRORS_S01.syn>>>
@XXCOS_EDI_ERRORS_S01.syn;
PROMPT XXCOS_EDI_HEADERS.syn>>>
@XXCOS_EDI_HEADERS.syn;
PROMPT XXCOS_EDI_HEADERS_S01.syn>>>
@XXCOS_EDI_HEADERS_S01.syn;
PROMPT XXCOS_EDI_HEADERS_S02.syn>>>
@XXCOS_EDI_HEADERS_S02.syn;
PROMPT XXCOS_EDI_INVENTORY.syn>>>
@XXCOS_EDI_INVENTORY.syn;
PROMPT XXCOS_EDI_INVENTORY_S01.syn>>>
@XXCOS_EDI_INVENTORY_S01.syn;
PROMPT XXCOS_EDI_INVENTORY_WORK.syn>>>
@XXCOS_EDI_INVENTORY_WORK.syn;
PROMPT XXCOS_EDI_INVENTORY_WORK_S01.syn>>>
@XXCOS_EDI_INVENTORY_WORK_S01.syn;
PROMPT XXCOS_EDI_LINES.syn>>>
@XXCOS_EDI_LINES.syn;
PROMPT XXCOS_EDI_LINES_S01.syn>>>
@XXCOS_EDI_LINES_S01.syn;
PROMPT XXCOS_EDI_ORDER_WORK.syn>>>
@XXCOS_EDI_ORDER_WORK.syn;
PROMPT XXCOS_EDI_ORDER_WORK_S01.syn>>>
@XXCOS_EDI_ORDER_WORK_S01.syn;
PROMPT XXCOS_EDI_STC_HEADERS.syn>>>
@XXCOS_EDI_STC_HEADERS.syn;
PROMPT XXCOS_EDI_STC_HEADERS_S01.syn>>>
@XXCOS_EDI_STC_HEADERS_S01.syn;
PROMPT XXCOS_EDI_STC_LINES.syn>>>
@XXCOS_EDI_STC_LINES.syn;
PROMPT XXCOS_EDI_STC_LINES_S01.syn>>>
@XXCOS_EDI_STC_LINES_S01.syn;
PROMPT XXCOS_FOR_ADPS_BONUS_IF.syn>>>
@XXCOS_FOR_ADPS_BONUS_IF.syn;
PROMPT XXCOS_FOR_ADPS_BONUS_IF_S01.syn>>>
@XXCOS_FOR_ADPS_BONUS_IF_S01.syn;
PROMPT XXCOS_FOR_ADPS_MONTHLY_IF.syn>>>
@XXCOS_FOR_ADPS_MONTHLY_IF.syn;
PROMPT XXCOS_FOR_ADPS_MONTHLY_IF_S01.syn>>>
@XXCOS_FOR_ADPS_MONTHLY_IF_S01.syn;
PROMPT XXCOS_ORDER_SOURCE_REF_S01.syn>>>
@XXCOS_ORDER_SOURCE_REF_S01.syn;
PROMPT XXCOS_PAYMENT.syn>>>
@XXCOS_PAYMENT.syn;
PROMPT XXCOS_PAYMENT_S01.syn>>>
@XXCOS_PAYMENT_S01.syn;
PROMPT XXCOS_PAYMENT_WORK.syn>>>
@XXCOS_PAYMENT_WORK.syn;
PROMPT XXCOS_REPORT_FORMS_REGISTER.syn>>>
@XXCOS_REPORT_FORMS_REGISTER.syn;
PROMPT XXCOS_REP_BUS_COUNTER_SUM_S01.syn>>>
@XXCOS_REP_BUS_COUNTER_SUM_S01.syn;
PROMPT XXCOS_REP_BUS_COUNT_SUM.syn>>>
@XXCOS_REP_BUS_COUNT_SUM.syn;
PROMPT XXCOS_REP_BUS_NEWCUST_SUM.syn>>>
@XXCOS_REP_BUS_NEWCUST_SUM.syn;
PROMPT XXCOS_REP_BUS_NEWCUST_SUM_S01.syn>>>
@XXCOS_REP_BUS_NEWCUST_SUM_S01.syn;
PROMPT XXCOS_REP_BUS_PERF.syn>>>
@XXCOS_REP_BUS_PERF.syn;
PROMPT XXCOS_REP_BUS_PERF_S01.syn>>>
@XXCOS_REP_BUS_PERF_S01.syn;
PROMPT XXCOS_REP_BUS_REPORT.syn>>>
@XXCOS_REP_BUS_REPORT.syn;
PROMPT XXCOS_REP_BUS_REPORT_S01.syn>>>
@XXCOS_REP_BUS_REPORT_S01.syn;
PROMPT XXCOS_REP_BUS_SALES_SUM.syn>>>
@XXCOS_REP_BUS_SALES_SUM.syn;
PROMPT XXCOS_REP_BUS_SALES_SUM_S01.syn>>>
@XXCOS_REP_BUS_SALES_SUM_S01.syn;
PROMPT XXCOS_REP_BUS_S_GROUP_SUM.syn>>>
@XXCOS_REP_BUS_S_GROUP_SUM.syn;
PROMPT XXCOS_REP_BUS_S_GROUP_SUM_S01.syn>>>
@XXCOS_REP_BUS_S_GROUP_SUM_S01.syn;
PROMPT XXCOS_REP_COST_DIV_LIST.syn>>>
@XXCOS_REP_COST_DIV_LIST.syn;
PROMPT XXCOS_REP_COST_DIV_LIST_S01.syn>>>
@XXCOS_REP_COST_DIV_LIST_S01.syn;
PROMPT XXCOS_REP_DELI_REQ.syn>>>
@XXCOS_REP_DELI_REQ.syn;
PROMPT XXCOS_REP_DELI_REQ_S01.syn>>>
@XXCOS_REP_DELI_REQ_S01.syn;
PROMPT XXCOS_REP_DIG_DV_LIST.syn>>>
@XXCOS_REP_DIG_DV_LIST.syn;
PROMPT XXCOS_REP_DIG_DV_LIST_S01.syn>>>
@XXCOS_REP_DIG_DV_LIST_S01.syn;
PROMPT XXCOS_REP_DIG_LIST.syn>>>
@XXCOS_REP_DIG_LIST.syn;
PROMPT XXCOS_REP_DIG_LIST_S01.syn>>>
@XXCOS_REP_DIG_LIST_S01.syn;
PROMPT XXCOS_REP_DIRECT_LIST.syn>>>
@XXCOS_REP_DIRECT_LIST.syn;
PROMPT XXCOS_REP_DIRECT_LIST_S01.syn>>>
@XXCOS_REP_DIRECT_LIST_S01.syn;
PROMPT XXCOS_REP_DLV_CHK_LIST.syn>>>
@XXCOS_REP_DLV_CHK_LIST.syn;
PROMPT XXCOS_REP_DLV_CHK_LIST_S01.syn>>>
@XXCOS_REP_DLV_CHK_LIST_S01.syn;
PROMPT XXCOS_REP_HHT_ERR_LIST.syn>>>
@XXCOS_REP_HHT_ERR_LIST.syn;
PROMPT XXCOS_REP_HHT_ERR_LIST_S01.syn>>>
@XXCOS_REP_HHT_ERR_LIST_S01.syn;
PROMPT XXCOS_REP_HHT_ERR_LIST_S02.syn>>>
@XXCOS_REP_HHT_ERR_LIST_S02.syn;
PROMPT XXCOS_REP_ORDER_ERR_LIST.syn>>>
@XXCOS_REP_ORDER_ERR_LIST.syn;
PROMPT XXCOS_REP_ORDER_ERR_LIST_S01.syn>>>
@XXCOS_REP_ORDER_ERR_LIST_S01.syn;
PROMPT XXCOS_REP_ORDER_LIST.syn>>>
@XXCOS_REP_ORDER_LIST.syn;
PROMPT XXCOS_REP_ORDER_LIST_S01.syn>>>
@XXCOS_REP_ORDER_LIST_S01.syn;
PROMPT XXCOS_REP_PICK_CHAIN_PRO.syn>>>
@XXCOS_REP_PICK_CHAIN_PRO.syn;
PROMPT XXCOS_REP_PICK_CHAIN_PRO_S01.syn>>>
@XXCOS_REP_PICK_CHAIN_PRO_S01.syn;
PROMPT XXCOS_REP_PICK_DELI_PRO.syn>>>
@XXCOS_REP_PICK_DELI_PRO.syn;
PROMPT XXCOS_REP_PICK_DELI_PRO_S01.syn>>>
@XXCOS_REP_PICK_DELI_PRO_S01.syn;
PROMPT XXCOS_REP_PICK_DELI_SALE.syn>>>
@XXCOS_REP_PICK_DELI_SALE.syn;
PROMPT XXCOS_REP_PICK_DELI_SALE_S01.syn>>>
@XXCOS_REP_PICK_DELI_SALE_S01.syn;
PROMPT XXCOS_REP_SCH_DLV_LIST.syn>>>
@XXCOS_REP_SCH_DLV_LIST.syn;
PROMPT XXCOS_REP_SCH_DLV_LIST_S01.syn>>>
@XXCOS_REP_SCH_DLV_LIST_S01.syn;
PROMPT XXCOS_SALES_EXP_HEADERS.syn>>>
@XXCOS_SALES_EXP_HEADERS.syn;
PROMPT XXCOS_SALES_EXP_HEADERS_S01.syn>>>
@XXCOS_SALES_EXP_HEADERS_S01.syn;
PROMPT XXCOS_SALES_EXP_LINES.syn>>>
@XXCOS_SALES_EXP_LINES.syn;
PROMPT XXCOS_SALES_EXP_LINES_S01.syn>>>
@XXCOS_SALES_EXP_LINES_S01.syn;
PROMPT XXCOS_SHOP_DIGESTION_HDRS.syn>>>
@XXCOS_SHOP_DIGESTION_HDRS.syn;
PROMPT XXCOS_SHOP_DIGESTION_HDRS_S01.syn>>>
@XXCOS_SHOP_DIGESTION_HDRS_S01.syn;
PROMPT XXCOS_SHOP_DIGESTION_LNS.syn>>>
@XXCOS_SHOP_DIGESTION_LNS.syn;
PROMPT XXCOS_SHOP_DIGESTION_LNS_S01.syn>>>
@XXCOS_SHOP_DIGESTION_LNS_S01.syn;
PROMPT XXCOS_TRX_NUMBER_LARGE_S01.syn>>>
@XXCOS_TRX_NUMBER_LARGE_S01.syn;
PROMPT XXCOS_TRX_NUMBER_S01.syn>>>
@XXCOS_TRX_NUMBER_S01.syn;
PROMPT XXCOS_TRX_NUMBER_SMALL_S01.syn>>>
@XXCOS_TRX_NUMBER_SMALL_S01.syn;
PROMPT XXCOS_UNIT_PRICE_MST_WORK.syn>>>
@XXCOS_UNIT_PRICE_MST_WORK.syn;
PROMPT XXCOS_VD_COLUMN_HEADERS.syn>>>
@XXCOS_VD_COLUMN_HEADERS.syn;
PROMPT XXCOS_VD_COLUMN_LINES.syn>>>
@XXCOS_VD_COLUMN_LINES.syn;
PROMPT XXCOS_VD_DELIV_HEADERS.syn>>>
@XXCOS_VD_DELIV_HEADERS.syn;
PROMPT XXCOS_VD_DELIV_LINES.syn>>>
@XXCOS_VD_DELIV_LINES.syn;
PROMPT XXCOS_VD_DIGESTION_HDRS.syn>>>
@XXCOS_VD_DIGESTION_HDRS.syn;
PROMPT XXCOS_VD_DIGESTION_HDRS_S01.syn>>>
@XXCOS_VD_DIGESTION_HDRS_S01.syn;
PROMPT XXCOS_VD_DIGESTION_LNS.syn>>>
@XXCOS_VD_DIGESTION_LNS.syn;
PROMPT XXCOS_VD_DIGESTION_LNS_S01.syn>>>
@XXCOS_VD_DIGESTION_LNS_S01.syn;
