PROMPT XXCOI_COOPERATION_CONTROL.syn>>>
@XXCOI_COOPERATION_CONTROL.syn;
PROMPT XXCOI_FORM_HEADER_ID_S01.syn>>>
@XXCOI_FORM_HEADER_ID_S01.syn;
PROMPT XXCOI_HHT_INV_TRANSACTIONS.syn>>>
@XXCOI_HHT_INV_TRANSACTIONS.syn;
PROMPT XXCOI_HHT_INV_TRANSACTIONS_S01.syn>>>
@XXCOI_HHT_INV_TRANSACTIONS_S01.syn;
PROMPT XXCOI_INVOICE_NO_S01.syn>>>
@XXCOI_INVOICE_NO_S01.syn;
PROMPT XXCOI_INV_CONTROL.syn>>>
@XXCOI_INV_CONTROL.syn;
PROMPT XXCOI_INV_CONTROL_S01.syn>>>
@XXCOI_INV_CONTROL_S01.syn;
PROMPT XXCOI_INV_RECEPTION_DAILY.syn>>>
@XXCOI_INV_RECEPTION_DAILY.syn;
PROMPT XXCOI_INV_RECEPTION_MONTHLY.syn>>>
@XXCOI_INV_RECEPTION_MONTHLY.syn;
PROMPT XXCOI_INV_RECEPTION_SUM.syn>>>
@XXCOI_INV_RECEPTION_SUM.syn;
PROMPT XXCOI_INV_RESULT.syn>>>
@XXCOI_INV_RESULT.syn;
PROMPT XXCOI_INV_RESULT_S01.syn>>>
@XXCOI_INV_RESULT_S01.syn;
PROMPT XXCOI_IN_HHT_INV_TRANSACTIONS.syn>>>
@XXCOI_IN_HHT_INV_TRANSACTIONS.syn;
PROMPT XXCOI_IN_INV_RESULT_FILE_IF.syn>>>
@XXCOI_IN_INV_RESULT_FILE_IF.syn;
PROMPT XXCOI_MST_VD_COLUMN.syn>>>
@XXCOI_MST_VD_COLUMN.syn;
PROMPT XXCOI_MST_VD_COLUMN_S01.syn>>>
@XXCOI_MST_VD_COLUMN_S01.syn;
PROMPT XXCOI_REP_BASE_DETAIL_EXPEND.syn>>>
@XXCOI_REP_BASE_DETAIL_EXPEND.syn;
PROMPT XXCOI_REP_BASE_DETAIL_RCPT.syn>>>
@XXCOI_REP_BASE_DETAIL_RCPT.syn;
PROMPT XXCOI_REP_BASE_EXPEND.syn>>>
@XXCOI_REP_BASE_EXPEND.syn;
PROMPT XXCOI_REP_BASE_RCPT.syn>>>
@XXCOI_REP_BASE_RCPT.syn;
PROMPT XXCOI_REP_EMPLOYEE_RCPT.syn>>>
@XXCOI_REP_EMPLOYEE_RCPT.syn;
PROMPT XXCOI_REP_FACTORY_STORE_LIST.syn>>>
@XXCOI_REP_FACTORY_STORE_LIST.syn;
PROMPT XXCOI_REP_INV_CHECKLIST.syn>>>
@XXCOI_REP_INV_CHECKLIST.syn;
PROMPT XXCOI_REP_KURAGAE_SHIP_LIST.syn>>>
@XXCOI_REP_KURAGAE_SHIP_LIST.syn;
PROMPT XXCOI_REP_KURAGAE_SLIP.syn>>>
@XXCOI_REP_KURAGAE_SLIP.syn;
PROMPT XXCOI_REP_KURAGAE_SLIP_S01.syn>>>
@XXCOI_REP_KURAGAE_SLIP_S01.syn;
PROMPT XXCOI_REP_PRACTICE_INVENTORY.syn>>>
@XXCOI_REP_PRACTICE_INVENTORY.syn;
PROMPT XXCOI_REP_SHIPSTORE_JOUR_LIST.syn>>>
@XXCOI_REP_SHIPSTORE_JOUR_LIST.syn;
PROMPT XXCOI_REP_STOCK_BALANCE_LIST.syn>>>
@XXCOI_REP_STOCK_BALANCE_LIST.syn;
PROMPT XXCOI_REP_STOCK_BALANCE_S01.syn>>>
@XXCOI_REP_STOCK_BALANCE_S01.syn;
PROMPT XXCOI_REP_STORAGE_INFO.syn>>>
@XXCOI_REP_STORAGE_INFO.syn;
PROMPT XXCOI_REP_STORAGE_INFO_S01.syn>>>
@XXCOI_REP_STORAGE_INFO_S01.syn;
PROMPT XXCOI_REP_VD_INVENTORY.syn>>>
@XXCOI_REP_VD_INVENTORY.syn;
PROMPT XXCOI_REP_VD_INVENTORY_S01.syn>>>
@XXCOI_REP_VD_INVENTORY_S01.syn;
PROMPT XXCOI_REP_WAREHOUSE_RCPT.syn>>>
@XXCOI_REP_WAREHOUSE_RCPT.syn;
PROMPT XXCOI_STORAGE_INFORMATION.syn>>>
@XXCOI_STORAGE_INFORMATION.syn;
PROMPT XXCOI_STORAGE_INFORMATION_S01.syn>>>
@XXCOI_STORAGE_INFORMATION_S01.syn;
PROMPT XXCOI_TMP_INV_RESULT.syn>>>
@XXCOI_TMP_INV_RESULT.syn;
PROMPT XXCOI_TMP_STANDARD_INV.syn>>>
@XXCOI_TMP_STANDARD_INV.syn;
PROMPT XXCOI_TMP_SVD_TRANSACTIONS.syn>>>
@XXCOI_TMP_SVD_TRANSACTIONS.syn;
PROMPT XXCOI_VD_RECEPTION_INFO.syn>>>
@XXCOI_VD_RECEPTION_INFO.syn;
PROMPT XXCOI_WK_COST_VARIANCE.syn>>>
@XXCOI_WK_COST_VARIANCE.syn;
PROMPT XXCOI_XXWSH_RESERVE_IF_S01.syn>>>
@XXCOI_XXWSH_RESERVE_IF_S01.syn;
