PROMPT XXCOK_BACKMARGIN_BALANCE.syn>>>
@XXCOK_BACKMARGIN_BALANCE.syn;
PROMPT XXCOK_BACKMARGIN_BALANCE_S01.syn>>>
@XXCOK_BACKMARGIN_BALANCE_S01.syn;
PROMPT XXCOK_BM_CONTRACT_ERR.syn>>>
@XXCOK_BM_CONTRACT_ERR.syn;
PROMPT XXCOK_BM_SUPPORT_BUDGET.syn>>>
@XXCOK_BM_SUPPORT_BUDGET.syn;
PROMPT XXCOK_BM_SUPPORT_BUDGET_S01.syn>>>
@XXCOK_BM_SUPPORT_BUDGET_S01.syn;
PROMPT XXCOK_COND_BM_SUPPORT.syn>>>
@XXCOK_COND_BM_SUPPORT.syn;
PROMPT XXCOK_COND_BM_SUPPORT_S01.syn>>>
@XXCOK_COND_BM_SUPPORT_S01.syn;
PROMPT XXCOK_CUST_SHIFT_INFO.syn>>>
@XXCOK_CUST_SHIFT_INFO.syn;
PROMPT XXCOK_CUST_SHIFT_INFO_S01.syn>>>
@XXCOK_CUST_SHIFT_INFO_S01.syn;
PROMPT XXCOK_DLV_COST_CALC_BUDGET.syn>>>
@XXCOK_DLV_COST_CALC_BUDGET.syn;
PROMPT XXCOK_DLV_COST_CALC_BUDGET_S01.syn>>>
@XXCOK_DLV_COST_CALC_BUDGET_S01.syn;
PROMPT XXCOK_DLV_COST_RESULT_INFO.syn>>>
@XXCOK_DLV_COST_RESULT_INFO.syn;
PROMPT XXCOK_DLV_COST_RESULT_INFO_S01.syn>>>
@XXCOK_DLV_COST_RESULT_INFO_S01.syn;
PROMPT XXCOK_DLV_COST_RESULT_SUM.syn>>>
@XXCOK_DLV_COST_RESULT_SUM.syn;
PROMPT XXCOK_DLV_COST_RESULT_SUM_S01.syn>>>
@XXCOK_DLV_COST_RESULT_SUM_S01.syn;
PROMPT XXCOK_MST_BM_CONTRACT.syn>>>
@XXCOK_MST_BM_CONTRACT.syn;
PROMPT XXCOK_MST_BM_CONTRACT_S01.syn>>>
@XXCOK_MST_BM_CONTRACT_S01.syn;
PROMPT XXCOK_REP_BM_BALANCE.syn>>>
@XXCOK_REP_BM_BALANCE.syn;
PROMPT XXCOK_REP_BM_CONTRACT_ERR.syn>>>
@XXCOK_REP_BM_CONTRACT_ERR.syn;
PROMPT XXCOK_REP_BM_PG_DETAIL.syn>>>
@XXCOK_REP_BM_PG_DETAIL.syn;
PROMPT XXCOK_REP_BM_PG_RECEIPT.syn>>>
@XXCOK_REP_BM_PG_RECEIPT.syn;
PROMPT XXCOK_REP_SELLING_TRNS_CHK.syn>>>
@XXCOK_REP_SELLING_TRNS_CHK.syn;
PROMPT XXCOK_REP_WHOLESALE_PAY.syn>>>
@XXCOK_REP_WHOLESALE_PAY.syn;
PROMPT XXCOK_SELLING_FROM_INFO.syn>>>
@XXCOK_SELLING_FROM_INFO.syn;
PROMPT XXCOK_SELLING_FROM_INFO_S01.syn>>>
@XXCOK_SELLING_FROM_INFO_S01.syn;
PROMPT XXCOK_SELLING_RATE_INFO.syn>>>
@XXCOK_SELLING_RATE_INFO.syn;
PROMPT XXCOK_SELLING_RATE_INFO_S01.syn>>>
@XXCOK_SELLING_RATE_INFO_S01.syn;
PROMPT XXCOK_SELLING_TO_INFO.syn>>>
@XXCOK_SELLING_TO_INFO.syn;
PROMPT XXCOK_SELLING_TO_INFO_S01.syn>>>
@XXCOK_SELLING_TO_INFO_S01.syn;
PROMPT XXCOK_SELLING_TRNS_INFO.syn>>>
@XXCOK_SELLING_TRNS_INFO.syn;
PROMPT XXCOK_SELLING_TRNS_INFO_S01.syn>>>
@XXCOK_SELLING_TRNS_INFO_S01.syn;
PROMPT XXCOK_SELLING_TRNS_INFO_S02.syn>>>
@XXCOK_SELLING_TRNS_INFO_S02.syn;
PROMPT XXCOK_SLIP_NUMBER_BM_S01.syn>>>
@XXCOK_SLIP_NUMBER_BM_S01.syn;
PROMPT XXCOK_SLIP_NUMBER_JI_S01.syn>>>
@XXCOK_SLIP_NUMBER_JI_S01.syn;
PROMPT XXCOK_SLIP_NUMBER_TR_S01.syn>>>
@XXCOK_SLIP_NUMBER_TR_S01.syn;
PROMPT XXCOK_TMP_001A05F_SEC_CODE.syn>>>
@XXCOK_TMP_001A05F_SEC_CODE.syn;
PROMPT XXCOK_TMP_EDI_SELLING_TRNS.syn>>>
@XXCOK_TMP_EDI_SELLING_TRNS.syn;
PROMPT XXCOK_TMP_SELLING_RATE.syn>>>
@XXCOK_TMP_SELLING_RATE.syn;
PROMPT XXCOK_TMP_WHOLESALE_BILL.syn>>>
@XXCOK_TMP_WHOLESALE_BILL.syn;
PROMPT XXCOK_WHOLESALE_BILL_HEAD.syn>>>
@XXCOK_WHOLESALE_BILL_HEAD.syn;
PROMPT XXCOK_WHOLESALE_BILL_HEAD_S01.syn>>>
@XXCOK_WHOLESALE_BILL_HEAD_S01.syn;
PROMPT XXCOK_WHOLESALE_BILL_LINE.syn>>>
@XXCOK_WHOLESALE_BILL_LINE.syn;
PROMPT XXCOK_WHOLESALE_BILL_LINE_S01.syn>>>
@XXCOK_WHOLESALE_BILL_LINE_S01.syn;
PROMPT XXCOK_WHOLESALE_PAYMENT.syn>>>
@XXCOK_WHOLESALE_PAYMENT.syn;
PROMPT XXCOK_WHOLESALE_PAYMENT_S01.syn>>>
@XXCOK_WHOLESALE_PAYMENT_S01.syn;
PROMPT XXCOK_WK_EDI_SELLING_TRNS.syn>>>
@XXCOK_WK_EDI_SELLING_TRNS.syn;
PROMPT XXCOK_WK_EDI_SELLING_TRNS_S01.syn>>>
@XXCOK_WK_EDI_SELLING_TRNS_S01.syn;
