PROMPT XXCOP_APPL_CONTROLS.syn>>>
@XXCOP_APPL_CONTROLS.syn;
PROMPT XXCOP_ITEM_IMPORT_ROW_NO_S1.syn>>>
@XXCOP_ITEM_IMPORT_ROW_NO_S1.syn;
PROMPT XXCOP_LEAF_DAY_OF_SERVICE.syn>>>
@XXCOP_LEAF_DAY_OF_SERVICE.syn;
PROMPT XXCOP_MRP_SCHEDULE_IF_S1.syn>>>
@XXCOP_MRP_SCHEDULE_IF_S1.syn;
PROMPT XXCOP_MRP_SCHEDULE_INTERFACE.syn>>>
@XXCOP_MRP_SCHEDULE_INTERFACE.syn;
PROMPT XXCOP_REP_FORECAST_CHECK_LIST.syn>>>
@XXCOP_REP_FORECAST_CHECK_LIST.syn;
PROMPT XXCOP_REP_FORECAST_PLANNING.syn>>>
@XXCOP_REP_FORECAST_PLANNING.syn;
PROMPT XXCOP_SHIPMENT_RESULTS.syn>>>
@XXCOP_SHIPMENT_RESULTS.syn;
PROMPT XXCOP_WK_FORECAST_TOTALING.syn>>>
@XXCOP_WK_FORECAST_TOTALING.syn;
PROMPT XXCOP_WK_SHIP_PLANNING.syn>>>
@XXCOP_WK_SHIP_PLANNING.syn;
PROMPT XXCOP_WK_SHIP_PLANNING_OUTPUT.syn>>>
@XXCOP_WK_SHIP_PLANNING_OUTPUT.syn;
PROMPT XXCOP_WK_YOKO_PLAN_OUTPUT.syn>>>
@XXCOP_WK_YOKO_PLAN_OUTPUT.syn;
