PROMPT XXCSO_ACCOUNT_SALES_PLANS.syn>>>
@XXCSO_ACCOUNT_SALES_PLANS.syn;
PROMPT XXCSO_ACCOUNT_SALES_PLANS_S01.syn>>>
@XXCSO_ACCOUNT_SALES_PLANS_S01.syn;
PROMPT XXCSO_APPROVAL_S01.syn>>>
@XXCSO_APPROVAL_S01.syn;
PROMPT XXCSO_BANK_ACCOUNTS.syn>>>
@XXCSO_BANK_ACCOUNTS.syn;
PROMPT XXCSO_BANK_ACCOUNTS_S01.syn>>>
@XXCSO_BANK_ACCOUNTS_S01.syn;
PROMPT XXCSO_CODE_ASSIGNMENTS.syn>>>
@XXCSO_CODE_ASSIGNMENTS.syn;
PROMPT XXCSO_CONTRACT_CUSTOMERS.syn>>>
@XXCSO_CONTRACT_CUSTOMERS.syn;
PROMPT XXCSO_CONTRACT_CUSTOMERS_S01.syn>>>
@XXCSO_CONTRACT_CUSTOMERS_S01.syn;
PROMPT XXCSO_CONTRACT_CUSTOMERS_S02.syn>>>
@XXCSO_CONTRACT_CUSTOMERS_S02.syn;
PROMPT XXCSO_CONTRACT_MANAGEMENTS.syn>>>
@XXCSO_CONTRACT_MANAGEMENTS.syn;
PROMPT XXCSO_CONTRACT_MANAGEMENTS_S01.syn>>>
@XXCSO_CONTRACT_MANAGEMENTS_S01.syn;
PROMPT XXCSO_DEPT_MONTHLY_PLANS.syn>>>
@XXCSO_DEPT_MONTHLY_PLANS.syn;
PROMPT XXCSO_DEPT_MONTHLY_PLANS_S01.syn>>>
@XXCSO_DEPT_MONTHLY_PLANS_S01.syn;
PROMPT XXCSO_DEPT_SALES_STAFFS.syn>>>
@XXCSO_DEPT_SALES_STAFFS.syn;
PROMPT XXCSO_DESTINATIONS.syn>>>
@XXCSO_DESTINATIONS.syn;
PROMPT XXCSO_DESTINATIONS_S01.syn>>>
@XXCSO_DESTINATIONS_S01.syn;
PROMPT XXCSO_IB_INFO_H.syn>>>
@XXCSO_IB_INFO_H.syn;
PROMPT XXCSO_IN_ITEM_DATA.syn>>>
@XXCSO_IN_ITEM_DATA.syn;
PROMPT XXCSO_IN_NOTES.syn>>>
@XXCSO_IN_NOTES.syn;
PROMPT XXCSO_IN_NOTES_S01.syn>>>
@XXCSO_IN_NOTES_S01.syn;
PROMPT XXCSO_IN_ROUTE_NO.syn>>>
@XXCSO_IN_ROUTE_NO.syn;
PROMPT XXCSO_IN_ROUTE_NO_S01.syn>>>
@XXCSO_IN_ROUTE_NO_S01.syn;
PROMPT XXCSO_IN_SALES_PLAN_DAY.syn>>>
@XXCSO_IN_SALES_PLAN_DAY.syn;
PROMPT XXCSO_IN_SALES_PLAN_DAY_S01.syn>>>
@XXCSO_IN_SALES_PLAN_DAY_S01.syn;
PROMPT XXCSO_IN_SALES_PLAN_MONTH.syn>>>
@XXCSO_IN_SALES_PLAN_MONTH.syn;
PROMPT XXCSO_IN_SALES_PLAN_MONTH_S01.syn>>>
@XXCSO_IN_SALES_PLAN_MONTH_S01.syn;
PROMPT XXCSO_IN_WORK_DATA.syn>>>
@XXCSO_IN_WORK_DATA.syn;
PROMPT XXCSO_PO_RQISTNS_IN_ALL_S01.syn>>>
@XXCSO_PO_RQISTNS_IN_ALL_S01.syn;
PROMPT XXCSO_PO_VENDORS_S01.syn>>>
@XXCSO_PO_VENDORS_S01.syn;
PROMPT XXCSO_PV_DEF.syn>>>
@XXCSO_PV_DEF.syn;
PROMPT XXCSO_PV_DEF_S01.syn>>>
@XXCSO_PV_DEF_S01.syn;
PROMPT XXCSO_PV_EXTRACT_TERM_DEF.syn>>>
@XXCSO_PV_EXTRACT_TERM_DEF.syn;
PROMPT XXCSO_PV_EXTRACT_TERM_DEF_S01.syn>>>
@XXCSO_PV_EXTRACT_TERM_DEF_S01.syn;
PROMPT XXCSO_PV_SORT_COLUMN_DEF.syn>>>
@XXCSO_PV_SORT_COLUMN_DEF.syn;
PROMPT XXCSO_PV_SORT_COLUMN_DEF_S01.syn>>>
@XXCSO_PV_SORT_COLUMN_DEF_S01.syn;
PROMPT XXCSO_PV_VIEW_COLUMN_DEF.syn>>>
@XXCSO_PV_VIEW_COLUMN_DEF.syn;
PROMPT XXCSO_PV_VIEW_COLUMN_DEF_S01.syn>>>
@XXCSO_PV_VIEW_COLUMN_DEF_S01.syn;
PROMPT XXCSO_QUOTE_HEADERS.syn>>>
@XXCSO_QUOTE_HEADERS.syn;
PROMPT XXCSO_QUOTE_HEADERS_S01.syn>>>
@XXCSO_QUOTE_HEADERS_S01.syn;
PROMPT XXCSO_QUOTE_LINES.syn>>>
@XXCSO_QUOTE_LINES.syn;
PROMPT XXCSO_QUOTE_LINES_S01.syn>>>
@XXCSO_QUOTE_LINES_S01.syn;
PROMPT XXCSO_REP_AUTO_SALE_CONT.syn>>>
@XXCSO_REP_AUTO_SALE_CONT.syn;
PROMPT XXCSO_REP_NOVISIT.syn>>>
@XXCSO_REP_NOVISIT.syn;
PROMPT XXCSO_REP_QUOTE_LIST.syn>>>
@XXCSO_REP_QUOTE_LIST.syn;
PROMPT XXCSO_REP_QUOTE_LIST_S01.syn>>>
@XXCSO_REP_QUOTE_LIST_S01.syn;
PROMPT XXCSO_REP_VISIT_ROUTE_MNG.syn>>>
@XXCSO_REP_VISIT_ROUTE_MNG.syn;
PROMPT XXCSO_REP_VISIT_SALESEMP.syn>>>
@XXCSO_REP_VISIT_SALESEMP.syn;
PROMPT XXCSO_REP_VISIT_SALE_PLAN.syn>>>
@XXCSO_REP_VISIT_SALE_PLAN.syn;
PROMPT XXCSO_SALES_HEADERS.syn>>>
@XXCSO_SALES_HEADERS.syn;
PROMPT XXCSO_SALES_HEADERS_HIST.syn>>>
@XXCSO_SALES_HEADERS_HIST.syn;
PROMPT XXCSO_SALES_HEADERS_HIST_S01.syn>>>
@XXCSO_SALES_HEADERS_HIST_S01.syn;
PROMPT XXCSO_SALES_HEADERS_S01.syn>>>
@XXCSO_SALES_HEADERS_S01.syn;
PROMPT XXCSO_SALES_LINES.syn>>>
@XXCSO_SALES_LINES.syn;
PROMPT XXCSO_SALES_LINES_HIST.syn>>>
@XXCSO_SALES_LINES_HIST.syn;
PROMPT XXCSO_SALES_LINES_HIST_S01.syn>>>
@XXCSO_SALES_LINES_HIST_S01.syn;
PROMPT XXCSO_SALES_LINES_S01.syn>>>
@XXCSO_SALES_LINES_S01.syn;
PROMPT XXCSO_SALES_NOTIFIES.syn>>>
@XXCSO_SALES_NOTIFIES.syn;
PROMPT XXCSO_SALES_NOTIFIES_S01.syn>>>
@XXCSO_SALES_NOTIFIES_S01.syn;
PROMPT XXCSO_SLS_PRSN_MNTHLY_PLNS.syn>>>
@XXCSO_SLS_PRSN_MNTHLY_PLNS.syn;
PROMPT XXCSO_SLS_PRSN_MNTHLY_PLNS_S01.syn>>>
@XXCSO_SLS_PRSN_MNTHLY_PLNS_S01.syn;
PROMPT XXCSO_SP_DECISION_ATTACHES.syn>>>
@XXCSO_SP_DECISION_ATTACHES.syn;
PROMPT XXCSO_SP_DECISION_ATTACHES_S01.syn>>>
@XXCSO_SP_DECISION_ATTACHES_S01.syn;
PROMPT XXCSO_SP_DECISION_CUSTS.syn>>>
@XXCSO_SP_DECISION_CUSTS.syn;
PROMPT XXCSO_SP_DECISION_CUSTS_S01.syn>>>
@XXCSO_SP_DECISION_CUSTS_S01.syn;
PROMPT XXCSO_SP_DECISION_HEADERS.syn>>>
@XXCSO_SP_DECISION_HEADERS.syn;
PROMPT XXCSO_SP_DECISION_HEADERS_S01.syn>>>
@XXCSO_SP_DECISION_HEADERS_S01.syn;
PROMPT XXCSO_SP_DECISION_HEADERS_S02.syn>>>
@XXCSO_SP_DECISION_HEADERS_S02.syn;
PROMPT XXCSO_SP_DECISION_LINES.syn>>>
@XXCSO_SP_DECISION_LINES.syn;
PROMPT XXCSO_SP_DECISION_LINES_S01.syn>>>
@XXCSO_SP_DECISION_LINES_S01.syn;
PROMPT XXCSO_SP_DECISION_SENDS.syn>>>
@XXCSO_SP_DECISION_SENDS.syn;
PROMPT XXCSO_SP_DECISION_SENDS_S01.syn>>>
@XXCSO_SP_DECISION_SENDS_S01.syn;
PROMPT XXCSO_SP_DECISION_WF_ORGS.syn>>>
@XXCSO_SP_DECISION_WF_ORGS.syn;
PROMPT XXCSO_SP_DECISION_WF_ORGS_S01.syn>>>
@XXCSO_SP_DECISION_WF_ORGS_S01.syn;
PROMPT XXCSO_SUM_VISIT_SALE_REP.syn>>>
@XXCSO_SUM_VISIT_SALE_REP.syn;
PROMPT XXCSO_TMP_SALES_PLAN.syn>>>
@XXCSO_TMP_SALES_PLAN.syn;
PROMPT XXCSO_TMP_SALES_REQUEST.syn>>>
@XXCSO_TMP_SALES_REQUEST.syn;
PROMPT XXCSO_TMP_SP_DEC_REQUEST.syn>>>
@XXCSO_TMP_SP_DEC_REQUEST.syn;
PROMPT XXCSO_TMP_TXN_UTILITY.syn>>>
@XXCSO_TMP_TXN_UTILITY.syn;
PROMPT XXCSO_WK_REQUISITION_PROC.syn>>>
@XXCSO_WK_REQUISITION_PROC.syn;
PROMPT XXCSO_XX03_VENDORS_IF_S01.syn>>>
@XXCSO_XX03_VENDORS_IF_S01.syn;
