PROMPT XXCSM_ITEM_PLAN_BDGT_S01.syn>>>
@XXCSM_ITEM_PLAN_BDGT_S01.syn;
PROMPT XXCSM_ITEM_PLAN_HEADERS.syn>>>
@XXCSM_ITEM_PLAN_HEADERS.syn;
PROMPT XXCSM_ITEM_PLAN_HEADER_S01.syn>>>
@XXCSM_ITEM_PLAN_HEADER_S01.syn;
PROMPT XXCSM_ITEM_PLAN_LINES.syn>>>
@XXCSM_ITEM_PLAN_LINES.syn;
PROMPT XXCSM_ITEM_PLAN_LINES_S01.syn>>>
@XXCSM_ITEM_PLAN_LINES_S01.syn;
PROMPT XXCSM_ITEM_PLAN_LOC_BDGT.syn>>>
@XXCSM_ITEM_PLAN_LOC_BDGT.syn;
PROMPT XXCSM_ITEM_PLAN_RESULT.syn>>>
@XXCSM_ITEM_PLAN_RESULT.syn;
PROMPT XXCSM_MST_GRANT_POINT.syn>>>
@XXCSM_MST_GRANT_POINT.syn;
PROMPT XXCSM_MST_QUALIFICATE_PNT.syn>>>
@XXCSM_MST_QUALIFICATE_PNT.syn;
PROMPT XXCSM_NEWS_ITEM_HDRS_ALL_S01.syn>>>
@XXCSM_NEWS_ITEM_HDRS_ALL_S01.syn;
PROMPT XXCSM_NEWS_ITEM_HEADERS_ALL.syn>>>
@XXCSM_NEWS_ITEM_HEADERS_ALL.syn;
PROMPT XXCSM_NEWS_ITEM_LINES_ALL.syn>>>
@XXCSM_NEWS_ITEM_LINES_ALL.syn;
PROMPT XXCSM_NEWS_ITEM_LINES_ALL_S01.syn>>>
@XXCSM_NEWS_ITEM_LINES_ALL_S01.syn;
PROMPT XXCSM_NEW_CUST_POINT_HST.syn>>>
@XXCSM_NEW_CUST_POINT_HST.syn;
PROMPT XXCSM_SALES_PLAN.syn>>>
@XXCSM_SALES_PLAN.syn;
PROMPT XXCSM_TMP_CUST_ACCOUNTS.syn>>>
@XXCSM_TMP_CUST_ACCOUNTS.syn;
PROMPT XXCSM_TMP_ITEM_PLAN_GUN.syn>>>
@XXCSM_TMP_ITEM_PLAN_GUN.syn;
PROMPT XXCSM_TMP_ITEM_PLAN_GUN_S01.syn>>>
@XXCSM_TMP_ITEM_PLAN_GUN_S01.syn;
PROMPT XXCSM_TMP_ITEM_PLAN_SALES.syn>>>
@XXCSM_TMP_ITEM_PLAN_SALES.syn;
PROMPT XXCSM_TMP_ITEM_PLAN_SALES_S01.syn>>>
@XXCSM_TMP_ITEM_PLAN_SALES_S01.syn;
PROMPT XXCSM_TMP_ITEM_PLAN_SALES_SUM.syn>>>
@XXCSM_TMP_ITEM_PLAN_SALES_SUM.syn;
PROMPT XXCSM_TMP_ITEM_PLAN_SALSUM_S01.syn>>>
@XXCSM_TMP_ITEM_PLAN_SALSUM_S01.syn;
PROMPT XXCSM_TMP_MONTH_ITEM_PLAN.syn>>>
@XXCSM_TMP_MONTH_ITEM_PLAN.syn;
PROMPT XXCSM_TMP_SALES_PLAN_CS.syn>>>
@XXCSM_TMP_SALES_PLAN_CS.syn;
PROMPT XXCSM_TMP_SALES_PLAN_GUN.syn>>>
@XXCSM_TMP_SALES_PLAN_GUN.syn;
PROMPT XXCSM_TMP_SALES_PLAN_HON.syn>>>
@XXCSM_TMP_SALES_PLAN_HON.syn;
PROMPT XXCSM_TMP_SALES_PLAN_REF.syn>>>
@XXCSM_TMP_SALES_PLAN_REF.syn;
PROMPT XXCSM_TMP_SALES_PLAN_TIME.syn>>>
@XXCSM_TMP_SALES_PLAN_TIME.syn;
PROMPT XXCSM_TMP_SALES_RESULT.syn>>>
@XXCSM_TMP_SALES_RESULT.syn;
PROMPT XXCSM_WK_NEW_CUST_GET_EMP.syn>>>
@XXCSM_WK_NEW_CUST_GET_EMP.syn;
PROMPT XXCSM_WK_SALES_PLAN.syn>>>
@XXCSM_WK_SALES_PLAN.syn;
PROMPT XXCSM_WK_VENDING_PNT.syn>>>
@XXCSM_WK_VENDING_PNT.syn;
