PROMPT XXCFO_ADPS_GL_INTERFACE.syn>>>
@XXCFO_ADPS_GL_INTERFACE.syn;
PROMPT XXCFO_PO_STATUS_MNG.syn>>>
@XXCFO_PO_STATUS_MNG.syn;
PROMPT XXCFO_REP_STANDARD_PO.syn>>>
@XXCFO_REP_STANDARD_PO.syn;
PROMPT XXCFO_TMP_STANDARD_DATA_PO.syn>>>
@XXCFO_TMP_STANDARD_DATA_PO.syn;
