PROMPT XXCFR_AR_TRX_INTERFACE_S1.syn>>>
@XXCFR_AR_TRX_INTERFACE_S1.syn;
PROMPT XXCFR_CSV_OUTS_TEMP.syn>>>
@XXCFR_CSV_OUTS_TEMP.syn;
PROMPT XXCFR_CSV_OUTS_TEMP_S1.syn>>>
@XXCFR_CSV_OUTS_TEMP_S1.syn;
PROMPT XXCFR_INVOICE_HEADERS.syn>>>
@XXCFR_INVOICE_HEADERS.syn;
PROMPT XXCFR_INVOICE_HEADERS_S1.syn>>>
@XXCFR_INVOICE_HEADERS_S1.syn;
PROMPT XXCFR_INVOICE_LINES.syn>>>
@XXCFR_INVOICE_LINES.syn;
PROMPT XXCFR_INV_INFO_TRANSFER.syn>>>
@XXCFR_INV_INFO_TRANSFER.syn;
PROMPT XXCFR_INV_TARGET_CUST_LIST.syn>>>
@XXCFR_INV_TARGET_CUST_LIST.syn;
PROMPT XXCFR_PAYMENT_NOTES.syn>>>
@XXCFR_PAYMENT_NOTES.syn;
PROMPT XXCFR_PAYMENT_NOTES_S1.syn>>>
@XXCFR_PAYMENT_NOTES_S1.syn;
PROMPT XXCFR_REP_INVOICE_LIST.syn>>>
@XXCFR_REP_INVOICE_LIST.syn;
PROMPT XXCFR_REP_SALES_REP_PAY_SCH.syn>>>
@XXCFR_REP_SALES_REP_PAY_SCH.syn;
PROMPT XXCFR_REP_ST_INVOICE_EX_TAX..syn>>>
@XXCFR_REP_ST_INVOICE_EX_TAX..syn;
PROMPT XXCFR_REP_ST_INVOICE_INC_TAX.syn>>>
@XXCFR_REP_ST_INVOICE_INC_TAX.syn;
PROMPT XXCFR_SALES_DATA_RELETES.syn>>>
@XXCFR_SALES_DATA_RELETES.syn;
PROMPT XXCFR_TAX_GAP_TRX_LIST.syn>>>
@XXCFR_TAX_GAP_TRX_LIST.syn;
