PROMPT HZ_CUST_ACCOUNTS_S1.syn>>>
@HZ_CUST_ACCOUNTS_S1.syn;
PROMPT XXCMM_CUST_ACCOUNTS.syn>>>
@XXCMM_CUST_ACCOUNTS.syn;
PROMPT XXCMM_IN_PEOPLE_IF.syn>>>
@XXCMM_IN_PEOPLE_IF.syn;
PROMPT XXCMM_MST_CORPORATE.syn>>>
@XXCMM_MST_CORPORATE.syn;
PROMPT XXCMM_OUT_PEOPLE_D_DISPENSER.syn>>>
@XXCMM_OUT_PEOPLE_D_DISPENSER.syn;
PROMPT XXCMM_REP_UNDEAL_LIST.syn>>>
@XXCMM_REP_UNDEAL_LIST.syn;
PROMPT XXCMM_SYSTEM_ITEMS_B.syn>>>
@XXCMM_SYSTEM_ITEMS_B.syn;
PROMPT XXCMM_SYSTEM_ITEMS_B_HST.syn>>>
@XXCMM_SYSTEM_ITEMS_B_HST.syn;
PROMPT XXCMM_SYSTEM_ITEMS_B_HST_S.syn>>>
@XXCMM_SYSTEM_ITEMS_B_HST_S.syn;
PROMPT XXCMM_WK_CUST_BATCH_REGIST.syn>>>
@XXCMM_WK_CUST_BATCH_REGIST.syn;
PROMPT XXCMM_WK_DISCCOST_BATCH_REGIST.syn>>>
@XXCMM_WK_DISCCOST_BATCH_REGIST.syn;
PROMPT XXCMM_WK_ITEMRSV_CSV.syn>>>
@XXCMM_WK_ITEMRSV_CSV.syn;
PROMPT XXCMM_WK_ITEM_BATCH_REGIST.syn>>>
@XXCMM_WK_ITEM_BATCH_REGIST.syn;
PROMPT XXCMM_WK_ITEM_CSV.syn>>>
@XXCMM_WK_ITEM_CSV.syn;
PROMPT XXCMM_WK_OPMCOST_BATCH_REGIST.syn>>>
@XXCMM_WK_OPMCOST_BATCH_REGIST.syn;
PROMPT XXCMM_WK_PEOPLE_RESP.syn>>>
@XXCMM_WK_PEOPLE_RESP.syn;
