PROMPT XXCCP_IF_JOB_STATUS.syn>>>
@XXCCP_IF_JOB_STATUS.syn;
PROMPT XXCCP_IF_JOB_STATUS_S01.syn>>>
@XXCCP_IF_JOB_STATUS_S01.syn;
PROMPT XXCCP_MRP_FILE_UL_INTERFACE.syn>>>
@XXCCP_MRP_FILE_UL_INTERFACE.syn;
PROMPT XXCCP_MRP_FILE_UL_S01.syn>>>
@XXCCP_MRP_FILE_UL_S01.syn;
PROMPT XXCCP_PROCESS_DATES.syn>>>
@XXCCP_PROCESS_DATES.syn;
