PROMPT XXCOS_EDI_STC_LINES_N01.ind>>>
@XXCOS_EDI_STC_LINES_N01.ind;
PROMPT XXCOS_PAYMENT_N01.ind>>>
@XXCOS_PAYMENT_N01.ind;
PROMPT XXCOS_SHOP_DIGESTION_LNS_U01.ind>>>
@XXCOS_SHOP_DIGESTION_LNS_U01.ind;
PROMPT XXCOS_VD_DIGESTION_LNS_U01.ind>>>
@XXCOS_VD_DIGESTION_LNS_U01.ind;
