PROMPT XXCOI_HHT_INV_TRANSACTIONS_N01.ind>>>
@XXCOI_HHT_INV_TRANSACTIONS_N01.ind;
PROMPT XXCOI_HHT_INV_TRANSACTIONS_N02.ind>>>
@XXCOI_HHT_INV_TRANSACTIONS_N02.ind;
PROMPT XXCOI_HHT_INV_TRANSACTIONS_N03.ind>>>
@XXCOI_HHT_INV_TRANSACTIONS_N03.ind;
PROMPT XXCOI_MST_VD_COLUMN_U01.ind>>>
@XXCOI_MST_VD_COLUMN_U01.ind;
PROMPT XXCOI_STORAGE_INFORMATION_N01.ind>>>
@XXCOI_STORAGE_INFORMATION_N01.ind;
PROMPT XXCOI_STORAGE_INFORMATION_N02.ind>>>
@XXCOI_STORAGE_INFORMATION_N02.ind;
PROMPT XXCOI_STORAGE_INFORMATION_N03.ind>>>
@XXCOI_STORAGE_INFORMATION_N03.ind;
