PROMPT XXCSO_ACCOUNT_SALES_PLANS_N01.ind>>>
@XXCSO_ACCOUNT_SALES_PLANS_N01.ind;
PROMPT XXCSO_ACCOUNT_SALES_PLANS_U01.ind>>>
@XXCSO_ACCOUNT_SALES_PLANS_U01.ind;
PROMPT XXCSO_ACCOUNT_SALES_PLANS_U02.ind>>>
@XXCSO_ACCOUNT_SALES_PLANS_U02.ind;
PROMPT XXCSO_BANK_ACCOUNTS_N01.ind>>>
@XXCSO_BANK_ACCOUNTS_N01.ind;
PROMPT XXCSO_CODE_ASSIGNMENTS_N01.ind>>>
@XXCSO_CODE_ASSIGNMENTS_N01.ind;
PROMPT XXCSO_CODE_ASSIGNMENTS_U01.ind>>>
@XXCSO_CODE_ASSIGNMENTS_U01.ind;
PROMPT XXCSO_CONTRACT_MANAGEMENTS_N01.ind>>>
@XXCSO_CONTRACT_MANAGEMENTS_N01.ind;
PROMPT XXCSO_DEPT_MONTHLY_PLANS_N01.ind>>>
@XXCSO_DEPT_MONTHLY_PLANS_N01.ind;
PROMPT XXCSO_DEPT_MONTHLY_PLANS_U01.ind>>>
@XXCSO_DEPT_MONTHLY_PLANS_U01.ind;
PROMPT XXCSO_DEPT_SALES_STAFFS_N01.ind>>>
@XXCSO_DEPT_SALES_STAFFS_N01.ind;
PROMPT XXCSO_DESTINATIONS_N01.ind>>>
@XXCSO_DESTINATIONS_N01.ind;
PROMPT XXCSO_DESTINATIONS_N02.ind>>>
@XXCSO_DESTINATIONS_N02.ind;
PROMPT XXCSO_IB_INFO_H_U01.ind>>>
@XXCSO_IB_INFO_H_U01.ind;
PROMPT XXCSO_IN_ROUTE_NO_N01.ind>>>
@XXCSO_IN_ROUTE_NO_N01.ind;
PROMPT XXCSO_IN_SALES_PLAN_DAY_N01.ind>>>
@XXCSO_IN_SALES_PLAN_DAY_N01.ind;
PROMPT XXCSO_IN_SALES_PLAN_MONTH_N01.ind>>>
@XXCSO_IN_SALES_PLAN_MONTH_N01.ind;
PROMPT XXCSO_IN_WORK_DATA_N01.ind>>>
@XXCSO_IN_WORK_DATA_N01.ind;
PROMPT XXCSO_IN_WORK_DATA_N02.ind>>>
@XXCSO_IN_WORK_DATA_N02.ind;
PROMPT XXCSO_PV_EXTRACT_TERM_DEF_N01.ind>>>
@XXCSO_PV_EXTRACT_TERM_DEF_N01.ind;
PROMPT XXCSO_PV_SORT_COLUMN_DEF_N01.ind>>>
@XXCSO_PV_SORT_COLUMN_DEF_N01.ind;
PROMPT XXCSO_PV_VIEW_COLUMN_DEF_N01.ind>>>
@XXCSO_PV_VIEW_COLUMN_DEF_N01.ind;
PROMPT XXCSO_QUOTE_HEADERS_U01.ind>>>
@XXCSO_QUOTE_HEADERS_U01.ind;
PROMPT XXCSO_REP_AUTO_SALE_CONT_U01.ind>>>
@XXCSO_REP_AUTO_SALE_CONT_U01.ind;
PROMPT XXCSO_REP_NOVISIT_U01.ind>>>
@XXCSO_REP_NOVISIT_U01.ind;
PROMPT XXCSO_REP_QUOTE_LIST_N01.ind>>>
@XXCSO_REP_QUOTE_LIST_N01.ind;
PROMPT XXCSO_REP_VISIT_ROUTE_MNG_U01.ind>>>
@XXCSO_REP_VISIT_ROUTE_MNG_U01.ind;
PROMPT XXCSO_REP_VISIT_SALESEMP_U01.ind>>>
@XXCSO_REP_VISIT_SALESEMP_U01.ind;
PROMPT XXCSO_REP_VISIT_SALE_PLAN_U01.ind>>>
@XXCSO_REP_VISIT_SALE_PLAN_U01.ind;
PROMPT XXCSO_SALES_HEADERS_U01.ind>>>
@XXCSO_SALES_HEADERS_U01.ind;
PROMPT XXCSO_SALES_LINES_HIST_N01.ind>>>
@XXCSO_SALES_LINES_HIST_N01.ind;
PROMPT XXCSO_SALES_LINES_N01.ind>>>
@XXCSO_SALES_LINES_N01.ind;
PROMPT XXCSO_SALES_NOTIFIES_N01.ind>>>
@XXCSO_SALES_NOTIFIES_N01.ind;
PROMPT XXCSO_SLS_PRSN_MNTHLY_PLNS_N01.ind>>>
@XXCSO_SLS_PRSN_MNTHLY_PLNS_N01.ind;
PROMPT XXCSO_SLS_PRSN_MNTHLY_PLNS_U01.ind>>>
@XXCSO_SLS_PRSN_MNTHLY_PLNS_U01.ind;
PROMPT XXCSO_SP_DECISION_ATTACHES_N01.ind>>>
@XXCSO_SP_DECISION_ATTACHES_N01.ind;
PROMPT XXCSO_SP_DECISION_CUSTS_U01.ind>>>
@XXCSO_SP_DECISION_CUSTS_U01.ind;
PROMPT XXCSO_SP_DECISION_HEADERS_N01.ind>>>
@XXCSO_SP_DECISION_HEADERS_N01.ind;
PROMPT XXCSO_SP_DECISION_HEADERS_U01.ind>>>
@XXCSO_SP_DECISION_HEADERS_U01.ind;
PROMPT XXCSO_SP_DECISION_LINES_N01.ind>>>
@XXCSO_SP_DECISION_LINES_N01.ind;
PROMPT XXCSO_SP_DECISION_SENDS_N01.ind>>>
@XXCSO_SP_DECISION_SENDS_N01.ind;
PROMPT XXCSO_SP_DECISION_SENDS_U01.ind>>>
@XXCSO_SP_DECISION_SENDS_U01.ind;
PROMPT XXCSO_SP_DECISION_WF_ORGS_U01.ind>>>
@XXCSO_SP_DECISION_WF_ORGS_U01.ind;
