PROMPT XXCSM_ITEM_LOC_BDGT_N01.ind>>>
@XXCSM_ITEM_LOC_BDGT_N01.ind;
PROMPT XXCSM_ITEM_PLAN_HEADERS_U01.ind>>>
@XXCSM_ITEM_PLAN_HEADERS_U01.ind;
PROMPT XXCSM_ITEM_PLAN_LINES_N01.ind>>>
@XXCSM_ITEM_PLAN_LINES_N01.ind;
PROMPT XXCSM_ITEM_PLAN_RESULT_N01.ind>>>
@XXCSM_ITEM_PLAN_RESULT_N01.ind;
PROMPT XXCSM_ITEM_PLAN_RESULT_N02.ind>>>
@XXCSM_ITEM_PLAN_RESULT_N02.ind;
PROMPT XXCSM_ITEM_PLAN_RESULT_N03.ind>>>
@XXCSM_ITEM_PLAN_RESULT_N03.ind;
PROMPT XXCSM_MST_QUALIFICATE_PNT_N01.ind>>>
@XXCSM_MST_QUALIFICATE_PNT_N01.ind;
PROMPT XXCSM_NEWS_ITEM_HDRS_ALL_N01.ind>>>
@XXCSM_NEWS_ITEM_HDRS_ALL_N01.ind;
PROMPT XXCSM_NEWS_ITEM_LINES_ALL_N01.ind>>>
@XXCSM_NEWS_ITEM_LINES_ALL_N01.ind;
PROMPT XXCSM_NEWS_ITEM_LINES_ALL_N02.ind>>>
@XXCSM_NEWS_ITEM_LINES_ALL_N02.ind;
