package itoen.oracle.apps.xxcso.common.schema.server;
import oracle.apps.fnd.framework.server.OAPlsqlEntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class XxcsoSlsPrsnMnthlyPlnsEOImpl extends OAPlsqlEntityImpl 
{
  protected static final int SLSPRSNMNTHLYPLNID = 0;
  protected static final int BASECODE = 1;
  protected static final int EMPLOYEENUMBER = 2;
  protected static final int YEARMONTH = 3;
  protected static final int FISCALYEAR = 4;
  protected static final int INPUTTYPE = 5;
  protected static final int GROUPNUMBER = 6;
  protected static final int GROUPLEADERFLAG = 7;
  protected static final int GROUPGRADE = 8;
  protected static final int PRIRSLTVDNEWSERVAMT = 9;
  protected static final int PRIRSLTVDNEXTSERVAMT = 10;
  protected static final int PRIRSLTVDEXISTSERVAMT = 11;
  protected static final int PRIRSLTVDTOTALAMT = 12;
  protected static final int PRIRSLTNEWSERVAMT = 13;
  protected static final int PRIRSLTNEXTSERVAMT = 14;
  protected static final int PRIRSLTEXISTSERVAMT = 15;
  protected static final int PRIRSLTTOTALAMT = 16;
  protected static final int PRIRSLTPRSNNEWSERVAMT = 17;
  protected static final int PRIRSLTPRSNNEXTSERVAMT = 18;
  protected static final int PRIRSLTPRSNEXISTSERVAMT = 19;
  protected static final int PRIRSLTPRSNTOTALAMT = 20;
  protected static final int BSCSLSVDNEWSERVAMT = 21;
  protected static final int BSCSLSVDNEXTSERVAMT = 22;
  protected static final int BSCSLSVDEXISTSERVAMT = 23;
  protected static final int BSCSLSVDTOTALAMT = 24;
  protected static final int BSCSLSNEWSERVAMT = 25;
  protected static final int BSCSLSNEXTSERVAMT = 26;
  protected static final int BSCSLSEXISTSERVAMT = 27;
  protected static final int BSCSLSTOTALAMT = 28;
  protected static final int BSCSLSPRSNNEWSERVAMT = 29;
  protected static final int BSCSLSPRSNNEXTSERVAMT = 30;
  protected static final int BSCSLSPRSNEXISTSERVAMT = 31;
  protected static final int BSCSLSPRSNTOTALAMT = 32;
  protected static final int TGTSALESVDNEWSERVAMT = 33;
  protected static final int TGTSALESVDNEXTSERVAMT = 34;
  protected static final int TGTSALESVDEXISTSERVAMT = 35;
  protected static final int TGTSALESVDTOTALAMT = 36;
  protected static final int TGTSALESNEWSERVAMT = 37;
  protected static final int TGTSALESNEXTSERVAMT = 38;
  protected static final int TGTSALESEXISTSERVAMT = 39;
  protected static final int TGTSALESTOTALAMT = 40;
  protected static final int TGTSALESPRSNNEWSERVAMT = 41;
  protected static final int TGTSALESPRSNNEXTSERVAMT = 42;
  protected static final int TGTSALESPRSNEXISTSERVAMT = 43;
  protected static final int TGTSALESPRSNTOTALAMT = 44;
  protected static final int RSLTVDNEWSERVAMT = 45;
  protected static final int RSLTVDNEXTSERVAMT = 46;
  protected static final int RSLTVDEXISTSERVAMT = 47;
  protected static final int RSLTVDTOTALAMT = 48;
  protected static final int RSLTNEWSERVAMT = 49;
  protected static final int RSLTNEXTSERVAMT = 50;
  protected static final int RSLTEXISTSERVAMT = 51;
  protected static final int RSLTTOTALAMT = 52;
  protected static final int RSLTPRSNNEWSERVAMT = 53;
  protected static final int RSLTPRSNNEXTSERVAMT = 54;
  protected static final int RSLTPRSNEXISTSERVAMT = 55;
  protected static final int RSLTPRSNTOTALAMT = 56;
  protected static final int VISVDNEWSERVAMT = 57;
  protected static final int VISVDNEXTSERVAMT = 58;
  protected static final int VISVDEXISTSERVAMT = 59;
  protected static final int VISVDTOTALAMT = 60;
  protected static final int VISNEWSERVAMT = 61;
  protected static final int VISNEXTSERVAMT = 62;
  protected static final int VISEXISTSERVAMT = 63;
  protected static final int VISTOTALAMT = 64;
  protected static final int VISPRSNNEWSERVAMT = 65;
  protected static final int VISPRSNNEXTSERVAMT = 66;
  protected static final int VISPRSNEXISTSERVAMT = 67;
  protected static final int VISPRSNTOTALAMT = 68;
  protected static final int DATALASTUPDATEFUNCTYPE = 69;
  protected static final int CREATEDBY = 70;
  protected static final int CREATIONDATE = 71;
  protected static final int LASTUPDATEDBY = 72;
  protected static final int LASTUPDATEDATE = 73;
  protected static final int LASTUPDATELOGIN = 74;
  protected static final int REQUESTID = 75;
  protected static final int PROGRAMAPPLICATIONID = 76;
  protected static final int PROGRAMID = 77;
  protected static final int PROGRAMUPDATEDATE = 78;
  private static oracle.apps.fnd.framework.server.OAEntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public XxcsoSlsPrsnMnthlyPlnsEOImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (oracle.apps.fnd.framework.server.OAEntityDefImpl)EntityDefImpl.findDefObject("itoen.oracle.apps.xxcso.common.schema.server.XxcsoSlsPrsnMnthlyPlnsEO");
    }
    return mDefinitionObject;
  }

  /**
   * 
   * Gets the attribute value for SlsPrsnMnthlyPlnId, using the alias name SlsPrsnMnthlyPlnId
   */
  public Number getSlsPrsnMnthlyPlnId()
  {
    return (Number)getAttributeInternal(SLSPRSNMNTHLYPLNID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SlsPrsnMnthlyPlnId
   */
  public void setSlsPrsnMnthlyPlnId(Number value)
  {
    setAttributeInternal(SLSPRSNMNTHLYPLNID, value);
  }

  /**
   * 
   * Gets the attribute value for BaseCode, using the alias name BaseCode
   */
  public Number getBaseCode()
  {
    return (Number)getAttributeInternal(BASECODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BaseCode
   */
  public void setBaseCode(Number value)
  {
    setAttributeInternal(BASECODE, value);
  }

  /**
   * 
   * Gets the attribute value for EmployeeNumber, using the alias name EmployeeNumber
   */
  public String getEmployeeNumber()
  {
    return (String)getAttributeInternal(EMPLOYEENUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for EmployeeNumber
   */
  public void setEmployeeNumber(String value)
  {
    setAttributeInternal(EMPLOYEENUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for YearMonth, using the alias name YearMonth
   */
  public String getYearMonth()
  {
    return (String)getAttributeInternal(YEARMONTH);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for YearMonth
   */
  public void setYearMonth(String value)
  {
    setAttributeInternal(YEARMONTH, value);
  }

  /**
   * 
   * Gets the attribute value for FiscalYear, using the alias name FiscalYear
   */
  public String getFiscalYear()
  {
    return (String)getAttributeInternal(FISCALYEAR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for FiscalYear
   */
  public void setFiscalYear(String value)
  {
    setAttributeInternal(FISCALYEAR, value);
  }

  /**
   * 
   * Gets the attribute value for InputType, using the alias name InputType
   */
  public String getInputType()
  {
    return (String)getAttributeInternal(INPUTTYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for InputType
   */
  public void setInputType(String value)
  {
    setAttributeInternal(INPUTTYPE, value);
  }

  /**
   * 
   * Gets the attribute value for GroupNumber, using the alias name GroupNumber
   */
  public String getGroupNumber()
  {
    return (String)getAttributeInternal(GROUPNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for GroupNumber
   */
  public void setGroupNumber(String value)
  {
    setAttributeInternal(GROUPNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for GroupLeaderFlag, using the alias name GroupLeaderFlag
   */
  public String getGroupLeaderFlag()
  {
    return (String)getAttributeInternal(GROUPLEADERFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for GroupLeaderFlag
   */
  public void setGroupLeaderFlag(String value)
  {
    setAttributeInternal(GROUPLEADERFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for GroupGrade, using the alias name GroupGrade
   */
  public String getGroupGrade()
  {
    return (String)getAttributeInternal(GROUPGRADE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for GroupGrade
   */
  public void setGroupGrade(String value)
  {
    setAttributeInternal(GROUPGRADE, value);
  }

  /**
   * 
   * Gets the attribute value for PriRsltVdNewServAmt, using the alias name PriRsltVdNewServAmt
   */
  public Number getPriRsltVdNewServAmt()
  {
    return (Number)getAttributeInternal(PRIRSLTVDNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriRsltVdNewServAmt
   */
  public void setPriRsltVdNewServAmt(Number value)
  {
    setAttributeInternal(PRIRSLTVDNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for PriRsltVdNextServAmt, using the alias name PriRsltVdNextServAmt
   */
  public Number getPriRsltVdNextServAmt()
  {
    return (Number)getAttributeInternal(PRIRSLTVDNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriRsltVdNextServAmt
   */
  public void setPriRsltVdNextServAmt(Number value)
  {
    setAttributeInternal(PRIRSLTVDNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for PriRsltVdExistServAmt, using the alias name PriRsltVdExistServAmt
   */
  public Number getPriRsltVdExistServAmt()
  {
    return (Number)getAttributeInternal(PRIRSLTVDEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriRsltVdExistServAmt
   */
  public void setPriRsltVdExistServAmt(Number value)
  {
    setAttributeInternal(PRIRSLTVDEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for PriRsltVdTotalAmt, using the alias name PriRsltVdTotalAmt
   */
  public Number getPriRsltVdTotalAmt()
  {
    return (Number)getAttributeInternal(PRIRSLTVDTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriRsltVdTotalAmt
   */
  public void setPriRsltVdTotalAmt(Number value)
  {
    setAttributeInternal(PRIRSLTVDTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for PriRsltNewServAmt, using the alias name PriRsltNewServAmt
   */
  public Number getPriRsltNewServAmt()
  {
    return (Number)getAttributeInternal(PRIRSLTNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriRsltNewServAmt
   */
  public void setPriRsltNewServAmt(Number value)
  {
    setAttributeInternal(PRIRSLTNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for PriRsltNextServAmt, using the alias name PriRsltNextServAmt
   */
  public Number getPriRsltNextServAmt()
  {
    return (Number)getAttributeInternal(PRIRSLTNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriRsltNextServAmt
   */
  public void setPriRsltNextServAmt(Number value)
  {
    setAttributeInternal(PRIRSLTNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for PriRsltExistServAmt, using the alias name PriRsltExistServAmt
   */
  public Number getPriRsltExistServAmt()
  {
    return (Number)getAttributeInternal(PRIRSLTEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriRsltExistServAmt
   */
  public void setPriRsltExistServAmt(Number value)
  {
    setAttributeInternal(PRIRSLTEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for PriRsltTotalAmt, using the alias name PriRsltTotalAmt
   */
  public Number getPriRsltTotalAmt()
  {
    return (Number)getAttributeInternal(PRIRSLTTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriRsltTotalAmt
   */
  public void setPriRsltTotalAmt(Number value)
  {
    setAttributeInternal(PRIRSLTTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for PriRsltPrsnNewServAmt, using the alias name PriRsltPrsnNewServAmt
   */
  public Number getPriRsltPrsnNewServAmt()
  {
    return (Number)getAttributeInternal(PRIRSLTPRSNNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriRsltPrsnNewServAmt
   */
  public void setPriRsltPrsnNewServAmt(Number value)
  {
    setAttributeInternal(PRIRSLTPRSNNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for PriRsltPrsnNextServAmt, using the alias name PriRsltPrsnNextServAmt
   */
  public Number getPriRsltPrsnNextServAmt()
  {
    return (Number)getAttributeInternal(PRIRSLTPRSNNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriRsltPrsnNextServAmt
   */
  public void setPriRsltPrsnNextServAmt(Number value)
  {
    setAttributeInternal(PRIRSLTPRSNNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for PriRsltPrsnExistServAmt, using the alias name PriRsltPrsnExistServAmt
   */
  public Number getPriRsltPrsnExistServAmt()
  {
    return (Number)getAttributeInternal(PRIRSLTPRSNEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriRsltPrsnExistServAmt
   */
  public void setPriRsltPrsnExistServAmt(Number value)
  {
    setAttributeInternal(PRIRSLTPRSNEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for PriRsltPrsnTotalAmt, using the alias name PriRsltPrsnTotalAmt
   */
  public Number getPriRsltPrsnTotalAmt()
  {
    return (Number)getAttributeInternal(PRIRSLTPRSNTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriRsltPrsnTotalAmt
   */
  public void setPriRsltPrsnTotalAmt(Number value)
  {
    setAttributeInternal(PRIRSLTPRSNTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for BscSlsVdNewServAmt, using the alias name BscSlsVdNewServAmt
   */
  public Number getBscSlsVdNewServAmt()
  {
    return (Number)getAttributeInternal(BSCSLSVDNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BscSlsVdNewServAmt
   */
  public void setBscSlsVdNewServAmt(Number value)
  {
    setAttributeInternal(BSCSLSVDNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for BscSlsVdNextServAmt, using the alias name BscSlsVdNextServAmt
   */
  public Number getBscSlsVdNextServAmt()
  {
    return (Number)getAttributeInternal(BSCSLSVDNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BscSlsVdNextServAmt
   */
  public void setBscSlsVdNextServAmt(Number value)
  {
    setAttributeInternal(BSCSLSVDNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for BscSlsVdExistServAmt, using the alias name BscSlsVdExistServAmt
   */
  public Number getBscSlsVdExistServAmt()
  {
    return (Number)getAttributeInternal(BSCSLSVDEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BscSlsVdExistServAmt
   */
  public void setBscSlsVdExistServAmt(Number value)
  {
    setAttributeInternal(BSCSLSVDEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for BscSlsVdTotalAmt, using the alias name BscSlsVdTotalAmt
   */
  public Number getBscSlsVdTotalAmt()
  {
    return (Number)getAttributeInternal(BSCSLSVDTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BscSlsVdTotalAmt
   */
  public void setBscSlsVdTotalAmt(Number value)
  {
    setAttributeInternal(BSCSLSVDTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for BscSlsNewServAmt, using the alias name BscSlsNewServAmt
   */
  public Number getBscSlsNewServAmt()
  {
    return (Number)getAttributeInternal(BSCSLSNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BscSlsNewServAmt
   */
  public void setBscSlsNewServAmt(Number value)
  {
    setAttributeInternal(BSCSLSNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for BscSlsNextServAmt, using the alias name BscSlsNextServAmt
   */
  public Number getBscSlsNextServAmt()
  {
    return (Number)getAttributeInternal(BSCSLSNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BscSlsNextServAmt
   */
  public void setBscSlsNextServAmt(Number value)
  {
    setAttributeInternal(BSCSLSNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for BscSlsExistServAmt, using the alias name BscSlsExistServAmt
   */
  public Number getBscSlsExistServAmt()
  {
    return (Number)getAttributeInternal(BSCSLSEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BscSlsExistServAmt
   */
  public void setBscSlsExistServAmt(Number value)
  {
    setAttributeInternal(BSCSLSEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for BscSlsTotalAmt, using the alias name BscSlsTotalAmt
   */
  public Number getBscSlsTotalAmt()
  {
    return (Number)getAttributeInternal(BSCSLSTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BscSlsTotalAmt
   */
  public void setBscSlsTotalAmt(Number value)
  {
    setAttributeInternal(BSCSLSTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for BscSlsPrsnNewServAmt, using the alias name BscSlsPrsnNewServAmt
   */
  public Number getBscSlsPrsnNewServAmt()
  {
    return (Number)getAttributeInternal(BSCSLSPRSNNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BscSlsPrsnNewServAmt
   */
  public void setBscSlsPrsnNewServAmt(Number value)
  {
    setAttributeInternal(BSCSLSPRSNNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for BscSlsPrsnNextServAmt, using the alias name BscSlsPrsnNextServAmt
   */
  public Number getBscSlsPrsnNextServAmt()
  {
    return (Number)getAttributeInternal(BSCSLSPRSNNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BscSlsPrsnNextServAmt
   */
  public void setBscSlsPrsnNextServAmt(Number value)
  {
    setAttributeInternal(BSCSLSPRSNNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for BscSlsPrsnExistServAmt, using the alias name BscSlsPrsnExistServAmt
   */
  public Number getBscSlsPrsnExistServAmt()
  {
    return (Number)getAttributeInternal(BSCSLSPRSNEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BscSlsPrsnExistServAmt
   */
  public void setBscSlsPrsnExistServAmt(Number value)
  {
    setAttributeInternal(BSCSLSPRSNEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for BscSlsPrsnTotalAmt, using the alias name BscSlsPrsnTotalAmt
   */
  public Number getBscSlsPrsnTotalAmt()
  {
    return (Number)getAttributeInternal(BSCSLSPRSNTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BscSlsPrsnTotalAmt
   */
  public void setBscSlsPrsnTotalAmt(Number value)
  {
    setAttributeInternal(BSCSLSPRSNTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for TgtSalesVdNewServAmt, using the alias name TgtSalesVdNewServAmt
   */
  public Number getTgtSalesVdNewServAmt()
  {
    return (Number)getAttributeInternal(TGTSALESVDNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TgtSalesVdNewServAmt
   */
  public void setTgtSalesVdNewServAmt(Number value)
  {
    setAttributeInternal(TGTSALESVDNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for TgtSalesVdNextServAmt, using the alias name TgtSalesVdNextServAmt
   */
  public Number getTgtSalesVdNextServAmt()
  {
    return (Number)getAttributeInternal(TGTSALESVDNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TgtSalesVdNextServAmt
   */
  public void setTgtSalesVdNextServAmt(Number value)
  {
    setAttributeInternal(TGTSALESVDNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for TgtSalesVdExistServAmt, using the alias name TgtSalesVdExistServAmt
   */
  public Number getTgtSalesVdExistServAmt()
  {
    return (Number)getAttributeInternal(TGTSALESVDEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TgtSalesVdExistServAmt
   */
  public void setTgtSalesVdExistServAmt(Number value)
  {
    setAttributeInternal(TGTSALESVDEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for TgtSalesVdTotalAmt, using the alias name TgtSalesVdTotalAmt
   */
  public Number getTgtSalesVdTotalAmt()
  {
    return (Number)getAttributeInternal(TGTSALESVDTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TgtSalesVdTotalAmt
   */
  public void setTgtSalesVdTotalAmt(Number value)
  {
    setAttributeInternal(TGTSALESVDTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for TgtSalesNewServAmt, using the alias name TgtSalesNewServAmt
   */
  public Number getTgtSalesNewServAmt()
  {
    return (Number)getAttributeInternal(TGTSALESNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TgtSalesNewServAmt
   */
  public void setTgtSalesNewServAmt(Number value)
  {
    setAttributeInternal(TGTSALESNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for TgtSalesNextServAmt, using the alias name TgtSalesNextServAmt
   */
  public Number getTgtSalesNextServAmt()
  {
    return (Number)getAttributeInternal(TGTSALESNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TgtSalesNextServAmt
   */
  public void setTgtSalesNextServAmt(Number value)
  {
    setAttributeInternal(TGTSALESNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for TgtSalesExistServAmt, using the alias name TgtSalesExistServAmt
   */
  public Number getTgtSalesExistServAmt()
  {
    return (Number)getAttributeInternal(TGTSALESEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TgtSalesExistServAmt
   */
  public void setTgtSalesExistServAmt(Number value)
  {
    setAttributeInternal(TGTSALESEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for TgtSalesTotalAmt, using the alias name TgtSalesTotalAmt
   */
  public Number getTgtSalesTotalAmt()
  {
    return (Number)getAttributeInternal(TGTSALESTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TgtSalesTotalAmt
   */
  public void setTgtSalesTotalAmt(Number value)
  {
    setAttributeInternal(TGTSALESTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for TgtSalesPrsnNewServAmt, using the alias name TgtSalesPrsnNewServAmt
   */
  public Number getTgtSalesPrsnNewServAmt()
  {
    return (Number)getAttributeInternal(TGTSALESPRSNNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TgtSalesPrsnNewServAmt
   */
  public void setTgtSalesPrsnNewServAmt(Number value)
  {
    setAttributeInternal(TGTSALESPRSNNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for TgtSalesPrsnNextServAmt, using the alias name TgtSalesPrsnNextServAmt
   */
  public Number getTgtSalesPrsnNextServAmt()
  {
    return (Number)getAttributeInternal(TGTSALESPRSNNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TgtSalesPrsnNextServAmt
   */
  public void setTgtSalesPrsnNextServAmt(Number value)
  {
    setAttributeInternal(TGTSALESPRSNNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for TgtSalesPrsnExistServAmt, using the alias name TgtSalesPrsnExistServAmt
   */
  public Number getTgtSalesPrsnExistServAmt()
  {
    return (Number)getAttributeInternal(TGTSALESPRSNEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TgtSalesPrsnExistServAmt
   */
  public void setTgtSalesPrsnExistServAmt(Number value)
  {
    setAttributeInternal(TGTSALESPRSNEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for TgtSalesPrsnTotalAmt, using the alias name TgtSalesPrsnTotalAmt
   */
  public Number getTgtSalesPrsnTotalAmt()
  {
    return (Number)getAttributeInternal(TGTSALESPRSNTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TgtSalesPrsnTotalAmt
   */
  public void setTgtSalesPrsnTotalAmt(Number value)
  {
    setAttributeInternal(TGTSALESPRSNTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for RsltVdNewServAmt, using the alias name RsltVdNewServAmt
   */
  public Number getRsltVdNewServAmt()
  {
    return (Number)getAttributeInternal(RSLTVDNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RsltVdNewServAmt
   */
  public void setRsltVdNewServAmt(Number value)
  {
    setAttributeInternal(RSLTVDNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for RsltVdNextServAmt, using the alias name RsltVdNextServAmt
   */
  public Number getRsltVdNextServAmt()
  {
    return (Number)getAttributeInternal(RSLTVDNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RsltVdNextServAmt
   */
  public void setRsltVdNextServAmt(Number value)
  {
    setAttributeInternal(RSLTVDNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for RsltVdExistServAmt, using the alias name RsltVdExistServAmt
   */
  public Number getRsltVdExistServAmt()
  {
    return (Number)getAttributeInternal(RSLTVDEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RsltVdExistServAmt
   */
  public void setRsltVdExistServAmt(Number value)
  {
    setAttributeInternal(RSLTVDEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for RsltVdTotalAmt, using the alias name RsltVdTotalAmt
   */
  public Number getRsltVdTotalAmt()
  {
    return (Number)getAttributeInternal(RSLTVDTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RsltVdTotalAmt
   */
  public void setRsltVdTotalAmt(Number value)
  {
    setAttributeInternal(RSLTVDTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for RsltNewServAmt, using the alias name RsltNewServAmt
   */
  public Number getRsltNewServAmt()
  {
    return (Number)getAttributeInternal(RSLTNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RsltNewServAmt
   */
  public void setRsltNewServAmt(Number value)
  {
    setAttributeInternal(RSLTNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for RsltNextServAmt, using the alias name RsltNextServAmt
   */
  public Number getRsltNextServAmt()
  {
    return (Number)getAttributeInternal(RSLTNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RsltNextServAmt
   */
  public void setRsltNextServAmt(Number value)
  {
    setAttributeInternal(RSLTNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for RsltExistServAmt, using the alias name RsltExistServAmt
   */
  public Number getRsltExistServAmt()
  {
    return (Number)getAttributeInternal(RSLTEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RsltExistServAmt
   */
  public void setRsltExistServAmt(Number value)
  {
    setAttributeInternal(RSLTEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for RsltTotalAmt, using the alias name RsltTotalAmt
   */
  public Number getRsltTotalAmt()
  {
    return (Number)getAttributeInternal(RSLTTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RsltTotalAmt
   */
  public void setRsltTotalAmt(Number value)
  {
    setAttributeInternal(RSLTTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for RsltPrsnNewServAmt, using the alias name RsltPrsnNewServAmt
   */
  public Number getRsltPrsnNewServAmt()
  {
    return (Number)getAttributeInternal(RSLTPRSNNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RsltPrsnNewServAmt
   */
  public void setRsltPrsnNewServAmt(Number value)
  {
    setAttributeInternal(RSLTPRSNNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for RsltPrsnNextServAmt, using the alias name RsltPrsnNextServAmt
   */
  public Number getRsltPrsnNextServAmt()
  {
    return (Number)getAttributeInternal(RSLTPRSNNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RsltPrsnNextServAmt
   */
  public void setRsltPrsnNextServAmt(Number value)
  {
    setAttributeInternal(RSLTPRSNNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for RsltPrsnExistServAmt, using the alias name RsltPrsnExistServAmt
   */
  public Number getRsltPrsnExistServAmt()
  {
    return (Number)getAttributeInternal(RSLTPRSNEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RsltPrsnExistServAmt
   */
  public void setRsltPrsnExistServAmt(Number value)
  {
    setAttributeInternal(RSLTPRSNEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for RsltPrsnTotalAmt, using the alias name RsltPrsnTotalAmt
   */
  public Number getRsltPrsnTotalAmt()
  {
    return (Number)getAttributeInternal(RSLTPRSNTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RsltPrsnTotalAmt
   */
  public void setRsltPrsnTotalAmt(Number value)
  {
    setAttributeInternal(RSLTPRSNTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for VisVdNewServAmt, using the alias name VisVdNewServAmt
   */
  public Number getVisVdNewServAmt()
  {
    return (Number)getAttributeInternal(VISVDNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VisVdNewServAmt
   */
  public void setVisVdNewServAmt(Number value)
  {
    setAttributeInternal(VISVDNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for VisVdNextServAmt, using the alias name VisVdNextServAmt
   */
  public Number getVisVdNextServAmt()
  {
    return (Number)getAttributeInternal(VISVDNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VisVdNextServAmt
   */
  public void setVisVdNextServAmt(Number value)
  {
    setAttributeInternal(VISVDNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for VisVdExistServAmt, using the alias name VisVdExistServAmt
   */
  public Number getVisVdExistServAmt()
  {
    return (Number)getAttributeInternal(VISVDEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VisVdExistServAmt
   */
  public void setVisVdExistServAmt(Number value)
  {
    setAttributeInternal(VISVDEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for VisVdTotalAmt, using the alias name VisVdTotalAmt
   */
  public Number getVisVdTotalAmt()
  {
    return (Number)getAttributeInternal(VISVDTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VisVdTotalAmt
   */
  public void setVisVdTotalAmt(Number value)
  {
    setAttributeInternal(VISVDTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for VisNewServAmt, using the alias name VisNewServAmt
   */
  public Number getVisNewServAmt()
  {
    return (Number)getAttributeInternal(VISNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VisNewServAmt
   */
  public void setVisNewServAmt(Number value)
  {
    setAttributeInternal(VISNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for VisNextServAmt, using the alias name VisNextServAmt
   */
  public Number getVisNextServAmt()
  {
    return (Number)getAttributeInternal(VISNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VisNextServAmt
   */
  public void setVisNextServAmt(Number value)
  {
    setAttributeInternal(VISNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for VisExistServAmt, using the alias name VisExistServAmt
   */
  public Number getVisExistServAmt()
  {
    return (Number)getAttributeInternal(VISEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VisExistServAmt
   */
  public void setVisExistServAmt(Number value)
  {
    setAttributeInternal(VISEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for VisTotalAmt, using the alias name VisTotalAmt
   */
  public Number getVisTotalAmt()
  {
    return (Number)getAttributeInternal(VISTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VisTotalAmt
   */
  public void setVisTotalAmt(Number value)
  {
    setAttributeInternal(VISTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for VisPrsnNewServAmt, using the alias name VisPrsnNewServAmt
   */
  public Number getVisPrsnNewServAmt()
  {
    return (Number)getAttributeInternal(VISPRSNNEWSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VisPrsnNewServAmt
   */
  public void setVisPrsnNewServAmt(Number value)
  {
    setAttributeInternal(VISPRSNNEWSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for VisPrsnNextServAmt, using the alias name VisPrsnNextServAmt
   */
  public Number getVisPrsnNextServAmt()
  {
    return (Number)getAttributeInternal(VISPRSNNEXTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VisPrsnNextServAmt
   */
  public void setVisPrsnNextServAmt(Number value)
  {
    setAttributeInternal(VISPRSNNEXTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for VisPrsnExistServAmt, using the alias name VisPrsnExistServAmt
   */
  public Number getVisPrsnExistServAmt()
  {
    return (Number)getAttributeInternal(VISPRSNEXISTSERVAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VisPrsnExistServAmt
   */
  public void setVisPrsnExistServAmt(Number value)
  {
    setAttributeInternal(VISPRSNEXISTSERVAMT, value);
  }

  /**
   * 
   * Gets the attribute value for VisPrsnTotalAmt, using the alias name VisPrsnTotalAmt
   */
  public Number getVisPrsnTotalAmt()
  {
    return (Number)getAttributeInternal(VISPRSNTOTALAMT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VisPrsnTotalAmt
   */
  public void setVisPrsnTotalAmt(Number value)
  {
    setAttributeInternal(VISPRSNTOTALAMT, value);
  }

  /**
   * 
   * Gets the attribute value for DataLastUpdateFuncType, using the alias name DataLastUpdateFuncType
   */
  public String getDataLastUpdateFuncType()
  {
    return (String)getAttributeInternal(DATALASTUPDATEFUNCTYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DataLastUpdateFuncType
   */
  public void setDataLastUpdateFuncType(String value)
  {
    setAttributeInternal(DATALASTUPDATEFUNCTYPE, value);
  }

  /**
   * 
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**
   * 
   * Gets the attribute value for RequestId, using the alias name RequestId
   */
  public Number getRequestId()
  {
    return (Number)getAttributeInternal(REQUESTID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RequestId
   */
  public void setRequestId(Number value)
  {
    setAttributeInternal(REQUESTID, value);
  }

  /**
   * 
   * Gets the attribute value for ProgramApplicationId, using the alias name ProgramApplicationId
   */
  public Number getProgramApplicationId()
  {
    return (Number)getAttributeInternal(PROGRAMAPPLICATIONID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ProgramApplicationId
   */
  public void setProgramApplicationId(Number value)
  {
    setAttributeInternal(PROGRAMAPPLICATIONID, value);
  }

  /**
   * 
   * Gets the attribute value for ProgramId, using the alias name ProgramId
   */
  public Number getProgramId()
  {
    return (Number)getAttributeInternal(PROGRAMID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ProgramId
   */
  public void setProgramId(Number value)
  {
    setAttributeInternal(PROGRAMID, value);
  }

  /**
   * 
   * Gets the attribute value for ProgramUpdateDate, using the alias name ProgramUpdateDate
   */
  public Date getProgramUpdateDate()
  {
    return (Date)getAttributeInternal(PROGRAMUPDATEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ProgramUpdateDate
   */
  public void setProgramUpdateDate(Date value)
  {
    setAttributeInternal(PROGRAMUPDATEDATE, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case SLSPRSNMNTHLYPLNID:
        return getSlsPrsnMnthlyPlnId();
      case BASECODE:
        return getBaseCode();
      case EMPLOYEENUMBER:
        return getEmployeeNumber();
      case YEARMONTH:
        return getYearMonth();
      case FISCALYEAR:
        return getFiscalYear();
      case INPUTTYPE:
        return getInputType();
      case GROUPNUMBER:
        return getGroupNumber();
      case GROUPLEADERFLAG:
        return getGroupLeaderFlag();
      case GROUPGRADE:
        return getGroupGrade();
      case PRIRSLTVDNEWSERVAMT:
        return getPriRsltVdNewServAmt();
      case PRIRSLTVDNEXTSERVAMT:
        return getPriRsltVdNextServAmt();
      case PRIRSLTVDEXISTSERVAMT:
        return getPriRsltVdExistServAmt();
      case PRIRSLTVDTOTALAMT:
        return getPriRsltVdTotalAmt();
      case PRIRSLTNEWSERVAMT:
        return getPriRsltNewServAmt();
      case PRIRSLTNEXTSERVAMT:
        return getPriRsltNextServAmt();
      case PRIRSLTEXISTSERVAMT:
        return getPriRsltExistServAmt();
      case PRIRSLTTOTALAMT:
        return getPriRsltTotalAmt();
      case PRIRSLTPRSNNEWSERVAMT:
        return getPriRsltPrsnNewServAmt();
      case PRIRSLTPRSNNEXTSERVAMT:
        return getPriRsltPrsnNextServAmt();
      case PRIRSLTPRSNEXISTSERVAMT:
        return getPriRsltPrsnExistServAmt();
      case PRIRSLTPRSNTOTALAMT:
        return getPriRsltPrsnTotalAmt();
      case BSCSLSVDNEWSERVAMT:
        return getBscSlsVdNewServAmt();
      case BSCSLSVDNEXTSERVAMT:
        return getBscSlsVdNextServAmt();
      case BSCSLSVDEXISTSERVAMT:
        return getBscSlsVdExistServAmt();
      case BSCSLSVDTOTALAMT:
        return getBscSlsVdTotalAmt();
      case BSCSLSNEWSERVAMT:
        return getBscSlsNewServAmt();
      case BSCSLSNEXTSERVAMT:
        return getBscSlsNextServAmt();
      case BSCSLSEXISTSERVAMT:
        return getBscSlsExistServAmt();
      case BSCSLSTOTALAMT:
        return getBscSlsTotalAmt();
      case BSCSLSPRSNNEWSERVAMT:
        return getBscSlsPrsnNewServAmt();
      case BSCSLSPRSNNEXTSERVAMT:
        return getBscSlsPrsnNextServAmt();
      case BSCSLSPRSNEXISTSERVAMT:
        return getBscSlsPrsnExistServAmt();
      case BSCSLSPRSNTOTALAMT:
        return getBscSlsPrsnTotalAmt();
      case TGTSALESVDNEWSERVAMT:
        return getTgtSalesVdNewServAmt();
      case TGTSALESVDNEXTSERVAMT:
        return getTgtSalesVdNextServAmt();
      case TGTSALESVDEXISTSERVAMT:
        return getTgtSalesVdExistServAmt();
      case TGTSALESVDTOTALAMT:
        return getTgtSalesVdTotalAmt();
      case TGTSALESNEWSERVAMT:
        return getTgtSalesNewServAmt();
      case TGTSALESNEXTSERVAMT:
        return getTgtSalesNextServAmt();
      case TGTSALESEXISTSERVAMT:
        return getTgtSalesExistServAmt();
      case TGTSALESTOTALAMT:
        return getTgtSalesTotalAmt();
      case TGTSALESPRSNNEWSERVAMT:
        return getTgtSalesPrsnNewServAmt();
      case TGTSALESPRSNNEXTSERVAMT:
        return getTgtSalesPrsnNextServAmt();
      case TGTSALESPRSNEXISTSERVAMT:
        return getTgtSalesPrsnExistServAmt();
      case TGTSALESPRSNTOTALAMT:
        return getTgtSalesPrsnTotalAmt();
      case RSLTVDNEWSERVAMT:
        return getRsltVdNewServAmt();
      case RSLTVDNEXTSERVAMT:
        return getRsltVdNextServAmt();
      case RSLTVDEXISTSERVAMT:
        return getRsltVdExistServAmt();
      case RSLTVDTOTALAMT:
        return getRsltVdTotalAmt();
      case RSLTNEWSERVAMT:
        return getRsltNewServAmt();
      case RSLTNEXTSERVAMT:
        return getRsltNextServAmt();
      case RSLTEXISTSERVAMT:
        return getRsltExistServAmt();
      case RSLTTOTALAMT:
        return getRsltTotalAmt();
      case RSLTPRSNNEWSERVAMT:
        return getRsltPrsnNewServAmt();
      case RSLTPRSNNEXTSERVAMT:
        return getRsltPrsnNextServAmt();
      case RSLTPRSNEXISTSERVAMT:
        return getRsltPrsnExistServAmt();
      case RSLTPRSNTOTALAMT:
        return getRsltPrsnTotalAmt();
      case VISVDNEWSERVAMT:
        return getVisVdNewServAmt();
      case VISVDNEXTSERVAMT:
        return getVisVdNextServAmt();
      case VISVDEXISTSERVAMT:
        return getVisVdExistServAmt();
      case VISVDTOTALAMT:
        return getVisVdTotalAmt();
      case VISNEWSERVAMT:
        return getVisNewServAmt();
      case VISNEXTSERVAMT:
        return getVisNextServAmt();
      case VISEXISTSERVAMT:
        return getVisExistServAmt();
      case VISTOTALAMT:
        return getVisTotalAmt();
      case VISPRSNNEWSERVAMT:
        return getVisPrsnNewServAmt();
      case VISPRSNNEXTSERVAMT:
        return getVisPrsnNextServAmt();
      case VISPRSNEXISTSERVAMT:
        return getVisPrsnExistServAmt();
      case VISPRSNTOTALAMT:
        return getVisPrsnTotalAmt();
      case DATALASTUPDATEFUNCTYPE:
        return getDataLastUpdateFuncType();
      case CREATEDBY:
        return getCreatedBy();
      case CREATIONDATE:
        return getCreationDate();
      case LASTUPDATEDBY:
        return getLastUpdatedBy();
      case LASTUPDATEDATE:
        return getLastUpdateDate();
      case LASTUPDATELOGIN:
        return getLastUpdateLogin();
      case REQUESTID:
        return getRequestId();
      case PROGRAMAPPLICATIONID:
        return getProgramApplicationId();
      case PROGRAMID:
        return getProgramId();
      case PROGRAMUPDATEDATE:
        return getProgramUpdateDate();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case SLSPRSNMNTHLYPLNID:
        setSlsPrsnMnthlyPlnId((Number)value);
        return;
      case BASECODE:
        setBaseCode((Number)value);
        return;
      case EMPLOYEENUMBER:
        setEmployeeNumber((String)value);
        return;
      case YEARMONTH:
        setYearMonth((String)value);
        return;
      case FISCALYEAR:
        setFiscalYear((String)value);
        return;
      case INPUTTYPE:
        setInputType((String)value);
        return;
      case GROUPNUMBER:
        setGroupNumber((String)value);
        return;
      case GROUPLEADERFLAG:
        setGroupLeaderFlag((String)value);
        return;
      case GROUPGRADE:
        setGroupGrade((String)value);
        return;
      case PRIRSLTVDNEWSERVAMT:
        setPriRsltVdNewServAmt((Number)value);
        return;
      case PRIRSLTVDNEXTSERVAMT:
        setPriRsltVdNextServAmt((Number)value);
        return;
      case PRIRSLTVDEXISTSERVAMT:
        setPriRsltVdExistServAmt((Number)value);
        return;
      case PRIRSLTVDTOTALAMT:
        setPriRsltVdTotalAmt((Number)value);
        return;
      case PRIRSLTNEWSERVAMT:
        setPriRsltNewServAmt((Number)value);
        return;
      case PRIRSLTNEXTSERVAMT:
        setPriRsltNextServAmt((Number)value);
        return;
      case PRIRSLTEXISTSERVAMT:
        setPriRsltExistServAmt((Number)value);
        return;
      case PRIRSLTTOTALAMT:
        setPriRsltTotalAmt((Number)value);
        return;
      case PRIRSLTPRSNNEWSERVAMT:
        setPriRsltPrsnNewServAmt((Number)value);
        return;
      case PRIRSLTPRSNNEXTSERVAMT:
        setPriRsltPrsnNextServAmt((Number)value);
        return;
      case PRIRSLTPRSNEXISTSERVAMT:
        setPriRsltPrsnExistServAmt((Number)value);
        return;
      case PRIRSLTPRSNTOTALAMT:
        setPriRsltPrsnTotalAmt((Number)value);
        return;
      case BSCSLSVDNEWSERVAMT:
        setBscSlsVdNewServAmt((Number)value);
        return;
      case BSCSLSVDNEXTSERVAMT:
        setBscSlsVdNextServAmt((Number)value);
        return;
      case BSCSLSVDEXISTSERVAMT:
        setBscSlsVdExistServAmt((Number)value);
        return;
      case BSCSLSVDTOTALAMT:
        setBscSlsVdTotalAmt((Number)value);
        return;
      case BSCSLSNEWSERVAMT:
        setBscSlsNewServAmt((Number)value);
        return;
      case BSCSLSNEXTSERVAMT:
        setBscSlsNextServAmt((Number)value);
        return;
      case BSCSLSEXISTSERVAMT:
        setBscSlsExistServAmt((Number)value);
        return;
      case BSCSLSTOTALAMT:
        setBscSlsTotalAmt((Number)value);
        return;
      case BSCSLSPRSNNEWSERVAMT:
        setBscSlsPrsnNewServAmt((Number)value);
        return;
      case BSCSLSPRSNNEXTSERVAMT:
        setBscSlsPrsnNextServAmt((Number)value);
        return;
      case BSCSLSPRSNEXISTSERVAMT:
        setBscSlsPrsnExistServAmt((Number)value);
        return;
      case BSCSLSPRSNTOTALAMT:
        setBscSlsPrsnTotalAmt((Number)value);
        return;
      case TGTSALESVDNEWSERVAMT:
        setTgtSalesVdNewServAmt((Number)value);
        return;
      case TGTSALESVDNEXTSERVAMT:
        setTgtSalesVdNextServAmt((Number)value);
        return;
      case TGTSALESVDEXISTSERVAMT:
        setTgtSalesVdExistServAmt((Number)value);
        return;
      case TGTSALESVDTOTALAMT:
        setTgtSalesVdTotalAmt((Number)value);
        return;
      case TGTSALESNEWSERVAMT:
        setTgtSalesNewServAmt((Number)value);
        return;
      case TGTSALESNEXTSERVAMT:
        setTgtSalesNextServAmt((Number)value);
        return;
      case TGTSALESEXISTSERVAMT:
        setTgtSalesExistServAmt((Number)value);
        return;
      case TGTSALESTOTALAMT:
        setTgtSalesTotalAmt((Number)value);
        return;
      case TGTSALESPRSNNEWSERVAMT:
        setTgtSalesPrsnNewServAmt((Number)value);
        return;
      case TGTSALESPRSNNEXTSERVAMT:
        setTgtSalesPrsnNextServAmt((Number)value);
        return;
      case TGTSALESPRSNEXISTSERVAMT:
        setTgtSalesPrsnExistServAmt((Number)value);
        return;
      case TGTSALESPRSNTOTALAMT:
        setTgtSalesPrsnTotalAmt((Number)value);
        return;
      case RSLTVDNEWSERVAMT:
        setRsltVdNewServAmt((Number)value);
        return;
      case RSLTVDNEXTSERVAMT:
        setRsltVdNextServAmt((Number)value);
        return;
      case RSLTVDEXISTSERVAMT:
        setRsltVdExistServAmt((Number)value);
        return;
      case RSLTVDTOTALAMT:
        setRsltVdTotalAmt((Number)value);
        return;
      case RSLTNEWSERVAMT:
        setRsltNewServAmt((Number)value);
        return;
      case RSLTNEXTSERVAMT:
        setRsltNextServAmt((Number)value);
        return;
      case RSLTEXISTSERVAMT:
        setRsltExistServAmt((Number)value);
        return;
      case RSLTTOTALAMT:
        setRsltTotalAmt((Number)value);
        return;
      case RSLTPRSNNEWSERVAMT:
        setRsltPrsnNewServAmt((Number)value);
        return;
      case RSLTPRSNNEXTSERVAMT:
        setRsltPrsnNextServAmt((Number)value);
        return;
      case RSLTPRSNEXISTSERVAMT:
        setRsltPrsnExistServAmt((Number)value);
        return;
      case RSLTPRSNTOTALAMT:
        setRsltPrsnTotalAmt((Number)value);
        return;
      case VISVDNEWSERVAMT:
        setVisVdNewServAmt((Number)value);
        return;
      case VISVDNEXTSERVAMT:
        setVisVdNextServAmt((Number)value);
        return;
      case VISVDEXISTSERVAMT:
        setVisVdExistServAmt((Number)value);
        return;
      case VISVDTOTALAMT:
        setVisVdTotalAmt((Number)value);
        return;
      case VISNEWSERVAMT:
        setVisNewServAmt((Number)value);
        return;
      case VISNEXTSERVAMT:
        setVisNextServAmt((Number)value);
        return;
      case VISEXISTSERVAMT:
        setVisExistServAmt((Number)value);
        return;
      case VISTOTALAMT:
        setVisTotalAmt((Number)value);
        return;
      case VISPRSNNEWSERVAMT:
        setVisPrsnNewServAmt((Number)value);
        return;
      case VISPRSNNEXTSERVAMT:
        setVisPrsnNextServAmt((Number)value);
        return;
      case VISPRSNEXISTSERVAMT:
        setVisPrsnExistServAmt((Number)value);
        return;
      case VISPRSNTOTALAMT:
        setVisPrsnTotalAmt((Number)value);
        return;
      case DATALASTUPDATEFUNCTYPE:
        setDataLastUpdateFuncType((String)value);
        return;
      case CREATEDBY:
        setCreatedBy((Number)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case LASTUPDATEDBY:
        setLastUpdatedBy((Number)value);
        return;
      case LASTUPDATEDATE:
        setLastUpdateDate((Date)value);
        return;
      case LASTUPDATELOGIN:
        setLastUpdateLogin((Number)value);
        return;
      case REQUESTID:
        setRequestId((Number)value);
        return;
      case PROGRAMAPPLICATIONID:
        setProgramApplicationId((Number)value);
        return;
      case PROGRAMID:
        setProgramId((Number)value);
        return;
      case PROGRAMUPDATEDATE:
        setProgramUpdateDate((Date)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number slsPrsnMnthlyPlnId)
  {
    return new Key(new Object[] {slsPrsnMnthlyPlnId});
  }
}