ALTER TABLE XXPO.XXPO_RCV_AND_RTN_TXNS ADD (
    JOURNAL_KEY   NUMBER(15),
    INVOICE_NUM   VARCHAR2(50 byte)
);
COMMENT ON COLUMN XXPO.XXPO_RCV_AND_RTN_TXNS.JOURNAL_KEY                             IS 'édñÛÉLÅ['
/
COMMENT ON COLUMN XXPO.XXPO_RCV_AND_RTN_TXNS.INVOICE_NUM                             IS 'êøãÅèëî‘çÜ'
/
