-- AR部門入力明細一時テーブル項目追加スクリプト
ALTER TABLE XX03.XX03_RECEIVABLE_SLIPS_LINE_IF ADD (
    ATTRIBUTE_CATEGORY             VARCHAR2(150),
    ATTRIBUTE1                     VARCHAR2(150),
    ATTRIBUTE2                     VARCHAR2(150),
    ATTRIBUTE3                     VARCHAR2(150),
    ATTRIBUTE4                     VARCHAR2(150),
    ATTRIBUTE5                     VARCHAR2(150),
    ATTRIBUTE6                     VARCHAR2(150),
    ATTRIBUTE7                     VARCHAR2(150),
    ATTRIBUTE8                     VARCHAR2(150),
    ATTRIBUTE9                     VARCHAR2(150),
    ATTRIBUTE10                    VARCHAR2(150),
    ATTRIBUTE11                    VARCHAR2(150),
    ATTRIBUTE12                    VARCHAR2(150),
    ATTRIBUTE13                    VARCHAR2(150),
    ATTRIBUTE14                    VARCHAR2(150),
    ATTRIBUTE15                    VARCHAR2(150)
)
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE_CATEGORY IS 'ATTRIBUTE_CATEGORY'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE1 IS 'ATTRIBUTE1'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE2 IS 'ATTRIBUTE2'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE3 IS 'ATTRIBUTE3'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE4 IS 'ATTRIBUTE4'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE5 IS 'ATTRIBUTE5'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE6 IS 'ATTRIBUTE6'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE7 IS 'ATTRIBUTE7'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE8 IS 'ATTRIBUTE8'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE9 IS 'ATTRIBUTE9'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE10 IS 'ATTRIBUTE10'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE11 IS 'ATTRIBUTE11'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE12 IS 'ATTRIBUTE12'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE13 IS 'ATTRIBUTE13'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE14 IS 'ATTRIBUTE14'
/
COMMENT ON COLUMN XX03.XX03_RECEIVABLE_SLIPS_LINE_IF.ATTRIBUTE15 IS 'ATTRIBUTE15'
/