ALTER TABLE XXCFR.XXCFR_PAYMENT_NOTES ADD (
   BMS_HEADER_DATA VARCHAR2(2000)
  ,BMS_LINE_DATA   VARCHAR2(1500)
);
--
COMMENT ON COLUMN XXCFR.XXCFR_PAYMENT_NOTES.BMS_HEADER_DATA  IS  '流通ＢＭＳヘッダデータ';
COMMENT ON COLUMN XXCFR.XXCFR_PAYMENT_NOTES.BMS_LINE_DATA    IS  '流通ＢＭＳ明細データ';
