ALTER TABLE XXCSO.XXCSO_DESTINATIONS
ADD(
  INVOICE_T_FLAG             VARCHAR2(1),
  INVOICE_T_NO               VARCHAR2(13),
  INVOICE_TAX_DIV_BM         VARCHAR2(1)
)
/
COMMENT ON COLUMN XXCSO.XXCSO_DESTINATIONS.INVOICE_T_FLAG            IS 'ìKäiêøãÅèëî≠çséñã∆é“ìoò^'
/
COMMENT ON COLUMN XXCSO.XXCSO_DESTINATIONS.INVOICE_T_NO              IS 'â€ê≈éñã∆é“î‘çÜ'
/
COMMENT ON COLUMN XXCSO.XXCSO_DESTINATIONS.INVOICE_TAX_DIV_BM        IS 'ê≈åvéZãÊï™'
/
