ALTER TABLE XXCSO.XXCSO_REP_MEMORANDUM
ADD(
  COMPANY_CODE             VARCHAR2(30),
  COMPANY_NAME             VARCHAR2(44)
)
/
COMMENT ON COLUMN XXCSO.XXCSO_REP_MEMORANDUM.COMPANY_CODE               IS 'âÔé–ÉRÅ[Éh'
/
COMMENT ON COLUMN XXCSO.XXCSO_REP_MEMORANDUM.COMPANY_NAME               IS 'âÔé–ñºèÃ'
/

