ALTER TABLE XXCSO.XXCSO_SP_DECISION_HEADERS
ADD(
  INSTALL_PAY_START_DATE        DATE         -- 支払期間開始日（設置協賛金）
, INSTALL_PAY_END_DATE          DATE         -- 支払期間終了日（設置協賛金）
, AD_ASSETS_PAYMENT_TYPE        VARCHAR2(1)  -- 支払条件（行政財産使用料）
, AD_ASSETS_PAY_START_DATE      DATE         -- 支払期間開始日（行政財産使用料）
, AD_ASSETS_PAY_END_DATE        DATE         -- 支払期間終了日（行政財産使用料）
)
/
COMMENT ON COLUMN XXCSO.XXCSO_SP_DECISION_HEADERS.INSTALL_PAY_START_DATE       IS '支払期間開始日（設置協賛金）'
/
COMMENT ON COLUMN XXCSO.XXCSO_SP_DECISION_HEADERS.INSTALL_PAY_END_DATE         IS '支払期間終了日（設置協賛金）'
/
COMMENT ON COLUMN XXCSO.XXCSO_SP_DECISION_HEADERS.AD_ASSETS_PAYMENT_TYPE       IS '支払条件（行政財産使用料）'
/
COMMENT ON COLUMN XXCSO.XXCSO_SP_DECISION_HEADERS.AD_ASSETS_PAY_START_DATE     IS '支払期間開始日（行政財産使用料）'
/
COMMENT ON COLUMN XXCSO.XXCSO_SP_DECISION_HEADERS.AD_ASSETS_PAY_END_DATE       IS '支払期間終了日（行政財産使用料）'
/