ALTER TABLE XXCSO.XXCSO_REP_AUTO_SALE_CONT
ADD(
  BM1_INVOICE_T_NO         VARCHAR2(14),
  INVOICE_T_NO             VARCHAR2(14)
)
/
COMMENT ON COLUMN XXCSO.XXCSO_REP_AUTO_SALE_CONT.BM1_INVOICE_T_NO               IS '登録番号（送付先）'
/
COMMENT ON COLUMN XXCSO.XXCSO_REP_AUTO_SALE_CONT.INVOICE_T_NO                   IS '登録番号（発行元）'
/

