ALTER TABLE XXCSO.XXCSO_DESTINATIONS
ADD(
  SITE_EMAIL_ADDRESS             VARCHAR2(150)   -- 仕入先サイトEメールアドレス
)
/
COMMENT ON COLUMN XXCSO.XXCSO_DESTINATIONS.SITE_EMAIL_ADDRESS        IS '仕入先サイトEメールアドレス'
/