/*
テーブルリリース用スクリプト

XXCCD_PEOPLE_EXPENSE_ACCOUNTSの下記項目を変更するためのALTER文スクリプト(ステップ2)

・UPDATE_IDの型をVARCHAR2(22)に変更

●使い方
①このファイルを指定して実行
②7．の件数が一致していればCOMMITを行う
*/

prompt 5．ALTER文実行
prompt 5-1．UPDATE_IDの型変更
ALTER TABLE XXCCD_PEOPLE_EXPENSE_ACCOUNTS MODIFY (UPDATE_ID VARCHAR2 (22));

prompt 6．退避用ワークテーブルからXXCCD_PEOPLE_EXPENSE_ACCOUNTSにデータを戻す
  INSERT INTO XXCCD_PEOPLE_EXPENSE_ACCOUNTS
    SELECT * FROM
      XXCCD_PEOPLE_EXPENSE_ACCOUNTS_wk;

prompt 7．XXCCD_PEOPLE_EXPENSE_ACCOUNTSと退避用ワークテーブルの件数確認
prompt 7-1．XXCCD_PEOPLE_EXPENSE_ACCOUNTS_wk
select count(*) FROM XXCCD_PEOPLE_EXPENSE_ACCOUNTS_wk;

prompt 7-2．XXCCD_PEOPLE_EXPENSE_ACCOUNTS
select count(*) FROM XXCCD_PEOPLE_EXPENSE_ACCOUNTS;
