/*
テーブルリリース用スクリプト

XXCCD_PEOPLE_EXPENSE_ACCOUNTSの下記項目を変更するためのALTER文スクリプト(ステップ1)

・UPDATE_IDの型をVARCHAR2(22)に変更

●使い方
①このファイルを指定して実行
②2．の最大サイズがVARCHAR(22)を超えていない、かつ3．の件数が一致していればCOMMITを行う
*/

prompt 1．XXCCD_PEOPLE_EXPENSE_ACCOUNTSのデータをコピーした、退避用ワークテーブルを作成
CREATE TABLE XXCCD_PEOPLE_EXPENSE_ACCOUNTS_wk AS SELECT * FROM XXCCD_PEOPLE_EXPENSE_ACCOUNTS;

prompt 2．インスタンスID格納項目の最大サイズ確認
prompt 件数：XXCCD_PEOPLE_EXPENSE_ACCOUNTS_wk
select MAX(LENGTH(UPDATE_ID)) FROM XXCCD_PEOPLE_EXPENSE_ACCOUNTS;

prompt 3．XXCCD_PEOPLE_EXPENSE_ACCOUNTSと退避用ワークテーブルの件数確認
prompt 3-1．XXCCD_PEOPLE_EXPENSE_ACCOUNTS_wk
select count(*) FROM XXCCD_PEOPLE_EXPENSE_ACCOUNTS_wk;

prompt 3-2．XXCCD_PEOPLE_EXPENSE_ACCOUNTS
select count(*) FROM XXCCD_PEOPLE_EXPENSE_ACCOUNTS;

prompt 4．XXCCD_PEOPLE_EXPENSE_ACCOUNTSのデータを削除
DELETE FROM XXCCD_PEOPLE_EXPENSE_ACCOUNTS;

prompt 2．の最大サイズがVARCHAR(22)を超えていない、かつ3．の件数が一致していればCOMMITを行う
