/*
テーブルリリース用スクリプト

XXCCD_JOB_REQUESTSの下記項目を変更するためのALTER文スクリプト(ステップ1)

・INSTANCE_IDの型をVARCHAR2(22)に変更
・ERROR_DETAILの桁数を4000に拡張
・CREATED_BYの桁数を113に拡張
・LAST_UPDATED_BYの桁数を113に拡張

●使い方
①このファイルを指定して実行
②7．の件数が一致していればCOMMITを行う
*/

prompt 5．ALTER文実行
prompt 5-1．INSTANCE_IDの型変更
ALTER TABLE XXCCD_JOB_REQUESTS MODIFY (INSTANCE_ID VARCHAR2 (22));

prompt 5-2．ERROR_DETAILの桁数拡張
ALTER TABLE XXCCD_JOB_REQUESTS MODIFY (ERROR_DETAIL VARCHAR2 (4000));

prompt 5-3．CREATED_BYの桁数拡張
ALTER TABLE XXCCD_JOB_REQUESTS MODIFY (CREATED_BY VARCHAR2 (113));

prompt 5-4．LAST_UPDATED_BYの桁数拡張
ALTER TABLE XXCCD_JOB_REQUESTS MODIFY (LAST_UPDATED_BY VARCHAR2 (113));

prompt 6．退避用ワークテーブルからXXCCD_JOB_REQUESTSにデータを戻す
  INSERT INTO XXCCD_JOB_REQUESTS
    SELECT * FROM
      XXCCD_JOB_REQUESTS_wk;

prompt 7．XXCCD_JOB_REQUESTSと退避用ワークテーブルの件数確認
prompt 7-1．XXCCD_JOB_REQUESTS_wk
select count(*) FROM XXCCD_JOB_REQUESTS_wk;

prompt 7-2．XXCCD_JOB_REQUESTS
select count(*) FROM XXCCD_JOB_REQUESTS;

prompt 7．の件数が一致していればCOMMITを行う
