ALTER TABLE XXCMM.XXCMM_WK_CUST_UPLOAD  ADD (
   TDB_CODE                 VARCHAR2(20)    -- TDBコード
  ,BASE_CODE                VARCHAR2(10)    -- 本部担当拠点
  ,CREDIT_LIMIT             VARCHAR2(10)    -- 与信限度額
  ,DECIDE_DIV               VARCHAR2(10)    -- 判定区分
  ,APPROVAL_DATE            VARCHAR2(30)    -- 決裁日付
  ,TAX_DIV                  VARCHAR2(10)    -- 消費税区分
  ,TAX_ROUNDING_RULE        VARCHAR2(40)    -- 税金端数処理
  ,INVOICE_GRP_CODE         VARCHAR2(160)   -- 売掛コード1（請求書）
  ,OUTPUT_FORM              VARCHAR2(160)   -- 請求書出力形式
  ,PRT_CYCLE                VARCHAR2(160)   -- 請求書発行サイクル
  ,PAYMENT_TERM             VARCHAR2(20)    -- 支払条件
  ,DELIVERY_BASE_CODE       VARCHAR2(10)    -- 納品拠点
  ,BILL_BASE_CODE           VARCHAR2(10)    -- 請求拠点
  ,RECEIV_BASE_CODE         VARCHAR2(10)    -- 入金拠点
  ,SALES_HEAD_BASE_CODE     VARCHAR2(10)    -- 販売先本部担当拠点
);
--
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.TDB_CODE              IS  'TDBコード';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.BASE_CODE             IS  '本部担当拠点';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.CREDIT_LIMIT          IS  '与信限度額';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.DECIDE_DIV            IS  '判定区分';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.APPROVAL_DATE         IS  '決裁日付';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.TAX_DIV               IS  '消費税区分';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.TAX_ROUNDING_RULE     IS  '税金端数処理';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.INVOICE_GRP_CODE      IS  '売掛コード1（請求書）';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.OUTPUT_FORM           IS  '請求書出力形式';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.PRT_CYCLE             IS  '請求書発行サイクル';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.PAYMENT_TERM          IS  '支払条件';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.DELIVERY_BASE_CODE    IS  '納品拠点';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.BILL_BASE_CODE        IS  '請求拠点';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.RECEIV_BASE_CODE      IS  '入金拠点';
COMMENT ON COLUMN XXCMM.XXCMM_WK_CUST_UPLOAD.SALES_HEAD_BASE_CODE  IS  '販売先本部担当拠点';
