/*
テーブルリリース用スクリプト

XXCCD_EMPLOYEE_DIFFERENCE_INFOの下記項目を変更するためのALTER文スクリプト(ステップ1)

・INSTANCE_IDの型をVARCHAR2(22)に変更

●使い方
①このファイルを指定して実行
②2．の最大サイズがVARCHAR(22)を超えていない、かつ3．の件数が一致していればCOMMITを行う
*/

prompt 1．XXCCD_EMPLOYEE_DIFFERENCE_INFOのデータをコピーした、退避用ワークテーブルを作成
CREATE TABLE XXCCD_EMPLOYEE_DIFFERENCE_INFO_wk AS SELECT * FROM XXCCD_EMPLOYEE_DIFFERENCE_INFO;

prompt 2．インスタンスID格納項目の最大サイズ確認
prompt 件数：XXCCD_EMPLOYEE_DIFFERENCE_INFO_wk
select MAX(LENGTH(INSTANCE_ID)) FROM XXCCD_EMPLOYEE_DIFFERENCE_INFO_wk;

prompt 3．XXCCD_EMPLOYEE_DIFFERENCE_INFOと退避用ワークテーブルの件数確認
prompt 3-1．XXCCD_EMPLOYEE_DIFFERENCE_INFO_wk
select count(*) FROM XXCCD_EMPLOYEE_DIFFERENCE_INFO_wk;

prompt 3-2．XXCCD_EMPLOYEE_DIFFERENCE_INFO
select count(*) FROM XXCCD_EMPLOYEE_DIFFERENCE_INFO;

prompt 4．XXCCD_EMPLOYEE_DIFFERENCE_INFOのデータを削除
DELETE FROM XXCCD_EMPLOYEE_DIFFERENCE_INFO;

prompt 2．の最大サイズがVARCHAR(22)を超えていない、かつ3．の件数が一致していればCOMMITを行う
