/*****************************************************************************************
 *
 * Copyright(c)Oracle Corporation Japan, 2005. All rights reserved.
 * Object Name : XX03_VENDORS_LOV_V
 *  9999/99/99  1.0          X.XXXXX      新規作成
 *  2005/09/22  11.5.10.1.5  S.Morisawa   パフォーマンス改善対応
 *  2006/10/03  11.5.10.2.6  S.Morisawa   マスタチェックの見直し(有効日のチェックを請求書日付で
 *                                        行なう項目とSYSDATEで行なう項目を再確認)
 *  2023/10/23  11.5.10.2.7  Y.Ooyama     E_本稼動_19496対応
*****************************************************************************************/
CREATE OR REPLACE VIEW APPS.XX03_VENDORS_LOV_V
 (VENDOR_ID ,LAST_UPDATE_DATE ,LAST_UPDATED_BY ,VENDOR_NAME ,VENDOR_NAME_ALT ,SEGMENT1 ,VENDORS_COL
 ,SUMMARY_FLAG ,ENABLED_FLAG ,SEGMENT2 ,SEGMENT3 ,SEGMENT4 ,SEGMENT5 ,LAST_UPDATE_LOGIN ,CREATION_DATE
 ,CREATED_BY ,EMPLOYEE_ID ,VENDOR_TYPE_LOOKUP_CODE ,CUSTOMER_NUM ,ONE_TIME_FLAG ,PARENT_VENDOR_ID
 ,ATTRIBUTE_CATEGORY ,ATTRIBUTE1 ,ATTRIBUTE2 ,ATTRIBUTE3 ,ATTRIBUTE4 ,ATTRIBUTE5 ,ATTRIBUTE6
 ,ATTRIBUTE7 ,ATTRIBUTE8 ,ATTRIBUTE9 ,ATTRIBUTE10 ,ATTRIBUTE11 ,ATTRIBUTE12 ,ATTRIBUTE13 ,ATTRIBUTE14
 ,ATTRIBUTE15 ,VENDOR_SITE_ID ,VENDOR_SITE_CODE ,BANK_ACCOUNT_NAME ,BANK_FULL_NAME ,INVOICE_CURRENCY_CODE
 ,TERM_ID ,TERM_NAME ,PAY_GROUP_CODE ,PAY_GROUP_MEANING ,AUTO_TAX_CALC_FLAG ,AP_TAX_ROUNDING_RULE
-- Ver11.5.10.2.7 ADD START
 ,DRAFTING_COMPANY
-- Ver11.5.10.2.7 ADD END
 )
AS
SELECT XVV.VENDOR_ID
     , XVV.LAST_UPDATE_DATE
     , XVV.LAST_UPDATED_BY
     , XVV.VENDOR_NAME
     , XVV.VENDOR_NAME_ALT
     , XVV.SEGMENT1
     , XVV.SEGMENT1 || XX00_PROFILE_PKG.VALUE('XX03_TEXT_DELIMITER')
                    || XVV.VENDOR_NAME AS VENDORS_COL
     , XVV.SUMMARY_FLAG
     , XVV.ENABLED_FLAG
     , XVV.SEGMENT2
     , XVV.SEGMENT3
     , XVV.SEGMENT4
     , XVV.SEGMENT5
     , XVV.LAST_UPDATE_LOGIN
     , XVV.CREATION_DATE
     , XVV.CREATED_BY
     , XVV.EMPLOYEE_ID
     , XVV.VENDOR_TYPE_LOOKUP_CODE
     , XVV.CUSTOMER_NUM
     , XVV.ONE_TIME_FLAG
     , XVV.PARENT_VENDOR_ID
     , XVV.ATTRIBUTE_CATEGORY
     , XVV.ATTRIBUTE1
     , XVV.ATTRIBUTE2
     , XVV.ATTRIBUTE3
     , XVV.ATTRIBUTE4
     , XVV.ATTRIBUTE5
     , XVV.ATTRIBUTE6
     , XVV.ATTRIBUTE7
     , XVV.ATTRIBUTE8
     , XVV.ATTRIBUTE9
     , XVV.ATTRIBUTE10
     , XVV.ATTRIBUTE11
     , XVV.ATTRIBUTE12
     , XVV.ATTRIBUTE13
     , XVV.ATTRIBUTE14
     , XVV.ATTRIBUTE15
     , XVSLV.VENDOR_SITE_ID
     , XVSLV.VENDOR_SITE_CODE
     , XVSLV.BANK_ACCOUNT_NAME
     , NVL2(XVSLV.BANK_NAME ,XVSLV.BANK_NAME || ' ' || XVSLV.BANK_BRANCH_NAME
                                             || ' ' || DECODE(XVSLV.BANK_ACCOUNT_TYPE ,'1' ,'普通' ,'2' ,'当座' ,'')
                                             || ' ' || XVSLV.BANK_ACCOUNT_NUM
                            ,null) AS BANK_FULL_NAME
     , XVSLV.INVOICE_CURRENCY_CODE
     , XVSLV.TERM_ID
     , XVSLV.TERM_NAME
     , XVSLV.PAY_GROUP_CODE
     , XVSLV.PAY_GROUP_MEANING
     , XVSLV.AUTO_TAX_CALC_FLAG
     , XVSLV.AP_TAX_ROUNDING_RULE
-- Ver11.5.10.2.7 ADD START
     , XVSLV.DRAFTING_COMPANY
-- Ver11.5.10.2.7 ADD END
FROM   XX03_VENDORS_V      XVV
     , table(XX03_SITE_INFO_PKG.site_info(XVV.vendor_id))  XVSLV
WHERE  XVV.VENDOR_ID                 = XVSLV.VENDOR_ID (+)
  AND  NVL(XVV.END_DATE_ACTIVE, TO_DATE('4712/12/31', 'YYYY/MM/DD')) > TRUNC(SYSDATE)
/

