PROMPT XXCMN_LOOKUP_VALUES2_V.vw >>>
@XXCMN_LOOKUP_VALUES2_V.vw;
PROMPT XXCMN_LOOKUP_VALUES_V.vw >>>
@XXCMN_LOOKUP_VALUES_V.vw;
PROMPT XXCMN_CARRIERS2_V.vw >>>
@XXCMN_CARRIERS2_V.vw;
PROMPT XXCMN_CARRIERS_V.vw >>>
@XXCMN_CARRIERS_V.vw;
PROMPT XXCMN_CATEGORIES2_V.vw >>>
@XXCMN_CATEGORIES2_V.vw;
PROMPT XXCMN_CATEGORIES_V.vw >>>
@XXCMN_CATEGORIES_V.vw;
PROMPT XXCMN_CUST_ACCOUNTS2_V.vw >>>
@XXCMN_CUST_ACCOUNTS2_V.vw;
PROMPT XXCMN_CUST_ACCOUNTS_V.vw >>>
@XXCMN_CUST_ACCOUNTS_V.vw;
PROMPT XXCMN_CUST_ACCT_SITES2_V.vw >>>
@XXCMN_CUST_ACCT_SITES2_V.vw;
PROMPT XXCMN_CUST_ACCT_SITES_V.vw >>>
@XXCMN_CUST_ACCT_SITES_V.vw;
PROMPT XXCMN_DELIVERY_LT2_V.vw >>>
@XXCMN_DELIVERY_LT2_V.vw;
PROMPT XXCMN_DELIVERY_LT_V.vw >>>
@XXCMN_DELIVERY_LT_V.vw;
PROMPT XXCMN_ITEM_MST2_V.vw >>>
@XXCMN_ITEM_MST2_V.vw;
PROMPT XXCMN_ITEM_MST_V.vw >>>
@XXCMN_ITEM_MST_V.vw;
PROMPT XXCMN_ITEM_CATEGORIES_V.vw >>>
@XXCMN_ITEM_CATEGORIES_V.vw;
PROMPT XXCMN_ITEM_CATEGORIES2_V.vw >>>
@XXCMN_ITEM_CATEGORIES2_V.vw;
PROMPT XXCMN_ITEM_CATEGORIES3_V.vw >>>
@XXCMN_ITEM_CATEGORIES3_V.vw;
PROMPT XXCMN_ITEM_CATEGORIES4_V.vw >>>
@XXCMN_ITEM_CATEGORIES4_V.vw;
PROMPT XXCMN_ITEM_CATEGORIES5_V.vw >>>
@XXCMN_ITEM_CATEGORIES5_V.vw;
PROMPT XXCMN_ITEM_CATEGORIES6_V.vw >>>
@XXCMN_ITEM_CATEGORIES6_V.vw;
PROMPT XXCMN_ITEM_LOCATIONS2_V.vw >>>
@XXCMN_ITEM_LOCATIONS2_V.vw;
PROMPT XXCMN_ITEM_LOCATIONS_V.vw >>>
@XXCMN_ITEM_LOCATIONS_V.vw;
PROMPT XXCMN_LOCATIONS2_V.vw >>>
@XXCMN_LOCATIONS2_V.vw;
PROMPT XXCMN_LOCATIONS_V.vw >>>
@XXCMN_LOCATIONS_V.vw;
PROMPT XXCMN_LOT_EACH_ITEM_V.vw >>>
@XXCMN_LOT_EACH_ITEM_V.vw;
PROMPT XXCMN_LOT_STATUS_V.vw >>>
@XXCMN_LOT_STATUS_V.vw;
PROMPT XXCMN_PARTIES2_V.vw >>>
@XXCMN_PARTIES2_V.vw;
PROMPT XXCMN_PARTIES_V.vw >>>
@XXCMN_PARTIES_V.vw;
PROMPT XXCMN_PARTY_SITES2_V.vw >>>
@XXCMN_PARTY_SITES2_V.vw;
PROMPT XXCMN_PARTY_SITES_V.vw >>>
@XXCMN_PARTY_SITES_V.vw;
PROMPT XXCMN_VENDORS2_V.vw >>>
@XXCMN_VENDORS2_V.vw;
PROMPT XXCMN_VENDORS_V.vw >>>
@XXCMN_VENDORS_V.vw;
PROMPT XXCMN_VENDOR_SITES2_V.vw >>>
@XXCMN_VENDOR_SITES2_V.vw;
PROMPT XXCMN_VENDOR_SITES_V.vw >>>
@XXCMN_VENDOR_SITES_V.vw;
PROMPT XXCMN_RCV_PAY_MST_ADJI_V.vw >>>
@XXCMN_RCV_PAY_MST_ADJI_V.vw;
PROMPT XXCMN_RCV_PAY_MST_OMSO_V.vw >>>
@XXCMN_RCV_PAY_MST_OMSO_V.vw;
PROMPT XXCMN_RCV_PAY_MST_PORC_PO_V.vw >>>
@XXCMN_RCV_PAY_MST_PORC_PO_V.vw;
PROMPT XXCMN_RCV_PAY_MST_PORC_RMA_V.vw >>>
@XXCMN_RCV_PAY_MST_PORC_RMA_V.vw;
PROMPT XXCMN_RCV_PAY_MST_PROD_V.vw >>>
@XXCMN_RCV_PAY_MST_PROD_V.vw;
PROMPT XXCMN_RCV_PAY_MST_TRNI_V.vw >>>
@XXCMN_RCV_PAY_MST_TRNI_V.vw;
PROMPT XXCMN_RCV_PAY_MST_XFER_V.vw >>>
@XXCMN_RCV_PAY_MST_XFER_V.vw;
PROMPT XXCMN_SOURCING_RULES2_V.vw >>>
@XXCMN_SOURCING_RULES2_V.vw;
PROMPT XXCMN_SOURCING_RULES_V.vw >>>
@XXCMN_SOURCING_RULES_V.vw;
PROMPT XXCMN_STND_UNIT_PRICE_V.vw >>>
@XXCMN_STND_UNIT_PRICE_V.vw;
PROMPT XXCMN_V_LOT_V.vw >>>
@XXCMN_V_LOT_V.vw;
PROMPT XXCMN_V_SET_GEN_V.vw >>>
@XXCMN_V_SET_GEN_V.vw;
PROMPT XXCMN_V_SET_POST_CODE_02_V.vw >>>
@XXCMN_V_SET_POST_CODE_02_V.vw;
PROMPT XXCMN_V_SET_YYYY_V.vw >>>
@XXCMN_V_SET_YYYY_V.vw;
