PROMPT XXCMN_DEL_N01.ind >>>
@XXCMN_DEL_N01.ind;
PROMPT XXCMN_DEL_N02.ind >>>
@XXCMN_DEL_N02.ind;
PROMPT XXCMN_EI_N01.ind >>>
@XXCMN_EI_N01.ind;
PROMPT XXCMN_IMB_N01.ind >>>
@XXCMN_IMB_N01.ind;
PROMPT XXCMN_IMB_N02.ind >>>
@XXCMN_IMB_N02.ind;
PROMPT XXCMN_IMB_N03.ind >>>
@XXCMN_IMB_N03.ind;
PROMPT XXCMN_PAR_N01.ind >>>
@XXCMN_PAR_N01.ind;
PROMPT XXCMN_RPM_N01.ind >>>
@XXCMN_RPM_N01.ind;
PROMPT XXCMN_RPM_N02.ind >>>
@XXCMN_RPM_N02.ind;
PROMPT XXCMN_RPM_N03.ind >>>
@XXCMN_RPM_N03.ind;
PROMPT XXCMN_RPM_N04.ind >>>
@XXCMN_RPM_N04.ind;
PROMPT XXCMN_RPM_N05.ind >>>
@XXCMN_RPM_N05.ind;
PROMPT XXCMN_RPM_N06.ind >>>
@XXCMN_RPM_N06.ind;
PROMPT XXCMN_SIP_N01.ind >>>
@XXCMN_SIP_N01.ind;
PROMPT XXCMN_SR_N01.ind >>>
@XXCMN_SR_N01.ind;
PROMPT XXCMN_SR_N02.ind >>>
@XXCMN_SR_N02.ind;
PROMPT XXCMN_TLC_N01.ind >>>
@XXCMN_TLC_N01.ind;
PROMPT XXCMN_XLA_N01.ind >>>
@XXCMN_XLA_N01.ind;
