PROMPT XXCMN_DELIVERY_LT.tab >>>
@XXCMN_DELIVERY_LT.tab;
PROMPT XXCMN_EMP_IF.tab >>>
@XXCMN_EMP_IF.tab;
PROMPT XXCMN_ITEM_IF.tab >>>
@XXCMN_ITEM_IF.tab;
PROMPT XXCMN_ITEM_MST_B.tab >>>
@XXCMN_ITEM_MST_B.tab;
PROMPT XXCMN_LOCATIONS_ALL.tab >>>
@XXCMN_LOCATIONS_ALL.tab;
PROMPT XXCMN_LOT_COST.tab >>>
@XXCMN_LOT_COST.tab;
PROMPT XXCMN_LOT_TRACE.tab >>>
@XXCMN_LOT_TRACE.tab;
PROMPT XXCMN_OUTBOUND.tab >>>
@XXCMN_OUTBOUND.tab;
PROMPT XXCMN_PARTIES.tab >>>
@XXCMN_PARTIES.tab;
PROMPT XXCMN_PARTY_IF.tab >>>
@XXCMN_PARTY_IF.tab;
PROMPT XXCMN_PARTY_SITES.tab >>>
@XXCMN_PARTY_SITES.tab;
PROMPT XXCMN_RCV_PAY_MST.tab >>>
@XXCMN_RCV_PAY_MST.tab;
PROMPT XXCMN_SHIP_METHODS.tab >>>
@XXCMN_SHIP_METHODS.tab;
PROMPT XXCMN_SITE_IF.tab >>>
@XXCMN_SITE_IF.tab;
PROMPT XXCMN_SOURCING_RULES.tab >>>
@XXCMN_SOURCING_RULES.tab;
PROMPT XXCMN_SR_LINES_IF.tab >>>
@XXCMN_SR_LINES_IF.tab;
PROMPT XXCMN_STANDARD_COST_IF.tab >>>
@XXCMN_STANDARD_COST_IF.tab;
PROMPT XXCMN_TXN_LOT_COST.tab >>>
@XXCMN_TXN_LOT_COST.tab;
PROMPT XXCMN_VENDORS.tab >>>
@XXCMN_VENDORS.tab;
PROMPT XXCMN_VENDOR_SITES_ALL.tab >>>
@XXCMN_VENDOR_SITES_ALL.tab;
