PROMPT XXCMN_DELIVERY_LT.syn >>>
@XXCMN_DELIVERY_LT.syn;
PROMPT XXCMN_DELIVERY_LT_S1.syn >>>
@XXCMN_DELIVERY_LT_S1.syn;
PROMPT XXCMN_DELIVERY_NO_S1.syn >>>
@XXCMN_DELIVERY_NO_S1.syn;
PROMPT XXCMN_DELIV_REQ_NO_S1.syn >>>
@XXCMN_DELIV_REQ_NO_S1.syn;
PROMPT XXCMN_EMP_IF.syn >>>
@XXCMN_EMP_IF.syn;
PROMPT XXCMN_ITEM_IF.syn >>>
@XXCMN_ITEM_IF.syn;
PROMPT XXCMN_ITEM_MST_B.syn >>>
@XXCMN_ITEM_MST_B.syn;
PROMPT XXCMN_LOCATIONS_ALL.syn >>>
@XXCMN_LOCATIONS_ALL.syn;
PROMPT XXCMN_LOT_COST.syn >>>
@XXCMN_LOT_COST.syn;
PROMPT XXCMN_LOT_TRACE.syn >>>
@XXCMN_LOT_TRACE.syn;
PROMPT XXCMN_MOVE_NO_S1.syn >>>
@XXCMN_MOVE_NO_S1.syn;
PROMPT XXCMN_ORDER_NO_S1.syn >>>
@XXCMN_ORDER_NO_S1.syn;
PROMPT XXCMN_OUTBOUND.syn >>>
@XXCMN_OUTBOUND.syn;
PROMPT XXCMN_PARTIES.syn >>>
@XXCMN_PARTIES.syn;
PROMPT XXCMN_PARTY_IF.syn >>>
@XXCMN_PARTY_IF.syn;
PROMPT XXCMN_PARTY_SITES.syn >>>
@XXCMN_PARTY_SITES.syn;
PROMPT XXCMN_RCV_PAY_MST.syn >>>
@XXCMN_RCV_PAY_MST.syn;
PROMPT XXCMN_REQUEST_NO_S1.syn >>>
@XXCMN_REQUEST_NO_S1.syn;
PROMPT XXCMN_RETURN_NO_S1.syn >>>
@XXCMN_RETURN_NO_S1.syn;
PROMPT XXCMN_SHIP_METHODS.syn >>>
@XXCMN_SHIP_METHODS.syn;
PROMPT XXCMN_SHIP_METHODS_S1.syn >>>
@XXCMN_SHIP_METHODS_S1.syn;
PROMPT XXCMN_SITE_IF.syn >>>
@XXCMN_SITE_IF.syn;
PROMPT XXCMN_SLIP_NO_S1.syn >>>
@XXCMN_SLIP_NO_S1.syn;
PROMPT XXCMN_SOURCING_RULES.syn >>>
@XXCMN_SOURCING_RULES.syn;
PROMPT XXCMN_SOURCING_RULES_S1.syn >>>
@XXCMN_SOURCING_RULES_S1.syn;
PROMPT XXCMN_SR_LINES_IF.syn >>>
@XXCMN_SR_LINES_IF.syn;
PROMPT XXCMN_STANDARD_COST_IF.syn >>>
@XXCMN_STANDARD_COST_IF.syn;
PROMPT XXCMN_TXN_LOT_COST.syn >>>
@XXCMN_TXN_LOT_COST.syn;
PROMPT XXCMN_VENDORS.syn >>>
@XXCMN_VENDORS.syn;
PROMPT XXCMN_VENDOR_SITES_ALL.syn >>>
@XXCMN_VENDOR_SITES_ALL.syn;
PROMPT XXCMN_WF_KEY_S1.syn >>>
@XXCMN_WF_KEY_S1.syn;
