PROMPT XXINV_MOV_HDR_S1.sqs >>>
@XXINV_MOV_HDR_S1.sqs;
PROMPT XXINV_MOV_LINE_S1.sqs >>>
@XXINV_MOV_LINE_S1.sqs;
PROMPT XXINV_MOV_LOT_S1.sqs >>>
@XXINV_MOV_LOT_S1.sqs;
PROMPT XXINV_MRP_FILE_UL_S1.sqs >>>
@XXINV_MRP_FILE_UL_S1.sqs;
PROMPT XXINV_MRP_FRCST_IF_S1.sqs >>>
@XXINV_MRP_FRCST_IF_S1.sqs;
PROMPT XXINV_STC_FORMULANO_S1.sqs >>>
@XXINV_STC_FORMULANO_S1.sqs;
PROMPT XXINV_STC_INVT_HHT_S1.sqs >>>
@XXINV_STC_INVT_HHT_S1.sqs;
PROMPT XXINV_STC_INVT_IF_S1.sqs >>>
@XXINV_STC_INVT_IF_S1.sqs;
PROMPT XXINV_STC_INVT_MOST_S1.sqs >>>
@XXINV_STC_INVT_MOST_S1.sqs;
PROMPT XXINV_STC_INVT_RSLT_S1.sqs >>>
@XXINV_STC_INVT_RSLT_S1.sqs;
PROMPT XXINV_STC_LOTNO_S1.sqs >>>
@XXINV_STC_LOTNO_S1.sqs;
