PROMPT XXINV_550C_TMP.syn >>>
@XXINV_550C_TMP.syn;
PROMPT XXINV_MOV_HDR_S1.syn >>>
@XXINV_MOV_HDR_S1.syn;
PROMPT XXINV_MOV_LINE_S1.syn >>>
@XXINV_MOV_LINE_S1.syn;
PROMPT XXINV_MOV_LOT_DETAILS.syn >>>
@XXINV_MOV_LOT_DETAILS.syn;
PROMPT XXINV_MOV_LOT_S1.syn >>>
@XXINV_MOV_LOT_S1.syn;
PROMPT XXINV_MOV_REQ_INSTR_HEADERS.syn >>>
@XXINV_MOV_REQ_INSTR_HEADERS.syn;
PROMPT XXINV_MOV_REQ_INSTR_LINES.syn >>>
@XXINV_MOV_REQ_INSTR_LINES.syn;
PROMPT XXINV_MRP_FILE_UL_INTERFACE.syn >>>
@XXINV_MRP_FILE_UL_INTERFACE.syn;
PROMPT XXINV_MRP_FILE_UL_S1.syn >>>
@XXINV_MRP_FILE_UL_S1.syn;
PROMPT XXINV_MRP_FORECAST_INTERFACE.syn >>>
@XXINV_MRP_FORECAST_INTERFACE.syn;
PROMPT XXINV_MRP_FRCST_IF_S1.syn >>>
@XXINV_MRP_FRCST_IF_S1.syn;
PROMPT XXINV_STC_FORMULANO_S1.syn >>>
@XXINV_STC_FORMULANO_S1.syn;
PROMPT XXINV_STC_INVENTORY_HHT_WORK.syn >>>
@XXINV_STC_INVENTORY_HHT_WORK.syn;
PROMPT XXINV_STC_INVENTORY_INTERFACE.syn >>>
@XXINV_STC_INVENTORY_INTERFACE.syn;
PROMPT XXINV_STC_INVENTORY_MONTH_STCK.syn >>>
@XXINV_STC_INVENTORY_MONTH_STCK.syn;
PROMPT XXINV_STC_INVENTORY_RESULT.syn >>>
@XXINV_STC_INVENTORY_RESULT.syn;
PROMPT XXINV_STC_INVT_HHT_S1.syn >>>
@XXINV_STC_INVT_HHT_S1.syn;
PROMPT XXINV_STC_INVT_IF_S1.syn >>>
@XXINV_STC_INVT_IF_S1.syn;
PROMPT XXINV_STC_INVT_MOST_S1.syn >>>
@XXINV_STC_INVT_MOST_S1.syn;
PROMPT XXINV_STC_INVT_RSLT_S1.syn >>>
@XXINV_STC_INVT_RSLT_S1.syn;
PROMPT XXINV_STC_LOTNO_S1.syn >>>
@XXINV_STC_LOTNO_S1.syn;
