PROMPT XXINV_INFO_SEC_V.vw >>>
@XXINV_INFO_SEC_V.vw;
PROMPT XXINV_MOV_LOV_DELI_NO_V.vw >>>
@XXINV_MOV_LOV_DELI_NO_V.vw;
PROMPT XXINV_MRP_LOV_GENERATION_V.vw >>>
@XXINV_MRP_LOV_GENERATION_V.vw;
PROMPT XXINV_MRP_LOV_YEAR_V.vw >>>
@XXINV_MRP_LOV_YEAR_V.vw;
PROMPT XXINV_RCV_PAY_MST2_V.vw >>>
@XXINV_RCV_PAY_MST2_V.vw;
PROMPT XXINV_RCV_PAY_MST6_V.vw >>>
@XXINV_RCV_PAY_MST6_V.vw;
PROMPT XXINV_RCV_PAY_MST7_V.vw >>>
@XXINV_RCV_PAY_MST7_V.vw;
PROMPT XXINV_RCV_PAY_MST8_V.vw >>>
@XXINV_RCV_PAY_MST8_V.vw;
PROMPT XXINV_RCV_PAY_MST9_V.vw >>>
@XXINV_RCV_PAY_MST9_V.vw;
PROMPT XXINV_STC_ENTRY_NO_V.vw >>>
@XXINV_STC_ENTRY_NO_V.vw;
PROMPT XXINV_STC_LOT_NO_V.vw >>>
@XXINV_STC_LOT_NO_V.vw;
PROMPT XXINV_STC_LOV_INFO_SEC_V.vw >>>
@XXINV_STC_LOV_INFO_SEC_V.vw;
PROMPT XXINV_STC_REASON_CODE2_V.vw >>>
@XXINV_STC_REASON_CODE2_V.vw;
PROMPT XXINV_STC_REASON_CODE_V.vw >>>
@XXINV_STC_REASON_CODE_V.vw;
PROMPT XXINV_STC_TRANS_V.vw >>>
@XXINV_STC_TRANS_V.vw;
PROMPT XXINV_STC_WHSE_MANAGE_POST_V.vw >>>
@XXINV_STC_WHSE_MANAGE_POST_V.vw;
PROMPT XXINV_STC_WH_CODE_V.vw >>>
@XXINV_STC_WH_CODE_V.vw;
