PROMPT XXINV_MLD_N01.ind >>>
@XXINV_MLD_N01.ind;
PROMPT XXINV_MLD_N02.ind >>>
@XXINV_MLD_N02.ind;
PROMPT XXINV_MLD_N03.ind >>>
@XXINV_MLD_N03.ind;
PROMPT XXINV_MRIH_N01.ind >>>
@XXINV_MRIH_N01.ind;
PROMPT XXINV_MRIH_N02.ind >>>
@XXINV_MRIH_N02.ind;
PROMPT XXINV_MRIH_N03.ind >>>
@XXINV_MRIH_N03.ind;
PROMPT XXINV_MRIH_N04.ind >>>
@XXINV_MRIH_N04.ind;
PROMPT XXINV_MRIH_N05.ind >>>
@XXINV_MRIH_N05.ind;
PROMPT XXINV_MRIH_N06.ind >>>
@XXINV_MRIH_N06.ind;
PROMPT XXINV_MRIH_N07.ind >>>
@XXINV_MRIH_N07.ind;
PROMPT XXINV_MRIH_N08.ind >>>
@XXINV_MRIH_N08.ind;
PROMPT XXINV_MRIL_N01.ind >>>
@XXINV_MRIL_N01.ind;
PROMPT XXINV_MRIL_N02.ind >>>
@XXINV_MRIL_N02.ind;
PROMPT XXINV_SII_N01.ind >>>
@XXINV_SII_N01.ind;
PROMPT XXINV_SII_N02.ind >>>
@XXINV_SII_N02.ind;
PROMPT XXINV_SII_N03.ind >>>
@XXINV_SII_N03.ind;
PROMPT XXINV_SII_N04.ind >>>
@XXINV_SII_N04.ind;
PROMPT XXINV_SIMS_N01.ind >>>
@XXINV_SIMS_N01.ind;
PROMPT XXINV_SIR_N01.ind >>>
@XXINV_SIR_N01.ind;
PROMPT XXINV_SIR_N02.ind >>>
@XXINV_SIR_N02.ind;
PROMPT XXINV_SIR_N03.ind >>>
@XXINV_SIR_N03.ind;
PROMPT XXINV_SIR_N04.ind >>>
@XXINV_SIR_N04.ind;