PROMPT XXINV_550C_TMP.tab >>>
@XXINV_550C_TMP.tab;
PROMPT XXINV_MOV_LOT_DETAILS.tab >>>
@XXINV_MOV_LOT_DETAILS.tab;
PROMPT XXINV_MOV_REQ_INSTR_HEADERS.tab >>>
@XXINV_MOV_REQ_INSTR_HEADERS.tab;
PROMPT XXINV_MOV_REQ_INSTR_LINES.tab >>>
@XXINV_MOV_REQ_INSTR_LINES.tab;
PROMPT XXINV_MRP_FILE_UL_INTERFACE.tab >>>
@XXINV_MRP_FILE_UL_INTERFACE.tab;
PROMPT XXINV_MRP_FORECAST_INTERFACE.tab >>>
@XXINV_MRP_FORECAST_INTERFACE.tab;
PROMPT XXINV_STC_INVENTORY_HHT_WORK.tab >>>
@XXINV_STC_INVENTORY_HHT_WORK.tab;
PROMPT XXINV_STC_INVENTORY_INTERFACE.tab >>>
@XXINV_STC_INVENTORY_INTERFACE.tab;
PROMPT XXINV_STC_INVENTORY_MONTH_STCK.tab >>>
@XXINV_STC_INVENTORY_MONTH_STCK.tab;
PROMPT XXINV_STC_INVENTORY_RESULT.tab >>>
@XXINV_STC_INVENTORY_RESULT.tab;
