PROMPT XXINV_MLD_N01.ind >>>
@XXINV_MLD_N01.ind;
PROMPT XXINV_MLD_N02.ind >>>
@XXINV_MLD_N02.ind;
PROMPT XXINV_MLD_N03.ind >>>
@XXINV_MLD_N03.ind;
PROMPT XXINV_MRIH_N01.ind >>>
@XXINV_MRIH_N01.ind;
PROMPT XXINV_MRIH_N02.ind >>>
@XXINV_MRIH_N02.ind;
PROMPT XXINV_MRIH_N03.ind >>>
@XXINV_MRIH_N03.ind;
PROMPT XXINV_MRIH_N04.ind >>>
@XXINV_MRIH_N04.ind;
PROMPT XXINV_MRIL_N01.ind >>>
@XXINV_MRIL_N01.ind;
PROMPT XXINV_MRIL_N02.ind >>>
@XXINV_MRIL_N02.ind;
