PROMPT XXPO_HEADERS_ALL.syn >>>
@XXPO_HEADERS_ALL.syn;
PROMPT XXPO_HEADERS_ALL_S1.syn >>>
@XXPO_HEADERS_ALL_S1.syn;
PROMPT XXPO_LOT_RESERVE_IF.syn >>>
@XXPO_LOT_RESERVE_IF.syn;
PROMPT XXPO_LOT_RESERVE_IF_ID_S1.syn >>>
@XXPO_LOT_RESERVE_IF_ID_S1.syn;
PROMPT XXPO_NAMAHA_PROD_TXNS.syn >>>
@XXPO_NAMAHA_PROD_TXNS.syn;
PROMPT XXPO_NAMAHA_PROD_TXNS_S1.syn >>>
@XXPO_NAMAHA_PROD_TXNS_S1.syn;
PROMPT XXPO_NAMAHA_PROD_TXNS_S2.syn >>>
@XXPO_NAMAHA_PROD_TXNS_S2.syn;
PROMPT XXPO_PRICE_HEADERS.syn >>>
@XXPO_PRICE_HEADERS.syn;
PROMPT XXPO_PRICE_HEADERS_ALL_S1.syn >>>
@XXPO_PRICE_HEADERS_ALL_S1.syn;
PROMPT XXPO_PRICE_LINES.syn >>>
@XXPO_PRICE_LINES.syn;
PROMPT XXPO_PRICE_LINES_S1.syn >>>
@XXPO_PRICE_LINES_S1.syn;
PROMPT XXPO_RCV_AND_RTN_TXNS.syn >>>
@XXPO_RCV_AND_RTN_TXNS.syn;
PROMPT XXPO_RCV_AND_RTN_TXNS_S1.syn >>>
@XXPO_RCV_AND_RTN_TXNS_S1.syn;
PROMPT XXPO_RCV_TXNS_INTERFACE.syn >>>
@XXPO_RCV_TXNS_INTERFACE.syn;
PROMPT XXPO_REQUISITION_HEADERS.syn >>>
@XXPO_REQUISITION_HEADERS.syn;
PROMPT xxpo_requisition_headers_s1.syn >>>
@xxpo_requisition_headers_s1.syn;
PROMPT XXPO_REQUISITION_LINES.syn >>>
@XXPO_REQUISITION_LINES.syn;
PROMPT XXPO_REQUISITION_LINES_S1.syn >>>
@XXPO_REQUISITION_LINES_S1.syn;
PROMPT XXPO_SUPPLY_REQ_HEADERS_IF.syn >>>
@XXPO_SUPPLY_REQ_HEADERS_IF.syn;
PROMPT XXPO_SUPPLY_REQ_HEADERS_IF_S1.syn >>>
@XXPO_SUPPLY_REQ_HEADERS_IF_S1.syn;
PROMPT XXPO_SUPPLY_REQ_LINES_IF.syn >>>
@XXPO_SUPPLY_REQ_LINES_IF.syn;
PROMPT XXPO_SUPPLY_REQ_LINES_IF_S1.syn >>>
@XXPO_SUPPLY_REQ_LINES_IF_S1.syn;
PROMPT XXPO_VENDOR_SPLY_TXNS_IF_ID_S1.syn >>>
@XXPO_VENDOR_SPLY_TXNS_IF_ID_S1.syn;
PROMPT XXPO_VENDOR_SUPPLY_TXNS.syn >>>
@XXPO_VENDOR_SUPPLY_TXNS.syn;
PROMPT XXPO_VENDOR_SUPPLY_TXNS_IF.syn >>>
@XXPO_VENDOR_SUPPLY_TXNS_IF.syn;
PROMPT XXPO_VENDOR_SUPPLY_TXNS_S1.syn >>>
@XXPO_VENDOR_SUPPLY_TXNS_S1.syn;
