PROMPT XXPO_CATEGORIES_V.vw >>>
@XXPO_CATEGORIES_V.vw;
PROMPT XXPO_PER_ALL_PEOPLE_F2_V.vw >>>
@XXPO_PER_ALL_PEOPLE_F2_V.vw;
PROMPT XXPO_PER_ALL_PEOPLE_F_V.vw >>>
@XXPO_PER_ALL_PEOPLE_F_V.vw;
PROMPT XXPO_SECURITY_SUPPLY_V.vw >>>
@XXPO_SECURITY_SUPPLY_V.vw;
