PROMPT XXPO_HEADERS_ALL_S1.sqs >>>
@XXPO_HEADERS_ALL_S1.sqs;
PROMPT XXPO_LOT_RESERVE_IF_ID_S1.sqs >>>
@XXPO_LOT_RESERVE_IF_ID_S1.sqs;
PROMPT XXPO_NAMAHA_PROD_TXNS_S1.sqs >>>
@XXPO_NAMAHA_PROD_TXNS_S1.sqs;
PROMPT XXPO_NAMAHA_PROD_TXNS_S2.sqs >>>
@XXPO_NAMAHA_PROD_TXNS_S2.sqs;
PROMPT XXPO_PRICE_HEADERS_ALL_S1.sqs >>>
@XXPO_PRICE_HEADERS_ALL_S1.sqs;
PROMPT XXPO_PRICE_LINES_S1.sqs >>>
@XXPO_PRICE_LINES_S1.sqs;
PROMPT XXPO_RCV_AND_RTN_TXNS_S1.sqs >>>
@XXPO_RCV_AND_RTN_TXNS_S1.sqs;
PROMPT XXPO_REQUISITION_HEADERS_S1.sqs >>>
@XXPO_REQUISITION_HEADERS_S1.sqs;
PROMPT XXPO_REQUISITION_LINES_S1.sqs >>>
@XXPO_REQUISITION_LINES_S1.sqs;
PROMPT XXPO_SUPPLY_REQ_HEADERS_IF_S1.sqs >>>
@XXPO_SUPPLY_REQ_HEADERS_IF_S1.sqs;
PROMPT XXPO_SUPPLY_REQ_LINES_IF_S1.sqs >>>
@XXPO_SUPPLY_REQ_LINES_IF_S1.sqs;
PROMPT XXPO_VENDOR_SPLY_TXNS_IF_ID_S1.sqs >>>
@XXPO_VENDOR_SPLY_TXNS_IF_ID_S1.sqs;
PROMPT XXPO_VENDOR_SUPPLY_TXNS_S1.sqs >>>
@XXPO_VENDOR_SUPPLY_TXNS_S1.sqs;
