PROMPT XXPO_HEADERS_ALL.tab >>>
@XXPO_HEADERS_ALL.tab;
PROMPT XXPO_LOT_RESERVE_IF.tab >>>
@XXPO_LOT_RESERVE_IF.tab;
PROMPT XXPO_NAMAHA_PROD_TXNS.tab >>>
@XXPO_NAMAHA_PROD_TXNS.tab;
PROMPT XXPO_PRICE_HEADERS.tab >>>
@XXPO_PRICE_HEADERS.tab;
PROMPT XXPO_PRICE_LINES.tab >>>
@XXPO_PRICE_LINES.tab;
PROMPT XXPO_RCV_AND_RTN_TXNS.tab >>>
@XXPO_RCV_AND_RTN_TXNS.tab;
PROMPT XXPO_RCV_TXNS_INTERFACE.tab >>>
@XXPO_RCV_TXNS_INTERFACE.tab;
PROMPT XXPO_REQUISITION_HEADERS.tab >>>
@XXPO_REQUISITION_HEADERS.tab;
PROMPT XXPO_REQUISITION_LINES.tab >>>
@XXPO_REQUISITION_LINES.tab;
PROMPT XXPO_SUPPLY_REQ_HEADERS_IF.tab >>>
@XXPO_SUPPLY_REQ_HEADERS_IF.tab;
PROMPT XXPO_SUPPLY_REQ_LINES_IF.tab >>>
@XXPO_SUPPLY_REQ_LINES_IF.tab;
PROMPT XXPO_VENDOR_SUPPLY_TXNS.tab >>>
@XXPO_VENDOR_SUPPLY_TXNS.tab;
PROMPT XXPO_VENDOR_SUPPLY_TXNS_IF.tab >>>
@XXPO_VENDOR_SUPPLY_TXNS_IF.tab;
