PROMPT XXPO_PH_N01.ind >>>
@XXPO_PH_N01.ind;
PROMPT XXPO_PH_N02.ind >>>
@XXPO_PH_N02.ind;
PROMPT XXPO_PH_N03.ind >>>
@XXPO_PH_N03.ind;
PROMPT XXPO_PL_N01.ind >>>
@XXPO_PL_N01.ind;
PROMPT XXPO_RART_N01.ind >>>
@XXPO_RART_N01.ind;
PROMPT XXPO_RART_N02.ind >>>
@XXPO_RART_N02.ind;
PROMPT XXPO_RART_N03.ind >>>
@XXPO_RART_N03.ind;
PROMPT XXPO_RART_N04.ind >>>
@XXPO_RART_N04.ind;
PROMPT XXPO_RART_N05.ind >>>
@XXPO_RART_N05.ind;
PROMPT XXPO_RART_N06.ind >>>
@XXPO_RART_N06.ind;
