PROMPT XXWIP_ADJ_CHARGES.tab >>>
@XXWIP_ADJ_CHARGES.tab;
PROMPT XXWIP_BILLING_MST.tab >>>
@XXWIP_BILLING_MST.tab;
PROMPT XXWIP_DELIVERYS.tab >>>
@XXWIP_DELIVERYS.tab;
PROMPT XXWIP_DELIVERYS_CTRL.tab >>>
@XXWIP_DELIVERYS_CTRL.tab;
PROMPT XXWIP_DELIVERYS_IF.tab >>>
@XXWIP_DELIVERYS_IF.tab;
PROMPT XXWIP_DELIVERY_CHARGES.tab >>>
@XXWIP_DELIVERY_CHARGES.tab;
PROMPT XXWIP_DELIVERY_CHARGES_IF.tab >>>
@XXWIP_DELIVERY_CHARGES_IF.tab;
PROMPT XXWIP_DELIVERY_COMPANY.tab >>>
@XXWIP_DELIVERY_COMPANY.tab;
PROMPT XXWIP_DELIVERY_DISTANCE.tab >>>
@XXWIP_DELIVERY_DISTANCE.tab;
PROMPT XXWIP_DELIVERY_DISTANCE_IF.tab >>>
@XXWIP_DELIVERY_DISTANCE_IF.tab;
PROMPT XXWIP_DELIVERY_LINES.tab >>>
@XXWIP_DELIVERY_LINES.tab;
PROMPT XXWIP_DRINK_TRANS_DELI_CHRGS.tab >>>
@XXWIP_DRINK_TRANS_DELI_CHRGS.tab;
PROMPT XXWIP_LEAF_TRANS_DELI_CHRGS.tab >>>
@XXWIP_LEAF_TRANS_DELI_CHRGS.tab;
PROMPT XXWIP_MATERIAL_DETAIL.tab >>>
@XXWIP_MATERIAL_DETAIL.tab;
PROMPT XXWIP_QT_INSPECTION.tab >>>
@XXWIP_QT_INSPECTION.tab;
PROMPT XXWIP_TRANSFER_FARE_INF.tab >>>
@XXWIP_TRANSFER_FARE_INF.tab;
PROMPT XXWIP_TRANSFER_FARE_SUM.tab >>>
@XXWIP_TRANSFER_FARE_SUM.tab;
PROMPT XXWIP_TRANSFER_INF.tab >>>
@XXWIP_TRANSFER_INF.tab;
PROMPT XXWIP_VOLUME_ACTUAL_IF.tab >>>
@XXWIP_VOLUME_ACTUAL_IF.tab;
