PROMPT XXWIP_BM_N01.ind >>>
@XXWIP_BM_N01.ind;
PROMPT XXWIP_DCHARGES_N01.ind >>>
@XXWIP_DCHARGES_N01.ind;
PROMPT XXWIP_DCOMPANY_N01.ind >>>
@XXWIP_DCOMPANY_N01.ind;
PROMPT XXWIP_DDISTANCE_N01.ind >>>
@XXWIP_DDISTANCE_N01.ind;
PROMPT XXWIP_DELIVERYS_N01.ind >>>
@XXWIP_DELIVERYS_N01.ind;
PROMPT XXWIP_DLINES_N01.ind >>>
@XXWIP_DLINES_N01.ind;
PROMPT XXWIP_DLINES_N02.ind >>>
@XXWIP_DLINES_N02.ind;
PROMPT XXWIP_MTDTL_N01.ind >>>
@XXWIP_MTDTL_N01.ind;
PROMPT XXWIP_MTDTL_N02.ind >>>
@XXWIP_MTDTL_N02.ind;
