PROMPT XXWIP_ADJ_CHARGES_S1.sqs >>>
@XXWIP_ADJ_CHARGES_S1.sqs;
PROMPT XXWIP_BILLING_MST_ID_S1.sqs >>>
@XXWIP_BILLING_MST_ID_S1.sqs;
PROMPT XXWIP_DELIVERYS_CTRL_ID_S1.sqs >>>
@XXWIP_DELIVERYS_CTRL_ID_S1.sqs;
PROMPT XXWIP_DELIVERYS_ID_S1.sqs >>>
@XXWIP_DELIVERYS_ID_S1.sqs;
PROMPT XXWIP_DELIVERYS_IF_ID_S1.sqs >>>
@XXWIP_DELIVERYS_IF_ID_S1.sqs;
PROMPT XXWIP_DELIVERY_CHARGES_ID_S1.sqs >>>
@XXWIP_DELIVERY_CHARGES_ID_S1.sqs;
PROMPT XXWIP_DELIVERY_CHARG_IF_ID_S1.sqs >>>
@XXWIP_DELIVERY_CHARG_IF_ID_S1.sqs;
PROMPT XXWIP_DELIVERY_COMPANY_ID_S1.sqs >>>
@XXWIP_DELIVERY_COMPANY_ID_S1.sqs;
PROMPT XXWIP_DELIVERY_DISTANCE_ID_S1.sqs >>>
@XXWIP_DELIVERY_DISTANCE_ID_S1.sqs;
PROMPT XXWIP_DELIVERY_LINES_ID_S1.sqs >>>
@XXWIP_DELIVERY_LINES_ID_S1.sqs;
PROMPT XXWIP_DELI_DISTANCE_IF_ID_S1.sqs >>>
@XXWIP_DELI_DISTANCE_IF_ID_S1.sqs;
PROMPT XXWIP_DRINK_TRANS_CHRGS_ID_S1.sqs >>>
@XXWIP_DRINK_TRANS_CHRGS_ID_S1.sqs;
PROMPT XXWIP_LEAF_TRANS_CHRGS_ID_S1.sqs >>>
@XXWIP_LEAF_TRANS_CHRGS_ID_S1.sqs;
PROMPT XXWIP_MTL_DETAIL_ADDON_ID_S1.sqs >>>
@XXWIP_MTL_DETAIL_ADDON_ID_S1.sqs;
PROMPT XXWIP_QT_INSPECT_REQ_NO_S1.sqs >>>
@XXWIP_QT_INSPECT_REQ_NO_S1.sqs;
PROMPT XXWIP_TRANSFER_FARE_INF_ID_S1.sqs >>>
@XXWIP_TRANSFER_FARE_INF_ID_S1.sqs;
PROMPT XXWIP_TRANSFER_FARE_SUM_ID_S1.sqs >>>
@XXWIP_TRANSFER_FARE_SUM_ID_S1.sqs;
PROMPT XXWIP_TRANSFER_INF_ID_S1.sqs >>>
@XXWIP_TRANSFER_INF_ID_S1.sqs;
