PROMPT XXWIP_ADJ_CHARGES.syn >>>
@XXWIP_ADJ_CHARGES.syn;
PROMPT XXWIP_ADJ_CHARGES_S1.syn >>>
@XXWIP_ADJ_CHARGES_S1.syn;
PROMPT XXWIP_BILLING_MST.syn >>>
@XXWIP_BILLING_MST.syn;
PROMPT XXWIP_BILLING_MST_ID_S1.syn >>>
@XXWIP_BILLING_MST_ID_S1.syn;
PROMPT XXWIP_DELIVERYS.syn >>>
@XXWIP_DELIVERYS.syn;
PROMPT XXWIP_DELIVERYS_CTRL.syn >>>
@XXWIP_DELIVERYS_CTRL.syn;
PROMPT XXWIP_DELIVERYS_CTRL_ID_S1.syn >>>
@XXWIP_DELIVERYS_CTRL_ID_S1.syn;
PROMPT XXWIP_DELIVERYS_ID_S1.syn >>>
@XXWIP_DELIVERYS_ID_S1.syn;
PROMPT XXWIP_DELIVERYS_IF.syn >>>
@XXWIP_DELIVERYS_IF.syn;
PROMPT XXWIP_DELIVERYS_IF_ID_S1.syn >>>
@XXWIP_DELIVERYS_IF_ID_S1.syn;
PROMPT XXWIP_DELIVERY_CHARGES.syn >>>
@XXWIP_DELIVERY_CHARGES.syn;
PROMPT XXWIP_DELIVERY_CHARGES_ID_S1.syn >>>
@XXWIP_DELIVERY_CHARGES_ID_S1.syn;
PROMPT XXWIP_DELIVERY_CHARGES_IF.syn >>>
@XXWIP_DELIVERY_CHARGES_IF.syn;
PROMPT XXWIP_DELIVERY_CHARG_IF_ID_S1.syn >>>
@XXWIP_DELIVERY_CHARG_IF_ID_S1.syn;
PROMPT XXWIP_DELIVERY_COMPANY.syn >>>
@XXWIP_DELIVERY_COMPANY.syn;
PROMPT XXWIP_DELIVERY_COMPANY_ID_S1.syn >>>
@XXWIP_DELIVERY_COMPANY_ID_S1.syn;
PROMPT XXWIP_DELIVERY_DISTANCE.syn >>>
@XXWIP_DELIVERY_DISTANCE.syn;
PROMPT XXWIP_DELIVERY_DISTANCE_ID_S1.syn >>>
@XXWIP_DELIVERY_DISTANCE_ID_S1.syn;
PROMPT XXWIP_DELIVERY_DISTANCE_IF.syn >>>
@XXWIP_DELIVERY_DISTANCE_IF.syn;
PROMPT XXWIP_DELIVERY_LINES.syn >>>
@XXWIP_DELIVERY_LINES.syn;
PROMPT XXWIP_DELIVERY_LINES_ID_S1.syn >>>
@XXWIP_DELIVERY_LINES_ID_S1.syn;
PROMPT XXWIP_DELI_DISTANCE_IF_ID_S1.syn >>>
@XXWIP_DELI_DISTANCE_IF_ID_S1.syn;
PROMPT XXWIP_DRINK_TRANS_CHRGS_ID_S1.syn >>>
@XXWIP_DRINK_TRANS_CHRGS_ID_S1.syn;
PROMPT XXWIP_DRINK_TRANS_DELI_CHRGS.syn >>>
@XXWIP_DRINK_TRANS_DELI_CHRGS.syn;
PROMPT XXWIP_LEAF_TRANS_CHRGS_ID_S1.syn >>>
@XXWIP_LEAF_TRANS_CHRGS_ID_S1.syn;
PROMPT XXWIP_LEAF_TRANS_DELI_CHRGS.syn >>>
@XXWIP_LEAF_TRANS_DELI_CHRGS.syn;
PROMPT XXWIP_MATERIAL_DETAIL.syn >>>
@XXWIP_MATERIAL_DETAIL.syn;
PROMPT XXWIP_MTL_DETAIL_ADDON_ID_S1.syn >>>
@XXWIP_MTL_DETAIL_ADDON_ID_S1.syn;
PROMPT XXWIP_QT_INSPECTION.syn >>>
@XXWIP_QT_INSPECTION.syn;
PROMPT XXWIP_QT_INSPECT_REQ_NO_S1.syn >>>
@XXWIP_QT_INSPECT_REQ_NO_S1.syn;
PROMPT XXWIP_TRANSFER_FARE_INF.syn >>>
@XXWIP_TRANSFER_FARE_INF.syn;
PROMPT XXWIP_TRANSFER_FARE_INF_ID_S1.syn >>>
@XXWIP_TRANSFER_FARE_INF_ID_S1.syn;
PROMPT XXWIP_TRANSFER_FARE_SUM.syn >>>
@XXWIP_TRANSFER_FARE_SUM.syn;
PROMPT XXWIP_TRANSFER_FARE_SUM_ID_S1.syn >>>
@XXWIP_TRANSFER_FARE_SUM_ID_S1.syn;
PROMPT XXWIP_TRANSFER_INF.syn >>>
@XXWIP_TRANSFER_INF.syn;
PROMPT XXWIP_TRANSFER_INF_ID_S1.syn >>>
@XXWIP_TRANSFER_INF_ID_S1.syn;
PROMPT XXWIP_VOLUME_ACTUAL_IF.syn >>>
@XXWIP_VOLUME_ACTUAL_IF.syn;
