PROMPT XXWIP_BATCH_ALL_V.vw >>>
@XXWIP_BATCH_ALL_V.vw;
PROMPT XXWIP_BATCH_DETAIL_INVEST_V.vw >>>
@XXWIP_BATCH_DETAIL_INVEST_V.vw;
PROMPT XXWIP_BATCH_DETAIL_REINVEST_V.vw >>>
@XXWIP_BATCH_DETAIL_REINVEST_V.vw;
PROMPT XXWIP_BATCH_HEADER_V.vw >>>
@XXWIP_BATCH_HEADER_V.vw;
PROMPT XXWIP_BATCH_LOT_INVEST_V.vw >>>
@XXWIP_BATCH_LOT_INVEST_V.vw;
PROMPT XXWIP_BATCH_LOT_REINVEST_V.vw >>>
@XXWIP_BATCH_LOT_REINVEST_V.vw;
PROMPT XXWIP_DRINK_TRANS_DELI_CHRG_V.vw >>>
@XXWIP_DRINK_TRANS_DELI_CHRG_V.vw;
PROMPT XXWIP_QT_INSPECTION_V.vw >>>
@XXWIP_QT_INSPECTION_V.vw;
PROMPT XXWIP_V_SET_DELIVERY_CODE_V.vw >>>
@XXWIP_V_SET_DELIVERY_CODE_V.vw;
