PROMPT XXWSH_OH_N01.ind >>>
@XXWSH_OH_N01.ind;
PROMPT XXWSH_OH_N02.ind >>>
@XXWSH_OH_N02.ind;
PROMPT XXWSH_OH_N03.ind >>>
@XXWSH_OH_N03.ind;
PROMPT XXWSH_OL_N01.ind >>>
@XXWSH_OL_N01.ind;
PROMPT XXWSH_OL_N02.ind >>>
@XXWSH_OL_N02.ind;
PROMPT XXWSH_TICO_N01.ind >>>
@XXWSH_TICO_N01.ind;
