PROMPT XXWSH_930C_TMP.syn >>>
@XXWSH_930C_TMP.syn;
PROMPT XXWSH_930D_TMP.syn >>>
@XXWSH_930D_TMP.syn;
PROMPT XXWSH_CAREERS_SCHEDULE_S1.syn >>>
@XXWSH_CAREERS_SCHEDULE_S1.syn;
PROMPT XXWSH_CARRIERS_SCHEDULE.syn >>>
@XXWSH_CARRIERS_SCHEDULE.syn;
PROMPT XXWSH_CARRIERS_SORT_TMP.syn >>>
@XXWSH_CARRIERS_SORT_TMP.syn;
PROMPT XXWSH_CARRIERS_SORT_TMP_S1.syn >>>
@XXWSH_CARRIERS_SORT_TMP_S1.syn;
PROMPT XXWSH_CONFIRM_BLOCK_TMP.syn >>>
@XXWSH_CONFIRM_BLOCK_TMP.syn;
PROMPT XXWSH_FRQ_ITEM_LOCATIONS.syn >>>
@XXWSH_FRQ_ITEM_LOCATIONS.syn;
PROMPT XXWSH_HHT_DELIVERY_INFO.syn >>>
@XXWSH_HHT_DELIVERY_INFO.syn;
PROMPT XXWSH_HHT_DELIVERY_INFO_S1.syn >>>
@XXWSH_HHT_DELIVERY_INFO_S1.syn;
PROMPT XXWSH_HHT_STOCK_DELIV_INFO_TMP.syn >>>
@XXWSH_HHT_STOCK_DELIV_INFO_TMP.syn;
PROMPT XXWSH_INTENSIVE_CARRIERS_TMP.syn >>>
@XXWSH_INTENSIVE_CARRIERS_TMP.syn;
PROMPT XXWSH_INTENSIVE_CARRIER_LN_TMP.syn >>>
@XXWSH_INTENSIVE_CARRIER_LN_TMP.syn;
PROMPT XXWSH_INTENSIVE_NO_S1.syn >>>
@XXWSH_INTENSIVE_NO_S1.syn;
PROMPT XXWSH_MIXED_CARRIERS_TMP.syn >>>
@XXWSH_MIXED_CARRIERS_TMP.syn;
PROMPT XXWSH_MOV_STOCK_REP_TMP.syn >>>
@XXWSH_MOV_STOCK_REP_TMP.syn;
PROMPT XXWSH_NOTIF_DELIVERY_INFO.syn >>>
@XXWSH_NOTIF_DELIVERY_INFO.syn;
PROMPT XXWSH_NOTIF_DELIVERY_INFO_S1.syn >>>
@XXWSH_NOTIF_DELIVERY_INFO_S1.syn;
PROMPT XXWSH_ORDER_HEADERS_ALL.syn >>>
@XXWSH_ORDER_HEADERS_ALL.syn;
PROMPT XXWSH_ORDER_HEADERS_ALL_S1.syn >>>
@XXWSH_ORDER_HEADERS_ALL_S1.syn;
PROMPT XXWSH_ORDER_LINES_ALL.syn >>>
@XXWSH_ORDER_LINES_ALL.syn;
PROMPT XXWSH_ORDER_LINES_ALL_S1.syn >>>
@XXWSH_ORDER_LINES_ALL_S1.syn;
PROMPT XXWSH_RESERVE_INTERFACE.syn >>>
@XXWSH_RESERVE_INTERFACE.syn;
PROMPT XXWSH_SHIPPING_HEADERS_IF.syn >>>
@XXWSH_SHIPPING_HEADERS_IF.syn;
PROMPT XXWSH_SHIPPING_HEADERS_IF_S1.syn >>>
@XXWSH_SHIPPING_HEADERS_IF_S1.syn;
PROMPT XXWSH_SHIPPING_LINES_IF.syn >>>
@XXWSH_SHIPPING_LINES_IF.syn;
PROMPT XXWSH_SHIPPING_LINES_IF_S1.syn >>>
@XXWSH_SHIPPING_LINES_IF_S1.syn;
PROMPT XXWSH_SHIPPING_STOCK_REP_TMP.syn >>>
@XXWSH_SHIPPING_STOCK_REP_TMP.syn;
PROMPT XXWSH_SHIPPNG_ADJ_BUCKET_TMP.syn >>>
@XXWSH_SHIPPNG_ADJ_BUCKET_TMP.syn;
PROMPT XXWSH_SHIPPNG_ADJ_PLAN_ACT_TMP.syn >>>
@XXWSH_SHIPPNG_ADJ_PLAN_ACT_TMP.syn;
PROMPT XXWSH_SHIP_ADJUST_ALL_TMP.syn >>>
@XXWSH_SHIP_ADJUST_ALL_TMP.syn;
PROMPT XXWSH_SHIP_ADJUST_DAYS_TMP.syn >>>
@XXWSH_SHIP_ADJUST_DAYS_TMP.syn;
PROMPT XXWSH_SHIP_ADJUST_TOTAL_TMP.syn >>>
@XXWSH_SHIP_ADJUST_TOTAL_TMP.syn;
PROMPT XXWSH_STOCK_DELIVERY_INFO_TMP.syn >>>
@XXWSH_STOCK_DELIVERY_INFO_TMP.syn;
PROMPT XXWSH_STOCK_DELIVERY_INFO_TMP2.syn >>>
@XXWSH_STOCK_DELIVERY_INFO_TMP2.syn;
PROMPT XXWSH_STOCK_LABEL_INFO_TMP.syn >>>
@XXWSH_STOCK_LABEL_INFO_TMP.syn;
PROMPT XXWSH_TEMP_DELIVERY_NO_S1.syn >>>
@XXWSH_TEMP_DELIVERY_NO_S1.syn;
PROMPT XXWSH_TIGHTENING_CONTROL.syn >>>
@XXWSH_TIGHTENING_CONTROL.syn;
PROMPT XXWSH_TIGHTENING_CONTROL_S1.syn >>>
@XXWSH_TIGHTENING_CONTROL_S1.syn;
