PROMPT XXWSH_CARRIERS_SCHEDULE_LN_V.vw >>>
@XXWSH_CARRIERS_SCHEDULE_LN_V.vw;
PROMPT XXWSH_DELIVERY_NO_ALL_V.vw >>>
@XXWSH_DELIVERY_NO_ALL_V.vw;
PROMPT XXWSH_DELIVERY_NO_SHIP_MOVE_V.vw >>>
@XXWSH_DELIVERY_NO_SHIP_MOVE_V.vw;
PROMPT XXWSH_DELIVER_TO_ALL_V.vw >>>
@XXWSH_DELIVER_TO_ALL_V.vw;
PROMPT XXWSH_DELIVER_TO_SHIP_MOVE_V.vw >>>
@XXWSH_DELIVER_TO_SHIP_MOVE_V.vw;
PROMPT XXWSH_HEAD_BRANCH_OR_VENDOR_V.vw >>>
@XXWSH_HEAD_BRANCH_OR_VENDOR_V.vw;
PROMPT XXWSH_HEAD_BRANCH_RF_DEPT_V.vw >>>
@XXWSH_HEAD_BRANCH_RF_DEPT_V.vw;
PROMPT XXWSH_INVOICE_V.vw >>>
@XXWSH_INVOICE_V.vw;
PROMPT XXWSH_LABEL_V.vw >>>
@XXWSH_LABEL_V.vw;
PROMPT XXWSH_OE_TRANSACTION_TYPES2_V.vw >>>
@XXWSH_OE_TRANSACTION_TYPES2_V.vw;
PROMPT XXWSH_OE_TRANSACTION_TYPES_V.vw >>>
@XXWSH_OE_TRANSACTION_TYPES_V.vw;
PROMPT XXWSH_REQ_NO_MOVE_NO_ALL_V.vw >>>
@XXWSH_REQ_NO_MOVE_NO_ALL_V.vw;
PROMPT XXWSH_REQ_NO_MOVE_NO_SH_MV2_V.vw >>>
@XXWSH_REQ_NO_MOVE_NO_SH_MV2_V.vw;
PROMPT XXWSH_REQ_NO_MOVE_NO_SH_MV_V.vw >>>
@XXWSH_REQ_NO_MOVE_NO_SH_MV_V.vw;
PROMPT XXWSH_RE_TIGHTENING_LIST_V.vw >>>
@XXWSH_RE_TIGHTENING_LIST_V.vw;
PROMPT XXWSH_SHIPMENT_SLIP_V.vw >>>
@XXWSH_SHIPMENT_SLIP_V.vw;
PROMPT XXWSH_SHIPPING_CLASS2_V.vw >>>
@XXWSH_SHIPPING_CLASS2_V.vw;
PROMPT XXWSH_SHIPPING_CLASS_V.vw >>>
@XXWSH_SHIPPING_CLASS_V.vw;
PROMPT XXWSH_SHIP_METHOD2_V.vw >>>
@XXWSH_SHIP_METHOD2_V.vw;
PROMPT XXWSH_SHIP_METHOD_V.vw >>>
@XXWSH_SHIP_METHOD_V.vw;
PROMPT XXWSH_TIGHTENED_LIST_V.vw >>>
@XXWSH_TIGHTENED_LIST_V.vw;
