PROMPT XXWSH_OH_N01.ind >>>
@XXWSH_OH_N01.ind;
PROMPT XXWSH_OH_N02.ind >>>
@XXWSH_OH_N02.ind;
PROMPT XXWSH_OH_N03.ind >>>
@XXWSH_OH_N03.ind;
PROMPT XXWSH_OL_N01.ind >>>
@XXWSH_OL_N01.ind;
PROMPT XXWSH_OL_N02.ind >>>
@XXWSH_OL_N02.ind;
PROMPT XXWSH_TICO_N01.ind >>>
@XXWSH_TICO_N01.ind;
PROMPT XXWSH_CS_N01.ind >>>
@XXWSH_CS_N01.ind;
PROMPT XXWSH_OH_N04.ind >>>
@XXWSH_OH_N04.ind;
PROMPT XXWSH_OH_N05.ind >>>
@XXWSH_OH_N05.ind;
PROMPT XXWSH_OH_N06.ind >>>
@XXWSH_OH_N06.ind;
PROMPT XXWSH_OH_N07.ind >>>
@XXWSH_OH_N07.ind;
PROMPT XXWSH_SH_N01.ind >>>
@XXWSH_SH_N01.ind;
PROMPT XXWSH_SL_N01.ind >>>
@XXWSH_SL_N01.ind;
