PROMPT XXWSH_CAREERS_SCHEDULE_S1.sqs >>>
@XXWSH_CAREERS_SCHEDULE_S1.sqs;
PROMPT XXWSH_CARRIERS_SORT_TMP_S1.sqs >>>
@XXWSH_CARRIERS_SORT_TMP_S1.sqs;
PROMPT XXWSH_FRQ_ITEM_LOCATIONS_ID_S1.sqs >>>
@XXWSH_FRQ_ITEM_LOCATIONS_ID_S1.sqs;
PROMPT XXWSH_HHT_DELIVERY_INFO_S1.sqs >>>
@XXWSH_HHT_DELIVERY_INFO_S1.sqs;
PROMPT XXWSH_INTENSIVE_NO_S1.sqs >>>
@XXWSH_INTENSIVE_NO_S1.sqs;
PROMPT XXWSH_NOTIF_DELIVERY_INFO_S1.sqs >>>
@XXWSH_NOTIF_DELIVERY_INFO_S1.sqs;
PROMPT XXWSH_ORDER_HEADERS_ALL_S1.sqs >>>
@XXWSH_ORDER_HEADERS_ALL_S1.sqs;
PROMPT XXWSH_ORDER_LINES_ALL_S1.sqs >>>
@XXWSH_ORDER_LINES_ALL_S1.sqs;
PROMPT XXWSH_SHIPPING_HEADERS_IF_S1.sqs >>>
@XXWSH_SHIPPING_HEADERS_IF_S1.sqs;
PROMPT XXWSH_SHIPPING_LINES_IF_S1.sqs >>>
@XXWSH_SHIPPING_LINES_IF_S1.sqs;
PROMPT XXWSH_TEMP_DELIVERY_NO_S1.sqs >>>
@XXWSH_TEMP_DELIVERY_NO_S1.sqs;
PROMPT XXWSH_TIGHTENING_CONTROL_S1.sqs >>>
@XXWSH_TIGHTENING_CONTROL_S1.sqs;
