PROMPT XXWSH_930C_TMP.tab >>>
@XXWSH_930C_TMP.tab;
PROMPT XXWSH_930D_TMP.tab >>>
@XXWSH_930D_TMP.tab;
PROMPT XXWSH_CARRIERS_SCHEDULE.tab >>>
@XXWSH_CARRIERS_SCHEDULE.tab;
PROMPT XXWSH_CARRIERS_SORT_TMP.tab >>>
@XXWSH_CARRIERS_SORT_TMP.tab;
PROMPT XXWSH_CONFIRM_BLOCK_TMP.tab >>>
@XXWSH_CONFIRM_BLOCK_TMP.tab;
PROMPT XXWSH_FRQ_ITEM_LOCATIONS.tab >>>
@XXWSH_FRQ_ITEM_LOCATIONS.tab;
PROMPT XXWSH_HHT_DELIVERY_INFO.tab >>>
@XXWSH_HHT_DELIVERY_INFO.tab;
PROMPT XXWSH_HHT_STOCK_DELIV_INFO_TMP.tab >>>
@XXWSH_HHT_STOCK_DELIV_INFO_TMP.tab;
PROMPT XXWSH_INTENSIVE_CARRIERS_TMP.tab >>>
@XXWSH_INTENSIVE_CARRIERS_TMP.tab;
PROMPT XXWSH_INTENSIVE_CARRIER_LN_TMP.tab >>>
@XXWSH_INTENSIVE_CARRIER_LN_TMP.tab;
PROMPT XXWSH_MIXED_CARRIERS_TMP.tab >>>
@XXWSH_MIXED_CARRIERS_TMP.tab;
PROMPT XXWSH_MOV_STOCK_REP_TMP.tab >>>
@XXWSH_MOV_STOCK_REP_TMP.tab;
PROMPT XXWSH_NOTIF_DELIVERY_INFO.tab >>>
@XXWSH_NOTIF_DELIVERY_INFO.tab;
PROMPT XXWSH_ORDER_HEADERS_ALL.tab >>>
@XXWSH_ORDER_HEADERS_ALL.tab;
PROMPT XXWSH_ORDER_LINES_ALL.tab >>>
@XXWSH_ORDER_LINES_ALL.tab;
PROMPT XXWSH_RESERVE_INTERFACE.tab >>>
@XXWSH_RESERVE_INTERFACE.tab;
PROMPT XXWSH_SHIPPING_HEADERS_IF.tab >>>
@XXWSH_SHIPPING_HEADERS_IF.tab;
PROMPT XXWSH_SHIPPING_LINES_IF.tab >>>
@XXWSH_SHIPPING_LINES_IF.tab;
PROMPT XXWSH_SHIPPING_STOCK_REP_TMP.tab >>>
@XXWSH_SHIPPING_STOCK_REP_TMP.tab;
PROMPT XXWSH_SHIPPNG_ADJ_BUCKET_TMP.tab >>>
@XXWSH_SHIPPNG_ADJ_BUCKET_TMP.tab;
PROMPT XXWSH_SHIPPNG_ADJ_PLAN_ACT_TMP.tab >>>
@XXWSH_SHIPPNG_ADJ_PLAN_ACT_TMP.tab;
PROMPT XXWSH_SHIP_ADJUST_ALL_TMP.tab >>>
@XXWSH_SHIP_ADJUST_ALL_TMP.tab;
PROMPT XXWSH_SHIP_ADJUST_DAYS_TMP.tab >>>
@XXWSH_SHIP_ADJUST_DAYS_TMP.tab;
PROMPT XXWSH_SHIP_ADJUST_TOTAL_TMP.tab >>>
@XXWSH_SHIP_ADJUST_TOTAL_TMP.tab;
PROMPT XXWSH_STOCK_DELIVERY_INFO_TMP.tab >>>
@XXWSH_STOCK_DELIVERY_INFO_TMP.tab;
PROMPT XXWSH_STOCK_DELIVERY_INFO_TMP2.tab >>>
@XXWSH_STOCK_DELIVERY_INFO_TMP2.tab;
PROMPT XXWSH_STOCK_LABEL_INFO_TMP.tab >>>
@XXWSH_STOCK_LABEL_INFO_TMP.tab;
PROMPT XXWSH_TIGHTENING_CONTROL.tab >>>
@XXWSH_TIGHTENING_CONTROL.tab;
