ALTER TABLE XXCOP.XXCOP_REP_FORECAST_PLANNING MODIFY(
  SHIP_TO_QUANTITY_15_MONTHS_AGO      NUMBER(15,2),
  SHIP_TO_QUANTITY_14_MONTHS_AGO      NUMBER(15,2),
  SHIP_TO_QUANTITY_13_MONTHS_AGO      NUMBER(13,2),
  SHIP_TO_QUANTITY_12_MONTHS_AGO      NUMBER(13,2),
  SHIP_TO_QUANTITY_11_MONTHS_AGO      NUMBER(13,2),
  SHIP_TO_QUANTITY_3_MONTHS_AGO       NUMBER(13,2),
  SHIP_TO_QUANTITY_2_MONTHS_AGO       NUMBER(13,2),
  SHIP_TO_QUANTITY_1_MONTHS_AGO       NUMBER(13,2),
  SHIP_TO_QUANTITY_FORECAST           NUMBER(13,2),
  FORECAST_QUANTITY_3_MONTHS_AGO      NUMBER(13,2),
  FORECAST_QUANTITY_2_MONTHS_AGO      NUMBER(13,2),
  FORECAST_QUANTITY_1_MONTHS_AGO      NUMBER(13,2),
  FORECAST_QUANTITY                   NUMBER(13,2),
  PRESENT_STOCK_QUANTITY              NUMBER(13,2),
  FORECAST_REMAINDER_QUANTITY         NUMBER(13,2),
  DELIVERY_FORECAST_QUANTITY          NUMBER(13,2),
  STOCK_FORECAST_QUANTITY             NUMBER(13,2)
)
/
