package itoen.oracle.apps.xxpo.lov.server;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ItemCode3VOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ItemCode3VOImpl()
  {
  }

  /**
   * 初期化メソッド。
   * @param itemCode 品目
   */
  public void initQuery(String itemCode)
  {    
    // WHERE句に品目を追加
    setWhereClause(null);
    setWhereClause(" item_code = :0");
    setWhereClauseParam(0, itemCode);

    // 検索実行    
    executeQuery();
  }
}