ALTER TABLE XXCOK.XXCOK_REP_WHOLESALE_PAY
ADD(
  STAMP1                  VARCHAR2(2)   -- ヘッダ用印１
, STAMP1_DESCRIPTION      VARCHAR2(40)  -- ヘッダ用印１摘要
, STAMP2                  VARCHAR2(2)   -- ヘッダ用印２
, STAMP2_DESCRIPTION      VARCHAR2(40)  -- ヘッダ用印２摘要
, STAMP3                  VARCHAR2(2)   -- ヘッダ用印３
, STAMP3_DESCRIPTION      VARCHAR2(40)  -- ヘッダ用印３摘要
, BASE_CODE               VARCHAR2(4)   -- 拠点コード
, BASE_NAME               VARCHAR2(360) -- 拠点名
, NET_SELLING_PRICE_LOW   NUMBER(8,2)   -- NET価格(下段)
, STAMP                   VARCHAR2(2)   -- 印
, ERROR_RATE              VARCHAR2(2)   -- 異常率
)
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.STAMP1                   IS 'ヘッダ用印１'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.STAMP1_DESCRIPTION       IS 'ヘッダ用印１摘要'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.STAMP2                   IS 'ヘッダ用印２'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.STAMP2_DESCRIPTION       IS 'ヘッダ用印２摘要'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.STAMP3                   IS 'ヘッダ用印３'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.STAMP3_DESCRIPTION       IS 'ヘッダ用印３摘要'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.BASE_CODE                IS '拠点コード'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.BASE_NAME                IS '拠点名'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.NET_SELLING_PRICE_LOW    IS 'NET価格下段(下段)'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.STAMP                    IS '印'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.ERROR_RATE               IS '異常率'
/
