ALTER TABLE XXCOK.XXCOK_INFO_WORK_HEADER ADD
(
     DISPLAY_CODE                 VARCHAR2(15)
    ,COMPANY_CODE_BD              VARCHAR2(150)
)
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_WORK_HEADER.DISPLAY_CODE                          IS '表示コード'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_WORK_HEADER.COMPANY_CODE_BD                       IS '会社コード（基準日）'
/
