ALTER TABLE XXCOK.XXCOK_TMP_014A01C_CUSTDATA2
ADD(
  CALC_TARGET_DATE_MIN  DATE
, CALC_TARGET_DATE_MAX  DATE
)
/
COMMENT ON COLUMN XXCOK.XXCOK_TMP_014A01C_CUSTDATA2.CALC_TARGET_DATE_MIN     IS 'åvéZëŒè€ä˙ä‘(MIN)'
/
COMMENT ON COLUMN XXCOK.XXCOK_TMP_014A01C_CUSTDATA2.CALC_TARGET_DATE_MAX     IS 'åvéZëŒè€ä˙ä‘(MAX)'
/