ALTER TABLE XXCOK.XXCOK_INFO_REV_HEADER ADD
(
     BM_PAYMENT_KBN                 VARCHAR2(1)
    ,TAX_CALC_KBN                   VARCHAR2(1)
    ,BM_TAX_KBN                     VARCHAR2(1)
    ,BANK_CHARGE_BEARER             VARCHAR2(1)
    ,SALES_FEE_NO_TAX               NUMBER(13)
    ,SALES_FEE_TAX                  NUMBER(13)
    ,SALES_FEE_WITH_TAX             NUMBER(13)
    ,ELECTRIC_AMT_NO_TAX            NUMBER(13)
    ,ELECTRIC_AMT_TAX               NUMBER(13)
    ,ELECTRIC_AMT_WITH_TAX          NUMBER(13)
    ,RECALC_TOTAL_FEE_NO_TAX        NUMBER(13)
    ,RECALC_TOTAL_FEE_TAX           NUMBER(13)
    ,RECALC_TOTAL_FEE_WITH_TAX      NUMBER(13)
    ,BANK_TRANS_FEE_NO_TAX          NUMBER(13)
    ,BANK_TRANS_FEE_TAX             NUMBER(13)
    ,BANK_TRANS_FEE_WITH_TAX        NUMBER(13)
    ,VENDOR_INVOICE_REGNUM          VARCHAR2(30)
)
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.BM_PAYMENT_KBN                           IS 'BM支払区分'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.TAX_CALC_KBN                             IS '税計算区分'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.BM_TAX_KBN                               IS 'BM税区分'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.BANK_CHARGE_BEARER                       IS '振込手数料負担者'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.SALES_FEE_NO_TAX                         IS '販売手数料（税抜）'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.SALES_FEE_TAX                            IS '販売手数料（消費税）'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.SALES_FEE_WITH_TAX                       IS '販売手数料（税込）'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.ELECTRIC_AMT_NO_TAX                      IS '電気代等（税抜）'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.ELECTRIC_AMT_TAX                         IS '電気代等（消費税）'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.ELECTRIC_AMT_WITH_TAX                    IS '電気代等（税込）'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.RECALC_TOTAL_FEE_NO_TAX                  IS '再計算済手数料計（税抜）'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.RECALC_TOTAL_FEE_TAX                     IS '再計算済手数料計（消費税）'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.RECALC_TOTAL_FEE_WITH_TAX                IS '再計算済手数料計（税込）'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.BANK_TRANS_FEE_NO_TAX                    IS '振込手数料（税抜）'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.BANK_TRANS_FEE_TAX                       IS '振込手数料（消費税）'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.BANK_TRANS_FEE_WITH_TAX                  IS '振込手数料（税込）'
/
COMMENT ON COLUMN XXCOK.XXCOK_INFO_REV_HEADER.VENDOR_INVOICE_REGNUM                    IS '送付先インボイス登録番号'
/
