ALTER TABLE XXCOK.XXCOK_REP_WHOLESALE_PAY
ADD(
  STAMP4                  VARCHAR2(2)   -- ヘッダ用印４
, STAMP4_DESCRIPTION      VARCHAR2(40)  -- ヘッダ用印４摘要
, TAX                     VARCHAR2(2)   -- 税
)
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.STAMP4                   IS 'ヘッダ用印４'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.STAMP4_DESCRIPTION       IS 'ヘッダ用印４摘要'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_WHOLESALE_PAY.TAX                      IS '税'
/
