ALTER TABLE XXCOK.XXCOK_TMP_014A01C_CUSTDATA2 ADD (
   VENDOR_DUMMY_FLAG    VARCHAR2(1)    --仕入先ダミーフラグ
);
COMMENT ON COLUMN XXCOK.XXCOK_TMP_014A01C_CUSTDATA2.VENDOR_DUMMY_FLAG     IS '仕入先ダミーフラグ';
