ALTER TABLE XXCOK.XXCOK_TARGET_CUST_INFO
  DROP CONSTRAINT XXCOK_TARGET_CUST_INFO_PK
;

ALTER TABLE XXCOK.XXCOK_TARGET_CUST_INFO
  ADD CONSTRAINT XXCOK_TARGET_CUST_INFO_PK
  PRIMARY KEY (CUST_CODE, CALC_TARGET_PERIOD_FROM)
;
