ALTER TABLE xxcok.xxcok_rep_bm_balance
ADD (
  P_PAYMENT_CODE           VARCHAR2(9)
 ,P_RESV_PAYMENT           VARCHAR2(8)
 ,H_UNPAID_ELEC_MARK       VARCHAR2(2)
 ,UNPAID_ELEC_MARK         VARCHAR2(2)
 ,ERR_FLAG                 VARCHAR2(1)
 ,RESV_PAYMENT_SORT        NUMBER
)
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_BALANCE.P_PAYMENT_CODE           IS '支払先コード(入力パラメータ)'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_BALANCE.P_RESV_PAYMENT           IS '支払ステータス(入力パラメータ)'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_BALANCE.H_UNPAID_ELEC_MARK       IS '変動電気代未払マーク(ヘッダ出力)'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_BALANCE.UNPAID_ELEC_MARK         IS '変動電気代未払マーク'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_BALANCE.ERR_FLAG                 IS 'エラーフラグ'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_BALANCE.RESV_PAYMENT_SORT        IS '支払ステータス並び順'
/
