ALTER TABLE XXCOK.XXCOK_MST_BM_CONTRACT
ADD(
  BM1_TAX_KBN             VARCHAR2(1)   -- BM1�ŋ敪
, BM2_TAX_KBN             VARCHAR2(1)   -- BM2�ŋ敪
, BM3_TAX_KBN             VARCHAR2(1)   -- BM3�ŋ敪
)
/
COMMENT ON COLUMN XXCOK.XXCOK_MST_BM_CONTRACT.BM1_TAX_KBN        IS 'BM1�ŋ敪'
/
COMMENT ON COLUMN XXCOK.XXCOK_MST_BM_CONTRACT.BM2_TAX_KBN        IS 'BM2�ŋ敪'
/
COMMENT ON COLUMN XXCOK.XXCOK_MST_BM_CONTRACT.BM3_TAX_KBN        IS 'BM3�ŋ敪'
/