ALTER TABLE XXCOK.XXCOK_COND_BM_SUPPORT
ADD(
  SELLING_AMT_NO_TAX      NUMBER(9.0)   -- îÑè„ã‡äz(ê≈î≤)
)
/
COMMENT ON COLUMN XXCOK.XXCOK_COND_BM_SUPPORT.SELLING_AMT_NO_TAX  IS 'îÑè„ã‡äz(ê≈î≤)'
/