ALTER TABLE xxcok.xxcok_rep_bm_pg_detail
ADD (
  BM_INDEX_3             VARCHAR2(20)
 ,BM_AMT_3               NUMBER
 ,ORG_SLIP_NUMBER        VARCHAR2(50)
 ,BANK_CHARGE_BEARER     VARCHAR2(1)
 ,BALANCE_CANCEL_DATE    DATE
)
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_INDEX_3             IS '合計見出し3'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_AMT_3               IS '合計手数料3'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.ORG_SLIP_NUMBER        IS '元伝票番号'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BANK_CHARGE_BEARER     IS '手数料負担者'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BALANCE_CANCEL_DATE    IS '残高取消日'
/
