ALTER TABLE xxcok.xxcok_rep_bm_pg_detail
ADD (
   PAYMENT_T_NO          VARCHAR2(14),
   INVOICE_T_NO          VARCHAR2(14),
   PAYMENT_AMT_SUM       NUMBER,
   SALES_AMT_SUM         NUMBER,
   TOTAL_TITLE_NAME1     VARCHAR2(6),
   TOTAL_TITLE_NAME2     VARCHAR2(6),
   TOTAL_TITLE_NAME3     VARCHAR2(6),
   BM_INDEX_NAME1        VARCHAR2(20),
   BM_INDEX_NAME2        VARCHAR2(20),
   BM_INDEX_NAME3        VARCHAR2(20),
   BM_INDEX_NAME4        VARCHAR2(20),
   TAX_TYPE1             VARCHAR2(20),
   TAX_TYPE2             VARCHAR2(20),
   TAX_TYPE3             VARCHAR2(20),
   TAX_TYPE4             VARCHAR2(20),
   TAX_TYPE5             VARCHAR2(20),
   BM_SUM_AMT1_1         NUMBER,
   BM_SUM_AMT1_2         NUMBER,
   BM_SUM_AMT1_3         NUMBER,
   BM_SUM_AMT1_4         NUMBER,
   BM_SUM_AMT1_SUBTOTAL  NUMBER,
   BM_SUM_AMT2_1         NUMBER,
   BM_SUM_AMT2_2         NUMBER,
   BM_SUM_AMT2_3         NUMBER,
   BM_SUM_AMT2_4         NUMBER,
   BM_SUM_AMT2_SUBTOTAL  NUMBER,
   BM_SUM_AMT3_1         NUMBER,
   BM_SUM_AMT3_2         NUMBER,
   BM_SUM_AMT3_3         NUMBER,
   BM_SUM_AMT3_4         NUMBER,
   BM_SUM_AMT3_SUBTOTAL  NUMBER,
   BM_TITLE1             VARCHAR2(20),
   BM_TITLE2             VARCHAR2(20),
   BM_TITLE3             VARCHAR2(20),
   BM_AMT1               NUMBER,
   BM_AMT2               NUMBER,
   BM_AMT3               NUMBER,
   PAYMENT_TYPE          VARCHAR2(2),
   TAX_TYPE              VARCHAR2(2),
   TAX_CALC_TYPE         VARCHAR2(2)
)
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.PAYMENT_T_NO              IS '登録番号（支払先）'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.INVOICE_T_NO              IS '登録番号（伊藤園）'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.PAYMENT_AMT_SUM           IS 'お支払金額'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.SALES_AMT_SUM             IS '販売金額合計'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.TOTAL_TITLE_NAME1         IS '合計行タイトル1'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.TOTAL_TITLE_NAME2         IS '合計行タイトル2'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.TOTAL_TITLE_NAME3         IS '合計行タイトル3'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_INDEX_NAME1            IS '合計見出し1'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_INDEX_NAME2            IS '合計見出し2'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_INDEX_NAME3            IS '合計見出し3'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_INDEX_NAME4            IS '合計見出し4'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.TAX_TYPE1                 IS '税区分1'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.TAX_TYPE2                 IS '税区分2'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.TAX_TYPE3                 IS '税区分3'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.TAX_TYPE4                 IS '税区分4'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.TAX_TYPE5                 IS '税区分5'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT1_1             IS '合計手数料1_1'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT1_2             IS '合計手数料1_2'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT1_3             IS '合計手数料1_3'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT1_4             IS '合計手数料1_4'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT1_SUBTOTAL      IS '合計手数料1小計'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT2_1             IS '合計手数料2_1'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT2_2             IS '合計手数料2_2'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT2_3             IS '合計手数料2_3'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT2_4             IS '合計手数料2_4'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT2_SUBTOTAL      IS '合計手数料2小計'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT3_1             IS '合計手数料3_1'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT3_2             IS '合計手数料3_2'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT3_3             IS '合計手数料3_3'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT3_4             IS '合計手数料3_4'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_SUM_AMT3_SUBTOTAL      IS '合計手数料3小計'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_TITLE1                 IS '販売手数料見出し1'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_TITLE2                 IS '販売手数料見出し2'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_TITLE3                 IS '販売手数料見出し3'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_AMT1                   IS '販売手数料1'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_AMT2                   IS '販売手数料2'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.BM_AMT3                   IS '販売手数料3'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.PAYMENT_TYPE              IS '支払区分'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.TAX_TYPE                  IS '税区分'
/
COMMENT ON COLUMN XXCOK.XXCOK_REP_BM_PG_DETAIL.TAX_CALC_TYPE             IS '税計算区分'
/
