CREATE OR REPLACE FORCE VIEW "APPS"."XXWIP_V_SET_DELIVERY_CODE_V" (
  "DELIVERY_COMPANY_CODE"
 ,"DELIVERY_COMPANY_NAME"
  ) AS 
  SELECT
    XDC.DELIVERY_COMPANY_CODE
   ,XCV.PARTY_NAME
  FROM   XXWIP_DELIVERY_COMPANY XDC
        ,XXCMN_CARRIERS_V      XCV
  WHERE  XDC.DELIVERY_COMPANY_CODE = XCV.PARTY_NUMBER
  GROUP BY
        XDC.DELIVERY_COMPANY_CODE,XCV.PARTY_NAME
  ORDER BY
        XDC.DELIVERY_COMPANY_CODE
/