ALTER TABLE XXCOS.XXCOS_REP_DELI_REQ  ADD (
   DLV_CONTRACTOR_INFO    VARCHAR2(160)
  ,OUTPUT_CODE            VARCHAR2(01)
);
--
COMMENT ON COLUMN XXCOS.XXCOS_REP_DELI_REQ.DLV_CONTRACTOR_INFO              IS  '‰^‘—¿•‰ŽÒî•ñ';
COMMENT ON COLUMN XXCOS.XXCOS_REP_DELI_REQ.OUTPUT_CODE                      IS  'o—Í‹æ•ª';
