ALTER TABLE XXCOS.XXCOS_SALES_EXP_LINES  ADD (
  TAX_CODE        VARCHAR2(50)  NULL  -- 税金コード
 ,TAX_RATE        NUMBER        NULL  -- 消費税率
);
--
COMMENT ON COLUMN XXCOS.XXCOS_SALES_EXP_LINES.TAX_CODE  IS  '税金コード';
COMMENT ON COLUMN XXCOS.XXCOS_SALES_EXP_LINES.TAX_RATE  IS  '消費税率';
