ALTER TABLE XXCOS.XXCOS_REP_LOT_PICK_CHAIN_PRO ADD
 (CUSTOMER_CODE VARCHAR2(9)
 ,CUSTOMER_NAME VARCHAR2(40));
COMMENT ON COLUMN XXCOS.XXCOS_REP_LOT_PICK_CHAIN_PRO.CUSTOMER_CODE IS 'å⁄ãqÉRÅ[Éh';
COMMENT ON COLUMN XXCOS.XXCOS_REP_LOT_PICK_CHAIN_PRO.CUSTOMER_NAME IS 'å⁄ãqñº';