ALTER TABLE XXCOS.XXCOS_TMP_ORDER_LIST_CUST  ADD (
   CUSTOMER_NAME      VARCHAR2(100)
  ,DELIVERY_BASE_NAME VARCHAR2(100)
  ,TSUKAGATAZAIKO_DIV VARCHAR2(2)
);
--
COMMENT ON COLUMN XXCOS.XXCOS_TMP_ORDER_LIST_CUST.CUSTOMER_NAME      IS 'å⁄ãqñº';
COMMENT ON COLUMN XXCOS.XXCOS_TMP_ORDER_LIST_CUST.DELIVERY_BASE_NAME IS 'î[ïiãíì_ñº';
COMMENT ON COLUMN XXCOS.XXCOS_TMP_ORDER_LIST_CUST.TSUKAGATAZAIKO_DIV IS 'í âﬂç›å…å^ãÊï™';
