ALTER TABLE XXCOS.XXCOS_REP_BUS_PERF  ADD (
   PREV_YEAR_SALE_AMOUNT      NUMBER
  ,PREV_YEAR_BUSINESS_COST    NUMBER
);
--
COMMENT ON COLUMN XXCOS.XXCOS_REP_BUS_PERF.PREV_YEAR_SALE_AMOUNT    IS '前年売上金額';
COMMENT ON COLUMN XXCOS.XXCOS_REP_BUS_PERF.PREV_YEAR_BUSINESS_COST  IS '前年営業原価';
