ALTER TABLE XXCOS.XXCOS_REP_LOT_PICK_DELI_SALE ADD
 (CUSTOMER_CODE VARCHAR2(9)
 ,CUSTOMER_NAME VARCHAR2(40));
COMMENT ON COLUMN XXCOS.XXCOS_REP_LOT_PICK_DELI_SALE.CUSTOMER_CODE IS 'å⁄ãqÉRÅ[Éh';
COMMENT ON COLUMN XXCOS.XXCOS_REP_LOT_PICK_DELI_SALE.CUSTOMER_NAME IS 'å⁄ãqñº';