ALTER TABLE XXCOS.XXCOS_REP_PICK_CHAIN_PRO  ADD (
  REGULAR_SALE_CLASS_HEAD                 VARCHAR2(4)           -- 定番特売区分（ヘッダ）
 ,REGULAR_SALE_CLASS_LINE                 VARCHAR2(4)           -- 定番特売区分（明細）
);
--
COMMENT ON COLUMN XXCOS.XXCOS_REP_PICK_CHAIN_PRO.REGULAR_SALE_CLASS_HEAD           IS  '定番特売区分（ヘッダ）';
COMMENT ON COLUMN XXCOS.XXCOS_REP_PICK_CHAIN_PRO.REGULAR_SALE_CLASS_LINE           IS  '定番特売区分（明細）';
