ALTER TABLE XXCOS.XXCOS_REP_DLV_CHK_LIST ADD (
   VD_COUNT       NUMBER         --VDリスト枚数
  ,OTHER_VD_COUNT NUMBER         --VD以外枚数
  ,CREATE_CLASS   VARCHAR2(2)    --作成元区分
);
COMMENT ON COLUMN XXCOS.XXCOS_REP_DLV_CHK_LIST.VD_COUNT       IS 'VDリスト枚数';
COMMENT ON COLUMN XXCOS.XXCOS_REP_DLV_CHK_LIST.OTHER_VD_COUNT IS 'VD以外枚数';
COMMENT ON COLUMN XXCOS.XXCOS_REP_DLV_CHK_LIST.CREATE_CLASS   IS '作成元区分'
