ALTER TABLE XXCOS.XXCOS_DLV_HEADERS_WORK ADD(
  TOTAL_SALES_AMT              NUMBER(8),                      -- 総販売金額
  CASH_TOTAL_SALES_AMT         NUMBER(8),                      -- 現金売りトータル販売金額
  PPCARD_TOTAL_SALES_AMT       NUMBER(8),                      -- PPカードトータル販売金額
  IDCARD_TOTAL_SALES_AMT       NUMBER(8)                       -- IDカードトータル販売金額
);
--
COMMENT ON COLUMN XXCOS.XXCOS_DLV_HEADERS_WORK.TOTAL_SALES_AMT           IS '総販売金額';
COMMENT ON COLUMN XXCOS.XXCOS_DLV_HEADERS_WORK.CASH_TOTAL_SALES_AMT      IS '現金売りトータル販売金額';
COMMENT ON COLUMN XXCOS.XXCOS_DLV_HEADERS_WORK.PPCARD_TOTAL_SALES_AMT    IS 'PPカードトータル販売金額';
COMMENT ON COLUMN XXCOS.XXCOS_DLV_HEADERS_WORK.IDCARD_TOTAL_SALES_AMT    IS 'IDカードトータル販売金額';
