ALTER TABLE XXCOS.XXCOS_EDI_HEADERS  ADD (
  TSUKAGATAZAIKO_DIV       VARCHAR2(10)    --�ʉߍ݌Ɍ^�敪
);
--
COMMENT ON COLUMN XXCOS.XXCOS_EDI_HEADERS.TSUKAGATAZAIKO_DIV                         IS  '�ʉߍ݌Ɍ^�敪(EDI�捞��)';
