ALTER TABLE XXCOS.XXCOS_EDI_INVENTORY ADD (
   BMS_HEADER_DATA VARCHAR2(2000)
  ,BMS_LINE_DATA   VARCHAR2(1500)
);
--
COMMENT ON COLUMN XXCOS.XXCOS_EDI_INVENTORY.BMS_HEADER_DATA  IS  '流通ＢＭＳヘッダデータ';
COMMENT ON COLUMN XXCOS.XXCOS_EDI_INVENTORY.BMS_LINE_DATA    IS  '流通ＢＭＳ明細データ';
