CREATE OR REPLACE FORCE VIEW "APPS"."XXINV_MOV_LOV_DELI_NO_V" (
  "DELIVERY_NO",
  "PRODUCT_FLG",
  "ITEM_CLASS"
  ) AS 
  SELECT
    DELIVERY_NO          -- 配送No
   ,PRODUCT_FLG          -- 製品識別区分
   ,ITEM_CLASS           -- 商品区分
  FROM  XXINV_MOV_REQ_INSTR_HEADERS  -- 移動依頼・指示ヘッダ(アドオン)
  WHERE DELIVERY_NO IS NOT NULL
  GROUP BY
        DELIVERY_NO
       ,PRODUCT_FLG
       ,ITEM_CLASS
  ORDER BY
        DELIVERY_NO
  ;
--
COMMENT ON COLUMN XXINV_MOV_LOV_DELI_NO_V.DELIVERY_NO   IS '配送No';
--
COMMENT ON TABLE  XXINV_MOV_LOV_DELI_NO_V IS '移動_値セット用VIEW_配送No' ;
/